### ISSUE TITLE
No Private Group Support?

### ISSUE THREAD

**Issue by davros85** [SharePoint/PnP-Sites-Core#1000]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When supplying isPrivate: true to the CreateUnifiedGroup method in the UnifiedGroupsUtility class, the Office 365 group should be created as a 'private' group, without giving read access to everyone.

#### Observed Behavior
The group and modern team site are created, marked as 'Public', and with 'Everyone Except External Users' added to the members group in the SharePoint site.

#### Steps to Reproduce
`UnifiedGroupsUtility.CreateUnifiedGroup("my group", "-", "mygroup", accessToken, owners, members, isPrivate: true, retryCount: 10, delay: 500);`

Having looked through the utility code - I can't see where the `isPrivate` variable is even being used?

**Comment by jansenbe** [comment]
Hi David,

Your observation is correct, we're not using the isPrivate flag yet. I've flagged this as a bug. Thanks for reporting this.

**Comment by davros85** [comment]
Thanks – you mean a bug with PnP or with the actual API?

**Comment by jansenbe** [comment]
I guess PnP, but we'll have to diagnose this first.

**Comment by davros85** [comment]
Yep - looks like we'll need to call the update method and set the visibility:
https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/group_update

**Comment by davros85** [comment]
Yup - just need to add:

`Visibility = isPrivate == true ? "Private" : "Public",`

to the new group command.

**Comment by jansenbe** [comment]
Thanks @davros85, I've added this. Will be in Feb release, so will close this issue now.

**Comment by davros85** [comment]
Hi all - whilst the group now gets set to Private - if it IS, the modern site URL coming out of the process in NULL in most cases. And whilst the owner may be added to the Exchange group side, the SP site doesn't have the permissions added. Also tried creating the group as public, adding the owners etc, then setting it to Private via an update - but the Privacy update has no effect. Is this PnP or the Graph API?
