### ISSUE TITLE
Apply-PnPProvisioningTemplate : Cannot change Hidden attribute for this field

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1002]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Applying a template should work.

#### Observed Behavior

PowerShell_ISE.exe Information: 0 : 2017-01-25 15:04:30.5702	[List instances]	[12]	[Debug]	Updating list Documents	628ms	66a99c81-3d12-419e-924e-505daca5de2f
PowerShell_ISE.exe Information: 0 : 2017-01-25 15:04:35.2117	[List instances]	[12]	[Debug]	Updating list Images	5269ms	66a99c81-3d12-419e-924e-505daca5de2f
PowerShell_ISE.exe Information: 0 : 2017-01-25 15:05:01.8650	[List instances]	[12]	[Debug]	Updating list Schemes	31926ms	66a99c81-3d12-419e-924e-505daca5de2f
PowerShell_ISE.exe Information: 0 : 2017-01-25 15:05:14.3265	[List instances]	[12]	[Debug]	Updating list Workflow History	44389ms	66a99c81-3d12-419e-924e-505daca5de2f
PowerShell_ISE.exe Information: 0 : 2017-01-25 15:06:08.0180	[List instances]	[12]	[Debug]	Code execution scope ended	98087ms	66a99c81-3d12-419e-924e-505daca5de2f
PowerShell_ISE.exe Information: 0 : 2017-01-25 15:06:08.0200	[Provisioning]	[12]	[Debug]	Code execution scope ended	119146ms	66a99c81-3d12-419e-924e-505daca5de2f
Apply-PnPProvisioningTemplate : Cannot change Hidden attribute for this field
At C:\Workspaces\Dalcour Maclaren\Triad.DalcourMaclaren\Triad.DalcourMaclaren.Provisioning\Install.ps1:119 char:3
+         Apply-PnPProvisioningTemplate -Web $web -Path "$path\Template ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplat

#### Steps to Reproduce
I've got a list with two content types.

Content Type 1
- Field 1
- Field 2
- Field 3  This is a hidden field!

Content Type 2
- Field 1
- Field 2 This is a hidden field!
- Field 3  

When creating the list "Cannot change Hidden attribute for this field" appears. It looks like the fieldref of the lists is trying to update the Hidden Attribute. Even though the template doesn't mention the hidden status. The apply template shouldn't set Hidden on a field if there isn't any Hidden mentioned in the template's fieldrefs.

The line in my templates causing the problem is:

> 
< pnp :FieldRef ID="334d25fc-81ae-4e27-8962-04f86d596381" Name="b3c99aa5e77b44d292ebcbe85414d6ec" Hidden="true" DisplayName="MyCompany_0" />

This is part of the Managed Metadata columns:

>  < pnp :FieldRef ID="b3c99aa5-e77b-44d2-92eb-cbe85414d6ec" Name="MyCompany" DisplayName="Client Company" />

**Comment by jansenbe** [comment]
This one requires further investigation. Do you happen to have a small template which reproes the issue?

**Comment by middiu** [comment]
I have exactly the same problem.
Any help is appreciated.

**Comment by Pieter-Veenstra** [comment]
I fiddled with the template after exporting the template as a .xml file.  So I don't have this problem however I do believe that there is an issue here.

**Comment by middiu** [comment]
Hi Pieter,
how did you end up solving this problem?

**Comment by Pieter-Veenstra** [comment]
With 

set-pnptracelog -on -level debug

Before the apply cmdlet I enable debug. Then I can identify the problem object and remove the hidden=true from the template.

**Comment by jansenbe** [comment]
@middiu : can you share the template you use to repro this?

**Comment by biste5** [comment]
Hi @Pieter-Veenstra ,

are your Content Type / Fields published from CT Hub maybe?
I'm having the same issue, but it seems to me this only happens with Metadata columns published from CT Hub

Massimo

**Comment by biste5** [comment]
Hi @jansenbe ,

I've been tracking down the issue, which seems easy to reproduce for me.

**Repro**
Custom Site Column: TestCol (simple string, but it doesn't really matter)
Custom Site Content Type: MyCT, referencing TestCol as **Hidden**

Custom List: MyList, referencing MyCT
Edit the list reference of MyCT, and set TestCol as Optional

This is an absolutely valid configuration scenario, which produces the XML provisioning attached.
So to reproduce, you can just try to apply the provisioning template to any SP site

[1002.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1261640/1002.txt)

**Comment by thunderstorm654** [comment]
Just ran into the same issue. Content type has fields set as 'hidden'. When applying the template to another site, code fails on the first hidden field with the same error 'Cannot change Hidden attribute for this field'.

**Comment by BrianDeJesus** [comment]
Was there a solution for this somewhere? It's closed but i cannot see where this has been solved here.
