### ISSUE TITLE
Display name in multifield lookups

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1003]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Lookup fields with multiple fields selected from the lookup list should be handled ok.

#### Observed Behavior

A lookup field like this fails:

< Field Type="Lookup" DisplayName="Group:Title Owner" List="{listid:Interest Group}" WebId="{siteid}" ShowField="Title" FieldRef="55cc236c-9b14-41a1-845e-8a6e8963ad67" ReadOnly="TRUE" UnlimitedLengthInDocumentLibrary="FALSE" ID="{a0a97065-a07d-4efe-b222-13b4a60610a3}" SourceID="{{listid:Associated Contacts}}" StaticName="Group_x003a_Title_x0020_Owner" Name="Group_x003a_Title_x0020_Owner" Version="1" />

This issue is the field with the :  in the DisplayName is created a s a new lookup rather than an extension on the existing one when a template is applied.            

#### Steps to Reproduce
Select multiple columns hen creating a lookup. The Get-PnPProvisioningTemplate works Apply-PnPProvisioningTemplate fails.

**Comment by jansenbe** [comment]
Did you use the primary field's display name or static name. Using static name does not work. Below XML is working for us, based on display name. Can you verify this in your environment?

```XML
    <Field ID="{3a18fcce-7eab-45d7-b6b6-c61cec868057}" Type="LookupMulti" Name="FLD_60" DisplayName="Fld 60" Group="PnP Demo" Required="FALSE" EnforceUniqueValues="FALSE" List="{{listid:Documents}}" WebId="{siteid}" ShowField="Title" Mult="TRUE" Sortable="FALSE" UnlimitedLengthInDocumentLibrary="TRUE" />
    <Field ID="{ea724dbb-9222-476a-9f5a-3e09e4e62b8d}" Type="LookupMulti" Name="FLD_60_Created" DisplayName="Fld 60:Created" Group="PnP Demo" List="{{listid:Documents}}" WebId="{siteid}" ShowField="Created" FieldRef="3a18fcce-7eab-45d7-b6b6-c61cec868057" ReadOnly="TRUE" Mult="TRUE" Sortable="FALSE" UnlimitedLengthInDocumentLibrary="TRUE" />
    <Field ID="{19bac6e3-84b6-4a03-9421-a81ccdef542e}" Type="LookupMulti" Name="FLD_60_Modified" DisplayName="Fld 60:Modified" Group="PnP Demo" List="{{listid:Documents}}" WebId="{siteid}" ShowField="Modified" FieldRef="3a18fcce-7eab-45d7-b6b6-c61cec868057" ReadOnly="TRUE" Mult="TRUE" Sortable="FALSE" UnlimitedLengthInDocumentLibrary="TRUE" />
    <Field ID="{D4F4C477-ADEE-4F19-B13C-450AE375EDC9}" Type="Lookup" Name="FLD_61" DisplayName="Fld 61" Group="PnP Demo" Required="FALSE" EnforceUniqueValues="FALSE" List="{{listid:Documents}}" WebId="{siteid}" ShowField="Title" Mult="FALSE" Sortable="FALSE" UnlimitedLengthInDocumentLibrary="TRUE" />
```

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
