### ISSUE TITLE
Issue with Get-PnPProvisioningTemplate with workflows

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1015]
_From @PzKfWg on January 5, 2017 19:52_

Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

####Which PnP repository should you use to report the issue?####
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
Latest release December 2016

#### Category
[X] Bug

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
I tried to export a template of a site with multiple complex SPD workflows (2010 and 2013 engine), but it did not work. I nailed down the issue to workflows with the switch "-Handlers Workflows". On the contrary, I could create the template with "-ExcludeHandlers Workflows". 

#### Observed Behavior
***From PowerShell:

> Get-PnPProvisioningTemplate -Out Workflows.xml -Handlers Workflows
> 
> Get-PnPProvisioningTemplate : hex 0x attendu dans '{0}'.  // "attendu dans" means "expected in"
> Au caractère Ligne:1 : 1
> + Get-PnPProvisioningTemplate -Out Workflows.xml -Handlers Workflows
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], FormatException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

***In the tracelog file:

> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	Code execution scope started	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	Base template available: STS0template	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	ProgressDelegate registered	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7462	[Extraction]	[9]	[Debug]	MessagesDelegate registered	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:04.7618	[Workflows]	[9]	[Debug]	Code execution scope started	0ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:07.5519	[OfficeDevPnP.Core]	[0]	[Information]	File d3e87945-5037-4806-9e89-590cfabc6b64.xaml saved to folder 	0ms	
> powershell.exe Information: 0 : 2017-01-05 14:45:07.5675	[Workflows]	[9]	[Debug]	Code execution scope ended	2799ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05
> powershell.exe Information: 0 : 2017-01-05 14:45:07.5675	[Extraction]	[9]	[Debug]	Code execution scope ended	2814ms	0c3ce918-d31f-43ac-bf32-1f15c2211b05

#### Steps to Reproduce
This is difficult to tell as there is a dozen of SPD workflows of multiple kinds and the tracelog does not seem to specify on which it stumbles. I can't find neither a list of known limitations in exporting workflows that could help nail down the issue.
Thank you for your attention!

_Copied from original issue: SharePoint/PnP#1581_

**Comment by jansenbe** [comment]
Would it be possible for you to debug this issue by stepping through the engine code? Basic WF exports are working as shown in this test case template https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/workflows_add_1605.xml.

**Comment by PzKfWg** [comment]
If you are asking me, I am really not a developer, so I would be hard pressed to know what to do! :-S

**Comment by jansenbe** [comment]
We've been experimenting with various wfs but could not repro. Closing the issue for now, feel free to re-open if you can do some client side debugging.

**Comment by e-gallis** [comment]
I was stumbling on the same error recently and I'm pretty sure I discovered the origin of this issue.
In my case, I had about 20 workflows to extract from my site collection and every time the error described above appeared on the same workflow.
So, I discovered that the thing that this workflow had and that others didn't is that it calls a reusable SP2010 workflow.
And I noticed that when I call the Get-PnPWorkflowDefinition function, it displays all list workflows but not the reusable ones. Which means that when the Get-PnPProvisioningTemplate tries to export my workflow that calls the SP2010 reusable workflow, it can't since it doesn't know this reusable workflow. So I guess that when it builds the XAML file it can't find a GUID for the reusable workflow and it says "Expected hex 0x value in '{0}'".
Hope this helps... and that the issue can be opened again.

**Comment by TanmayDharmaraj** [comment]
This occurred for me too and in my case it was on the below occasions when a workflow was associated to a list that didn't exist. The exact error occurred at `Guid.Parse`

https://github.com/SharePoint/PnP-Sites-Core/blob/bcd9d7582e26f7937518ba58852b6fb861caa23c/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWorkflows.cs#L77

Luckily I also had another workflow that started an approval workflow and that worked fine as opposed to what @e-gallis mentioned.
