### ISSUE TITLE
The content type “System Page Layout” at “/sites/my-site” is sealed. pnp provisioning engine SharePoint online

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1020]
_From @Ragnarok99 on December 21, 2016 19:42_

####Which PnP repository should you use to report the issue?####
https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.Framework.Console

#### Category
[X] error

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Observed Behavior
I'm doing some test copying sites with the pnp provisioning engine framework and at ApplyProvisioningTemplate at  step **content type** I get this error The content type "System Page Layout" at "..." is sealed.

Anybody knows what is happening and what can i do?

xml template here: https://mega.nz/#!6A93yIKQ!0jceGpJ37B6w6ZQfahv4H13EK1G0cMcy1qH_Y7WXxgs

_Copied from original issue: SharePoint/PnP#1574_

**Comment by VesaJuvonen** [comment]
Looking on the template, this is pretty messy site. It's a team site where publishing features have been activated, which really is not a recommended approach, but is indeed supported. This combination has then generated also publishing content types to be exported on the template, which technically would not be needed. You could solve the issue by removing the System Page Layout content type definition from the template manually, but if the flow is fully automated, that's not optimal.

We'll also have a look if we could deal with this Sealed exception in more gracefully, since it's a known exception related on the content type updates - https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.contenttype.update.aspx.

Since this exception is really around the PnP Provisioning Engine, will relocate this issue to right repository (including comments) and close this one here.

**Comment by jansenbe** [comment]
Adding enhancement label for investigating if/how we can handle sealed ct's

**Comment by Pieter-Veenstra** [comment]
I just found the same issue. I've got a subsite ( Base template teamsite) and root site collection that has been created as a publishing portal. I want to move this subsite to a separate site collection. My new site collection is a team site. To get the custom content types across I've exported the publishing portal with all its custom content types.

This is a bit of an "round hole, square peg" kind of problem. Manually cleaning the template and only including the custom columns and content types must be the best way forward.

**Comment by jansenbe** [comment]
The March release will filter publishing content types since they're indeed default ct's. That hopefully will already help a bit. See https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/BuiltInContentTypeId.cs#L75

**Comment by jansenbe** [comment]
We also added better support for sealed CT's...if a CT is sealed and the template is not "un-sealing" it we'll not try to update the CT anymore. See https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs#L79

**Comment by jansenbe** [comment]
@Ragnarok99: can you verify if you still reproduce this issue with our March release?

**Comment by Pieter-Veenstra** [comment]
Hi  @jansenbe,

The problem still occurs for the following two content types:

ID="0x01010007FF3E057FA8AB4AA42FCB67B453FFC100E214EEE741181F4E9F7ACC43278EE811" Name="Page Layout"

ID="0x0120D520A8" Name="System Media Collection"

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
