### ISSUE TITLE
Missing pages content with CSOM GetProvisioningTemplate output vs PS output

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1021]
_From @nickdelrosario on September 28, 2016 22:31_

**Which PnP repository to report the issue?**
SharePointPnPCoreOnline v2.7.1609.3 - Provisioning Engine

**Category**

[ ] Bug

**Environment**

[ ] Office 365 / SharePoint Online

**Expected or Desired Behavior**

Create Provisioning Template with default page content and composed look

**Observed Behavior**

Generated XML template is missing pages content. PowerShell command for the same request generated properly.

**Steps to Reproduce**

Here is the sample CSOM Code I run vs PS:
            //Provision Site Directory Site
            //TODO: Change to Dynamcially pull from request list
            Uri templateURI = new Uri("https://nickdelrosario.sharepoint.com/sites/templatesteamsite2");
            ProvisioningTemplate template = null;

```
        //Get the realm for the URL
        string templateRealm = TokenHelper.GetRealmFromTargetUrl(templateURI);

        //Get the access token for the URL.  
        //   Requires this app to be registered with the tenant
        string accessToken = TokenHelper.GetAppOnlyAccessToken(
            TokenHelper.SharePointPrincipal,
            templateURI.Authority, templateRealm).AccessToken;

        //Get client context with access token
        using (var templateCtx =
            TokenHelper.GetClientContextWithAccessToken(
                templateURI.ToString(), accessToken))
        {

            ProvisioningTemplateCreationInformation templateCI = new ProvisioningTemplateCreationInformation(templateCtx.Web);
            FileSystemConnector fileSystemConnector = new FileSystemConnector(String.Format(@"{0}\..\..\Templates",
                                        AppDomain.CurrentDomain.BaseDirectory), "");

            templateCI.FileConnector = fileSystemConnector;
            templateCI.PersistBrandingFiles = true;
            templateCI.ProgressDelegate = (message, step, total) =>
            {
                Console.WriteLine("{0}/{1}\t{2}", step, total, message);
            };

            template = templateCtx.Web.GetProvisioningTemplate(templateCI);

            XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(String.Format(@"{0}\..\..\Templates",
                                        AppDomain.CurrentDomain.BaseDirectory), "");
            provider.SaveAs(template, "TeamSiteTemplate.xml");
```

**Powershell:**
<img width="1036" alt="ps screengrab" src="https://cloud.githubusercontent.com/assets/22508898/18934722/f7a74c9c-85a0-11e6-98d9-f2c792912189.PNG">

**See XML outputs that differ:**
CSOM
[CSOMGenerated.txt](https://github.com/OfficeDev/PnP/files/499385/CSOMGenerated.txt)

PS
[PSGenerated.txt](https://github.com/OfficeDev/PnP/files/499386/PSGenerated.txt)

_Copied from original issue: SharePoint/PnP#1535_

**Comment by VesaJuvonen** [comment]
_From @petepuu on January 5, 2017 8:8_

Hi,

I have exactly the same problem against SharePoint 2016. If I export template in PS like below the pages and pagecontents is included but what I just realized is that it only exports the welcome page! None of the other pages I have in SitePages library are not exported
![image](https://cloud.githubusercontent.com/assets/8307644/22283233/c00f4c98-e2e9-11e6-9a75-aadc48a02c81.png)


Testing using console app with similar CSOM code the template file is basically empty
![image](https://cloud.githubusercontent.com/assets/8307644/21672964/9a993ca0-d32e-11e6-983d-e775edbd5a5a.png)


**PowerShell**
[ps_sts0.txt](https://github.com/SharePoint/PnP/files/686699/ps_sts0.txt)

**CSOM**
[csom_sts0.txt](https://github.com/SharePoint/PnP/files/686700/csom_sts0.txt)

**Comment by VesaJuvonen** [comment]
_From @petepuu on January 25, 2017 21:57_

I did some debugging of PageContents handler and found out that this is caused by WillExtract method which checks is the ClientContext.Credentials defined. In my CSOM test using console application I do not explicitly set the credentials, so this method will return FALSE

![image](https://cloud.githubusercontent.com/assets/8307644/22309971/33c0f9d6-e356-11e6-957f-85db9f6424c0.png)

But if setting credentials in console app for example like below then it works of course in a same way than in PowerShell version where credentials are passed

![image](https://cloud.githubusercontent.com/assets/8307644/22309902/f2a7233a-e355-11e6-883b-35ecb9430623.png)

I guess that this check can be removed? I still need to test this in my site provisioning add-in with app-only permissions by defining the _willExtract to be always TRUE.

Pete

**Comment by VesaJuvonen** [comment]
This really comes down on app-only vs user context usage. We will absolutely have a look on this more closely to see the root cause of the issue. Since this however is related on the PnP Core Component, I'll relocate this issue to right repository, so that the issue does not get lost.

**Comment by jansenbe** [comment]
Don't think we have an issue here anymore, the latest version will always set _willExtract to true in case of Online (as of Jan 14th). For on-premises we can't extract web part XML because there's no API for it when using app-only. Using credential flow we're using the exportwp.asp page to grab the web part XML, but this requires a user context to work.

So using the dev build you can verify this already today, alternatively you'll need to wait for our February release which will be out soon.

I'm closing the issue now, but feel free to re-open in case it still is an issue for when testing with dev version or upcoming Feb release.

**Comment by Balakrishnanse** [comment]
Hi,

  I am facing the same issue none of custom pages are exported. I checked it in CSOM as well as in Powershell.

OfficeDevPnP.Core : **Version** - 2.15.1705.0   **Run time Version** : v4.0.30319

Below is the CSOM code used to get the template
 
ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(rootweb);
ptci.PersistBrandingFiles = true;
ptci.PersistPublishingFiles = true;
ptci.IncludeNativePublishingFiles = true;
ptci.FileConnector = new FileSystemConnector(String.Format(@"{0}\..\..\", AppDomain.CurrentDomain.BaseDirectory), "");
ProvisioningTemplate template = rootweb.GetProvisioningTemplate(ptci);
XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(
                    String.Format(@"{0}\..\..\", AppDomain.CurrentDomain.BaseDirectory), "");
                provider.SaveAs(template, "RootPnpProvision.XML");

__________________________________________________________________________________________________________

Connect-PnPOnline
cmdlet Connect-PnPOnline at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Url: https://mytenant.sharepoint.in/sites/SourceSite
PS C:\Windows\system32> $path="C:\mytemplate.xml"
PS C:\Windows\system32> Get-PnPProvisioningTemplate -Out $path;
 ____________________________________________________________________________________________________________
