### ISSUE TITLE
SetDefaultColumnValues method not working with SharePoint Online

### ISSUE THREAD

**Issue by FranckyC** [SharePoint/PnP-Sites-Core#1024]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Default values must be applied on the list

#### Observed Behavior
The method is called with no error message but values are not applied in the list. 

#### Steps to Reproduce
Using the 2.11.1701.1 SharePointPnPCoreOnline NuGet package from the extensibility provider implemented in the [Business.O365StarterIntranet](https://github.com/SharePoint/PnP/tree/master/Solutions/Business.O365StarterIntranet/Provisioning/Intranet.Providers) solution. The method is called with no error message. However, in the target list (the "Pages" library), the configuration is not applied. The same method works for SharePoint 2013 On-Premise.

**Comment by jansenbe** [comment]
Does not seem to be a generic issue as our test case for this is working in all environments: https://testautomation.sharepointpnp.com/Testcase/Details/1388049?branch=dev. Might be related to publishing infra and the pages library. More research is needed

**Comment by jansenbe** [comment]
Hi @FranckyC , can you still reproduce this? Internal testing didn't reproduce this.

**Comment by FranckyC** [comment]
Hi @jansenbe, just tested with the march release package (2.13.1703.0) and same behavior, default values are not applied. The target SharePoint Online site has the modern UI activated, could it have an impact?

**Comment by jansenbe** [comment]
@FranckyC : does this involve default values on taxonomy fields? @ivanvagunin proposed a PR for this #1118 which might help

**Comment by FranckyC** [comment]
@jansenbe Yes, the issue involves taxonomy fields but in my case, default values are applied directly on the list, not at the site column level.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
