### ISSUE TITLE
Site Fields With Special Symbols Fails to Create

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1026]
_From @shanechristy on September 8, 2016 16:47_

I am trying to provision fields that have special symbols in their display name, and I receive an exception stating that "The field was found invalid" when applying the template to site. I've managed to reproduce this issue with a question mark symbol and parenthesis. Removing the symbol from display name fixes the issue.

The exception is being thrown by the Void CreateField method in SharePoint.Client.Web.

Here is an example of a displayname in the schema throwing an exception

`DisplayName=\"{res:Virtual?_DisplayName}`

while this imports just fine

`DisplayName=\"{res:Virtual_DisplayName}`

I think, if possible,  I should be able to apply a template without having to manually replace the offending symbol in the schema.

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#124_

**Comment by VesaJuvonen** [comment]
_From @PaoloPia on December 2, 2016 12:42_

Hi,
Thanks for using the PnP Provisioning Engine. Can you share much more details about the exception (error message and stack trace) that you get? Of course you cannot use any not supported character in the field name, but we want to be sure that it is not an issue related to our custom implementation of the provisioning engine. Thanks.

**Comment by jansenbe** [comment]
Can you specify which characters you've been using in the field displayname? This will help with testing this problem.

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
