### ISSUE TITLE
Apply-SPOProvisioningTemplate : The provided template is not valid!

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1027]
_From @ntinykumar on September 29, 2016 8:35_

I have done this migration from free trail tenant to tenant using  using PnP provision engine approach. This work perfectly fine but when I actually get the template xml file from my client SharePoint online 2013 site and when apply template to another tenant give below error which we could not able to find out.

PS D:\t> Apply-SPOProvisioningTemplate .\PnPDemo.xml
Apply-SPOProvisioningTemplate : The provided template is not valid!
At line:1 char:1
- Apply-SPOProvisioningTemplate .\PnPDemo.xml
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ApplicationException
  - FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

Your help is appreciated.

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#126_

**Comment by VesaJuvonen** [comment]
_From @PaoloPia on December 2, 2016 12:47_

Hi,
Thanks for using the PnP Provisioning Engine. Can you share the template XML?

**Comment by erwinvanhunen** [comment]
We're closing this issue as no response have been provided. Do not hesitate to reopen this issue if necessary.
