### ISSUE TITLE
Get-SPOProvisioningTemplate The file is not checked out. You must first check out this document before making changes"

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1028]
_From @petercarson on December 5, 2016 16:0_

I'm getting the error "Get-SPOProvisioningTemplate The file is not checked out. You must first check out this document before making changes".  I have write access, I've tried with an existing file there and not, and running PowerShell as administrator.  This is a SharePoint Online environment.
https://github.com/SharePoint/PnP/issues/921 sounds similar.  Any advice on solving this?

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#145_

**Comment by VesaJuvonen** [comment]
_From @petercarson on December 8, 2016 16:31_

So it seems to be an issue when creating a template from a Groups site.  Our https://envisionit.sharepoint.com tenant is First Release, and my plan was to create a template from a customized site from the Group site.  I tried again with a vanilla team site provisioned normally through SharePoint, and it created the template fine.  I then tried a brand new vanilla Groups site, and I got the same error.  Is this an incompatibility with the GROUPS#0 site template?

I ran it with Set-SPOTraceLog -On -Level Debug turned on to get a verbose log.  I've attached the results.  I also attached the log for the clean run.  You'll see right at the beginning there is an "Error occured while retrieving basetemplate" in the problem case.

[Debug Error.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/639988/Debug.Error.txt)
[Debug Success.txt](https://github.com/SharePoint/PnP-Provisioning-Schema/files/639987/Debug.Success.txt)

**Comment by VesaJuvonen** [comment]
_From @petercarson on December 8, 2016 16:39_

Chatting outside of this thread, and it sounds like I'm a little early for PnP Remote Provisioning with Groups sites.  Support is planned for the December release that is imminently coming.  I'll update with the results from that when it comes out.

**Comment by jansenbe** [comment]
Extracting group sites is supported now by the engine, the proper group base template is in place so you should get clean templates. I'll close this issue for now, but feel free to re-open if you still have issues exporting group sites using the latest version of the engine.

**Comment by ravick4u** [comment]
@VesaJuvonen I am getting this error with sites created with template STS#3(Modern Site without Group).

PowerShell_ISE.exe Error: 0 : 2018-09-11 13:35:28.8516	[Provisioning]	[0]	[Error]	Error occured while retrieving basetemplate	0ms	
PowerShell_ISE.exe Error: 0 : 2018-09-11 13:35:29.0236	[Provisioning]	[0]	[Error]	Error occured while retrieving basetemplate	0ms

**Comment by ChouguleV** [comment]
@ravick4u Did you get any response/solution on it. I am facing the same issue for STS#3(Modern Site without Group)

powershell.exe Error: 0 : 2019-02-19 12:47:16.6294      [Provisioning]  [0]     [Error] Error occured while retrieving basetemplate                                                                 0
ms
powershell.exe Error: 0 : 2019-02-19 12:47:16.8496      [Provisioning]  [0]     [Error] Error occured while retrieving basetemplate                                                                 0
ms

Which I believe causing issue while applying the template at the end I am getting File not found error for a field in Style library.
