### ISSUE TITLE
Field in ListInstance is not support multi-language

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1029]
_From @iiunknown on December 13, 2016 11:15_

Hi,

I defined Field in ListInstance,  and want to use multi-language resource, I got an error:

```
Apply-SPOProvisioningTemplate : The field was found invalid:  {{listid:****}
```

The template xml file is in the blow:

```xml
...
 <pnp:ListInstance ...>
          ...
          <pnp:Fields>
            <Field ID="{bada6643-e44b-4c88-8eb7-923a119b6ed2}" Name="Memo" Type="Note" DisplayName="{resource: Note}" ... />
          </pnp:Fields>
 </pnp:ListInstance>
...
```

Multi-language lable is ok for SiteField, so, I think it's a bug, please help me, thanks. 

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#152_

**Comment by VesaJuvonen** [comment]
_From @iiunknown on January 12, 2017 3:58_

Is it a  bug or something? anybody help me?

**Comment by erwinvanhunen** [comment]
Hi @iiunknown, this error occurs if the engine encounters a field with tokens that cannot be resolved. I see you're using a resource token called Note. Is that token present in all your resource files that you provided in your template? As the code we run on sitefields to check for unresolved tokens is the same code for listinstance fields, if you provision this specific field as a site field, does that work (e.g. with the same resource token 'Note'.

**Comment by jansenbe** [comment]
Would also recommend checking out our test case for this: https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/localization_add.xml and https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.en-us.resx.

Let us know if you still can't achieve your scenario using the provided sample.

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
