### ISSUE TITLE
Versioning not considered when template is applied

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1030]
_From @r998877 on December 19, 2016 9:54_

From an existing "master" site having lists with versioning enabled I create a provisioning template. Applying this template to a different (empty) site does not enable versioning for those lists. In the extracted xml version settings are shown correctly.
` <pnp:ListInstance Title="Changes" Description="" DocumentTemplate="" TemplateType="100" Url="Lists/Changes" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-de22-43b2-a848-c05709900100" ContentTypesEnabled="true">`

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#154_

**Comment by VesaJuvonen** [comment]
thx r998877, this should work accordingly based on the core component code, which means that we would request additional details around the SharePoint environment (online, on-premises, CU?) and the used PnP Core component version for troubleshooting.

Since this clearly relates on the implementation of the engine in core component, will relocate the issue to sites-core repository and close this one. We would still need the additional details to be able to proceed with the issue resolution.

**Comment by jansenbe** [comment]
Internal testing showed this to work. Closing this issue now, but don't hesitate to re-open if it still reproes with the latest March 2017 release
