### ISSUE TITLE
PNP Command "Get-PnPProvisioningTemplate" does not export 2010 Workflows 

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1031]
_From @Bestebreurtje on December 21, 2016 14:28_

Hello,

The PNP command "Get-PnPProvisioningTemplate" of a SharePoint Online Site does not export 2010 Workflows but only 2013 Workflows. 

Is anyone familiar with this issue?

The reason why I use 2010 Workflows is because a 2013 Workflow cannot create a Documentset.

Kind Regards,

Jeroen Bestebreurtje 

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#156_

**Comment by VesaJuvonen** [comment]
_From @abelunibo on January 30, 2017 22:5_

Same issue here, I think it is not supported. Have you find any workaround?

**Comment by VesaJuvonen** [comment]
_From @Bestebreurtje on January 31, 2017 8:17_

Our workaround is an Event Receiver which starts a PowerShell command and create a Documentset. Unfortunately, I couldn’t use a designer Workflow for this case


Vriendelijke groet, kind regards,

bam_ict

Jeroen Bestebreurtje
Business Consultant DMS
BAM ICT Application Services

T +31 (0)6 50 65 52 93
E jeroen.bestebreurtje@bam.com<mailto:jeroen.bestebreurtje@bam.com>


[cid:image001.png@01D27BA2.D4D31F50]
Royal BAM Group nv
Runnenburg 9, 3981 AZ Bunnik, The Netherlands | P.O. Box 20, 3980 CA Bunnik
Trade Register 30058019  www.bam.com<http://www.bam.com>

Van: Abel Garcia [mailto:notifications@github.com]
Verzonden: maandag 30 januari 2017 23:05
Aan: SharePoint/PnP-Provisioning-Schema <PnP-Provisioning-Schema@noreply.github.com>
CC: Bestebreurtje, Jeroen <jeroen.bestebreurtje@bam.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SharePoint/PnP-Provisioning-Schema] PNP Command "Get-PnPProvisioningTemplate" does not export 2010 Workflows (#156)


Same issue here, I think it is not supported. Have you find any workaround?

**Comment by VesaJuvonen** [comment]
Hi @Bestebreurtje and @abelunibo,
provisioning engine does not indeed currently support SP2010 workflow export and this has been more around lack of community contributions around this area, since implementation is dependent on the work we all do cross the community. This has though come up with now few times, so we are looking what we can do in the future around the PnP engine for this.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by mblennegard** [comment]
@VesaJuvonen , did anything happen with this one? Or is it unlikely to be implemented at all, with Microsoft Flow in many cases replacing Designer Workflows?

**Comment by VesaJuvonen** [comment]
There are no updates on this area. No contributions from others in the community for this area, so no further progress for now. We are absolutely open for this capability, but it would require people to contribute on it.

**Comment by mblennegard** [comment]
Allright.

Do you have any information for pointing in the right direction for
implementing this?
You mentioned in a previous comment that there are some ways to export the
2010 workflows.

Den ons 2 okt. 2019 kl 14:10 skrev Vesa Juvonen <notifications@github.com>:
