### ISSUE TITLE
Page extraction / Provisioning

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1032]
_From @KEMiCZA on December 13, 2016 13:5_

Hi all. I'm having difficulties extracting a page with it's webparts into the xml file structure. In the documentation it's mentioned that you can provision pages, and I can do it manually except for the webparts. I'm trying to provisiong a page with a 'Site Users' webpart with the following XML:
`	  <pnp:Pages>
        <pnp:Page Layout="Custom" Overwrite="true" Url="{site}/SitePages/AnotherWikiPage.aspx">
          <pnp:Fields>
            <pnp:Field FieldName="WikiField">
              <![CDATA[
              The Wiki page HTML code here dsssssssssssss!
              ]]>
            </pnp:Field>
          </pnp:Fields>
          <pnp:WebParts>
            <pnp:WebPart Column="1" Row="1" Title="Site Users">
              <pnp:Contents>
                <webParts>
                  <webPart xmlns="http://schemas.microsoft.com/WebPart/v3">
				  <metaData><type name="Microsoft.SharePoint.WebPartPages.MembersWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" />
				  <importErrorMessage>Cannot import this Web Part.</importErrorMessage></metaData>
                    <data>
                      <properties>
                        <property name="ExportMode" type="exportmode">All</property>
                        <property name="HelpUrl" type="string" />
                        <property name="Hidden" type="bool">False</property>
                        <property name="Description" type="string">Use the Site Users Web Part to see a list of the site users and their online status.</property>
                        <property name="CatalogIconImageUrl" type="string" />
						<property name="IsIncluded" type="bool">true</property>
                        <property name="Title" type="string">USers show mmeee</property>
						<property name="MembershipGroupId" type="string">6</property>
                        <property name="AllowHide" type="bool">True</property>
                        <property name="AllowMinimize" type="bool">True</property>
                        <property name="AllowZoneChange" type="bool">True</property>
                        <property name="TitleUrl" type="string" />
                        <property name="ChromeType" type="chrometype">None</property>
                        <property name="AllowConnect" type="bool">True</property>
                        <property name="Width" type="unit" />
                        <property name="Height" type="unit" />
                        <property name="HelpMode" type="helpmode">Navigate</property>
                        <property name="AllowEdit" type="bool">True</property>
                        <property name="TitleIconImageUrl" type="string" />
                        <property name="Direction" type="direction">NotSet</property>
                        <property name="AllowClose" type="bool">True</property>
                        <property name="ChromeState" type="chromestate">Normal</property>
                      </properties>
                    </data>
                  </webPart>
                </webParts>
              </pnp:Contents>
            </pnp:WebPart>
          </pnp:WebParts>
        </pnp:Page>
      </pnp:Pages>`

The page gets created, but the webpart is missing. Any ideas/help would be appreciated. Thanks

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#153_

**Comment by VesaJuvonen** [comment]
Hi @KEMiCZA, 
since this is more of a question around the support in the PnP sites core component around the provisioning, will move this to PnP-Sites-Core repository. We would though request additional environmental details on your case, so that we can reproduce the this and possibly give you insights on the resolution. Are you using SP Online, on-premises, which CU and what NuGet package?

**Comment by jansenbe** [comment]
See https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/pages_add.xml#L12 for a sample on how to this. Can you let us know if using recommended approach it still does not work for you?

**Comment by KEMiCZA** [comment]
@VesaJuvonen @jansenbe 
Issue is resolved for reference see:
https://github.com/SharePoint/PnP-Sites-Core/issues/584
https://github.com/SharePoint/PnP-Sites-Core/issues/997

**Comment by jansenbe** [comment]
Thanks @KEMiCZA ,

I'll close the issue now.
