### ISSUE TITLE
provision page layout + associated content type, publishing page instance

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#1033]
_From @dorin2006 on December 23, 2016 13:22_

People please help!!! Great tool, but... 

1. how to provision publishing page instance in pages library ?

Or this is not supported yet ?

thanks in advance!!!

p.s. I've managed to provision custom publishing page layout and associated content type ( not a publishing page instance yet ) as follows:
 <pnp:File Src="PageLayouts\GenericPageLayout.aspx" Folder="_catalogs/MasterPage" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentType" Value="Page Layout" />
            <pnp:Property Key="PublishingAssociatedContentType" Value=";#Page;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF39;#" />
          </pnp:Properties>
        </pnp:File>

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#158_

**Comment by VesaJuvonen** [comment]
Hi @dorin2006,
since this is more around the PnP-Sites-Core engine, will relocate this to PnP-sites-Core repository for further processing.

**Comment by jansenbe** [comment]
Hi @dorin2006, 

The engine does not natively support creating publishing pages, but community created a PnP provisioning extension that can do this for you. See https://github.com/SharePoint/PnP/blob/master/Samples/Provisioning.Extensibility/README.md. 

Hope this will help you solve your problem. Will close the issue now.

**Comment by vman** [comment]
Hi @jansenbe and @VesaJuvonen 

I am using the v2.13.1703 of SharePointPnPCoreOnline and it looks like Publishing Layouts and Pages are both being created without any problem with using the <pnp:File> element. My schema looks like this:

The pagelayout:
```
<pnp:File Src="PageLayouts\My.Custom.PageLayout.aspx" Folder="{masterpagecatalog}" Overwrite="true" Level="Published">
  <pnp:Properties>
	<pnp:Property Key="Title" Value="My Custom Page Layout" />
	<pnp:Property Key="MasterPageDescription" Value="My Custom Page Layout" />
	<pnp:Property Key="ContentType" Value="Page Layout" />
	<pnp:Property Key="UIVersion" Value="['15']" />
	<pnp:Property Key="PublishingAssociatedContentType" Value=";#Welcome Page;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF390064DEA0F50FC8C147B0B6EA0636C4A7D4;#"/>
	<pnp:Property Key="PublishingPreviewImage" Value="{masterpagecatalog}/en-US/Preview%20Images/BlankWebPartPage.png, {masterpagecatalog}/en-US/Preview%20Images/BlankWebPartPage.png" />
  </pnp:Properties>
</pnp:File>
```

And then the page:

```
<pnp:File Src="PublishingPages\Home.aspx" Folder="{site}/Pages" Overwrite="true" Level="Published">
  <pnp:Properties>
	<pnp:Property Key="ContentTypeId" Value="{contenttypeid:Welcome Page}" />
	<pnp:Property Key="Title" Value="My Page Instance" />
	<pnp:Property Key="PublishingPageLayout" Value="{masterpagecatalog}/My.Custom.PageLayout.aspx, My Custom Page Layout" />
	<pnp:Property Key="PublishingPageContent" Value="Welcome" />
  </pnp:Properties>
  <pnp:WebParts>
	<pnp:WebPart Title="Content" Zone="wpz_Left" Order="0">
	  <pnp:Contents>
		<WebPart xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/WebPart/v2">
		  <Title>My Title</Title>
		  <FrameType>None</FrameType>
		  <Assembly>Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c</Assembly>
		  <TypeName>Microsoft.SharePoint.WebPartPages.ContentEditorWebPart</TypeName>
		</WebPart>
	  </pnp:Contents>
	</pnp:WebPart>
  </pnp:WebParts>
</pnp:File>
```

Has this been included recently in the Provisioning engine?
