### ISSUE TITLE
Generic and reusable Embed JavaScript technique

### ISSUE THREAD

**Issue by levesquesamuel** [SharePoint/PnP-Sites-Core#1042]
#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
It would be great if we could provision and embed files the same way it is done with the Enable-SPResponsiveUI cmdlet. I'm thinking of a generic way to do this, eg : "Enable-EmbedJavaScript -folder c:\folder -site http://site". All files (JS,CSS) within the specified folder or using an XML file would then be provisionned and embed in the head of the page. This would make the embed javascript technique more accessible to those not confortable with Add-ins and hence avoid masterpage modifications.

**Comment by jansenbe** [comment]
Hi @levesquesamuel ,

Thanks for proposing this idea. This indeed would make things slightly easier but today folks can already realize this by uploading the JS to SharePoint library and adding it to all pages using a custom action. See https://msdn.microsoft.com/en-us/pnp_articles/customize-your-sharepoint-site-ui-by-using-javascript for more details on this. 

Given that for modern experiences (like the modern team sites, modern list and libraries) the current model for embedding JS is not supported anymore + given the existing documented models around JS embedding for classic sites we're not going to implement the proposed change. You obviously can add this to your own code base in case you'll need this often.

**Comment by levesquesamuel** [comment]
Thx for the answer @jansenbe
