### ISSUE TITLE
External list in PnP Provisioning Template

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1044]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
External lists are exported without any problem (although maybe some infromation needed to recreate the list may need to be added)

#### Observed Behavior
When Applying the template the external list is failing

More details also on tech community:

https://techcommunity.microsoft.com/t5/SharePoint-Developer/PnP-Provisioning-Engine-and-external-lists/m-p/44464/highlight/false#M1431

#### Steps to Reproduce

Add external list to a site.

export the site as a template. Then apply the template to a new site.

**Comment by Pieter-Veenstra** [comment]
@VesaJuvonen, @jansenbe,

 I've done some more investigation into this issue today.

For external lists we're not storing any data source connections etc. So this is likely to need schema changes etc. 

Are there any plans to implement this? External lists are quite a common element of our solutions and therefore this could be quite painful if this isn't included.

**Comment by jansenbe** [comment]
Hi Pieter,

We'll take this one into consideration. I've created an issue in the pnp-provisioning-schema repository to track this. See https://github.com/SharePoint/PnP-Provisioning-Schema/issues/172. Will close this one now since we've a new issue open in the correct repo.
