### ISSUE TITLE
Version attribute of List instance' field

### ISSUE THREAD

**Issue by akdum** [SharePoint/PnP-Sites-Core#1047]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online

#### Expected or Desired Behavior
There are no version attributes in schema.

#### Observed Behavior
<Field Name="EP_Position" Group="Custom columns" Type="Number" StaticName="EP_Position" DisplayName="Position" Commas="False" Decimals="0" Overwrite="TRUE" Required="FALSE" ID="{03eda717-97da-4453-9fef-369cc5df4e1e}" SourceID="{{siteid}}" **Version="3"** Customization="" ColName="float1" RowOrdinal="0" EnforceUniqueValues="TRUE" Indexed="TRUE" Min="1" Max="5" Percentage="FALSE" />

#### Steps to Reproduce
1. Create custom column on site.
2. Reuse it in CT and in list instance.
3. Export template from site.

#### Submission Guidelines
I propose to modify ObjectListInstance.cs, ExtractFields method.

**Comment by jansenbe** [comment]
Hi @akdum ,

In our provisioning schema we're we've not defined the SharePoint field schema as that's complex and undocumented. We've taken the approach to just allow any SharePoint field xml structure and only do a basic validation (see IsFieldXmlValid method in ObjectHandlerBase.cs). 

Hope this clarifies things.

**Comment by akdum** [comment]
Good day, @jansenbe 

Sorry, but you can find in code (ObjectField class, ExtractObjects method) the following lines:
                        // Check if we have version attribute. Remove if exists 
                        if (element.Attribute("Version") != null)
                        {
                            element.Attributes("Version").Remove();
                            fieldXml = element.ToString();
                        }
I propose to add similar functionality to ObjectListInstance class, ExtractFields method.
