### ISSUE TITLE
Creating a new Site along with Customization 

### ISSUE THREAD

**Issue by virendramunot** [SharePoint/PnP-Sites-Core#1054]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[] Query
#### Environment
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Jan 2016 15.0.4787.1000
#### Expected or Desired Behavior
The expectation is the engine should first create site and then apply the customization like Navigation, pages in the pages library, New Columns if there are any created or New Content Types etc.

#### Observed Behavior
Not sure if the examples or videos showing how to do this. The current video shows only branding applying of information or creation of new list without any content. I have created some pages in my custom site templates under pages libraries and showing those pages as Links on Global Navigation but this data is not appearing. Mainly the engine should provisioning first the new site based on the template.

######My Requirement in details
We would like to create a custom site template which can be used to create sub sites in the same site collection with new name and apply all the customization including custom pages and all the data that are available in the list. As we are using some look up columns for which the data is coming from the different list so list is also should be created containing data.

Is this possible using PNP core Remote provisioning solution?

**Comment by jansenbe** [comment]
Hi @virendramunot , the PnP provisioning engine does allow you to create a template containing list, content types, navigation and more more artefacts and apply it. You'll have to create to create the actual (sub) site yourselves though. Let me know if this answers your question

**Comment by virendramunot** [comment]
Thanks @jansenbe ....I thought PNP engine will help to automate the Complete site provisioning process starting from creating a subsite using the custom template with all the default features and data that are saved in the template. 

Thanks alot for clarifying this.

**Comment by jansenbe** [comment]
Sure, my pleasure. Will close this issue now.
