### ISSUE TITLE
AuthorizationManager in ClientContext throws uncatchable Exception when user cancels sign in

### ISSUE THREAD

**Issue by dtotzke** [SharePoint/PnP-Sites-Core#1057]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Native client on first use before any authentication has occurred and no token is locally available.

#### Expected or Desired Behavior
Calling ClientContext.ExecuteQuery() displays the Browser for authentication.  
Cancelling the sign-in by clicking the close (x) button of the browser dialog should result in an Exception that can be caught in the native application so that it can be ignored/dealt with.

#### Observed Behavior
Calling ClientContext.ExecuteQuery() displays the Browser for authentication.  
Cancelling the sign-in by clicking the close (x) button of the browser dialog results in an Exception that CANNOT be caught in the native application causing it to crash..

#### Steps to Reproduce
		static void Main(string[] args) {
			FileCache cache = new FileCache(@"c:\temp\TokenCache.dat");
			cache.Clear();
			Console.ReadLine();

			try {
				using (ClientContext context = new AuthenticationManager().
							GetAzureADNativeApplicationAuthenticatedContext(
							"https://blah.sharepoint.com",
							"my client id",
							"http://MyRedirectUrl", cache)) {
					Web web = context.Web;
					context.Load(web);
					
					var lists = context.Web.Lists;
					context.Load(lists, lst => lst.Where(l => l.Hidden == false));
					context.ExecuteQuery();
					string title = web.Title;
					foreach (var list in lists) {
						Console.WriteLine(list.Title);
					}
					Console.WriteLine(title);
					Console.ReadLine();
				}
			} catch (Exception ex) {
                                // this will NOT catch the exception caused by the user cancelling log in.
				Console.WriteLine(ex.Message);
			}
		}

**Comment by jansenbe** [comment]
Thanks @dtotzke for reporting this. I've fixed this so we're not throwing an exception from an async method  cause that exception is thrown on a different thread and therefore it cannot be caught when you're using this from a console app. Instead I'm writing now an error to the log...result in your case will be an access denied message from SharePoint which you can simply catch. Will close the issue now
