### ISSUE TITLE
Private Group cannot get ModernSiteUrl 

### ISSUE THREAD

**Issue by davros85** [SharePoint/PnP-Sites-Core#1061]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Creating a group with Private set, the code should still return the ModernSiteUrl of that SharePoint site to be accessed and used elsewhere. The account used as group creator should have full access to the SP site.

#### Observed Behavior
When creating a group as Private, the Modern Site url call continually fails, and returns null. Even using huge replay timeouts.

#### Steps to Reproduce
Create the group, set isPrivate = true, check the URL coming back.

**Comment by davros85** [comment]
Hi guys - any updates / thoughts on this?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
