### ISSUE TITLE
ClientContextExtensions.HasMinimalServerLibraryVersion works incorrectly for SP 2013

### ISSUE THREAD

**Issue by ivanvagunin** [SharePoint/PnP-Sites-Core#1063]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
HasMinimalServerLibraryVersion checks server library version and compares with given value

#### Observed Behavior
In fact, if ONPREMISES symbol defined, it compares given value with "MicrosoftSharePointTeamServices" HTTP header value, which does not seem to be somehow related to actual server library version. "MicrosoftSharePointTeamServices" at least for SP 2013 contains something like: 15.0.0.xxxx so it always smaller than real server library version (tested with Jan 2017 CU).
Here is screenshot from my local environment:
![image](https://cloud.githubusercontent.com/assets/8759790/23069723/3c9ccbb0-f531-11e6-9111-96f355eb0726.png)

#### Steps to Reproduce
Execute with SharePoint 2013 farm

**Comment by jansenbe** [comment]
Hi @ivanvagunin ,

I've added an alternative implementation for on-premises: https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs#L227

Hope this solves the problem, would you be able to verify this in your environment as well. It's working fine for my 2013/2016 labs but additional validation is always good.

**Comment by ivanvagunin** [comment]
Hi Bert,

Thanks for the fix! I have few comments on that:
Line 244: $"{urlUri.Scheme}://{urlUri.DnsSafeHost}/_vti_pvt/service.cnf" - as far as I know, DnsDafeHost does not include port number, so it will work only for default port for the schema

Line 245:  request.UseDefaultCredentials = true; - I suppose it will work with Windows auth only when current account have sufficient permissions, in case of app running in anonymous context (or pool account does not have permissions) most likely will get access denied.

Other than that it looks good, unfortunately my dev environment is down at the moment, I'll test once fix it. 
__
Br, Ivan

**Comment by jansenbe** [comment]
Thanks for the feedback @ivanvagunin . Good point about the DNSSafeHost, I'll update that one. Regarding the auth there indeed might be cases (running under low privileged account with app-only) that might still be an issue...but today the implementation does not work at all, so we're already in better shape.

**Comment by jansenbe** [comment]
Tried to hit the url from a browser running under "nt authority\network system" and that prompts for credentials. But I think most on-premises customers are typically running their processes using a service account and they can at least grant this account read permissions, even if their process is running app-only. Thoughts?

**Comment by ivanvagunin** [comment]
This method (ClientContextExtensions.HasMinimalServerLibraryVersion) is called during applying of provisioning template (when provisioning content types or smth) and in most of our implementations (not sure if it is really common case or not) template is applied by high trust apps, so mixing up the authentication is not something we'd like to get.

Is there any other endpoint that would return correct version info (the one that could be access anonymously or with bearer token)? If that is not the case, I guess it is better to add "try catch" and return false in case 401 is returned.

**Comment by jansenbe** [comment]
I'm still searching for more reliable options...today the method does return false in case of a 401, essentially the same as the non working scenario we had before.

**Comment by ivanvagunin** [comment]
indeed, I missed that it's already in try statement, so it does not make it worse )

**Comment by PierreBiname** [comment]
Hi, I still have the problem with the version comparaison.
this line : 
`var compareToVersion = new Version(minimallyRequiredVersion.Major, minimallyRequiredVersion.MajorRevision, minimallyRequiredVersion.Minor, 0);`

Return always 15.0.0.0 instead of 15.0.4787.0.

So my version is always newer than 15.0.0.0 and it creates some bugs in pnp related to that.

minimallyRequiredVersion.Minor should be minimallyRequiredVersion.Build.

I hope it helps.

Regards,

Pierre

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
