### ISSUE TITLE
Sharepoint Online issue while creating new sites

### ISSUE THREAD

**Issue by rathnamvemula** [SharePoint/PnP-Sites-Core#1082]
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
I am facing the issue while creating a new site. I am using the version 2.11.1701.1 It does not happen all the times.
Here is the code snippet:

`                      tenant.CreateSiteCollection(newSite, true, true, timeoutFunction: (operationMessage) =>
                        {

                            if (operationMessage == TenantOperationMessage.CreatingSiteCollection)
                            {
                                Log.Info(Constants.LOGGING_SOURCE, "Site collection creation is still in Progress");
                            }
                            if (watch.Elapsed.TotalMinutes > 30)
                            {
                                Log.Info(Constants.LOGGING_SOURCE, "Cancelling the Wait loop");
                                watch.Stop();
                                return true;// set to true to cancel the wait loop
                            }
                            else
                                return false;
                        });
                        if (tenant.SiteExists(newSite.Url))
                        {
                            Site site = tenant.GetSiteByUrl(siteUrl);
                            Web web = site.RootWeb;

                            adminContext.Load(site, s => s.Url);
                            adminContext.Load(web, w => w.Url);
                            adminContext.ExecuteQueryRetry();

                            // Enable Secondary Site Collection Administrator
                            if (!String.IsNullOrEmpty(job.SecondarySiteCollectionAdmin))
                            {
                                var secondarySiteCollAdmin = job.SecondarySiteCollectionAdmin.Split('|');
                                var secondarySiteCollAdminEmail = secondarySiteCollAdmin.Last();

                                Microsoft.SharePoint.Client.User secondaryOwner = web.EnsureUser(secondarySiteCollAdminEmail);
                                secondaryOwner.IsSiteAdmin = true;
                                secondaryOwner.Update();

                                web.SiteUsers.AddUser(secondaryOwner);
                                adminContext.ExecuteQueryRetry();
                            }

                            EnableSharingOnSiteCollection(tenant, siteUrl);

                            Log.Info(Constants.LOGGING_SOURCE, $"Site {site.Url} Created");
                        }`

#### Observed Behavior.
It is throwing the following error
## Details from Log:
Temp eating exception to issue in service (December 2016). Exception is {0}.]	[0]	[Error]	Type = Microsoft.SharePoint.Client.ServerException
Message = **Operation is not valid due to the current state of the object.**
Source = Microsoft.SharePoint.Client.Runtime
ServerStackTrace = 
ServerErrorCode = -1
ServerErrorTypeName = System.InvalidOperationException
ServerErrorTraceCorrelationId = 6546d89d-00ad-3000-a987-5c7c13028f9f
TargetSite = Void ProcessResponseStream(System.IO.Stream)
StackTrace =    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.TenantExtensions.GetSiteGuidByUrl(Tenant tenant, Uri siteFullUrl)
   at Microsoft.SharePoint.Client.TenantExtensions.CreateSiteCollection(Tenant tenant, SiteEntity properties, Boolean removeFromRecycleBin, Boolean wait, Func`2 timeoutFunction)

#### Steps to Reproduce
It is happening intermittently.

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
This is unfortunately oob issue. If you update on the latest PnP version, we will deal with the possible exception inside of the PnP methods. Fix is coming to this in SPO side soon, but unfortunately not there yet.

**Comment by jansenbe** [comment]
Closing as this will be fixed soon.
