### ISSUE TITLE
Break up Core features into more granular packages to avoid taking Nuget dependencies like web API for non-web projects

### ISSUE THREAD

**Issue by tafs7** [SharePoint/PnP-Sites-Core#1085]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

The current PnP-Site-Core repo produces a nuget package that has dependencies on ASP.NET Web API packages.  However, a lot of the functionality provided by Core does not leverage such dependencies.

This causes user of the core package to take on those dependencies, even when they are building in a console application or some other non-web application.

Could the Web API-specific features be moved to a separate project and nuget package, which in turn depends on a more project-type agnostic Core package?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
