### ISSUE TITLE
JS Link not imported correctly

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1091]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When a JSLink is set on a view in a list this should be applied.

So when this is included:
`<JSLink>~site/SiteAssets/JSLink_ClientContact.js</JSLink>`

Then this should be applied

#### Observed Behavior
 JSLink is always ignored.

There is some code in ObjectListInstance.cs that seems to try to apply the JsLink however this is not working:

`// JSLink
                var jslinkElement = viewElement.Descendants("JSLink").FirstOrDefault();
                if (jslinkElement != null)
                {
                    var jslink = jslinkElement.Value;
                    if (createdView.JSLink != jslink)
                    {
                        createdView.JSLink = jslink;
                        createdView.Update();
                    }
                }
                createdList.Update();
                web.Context.ExecuteQueryRetry();`

#### Steps to Reproduce

Manually edit the template to include the JSLink (related to issue #1090 ) and then apply to a site.

**Comment by stevus1970** [comment]
I had a similar issue which appeared to be the result of token replacement being carried out prior to provisioning so ~sitecollection was replaced with an absolute URL which meant the JSLink reference no longer worked.  Don't know if that helps.

**Comment by jansenbe** [comment]
Hi @Pieter-Veenstra ,

I've implemented your PR...so the issue should be gone now. Please confirm.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
