### ISSUE TITLE
Explicit fields in View not working

### ISSUE THREAD

**Issue by KbWorks** [SharePoint/PnP-Sites-Core#1094]
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X] Bug

#### Environment
[ X] Office 365 / SharePoint Online

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When adding explicit fields in the xml you would expect that the view will be provisioned with them. I have tried it in my own code but was unable to achieve the behaviour i tried to do it via listviewxml.  

#### Observed Behavior
When explicit fields are in the view they are provisioned as normal fields which means they show up in the view instead of being hiden
`<View Name="{2AC983A0-C495-4358-B821-7A465635AE08}" Type="HTML" DisplayName="All Assets" Url="{site}/MediaLibrary/Forms/All Assets.aspx" Level="1" BaseViewID="40" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=44" >
            <Query>
              <OrderBy>
                <FieldRef Name="LinkFilename" />
              </OrderBy>
            </Query>
            <ViewFields>
              <FieldRef Name="ContentType" />
              <FieldRef Name="DocIcon" />
              <FieldRef Name="LinkFilenameNoMenu" />
              <FieldRef Name="Modified" />
              <FieldRef Name="Editor" />
              <FieldRef Name="MediaLengthInSeconds" />
              <FieldRef Name="NameOrTitle" Explicit="TRUE" CalloutMenu="TRUE" />
              <FieldRef Name="FileSizeDisplay" Explicit="TRUE" />
              <FieldRef Name="ImageSize" Explicit="TRUE" />
              <FieldRef Name="ImageWidth" Explicit="TRUE" />
              <FieldRef Name="ImageHeight" Explicit="TRUE" />
              <FieldRef Name="VideoWidthInPixels" Explicit="TRUE" />
              <FieldRef Name="VideoHeightInPixels" Explicit="TRUE" />
              <FieldRef Name="PreviewOnForm" Explicit="TRUE" />
              <FieldRef Name="Created_x0020_Date" Explicit="TRUE" />
              <FieldRef Name="Author" Explicit="TRUE" />
              <FieldRef Name="_Comments" Explicit="TRUE" />
              <FieldRef Name="PeopleInMedia" Explicit="TRUE" />
              <FieldRef Name="VideoSetDescription" Explicit="TRUE" />
              <FieldRef Name="VideoSetOwner" Explicit="TRUE" />
              <FieldRef Name="VideoSetUserOverrideEncoding" Explicit="TRUE" />
              <FieldRef Name="VideoSetDefaultEncoding" Explicit="TRUE" />
              <FieldRef Name="VideoSetExternalLink" Explicit="TRUE" />
              <FieldRef Name="VideoSetShowDownloadLink" Explicit="TRUE" />
              <FieldRef Name="VideoSetShowEmbedLink" Explicit="TRUE" />
              <FieldRef Name="VideoSetRenditionsInfo" Explicit="TRUE" />
            </ViewFields>
            <RowLimit Paged="TRUE">20</RowLimit>
            <JSLink>clienttemplates.js|SP.UI.TileView.js|SP.UI.AssetLibrary.js|callout.js</JSLink>
            <XslLink>AssetPicker.xsl</XslLink>
            <Toolbar Type="Standard"/>
          </View>`

#### Steps to Reproduce
first to a extract from a media library with explicit fields added them to my template and uploaded them back.
In the ObjectListInstance class i tried to achieve the solution without result. At the moment we provision the list without views and add them after creation using a extention provider.

Hope it is possible to fix

**Comment by jansenbe** [comment]
Thanks for reporting this @KbWorks , we'll need to look into this.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
