### ISSUE TITLE
Welcome pages and lists and PnP 

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1095]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When the welcome page of a site is set to a view within a list, the site should still be exportable.

#### Observed Behavior
```
Get-PnPProvisioningTemplate : Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null.
"ListItemAllFields
"
At D:\Temp\Powershell\GetPnPTemplateClients.ps1:9 char:1
+ Get-PnPProvisioningTemplate -Web $sourceWeb -Out "d:\Temp\DMPowershel ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate
```
See also: https://techcommunity.microsoft.com/t5/SharePoint-Developer/Welcome-pages-and-lists-and-PnP/m-p/50107#M1688

#### Steps to Reproduce
Set welcome page to list view and export the site using Get-PnPProvisioningTemplate

**Comment by jansenbe** [comment]
Thanks for logging this @Pieter-Veenstra . We'll have to look into this.

**Comment by Pieter-Veenstra** [comment]
Hi @jansenbe ,

I just came across this issue again. When you create a new tenant at https://demos.microsoft.com The tenant is created with a welcome page:

https://mod164441.sharepoint.com/Lists/Office%20365%20Demos/Tiles.aspx

( Great Url by the way with all those spaces  )

It's a shame that a standard demo site doesn't work with PnP. Of course it's easy to delete the default site and create a new one. Or create a page instead of a list view.
