### ISSUE TITLE
Applying provisioning template more than once loses required status on list fields

### ISSUE THREAD

**Issue by 2toLeadMike** [SharePoint/PnP-Sites-Core#1096]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: May 2016 CU

#### Expected or Desired Behavior
I created a plain publishing site, then added a site column,, a CT referencing the column, and a list referencing the CT. The site column and ct are both set to required. The template is then extracted, then reused on another blank pub site.

When applied to a new site collection, there should be no changes by running the exact same template repeatedly.

#### Observed Behavior
The required attribute of the list field is set to false on the 2nd run, further runs keep the required setting to false.

#### Steps to Reproduce
Please see attached barebones PnP template. It contains a single field/CT/list linked together. The first deployment will work, and the field will be required. Any further deployments will adjust the list to have the field set as not required.

Using Feb 2017 release (SP 2013)
[test.txt](https://github.com/SharePoint/PnP-Sites-Core/files/817914/test.txt)

**Comment by jansenbe** [comment]
Thanks for logging this issue @2toLeadMike , we'll need to investigate this

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
