### ISSUE TITLE
 "Argument SiteUrl must be a tenant administration site."

### ISSUE THREAD

**Issue by shravanjoshi88** [SharePoint/PnP-Sites-Core#1102]
#### Category
[x] Bug

#### Environment
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Microsoft.Online.SharePoint.Client.Tenant.dll 
version 15.0.4711.1101
OfficeDevPnP.Core.dll
version 2.5.1606.2

#### Expected or Desired Behavior
We are using on-premises SharePoint 2013 environment to create site collection using below code

using Microsoft.SharePoint.Client;
using Microsoft.Online.SharePoint.TenantAdministration;
using OfficeDevPnP.Core.Entities;

namespace Provisioning.Site
{
    internal class SiteProvisioning: ProvisioningBase
    {
        private Microsoft.Online.SharePoint.TenantAdministration.Tenant _tenant;

        public SiteProvisioning(ClientContext context): base(context)
        {
            _tenant = new Microsoft.Online.SharePoint.TenantAdministration.Tenant(context);
			
			SiteConfiguration siteConfig = (SiteConfiguration)_siteConfig;
			SiteEntity siteEntity = new SiteEntity();
            siteEntity.Url = siteConfig.Url.ToString();
            siteEntity.SiteOwnerLogin = _configuration.PrimarySiteCollAdmin;
            siteEntity.Title = siteConfig.Subject;
            siteEntity.Template = "STS#0";
            _tenant.CreateSiteCollection(siteEntity);
        }

        public override void Provision()
        {
             CreateSiteCollection();            
         }
    }
}

#### Observed Behavior
Getting exception  "Argument SiteUrl must be a tenant administration site."

#### Steps to Reproduce
I have used below powershell comments :

**To create the tenant site collection-**
$AdminType = [Microsoft.SharePoint.SPAdministrationSiteType]::TenantAdministration
New-SPSite -Url $SiteURL -Template "TENANTADMIN#0" -OwnerAlias "XX_XXXX" -AdministrationSiteType $AdminType -Name $SiteURL

**Enable the Developer Site Collection Feature-**
Enable-SPFeature e374875e-06b6-11e0-b0fa-57f5dfd72085 –url $SiteURL

**Enable the remote site collection creation for on-prem in web application level.**
$webapp=Get-SPWebApplication $WebApplicationUrl
$newProxyLibrary = New-Object "Microsoft.SharePoint.Administration.SPClientCallableProxyLibrary"
$newProxyLibrary.AssemblyName = "Microsoft.Online.SharePoint.Dedicated.TenantAdmin.ServerStub, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"
$newProxyLibrary.SupportAppAuthentication = $true
$webapp.ClientCallableSettings.ProxyLibraries.Add($newProxyLibrary)
$webapp.Update()

**Set admin site type property to the site collection using PS for any site collection type.**
$site = get-spsite -Identity $SiteURL
$site.AdministrationSiteType = [Microsoft.SharePoint.SPAdministrationSiteType]::TenantAdministration

PS: The site collection is created using "TENANTADMIN#0" template and AdministrationSiteType is also set as TenantAdministration still getting exception "Argument SiteUrl must be a tenant administration site." at _tenant.CreateSiteCollection(siteEntity); (mentioned in the code above)

Please let me know if you need more information

**Comment by jansenbe** [comment]
Please follow this guidance to enable site collection creation using C# for on-premises: https://github.com/SharePoint/PnP-Tools/tree/master/Scripts/SharePoint.SiteColProvisioning.Configuration. Will close this issue, but feel free to re-open in case this does not help.

**Comment by shravanjoshi88** [comment]
Hi Bert,
Thanks for the guidance.
We have tried running two powershell scripts mentioned in the solution but still we are getting the same error.

Error from the log files :
SharePoint Foundation	CSOM	ahjq1	High	Exception occured in scope Microsoft.Online.SharePoint.Dedicated.TenantAdministration.Tenant.ctor. Exception=System.InvalidOperationException: Argument SiteUrl must be a tenant administration site.     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantAdminHelper.DoSecurityValidation()     at Microsoft.Online.SharePoint.Dedicated.TenantAdministration.TenantServerStub.InvokeConstructor(XmlNodeList xmlargs, ProxyContext proxyContext)     at Microsoft.SharePoint.Client.ServerStub.InvokeConstructorWithMonitoredScope(XmlNodeList args, ProxyContext proxyContext)	c953dc9d-ec09-800e-c9d2-224d0fea0488
