### ISSUE TITLE
Web part connections are ignored in PnP templates

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1103]
#### Category
[X] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When web parts are connected the templates should include information about this so that it can be applied to another site

#### Observed Behavior
When two web parts have a connection setup then the PnP templates do not include any data related to these connections.

#### Steps to Reproduce
Create a page with for example an List view web part and an RSS web part where the list view web part supplies the Url to the RSS web part. Then export the site as a PnP template and apply this to another site.

**Comment by jansenbe** [comment]
@Pieter-Veenstra : can you make an issue in the https://github.com/SharePoint/PnP-Provisioning-Schema/issues repository for this one...we can evaluate support for this as part of new schema as we might need schema extensions to support this.

**Comment by jansenbe** [comment]
Closing this one as we're tracking this as part of the proposed updates for our future PnP provisioning engine schema.
