### ISSUE TITLE
Applying provisioning template with lookup fields fails

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#1105]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Proper handling of lookup fields in applying Provisioning Templates

#### Observed Behavior
Applying a template with a lookup field defined in it fails

#### Steps to Reproduce

- Create Team Site "A" and "B"
- In Team Site "A" create List "My lookup list"
- In Team Site "A" create Field "My Lookup field" referencing "My lookup list"
- Save Team Site "A" as template using Get-PnPProvisioningTemplate
- Apply template to Team Site "B" using Apply-PnPProvisioningTemplate

More details
https://techcommunity.microsoft.com/t5/SharePoint-Developer/Error-Provisioning-a-site-containing-Lookup-column-using-PnP/m-p/51353#M1736

**Comment by jansenbe** [comment]
Thanks for reporting this @paulpascha, looks like something that should get fixed.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
