### ISSUE TITLE
Structural Top Link Navigation Nodes should support MUI (SP2013 SP1 CU Oct 2016)

### ISSUE THREAD

**Issue by cangot** [SharePoint/PnP-Sites-Core#1107]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

SP1 + CU October 2016 English + Language Pack French.

#### Expected or Desired Behavior
Structural Top Link Navigation Nodes should support MUI when using resources files with the PnP Template.

#### Observed Behavior
The Method "LocalizeNavigationNode" in  [LocalizationExtensions.cs](https://github.com/SharePoint/PnP-Sites-Core/blob/9599cf2d801dbecf48112f6f693d1cc979815bb9/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/LocalizationExtensions.cs) supports multiple languages for the Node title by using the "Accept-Language" HTTP Header and refering to this [article](http://sadomovalex.blogspot.fr/2015/09/localize-web-part-titles-via-client.html) which is claiming that this approach is supported by SharePoint 2013.

but the method ProvisionStructuralNavigationNodes in "[ObjectNavigation.cs](https://github.com/SharePoint/PnP-Sites-Core/blob/24540c20d28a3db7960bf5c86d08645684958bfe/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs)" is not calling LocalizeNavigationNode for SharePoint 2013 :

**#if !SP2013**
                if (node.Title.ContainsResourceToken())
                {
                    navNode.LocalizeNavigationNode(web, node.Title, parser, scope);
                }
**#endif**

#### Steps to Reproduce
PnP Template

<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.11.1701.1, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Localizations>
    <pnp:Localization LCID="1033" Name="English" ResourceFile="resources/resources.en-us.resx" />
    <pnp:Localization LCID="1036" Name="French" ResourceFile="resources/resources.fr-fr.resx" />
  </pnp:Localizations>
  <pnp:Templates ID="CONTAINER-SITETEMPLATES">
    <pnp:ProvisioningTemplate ID="SITETEMPLATES" Version="1" BaseSiteTemplate="STS#0">
      <pnp:WebSettings NoCrawl="false" WelcomePage="SitePages/Home.aspx" SiteLogo="" />
      <pnp:SupportedUILanguages>
        <pnp:SupportedUILanguage LCID="1033" />
        <pnp:SupportedUILanguage LCID="1036" />
      </pnp:SupportedUILanguages>
      
      <pnp:Navigation>
        <pnp:GlobalNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="true">
            <pnp:NavigationNode Title="{resource:TopNavHome}" Url="{site}" IsExternal="false" IsVisible="true" />
            <pnp:NavigationNode Title="{resource:TopNavLibraries}" Url="{site}/_layouts/viewlsts.aspx" IsExternal="false" IsVisible="true" />
            <pnp:NavigationNode Title="{resource:TopNavLists}" Url="{site}/_layouts/viewlsts.aspx" IsExternal="false" IsVisible="true" />
            <pnp:NavigationNode Title="{resource:TopNavLinks}" Url="{site}/Lists/Links/" IsExternal="false" IsVisible="true" />
          </pnp:StructuralNavigation>
        </pnp:GlobalNavigation>
      </pnp:Navigation>  
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

**Comment by jansenbe** [comment]
You've a point @cangot : don't immediately recall why we excluded 2013 when this was implemented. Will need to test this.

**Comment by cangot** [comment]
Ok, thank you for looking into it.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
