### ISSUE TITLE
Not able to Deploy Master Page using Web.DeployMasterPage Method

### ISSUE THREAD

**Issue by virendramunot** [SharePoint/PnP-Sites-Core#1111]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. - PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X ] Bug
[ ] Enhancement

#### Environment

[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4787.1000
#### Expected or Desired Behavior
The Below code should deploy the Master Page.

 using (ClientContext ctx = new ClientContext("This is my subsite URL"))
                {
                    ctx.Credentials = new NetworkCredential("Administrator", "Password", "Domain");
                    ctx.ExecutingWebRequest += ctx_ExecutingWebRequest;
                    // Just to output the site details
                    Web web = ctx.Web;
                    ctx.Load(web, w => w.Title);
                   
                    ctx.ExecuteQuery();
                    web.DeployMasterPage("E:\\Resources\\My_System.master", "MY_System", "My System Master Page");
                                       
                }
Note - The Resources folder is in my Project
#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
I am creating a Remote Site Provisioning tool
1. Create a Console application.
2. Add all the Microsoft. SharePoint. Client and its related references Assembly
3. Add the Office.Core.PNP assemblies to reference
4. Add the above give code with appropriate Credentials and details.
5. Build and Run

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi, master pages always have to be added to the root site of the site collection. Can you repro the issue with when adding to root site of your site collection? Als please provide a stack trace of the error if it still happens.

**Comment by virendramunot** [comment]
Thanks Jansebe. It worked.

**Comment by jansenbe** [comment]
Thanks for the feedback @virendramunot , will close this issue now.
