### ISSUE TITLE
Get-PnPProvisioningTemplate -Handlers ContentTypes

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1112]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior

To provision all fields from a template the Fields handler can be used (Get-PnPProvisioningTemplate -Handlers Fields )
This should mean that when provisioning Content types only the Handler ContentTypes should be used.

#### Observed Behavior

**Get-PnPProvisioningTemplate -Handlers ContentTypes** re-provisions the fields as well. At the moment there is no way to provision just content types. The current behaviour should happen only with the following Cmd:
Get-PnPProvisioningTemplate -Handlers Fields, ContentTypes

#### Steps to Reproduce
Run **Get-PnPProvisioningTemplate -Handlers ContentTypes**

**Comment by jansenbe** [comment]
When I the February version I only see content types in the generated XML. Content types do have fieldrefs but we're not exporting the field themselves. Can you further clarify?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
