### ISSUE TITLE
PNP Core Code throws many errors...Thinking if it is really worth to use PnP Framework for SharePoint  Developmen

### ISSUE THREAD

**Issue by virendramunot** [SharePoint/PnP-Sites-Core#1113]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 

- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X] Bug

#### Environment

[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4787.1000
#### Expected or Desired Behavior
The Office.Core.PnP solution should compile in VS 2013 

#### Observed Behavior
It throws to many error and never compiled and no help is available to ensure what needs to be done when errors are produce
#### Steps to Reproduce
downloaded the PNP COde and open it in VS2013

![image](https://cloud.githubusercontent.com/assets/11777835/23757413/c60e5770-050c-11e7-9796-8e6f73118b5e.png)

![image](https://cloud.githubusercontent.com/assets/11777835/23757474/f16e1586-050c-11e7-9d53-f9c895d4798f.png)

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
You need VS2015 or higher to compile. The compilation errors you see are new C# features.

**Comment by virendramunot** [comment]
Thanks. Can you help me with other query which is at https://github.com/SharePoint/PnP-Sites-Core/issues/1111
