### ISSUE TITLE
Template Provisoning Files - Setting Taxonomy Field VAlues

### ISSUE THREAD

**Issue by jimmywim** [SharePoint/PnP-Sites-Core#1114]
#### Category
[o ] Bug
[ ] Enhancement

#### Environment
[o ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Taxonomy field values to be set on uploaded files where the value is specified inthe JSON file that specifies metadata

#### Observed Behavior
Taxonomy field values are not populated

#### Steps to Reproduce
Use a JSON file such as this when uploading via the pnp:Files template block:

(Behaviour is seen on both single and multi valued taxonomy fields.

Deserialization code in the codebase has been tested independently, and the values in the "Category" fields below successfully deserialize to a TaxonomyFieldValue[] array object.

The "Title" field successfully is set from this file also, so the framework is definitely reading the values correctly. Any Syntax errors in the text body of the Category Value are thrown during processing, so the Category field is also definitely being read.

This sample below does not error but the Category value is not set.

```
{
    "..\\HR_Files\\Files\\HRDocuments\\Cycling to work Scheme.pdf": {
        "Title": "Cycling to Work",
        "Category": "[{ \"Label\": \"Health\", \"TermGuid\": \"f070cc69-28b4-482d-9f8d-09eac34c8f41\", \"WssId\": \"-1\" }]"
    },
    "..\\HR_Files\\Files\\HRDocuments\\Dental Plan.pdf": {
        "Title": "Dental Plan",
        "Category": "[{ \"Label\": \"Health\", \"TermGuid\": \"f070cc69-28b4-482d-9f8d-09eac34c8f41\", \"WssId\": \"-1\" }]"
    }
}
```

**Comment by jansenbe** [comment]
Hi @jimmywim , thanks for logging this issue. Quick scan of the code seems to indicate this should work, but it apparently it doesn't...more research is needed.

**Comment by olemp** [comment]
Having the same issue. It worked before.

**Comment by krainer** [comment]
This does still seem to be an issue -> addition of a publishing page in the pnp template (below sample is with hardcoded id's these are added through parameters)

The below will add the single value mms field but not the multi value field

Looking at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectFiles at the <case "TaxonomyFieldTypeMulti"> the multifield is added as a TaxonomyFieldValue[] - wouldn't the correct type be TaxonomyFieldValueCollection instead?

<pnp:File Src="home.aspx" Folder="{site}/Pages" Overwrite="true" Level="Published">
  <pnp:Properties>
    <pnp:Property Key="ContentTypeId" Value="{contenttypeid:Distribution Page}" />
    <pnp:Property Key="Title" Value="{sitename}" />
    <pnp:Property Key="PublishingPageLayout" Value="{sitecollection}/_catalogs/masterpage/Distribution.aspx, Distribution Page" />            
    <pnp:Property Key="PublishingContact" Value="{siteowner}" />
    <pnp:Property Key="MMSMultiple" Value='[{"Label":"DefaultValue","TermGuid":"96d220b5-27fd-45fc-a8cc-16a0f69b0a0f","WssId":-1,"TypeId":"{19e70ed0-4177-456b-8156-015e4d163ff8}"},{"Label":"World","TermGuid":"6dbcc6e9-7558-43eb-9f15-8d9fe38c74e7","WssId":-1,"TypeId":"{19e70ed0-4177-456b-8156-015e4d163ff8}"}]' />
    <pnp:Property Key="MMSSingle" Value='{"Label":"DefaultValue","TermGuid":"0fc39a5e-0335-4847-9612-14a8cf97e3a6","WssId":-1,"TypeId":"{19e70ed0-4177-456b-8156-015e4d163ff8}"}' />
  </pnp:Properties>
</pnp:File>

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
