### ISSUE TITLE
ListInstance MajorVersionLimit is never set on SP2013

### ISSUE THREAD

**Issue by ejbeuker** [SharePoint/PnP-Sites-Core#1116]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
When creating a listinstance with the following attributes:
- EnableVersioning="true"
- EnableMinorVersions="false"
- MaxVersionLimit="10"

I would expect a list instance to be created with the major version limit set to 10

#### Observed Behavior
Versioning is enabled on the list but the major version limit is not set.

On line 1324 of the ObjectListInstance.cs file the MajorVersionLimit is not set for SharePoint 2013:
#if !SP2013
                    createdList.MajorVersionLimit = list.MaxVersionLimit;
#endif

Is there a reason for this logic?
Because when i set it directly with the CSOM api, it works fine:

var list = _clientContext.Web.Lists.GetByTitle(actionData.ListTitle);

            list.EnableVersioning = actionData.EnableVersioning;
            list.MajorVersionLimit = actionData.MajorVersionLimit;
            list.Update();
            _clientContext.ExecuteQuery();

**Comment by jansenbe** [comment]
@ejbeuker : are you using the 2013 CSOM version and if so which version are you using?

**Comment by biste5** [comment]
Bert, 
I think he's meaning that the pre-processor directives, and in general the logic in ObjectListInstance, especially [ObjectListInstance:1336-1338](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs#L1336-L1338) (for example) don't look really correct.

I mean:
[here](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs#L922-L925) _MajorVersionLimit_ isn't included in case is 2013 On-Prem, but then it's anyway later used [here](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs#L1046-L1049)

I think with some bettere unit tests should come evident.

HTH

**Comment by ejbeuker** [comment]
We are using 2013 CSOM, version: 15.0.4801.1000

**Comment by jansenbe** [comment]
Thanks for the feedback, we'll further need to investigate then.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
