### ISSUE TITLE
Apply provisioning template on modern sites breaks when template includes 'Style Library'

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#1117]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I have a modern site just created, for which I extracted its provisioning template using PnP-PowerShell.
I want to reuse this template to apply to other modern sites

#### Observed Behavior
The extracted template contains the following XML portion

```xml
...
 <pnp:ListInstance Title="Style Library" Description="Use the style library to store style sheets, such as CSS or XSL files. The style sheets in this gallery can be used by this site or any of its subsites." DocumentTemplate="" TemplateType="101" Url="Style Library" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="500" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-e717-4e80-aa17-d0c71b360101" EnableAttachments="false">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0101" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{C18A8232-EF5D-450B-98B6-312F2A78F5C1}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Documents" Url="/sites/TestModern/Style Library/Forms/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=44">
              <Query>
                <OrderBy>
                  <FieldRef Name="FileLeafRef" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="DocIcon" />
                <FieldRef Name="LinkFilename" />
                <FieldRef Name="Modified" />
                <FieldRef Name="Editor" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="ccc1037f-f65e-434a-868e-8c98af31fe29" Name="_ComplianceFlags" DisplayName="Label setting" />
            <pnp:FieldRef ID="d4b6480a-4bed-4094-9a52-30181ea38f1d" Name="_ComplianceTag" DisplayName="Labels" />
            <pnp:FieldRef ID="92be610e-ddbb-49f4-b3b1-5c2bc768df8f" Name="_ComplianceTagWrittenTime" DisplayName="Label Applied" />
            <pnp:FieldRef ID="418d7676-2d6f-42cf-a16a-e43d2971252a" Name="_ComplianceTagUserId" DisplayName="Label applied by" />
            <pnp:FieldRef ID="8382d247-72a9-44b1-9794-7b177edc89f3" Name="_IsRecord" DisplayName="Item is a Record" />
          </pnp:FieldRefs>
   </pnp:ListInstance>
...
```

It generates an 'Access denied' error while applying this template

Tenant name: mod144391
correlation ID: 5faadc9d-a08b-3000-d8a5-d7fdc51b3d2a
Exception details:

> Type = Microsoft.SharePoint.Client.ServerUnauthorizedAccessException
Message = Access denied. You do not have permission to perform this action or access this resource.
Source = Microsoft.SharePoint.Client.Runtime
ServerStackTrace =
ServerErrorCode = -2147024891
ServerErrorTypeName = System.UnauthorizedAccessException
ServerErrorTraceCorrelationId = 5faadc9d-a08b-3000-d8a5-d7fdc51b3d2a
TargetSite = Void ProcessResponseStream(System.IO.Stream)
StackTrace =    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 90
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 45
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectListInstance.cs:line 206
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 248
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\WebExtensions.cs:line 1174
   at PnPTemplatesConsole.Program.Main(String[] args) in C:\Users\massimo\Documents\Visual Studio 2015\Projects\PnPTemplatesConsole\PnPTemplatesConsole\Program.cs:line 34
HResult = -2146233088

#### Steps to Reproduce
- Create a new modern site (from UI)
- Add a new custom list named _MyList_ to the site (still using UI)
- Run `Get-PnPProvisioningTemplate` to get the template definition of that site
- Run `Apply-PnPProvisioningTemplate` against the same site

It will generate an exception

> Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.

**Comment by jansenbe** [comment]
Modern sites are created quickly because the bulk of the provisioning work is done async using a timer job. Site Assets is one of the libraries that will be created async...what happens in you try to apply the same template later on, when the actual style library was provisioned by the async provisioning process?

**Comment by biste5** [comment]
Hi Bert,

> what happens in you try to apply the same template later on, when the actual style library was provisioned by the async provisioning process?

that is exactly what I'm doing.

**Comment by biste5** [comment]
Also, I'm referring about **Style Library**, and not Site Assets, for this specific case.

That one about Site Assets may come too later :)

**Comment by jansenbe** [comment]
Thanks @biste5 for the feedback. This is an area that definitely requires additional testing. One of the ideas we're having is building some "waiting" logic that you can use to wait for a "complete" modern creation. Alternatively I think we should also investigate on making the engine resilient when a template is applied on a site which is not yet fully created.

**Comment by biste5** [comment]
Bert, I don't fully understand your comment.
I have a fully created modern site
I extract the PnP XML template of that site
I try to apply the same XML on the same site, and i get that error.

We're not in situation of things still being provisioned then, imho

**Comment by biste5** [comment]
I think this issue is in CSOM (Microsoft.SharePoint.Client.dll), and not in actual PnP code..

**Comment by cjohnsonO365** [comment]
I see the same behavior when applying a template to a Team site created as an O365 Group.  As soon as I remove the Style Library list instance, all is well.

**Comment by VishwanathaNayak** [comment]
Any update on this issue. Any one got it working yet.
Appreciate any guidance here.
Thanks in advance.

**Comment by marcdepelteau** [comment]
Do we have an update on this? I am experiencing the same issue.

With Classic Sites we could use the following, but it says the site is active and we still cannot apply the template.
```
 while ((Get-SPOSite -Filter "Url -like '*$($newSiteUrl)*'").Status -ne "Active")
{
   Write-Host "Waiting"
   Sleep -s 10
}
```
There is something going on in the background with the Owner Group that makes the User not able to apply a template to a newly created site. 

The User is the Owner of the Outlook Group, but isn't an Owner on the SharePoint side yet, so he does not have the necessary rights to apply the template. From what I have experienced, it takes some time between 5 minutes and 4 hours before the User is correctly added.

**Comment by vipulkelkar** [comment]
I too have this issue and removing the Style Library from the template works however, I am fetching the template from one site and applying it to another site as one step after the other in a script so there is no way for me to exclude that node from the XML. How can I exclude the style library while generating or applying the template. Is it possible through the excludehandlers ?

**Comment by marcdepelteau** [comment]
@vipulkelkar are you doing this via PowerShell? You could always process the XML in Powershell and remove the node in between the two scripts?

**Comment by vipulkelkar** [comment]
@marcdepelteau  Yeah, I ended up doing the same thing :)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by altaaia** [comment]
This is issue is still persistent. We run Apply Provisioning Template from PowerShell automation scripts. It ends up applying most of the components, however finishing with: 
Apply-PnPProvisioningTemplate : {"error":{"code":"-2147024891,
System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to
perform this action or access this resource."}}}
ServerErrorTraceCorrelationId: bdd1789f-10c5-0000-517c-671a86294a81
