### ISSUE TITLE
BUG: UnifiedGroupUtility Creator/Owner Permissions Not Set for Modern Team Site

### ISSUE THREAD

**Issue by jchilde** [SharePoint/PnP-Sites-Core#1119]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
 UnifiedGroupsUtility.CreateUnifiedGroup should create an Office 365 Unified Group.  The Group includes a Modern Team Site.  The owner of the group is set based on the credentials used if no owner is specified.  That owner will also become the Modern Team Site owner with administrative permissions.

#### Observed Behavior
The group is created with a modern team site.  The owner of the group is set based upon the credentials used. - good so far
HOWEVER: the owner of the group is NOT made an administrator of the Modern Team Site.  It appears that the group owner is the administrator where listed within the Modern Team Site, but no administrative features are available.  

#### Steps to Reproduce
1. Obtain graph token
2. execute UnifiedGroupsUtility.CreateUnifiedGroup with or with specifying the owner and members.
3. Open the new Modern Team Site.
4. Open site settings.
5. See that user is not an administrator of the site.

**Comment by PaoloPia** [comment]
Hi jchilde,
Thanks for your feedback. Unfortunately what you see is a known behavior and it is just a matter of waiting few minutes (sometimes hours) because an asynchronous process will configure permissions. I would encourage you to try later (let's say at least one hour later) after the group creation and most likely  you will see all the administrative settings available for your group's owner.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
