### ISSUE TITLE
Apply template to a modern team site

### ISSUE THREAD

**Issue by sverleysen** [SharePoint/PnP-Sites-Core#1121]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: /

#### Expected or Desired Behavior
Applying a template to a Modern Team Site (created when you created the Office 365 Group)

#### Observed Behavior
I get 2 errors:

- I get an access denied on the Style Library when adding the site columns. I didn't add or change anything so I deleted it from the template xml so I could continue my testing.

- I get an access denied while setting the navigation. The navigation type of the current navigation is StructuralLocal. I tried debugging it and when setting the navigation type, it sets the propertybagvalue "__NavigationShowSiblings" to false which results in the access denied exception.

#### Steps to Reproduce

1. Create a modern team site
2. Export the template using PnP:
` ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(ctx.Web);

                // Create FileSystemConnector, so that we can store composed files temporarely somewhere 
                ptci.FileConnector = new FileSystemConnector(@"c:\temp\pnpprovisioningdemo", "");
                ptci.PersistBrandingFiles = true;
                ptci.ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
                {
                    // Only to output progress for console UI
                    Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                };

                // Execute actual extraction of the tepmplate
                ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);

                // We can also serialize this template for future usage if we want, not really needed
                XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp\pnpprovisioningdemo", "");
                provider.SaveAs(template, "PnPProvisioningDemo.xml");`
3. Apply the template to a new modern template using Pnp:
` XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp\pnpprovisioningdemo", "");
                ProvisioningTemplate template = provider.GetTemplate("PnPProvisioningDemo.xml");
                ProvisioningTemplateApplyingInformation ptai = new ProvisioningTemplateApplyingInformation();
                web.ApplyProvisioningTemplate(template, ptai);`

[used code.txt](https://github.com/SharePoint/PnP-Sites-Core/files/837608/used.code.txt)
[PnPProvisioningDemo.txt](https://github.com/SharePoint/PnP-Sites-Core/files/837595/PnPProvisioningDemo.txt)

**Comment by biste5** [comment]
did you verify against the very latest release just published (v ..1703)?

Possibly a duplicate, and already fixed by https://github.com/SharePoint/PnP-Sites-Core/issues/1106

**Comment by sverleysen** [comment]
I just tested it with the latest release and the navigation works. 
The issue with the style library still exists.

Thanks.

**Comment by VishwanathaNayak** [comment]
Any updates on the issue with Style library? Really appreciate any suggestions to address this.

Thanks.
