### ISSUE TITLE
List fields are always added to the default content type only

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1122]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When multiple content types are created on a list, export and imported to a new site then you would expect  that each content type has the same columns specified as originally.

#### Observed Behavior
When multiple content types are created on a list, export and imported to a new site then all custom list fields are added to the default content type only.

#### Steps to Reproduce
Create list with multiple content types with each a different set of custom list columns

**Comment by parithon** [comment]
Did this bug get lost in the heap?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
