### ISSUE TITLE
Apply-PnPProvisioningTemplate : Value cannot be null; Parameter name: source

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1125]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4885.1000

#### Expected or Desired Behavior
An exported template should import without errors

#### Observed Behavior
When taking a publishing site from one farm to another my template includes:
```
<pnp:GlobalNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="false" />
        </pnp:GlobalNavigation>
```
This results in the following error message:
Apply-PnPProvisioningTemplate : Value cannot be null; Parameter name: source

When I remove the global navigation the problem goes away.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
