### ISSUE TITLE
Add-PnPPublishingPage errors on checkin if content type has required fields

### ISSUE THREAD

**Issue by repton-infinity** [SharePoint/PnP-Sites-Core#1130]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
If you do the following:

1. Create a content type with some required fields
2. Create a page layout based on that content type
3. Use Add-PnPPublishingPage to create a page based on that page layout

then the page will be created, but the command will throw an error:

`Add-PnPPublishingPage : You must fill out all required properties before checking in this document.`

I suggest adding a -CheckIn switch parameter to the extension function, and then to the commandlet. If I specify -CheckIn:$false, the page will be created but not checked in. This will prevent the error message.

[https://github.com/SharePoint/PnP-Sites-Core/blob/38ad99fc5666b3432c1e964378c25738b2169a1c/Core/OfficeDevPnP.Core/Extensions/PublishingExtensions.cs](url)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
