### ISSUE TITLE
Get-PnPFile doesn't create folders

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1131]
#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When files need to be created using Get-PnPFile in not existing folders on file systems the folders should be created. Inline with the behavior of Get-PnPProvisioningTemplate

#### Observed Behavior
When running:

`Get-PnPFile -Url $fileUrl -Path $path -Filename $fileName -AsFile`

and the $path doesn't exist an error message appears:

Could not find a part of the path ....

#### Steps to Reproduce
Run the following command while only part the $path exists:
Get-PnPFile -Url $fileUrl -Path $path -Filename $fileName -AsFile

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
