### ISSUE TITLE
Typo in time zone description

### ISSUE THREAD

**Issue by teylyn** [SharePoint/PnP-Sites-Core#1134]
I can't tell if this is Powershell, or core, or even Office 365

The description for the time zone id 17 shows as "Aukland Wellington". 

It should be "Auckland Wellington"

Note the "ck" in "Auckland"

thanks

**Comment by jansenbe** [comment]
Thanks for letting us know @teylyn . Changing this typo will however potentially break existing Sites core users, so for now we'll leave this as is.
