### ISSUE TITLE
List Security not handled

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1136]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When a list has unique permissions (broken inheritance) then it should be possible to e3xclude the list permissions from any updates.  When moving between multiple tenants the tenant name of accounts may not match. It should be possible to ignore security on lists. (Exclude Handler??) 

#### Observed Behavior

When a list with user account details included is part of a template then the following error  is thrown:

```

Apply-PnPProvisioningTemplate : The specified user i:0#.f|membership|myuser@mytenant.onmicrosoft.com could not be found.

```

#### Steps to Reproduce
Create list. 
break inheritance.
Set permissions
apply template to different tenant

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
