### ISSUE TITLE
Nested (child) terms are not provisioned when term set exists

### ISSUE THREAD

**Issue by oyvindam** [SharePoint/PnP-Sites-Core#1137]
Hi.

Just discovered this behaviour when trying to add a set of child terms to a term set. 

Everything is provisioned correctly on the initial run when no term sets exist in the term store. 
We the tried to update the term sets by adding child terms in the template.
In this case only the parent terms are provisioned and all child terms are eignored.

#### Category
[ ] Bug
[ x ] Enhancement 

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Child terms should be provisioned as declared in the template

#### Observed Behavior
Child terms are not provisioned when the term set already exists

#### Steps to Reproduce

Term set
-- Parent Term
---- Child Term  <-- Not provisioned when the term set exists in the term store
------ Child term <-- Not provisioned when the term set exists in the term store

Simple template example:
`            <pnp:TermSet Name="TestTermset_1" ID="{19E7E071-412A-476B-B60B-94BF25A4485E}" Language="1033">
              <pnp:Terms>
                <pnp:Term Name="TestTermParent_1" ID="{74FE0C5C-6F20-4693-9929-41E5F6BCBD85}" IsAvailableForTagging="false">
                  <pnp:Terms>
                    <pnp:Term Name="TestTermChild_1" ID="{B3521D72-1BF9-4932-9AA6-244D8B349F9F}">
                      <pnp:Terms>
                        <pnp:Term Name="TestTermChild_1_1" ID="{460E4831-ECA6-488A-A5B2-ACD995523126}">
                        </pnp:Term>
                      </pnp:Terms>
                    </pnp:Term>
                  </pnp:Terms>
                </pnp:Term>
              </pnp:Terms>
            </pnp:TermSet>`

**Comment by lscheuerman** [comment]
Yes, please fix this!

**Comment by NicolajHedeager** [comment]
This really needs to be fixed!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
