### ISSUE TITLE
Cannot create modern page using CSOM extensions

### ISSUE THREAD

**Issue by arunakshi** [SharePoint/PnP-Sites-Core#1138]
Hi,

 I am getting the following error while creating modern pages in classic sites via CSOM extension methods. The page is getting created but it fails to update the properties of the page. 

Category
[ ] Bug
[X] Enhancement

Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Expected or Desired Behavior
Expected Behavior is that it creates the modern pages and those pages can be openable. 

Observed Behavior
It breaks while creating the pages and I am getting the following error after setting properties and with ExecuteQuery operation. 

Here is the error which I am getting:
Column '**ClientSideApplicationId**' does not exist. It may have been deleted by another user. 

Steps to Reproduce
Create a modern page using CSOM extension methods in a classic site. I just followed MSDN docs and youtube videos.

Do we need to activate any feature in the SiteCollection to have ClientSideApplicationId column available in SiteCollection?

Any ideas please!

**Comment by arunakshi** [comment]
I found that this is working with **Site Pages** library. I tried with Pages library which result in that issue.

**Comment by stonekw** [comment]
I discovered the issue for me. My ClientContext was created for the root web of the site collection, however I was trying to create a client side page in a sub web. The spPagesLibrary property of the ClientSidePage class is getting assigned a list relative to the context passed into the constructor: 
`this.Context.Web.GetListByUrl(value)`

It seems it doesn't support passing in another context other than one created for the web where the page is going to be created.
