### ISSUE TITLE
Including PageContents handler in ProvisioningTemplateCreationInformation causes Method not found: 'System.String Microsoft.SharePoint.Client.WebParts.WebPartDefinition.get_ZoneId()'

### ISSUE THREAD

**Issue by bengtmoss** [SharePoint/PnP-Sites-Core#1140]
Category
[X] Bug
[ ] Enhancement
Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: December 2016

This code:

```
ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(ctx.Web);
ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);
```

results in the following exception:
Method not found: 'System.String Microsoft.SharePoint.Client.WebParts.WebPartDefinition.get_ZoneId()'

NOTE this workaround:
`ptci.HandlersToProcess ^= Handlers.PageContents;
`

But I got the impression that this bug had been fixed in connection with ApplyProvisioningTemplate
(#866)

**Comment by bengtmoss** [comment]
Any thoughts on this, anyone?

**Comment by JohanVanderBeach** [comment]
I'm getting the same issue with the latest code and also sharepoint 2013 on premises.

**Comment by NormanMann** [comment]
I'm having the same issue. 
SharePoint 2013 on premises and April 2017 Release. 
SharePoint Servers were not updated or changed. It worked earlier using the older Apply-SPOProvisioningTemplate Cmdlet.

**Comment by okms** [comment]
This issue is still here in June 2017 release

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
