### ISSUE TITLE
Overwriting existing page /SitePages/Home.aspx failed

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1141]
#### Category
[ X ] Bug
[ X ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Overwriting existing pages is the default option in PnP templates
It's only possible to export the welcome page.

I noticed the message below:

Overwriting existing page /SitePages/Home.aspx failed: The item that you are trying to delete is the current welcome page and cannot be deleted

Does this mean that the overwrite option of pages is floored?

Maybe a better way of doing this would be:

1. Set the welcome page Url to anything else than the welcome page.
2. Update the welcome page ( including overwrite)
3. Update the welcome page again.

#### Observed Behavior

```
PowerShell_ISE.exe Information: 0 : 2017-03-23 10:16:59.8092	[Pages]	[13]	[Debug]	Overwriting existing page /SitePages/Home.aspx	504ms	8c147d0c-6a66-48a9-8f83-0dfde49
9fe30
PowerShell_ISE.exe Error: 0 : 2017-03-23 10:17:00.2313	[Pages]	[13]	[Error]	Overwriting existing page /SitePages/Home.aspx failed: The item that you are trying to del
ete is the current welcome page and cannot be deleted. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPages.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTem
plateApplyingInformation applyingInformation)	926ms	8c147d0c-6a66-48a9-8f83-0dfde499fe30


```
#### Steps to Reproduce
Export and import PnP template with welcome page included

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
