### ISSUE TITLE
Navigation items are not created correctly

### ISSUE THREAD

**Issue by Smile4ever** [SharePoint/PnP-Sites-Core#1142]
#### Category
[ x ] Bug

#### Environment
[ x ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Navigation items should be created in the order they appear in the template.
Navigation items should keep their indentation if they have any.

#### Observed Behavior
Navigation items are created in alphabetical order, not in the order they appear in the provisioning template.
Navigation items are not created at the right indentation: they don't have indentation.

#### Steps to Reproduce
* Extract a template from a web with PnP PowerShell.
```
Connect-PnPOnline -Url http://xx.sharepoint.com/sites/SiteCollection
Get-PnPProvisioningTemplate -Out C:\sitetemplates\template.xml
```

* Import the template again using code:

```
string url = "http://xx.sharepoint.com/sites/SiteCollection";
string templateName = "template.xml";
string userName = "username@xx.onmicrosoft.com";
SecureString password;

XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider(@"C:\sitetemplates", "");

ClientContext context = new ClientContext(url);
context.Credentials = new SharePointOnlineCredentials(userName, password);
context.ExecuteQuery();

Web web = context.Web;
context.Load(web);
context.ExecuteQuery();

ProvisioningTemplate loadedTemplate = provider.GetTemplate(templateName);
web.ApplyProvisioningTemplate(loadedTemplate);
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
