### ISSUE TITLE
There should be a duplicate check for NavigationNodes

### ISSUE THREAD

**Issue by sebastianmattar** [SharePoint/PnP-Sites-Core#1147]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
I want to apply the same template several times to implement site collection updates. When adding navigation nodes the pnp framework should check if a similar node already exists and only add a new one if it does not exist yet.

I will happily implement the change myself if there is a chance it will be integrated with the main branch.

#### Observed Behavior
When provisioning NavigationNodes there is no check if a similar node already exists. Every template import will add a new navigation node with the same title and url.

#### Steps to Reproduce
Apply the following template multiple times.
```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.9.1611.0, Culture=neutral, PublicKeyToken=d8f0f7d8ea55cb0a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-DD6D590BBF6D4D31A19021D8512C86C6">
    <pnp:ProvisioningTemplate ID="TEMPLATE-DD6D590BBF6D4D31A19021D8512C86C6" Version="1">
      <pnp:Navigation>
        <pnp:CurrentNavigation NavigationType="StructuralLocal">
          <pnp:StructuralNavigation RemoveExistingNodes="false">
            <pnp:NavigationNode Title="Duplicate" Url="{site}" />
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>
      </pnp:Navigation>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

**Comment by wnzn** [comment]
You can solve this by setting RemoveExistingNodes to "true", although it would mean changes in the navigation of the destination site would be omitted.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
