### ISSUE TITLE
Not able to add PnP tokens as string

### ISSUE THREAD

**Issue by sagar2610** [SharePoint/PnP-Sites-Core#1149]
Hi,

Whenever I set a JSLink like ~siteCollection/_catalogs/masterpage/...., the "~siteCollection" is resolved by PnP to serverrelativeurl. I don't want it to resolve "~siteCollection".

Same problem while setting query of a searchResults webpart. path:{site}, it will resolve {site} and then add.
I want to add these tokens as it is.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
