### ISSUE TITLE
Bug (with fix): AzureBlob subfolder path issue in Provisioing logic

### ISSUE THREAD

**Issue by weshackett** [SharePoint/PnP-Sites-Core#1150]
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
If you store your PnP provisioning templates using Azure blob storage and have assets in sub folders when executed to provision an error is thrown about missing files. While debugging I determined it was within ObjectFiles.cs line 442(ish) in a method called GetFileStream. Within this method there is some path manipulation and it uses only \ and thus in blob storage scenarios incorrectly assembles the full path string. This then causes a silent exception to be handled that the file is not found.

#### Observed Behavior
Provisioning will complete, and only with verbose logging is the error shown. The file is never found in a subfolder

#### Steps to Reproduce
Create any PnP template which stores assets such as aspx layouts in a sub folder. Deploy these to Azure blob storage and then run provisioning with verbose logging.

#### Code to fix

I wasn't sure how to do a proper PR so here is the method with the fixes:

private static Stream GetFileStream(ProvisioningTemplate template, Model.File file)
        {
            var fileName = file.Src;
            var container = String.Empty;
            if (fileName.Contains(@"\") || fileName.Contains(@"/"))
            {
                var tempFileName = fileName.Replace(@"/", @"\");
                container = fileName.Substring(0, tempFileName.LastIndexOf(@"\"));
                fileName = fileName.Substring(tempFileName.LastIndexOf(@"\") + 1);
            }

            // add the default provided container (if any)
            if (!String.IsNullOrEmpty(container))
            {
                if (!String.IsNullOrEmpty(template.Connector.GetContainer()))
                {
                    if(container.StartsWith("/"))
                    {
                        container = container.TrimStart("/".ToCharArray());
                    }

                    if (template.Connector.GetType() == typeof(OfficeDevPnP.Core.Framework.Provisioning.Connectors.AzureStorageConnector))
                    {
                        var fullFileName = file.Src;

                        if (template.Connector.GetContainer().EndsWith("/"))
                        {
                            container = $@"{template.Connector.GetContainer()}{container}";
                        }
                        else
                        {
                            container = $@"{template.Connector.GetContainer()}/{container}";
                        }
                    }
                    else
                    {
                        container = $@"{template.Connector.GetContainer()}\{container}";
                    }
                }
            }
            else
            {
                container = template.Connector.GetContainer();
            }

            var stream = template.Connector.GetFileStream(fileName, container);
            if (stream == null)
            {
                //Decode the URL and try again
                fileName = WebUtility.UrlDecode(fileName);
                stream = template.Connector.GetFileStream(fileName, container);
            }

            return stream;
        }
    }

**Comment by jansenbe** [comment]
Thanks for this fix @weshackett. We'll include this in the June release
