### ISSUE TITLE
Get-PnPProvisioningTemplate : Field or property "MajorVersionLimit" does not exist.

### ISSUE THREAD

**Issue by dannyfoncke** [SharePoint/PnP-Sites-Core#1152]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
generation of the provsioning template 

The 'source' site is a standard, via UI, created publishing subsite. Nothing added, deleted or changed. 
SharePoint 2013 is a single server dev machine
-CurrentCredentials has all rights 

#### Observed Behavior

PS C:\Users\......\Documents\WindowsPowerShell\Modules\SharePointPnPPowerShell2013> Connect-PnPOnline http://..../sites/pub3/test1 -CurrentCredentials
PS C:\Users\......\Documents\WindowsPowerShell\Modules\SharePointPnPPowerShell2013> Get-PnPProvisioningTemplate
**Get-PnPProvisioningTemplate : Field or property "MajorVersionLimit" does not exist.**
At line:1 char:1
+ Get-PnPProvisioningTemplate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

**Comment by thearturs** [comment]
What CU are you running?

**Comment by pitsta** [comment]
Hi there I am getting the same issue. I am using the latest CU May 2017 for SharePoint 2013 On-prem.

This is the script i am running and the output:

PS C:\WINDOWS\system32> Get-PnPProvisioningTemplate -Out "C:\Users\ShaunPitt\OneDrive - QIKSOLVE PTY LTD\Projects\Ensign\deviations\p
rovisioning\lists\pnp_lists_ensigntest.xml" -Handlers Lists
powershell.exe Information: 0 : 2017-06-07 11:05:05.2255        [Extraction]    [10]    [Debug] Code execution scope started    0ms
ecd38085-a7b0-46c9-bba2-adb8b41bdf99
powershell.exe Information: 0 : 2017-06-07 11:05:05.2255        [Extraction]    [10]    [Debug] Base template available: BLANKINTERNE
T0template      0ms     ecd38085-a7b0-46c9-bba2-adb8b41bdf99
powershell.exe Information: 0 : 2017-06-07 11:05:05.2255        [Extraction]    [10]    [Debug] ProgressDelegate registered     2ms
ecd38085-a7b0-46c9-bba2-adb8b41bdf99
powershell.exe Information: 0 : 2017-06-07 11:05:05.2255        [Extraction]    [10]    [Debug] MessagesDelegate registered     3ms
ecd38085-a7b0-46c9-bba2-adb8b41bdf99
powershell.exe Information: 0 : 2017-06-07 11:05:05.5174        [List instances]        [10]    [Debug] Code execution scope started
0ms     ecd38085-a7b0-46c9-bba2-adb8b41bdf99
powershell.exe Information: 0 : 2017-06-07 11:05:05.9046        [List instances]        [10]    [Debug] Code execution scope ended
389ms   ecd38085-a7b0-46c9-bba2-adb8b41bdf99
powershell.exe Information: 0 : 2017-06-07 11:05:05.9046        [Extraction]    [10]    [Debug] Code execution scope ended      684ms
ecd38085-a7b0-46c9-bba2-adb8b41bdf99
Get-PnPProvisioningTemplate : Field or property "MajorVersionLimit" does not exist.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Out "C:\Users\ShaunPitt\OneDrive - QIKSO ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

**Comment by BitSchupser** [comment]
I also experienced the same issue working with SP 2013 on premise.

I found out that the fields "MajorVersionLimit" and "MajorWithMinorVersionsLimit" are not exposed to the client APIs in SharePoint 2013 (see https://sharepoint.stackexchange.com/a/131563). Could this fact pose the problem?

Are there any workarounds for this problem?

**Comment by Justin-Nash** [comment]
How does this fix the issue? 

Get-PnPProvisioningTemplate : Field or property "MajorVersionLimit" does not exist.

Your proposed solution is floored, there are document libraries that have “MajorVersionLimit” how do you get there template? 

I would advise creating the template without the “MajorVersionLimit” with a warning not an error.
