### ISSUE TITLE
What constitutes a NoScriptSite

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Sites-Core#1153]
#### Category
[x] Question

#### Environment
[x] Office 365 / SharePoint Online

Today the extension method **web.IsNoScriptSite** checks effective permissions as well as which **WebTemplate** is used. I propose to remove the template check, as you are allowed to turn on scripting for the any site which has it disabled by default - thus checking the effective permissions should be enough.

**Comment by jansenbe** [comment]
Hi Mikael,

I already removed the webtemplate check on 27/3 as today you can have modern team sites with "noscript" disabled (requires you to set it using PS/API). Will close this issue
