### ISSUE TITLE
PNP templates and custom files

### ISSUE THREAD

**Issue by LeoGoGarcia** [SharePoint/PnP-Sites-Core#1154]
#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Hello all, 

is there a easy way to, using GetPnPProvisioningTemplate and ApplyPnPProvisioningTemplate, we get all files inside libraries too? 

I know there is a pnp:file section in XML schema but in my case we're not saving templates into files (we're getting templates on run-time). 

Thanks in advance, 

Leonardo

**Comment by Pieter-Veenstra** [comment]
Hi @LeoGoGarcia,

Currently the answer is no.

I've been working on a solution for this, which is based on PnP PowerShell. I expect to make this available to the community straight after Easter.

I've not included the meta data of the documents. My main aim was to be able to copy site assets and display templates from one tenant to another. Would this work for you?

Thanks,
Pieter

**Comment by LeoGoGarcia** [comment]
Hello @Pieter-Veenstra , 

a simple copy would work for me, yes. I don't need metadata neither. 

If would share your script it'll be highly apreciated, yes. If I adapt it into my C# solution I can also share with the community. 

In your case it'll be a copy of documents *AFTER* the applycation of PNP template or you'll integrate files on GetPnPProvisioningTemplate (and reference them on the template) to be applied during ApplyPnPProvisioningTemplate?

Cheers, 

Leonardo

**Comment by Pieter-Veenstra** [comment]
My scripts do quite a bit more. See the for the details here:

https://veenstra.me.uk/2017/03/30/office-365-sharepoint-20132016-replicating-or-migrating-sharepoint-sites/

In short the aim of these scripts are to copy whole tenants or part of a tenant from one tenant to another.

**Comment by LeoGoGarcia** [comment]
I leave a comment on your blog, @PieterVeenstra . 

Looking forward for your scripts, then. 

Thanks in advance,

Leonardo
