### ISSUE TITLE
clientcontext.Web.ApplyProvisioningTemplate (called from import-pnpTermGroupFromXml) error

### ISSUE THREAD

**Issue by CHinton123** [SharePoint/PnP-Sites-Core#1155]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4849.1000

#### Expected or Desired Behavior
Expect that Term Group be created and populated without throwing exception

#### Observed Behavior
Import-pnpTermGroupFromXML throws exception "Specified argument was out of the range of valid values.  Parameter name: index

#### Steps to Reproduce

1. Create a term group in SharePoint via web interface, in my case named "foo".
2. Create term set in Foo group named "Foo Set"
3. Create term "Foo Term 1" in "Foo Set"
4. Create Term "Foo Term 2" in "Foo Set"
5. Export term set XML with pnp-powershell command export-pnpTermGroupToXML -identity "Foo" -out Foo.xml
6. Delete "Foo Set" from Group "Foo"
7. Delete Group "Foo"
8. Import term group with pnp-powershell command Import-pnpTermGroupFromXml -Path foo.xml
9. Observe error text:

> Import-pnpTermGroupFromXml : Specified argument was out of the range of valid values.
> Parameter name: index
> At line:1 char:1
> + Import-pnpTermGroupFromXml -Path foo.xml
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Import-PnPTermGroupFromXml], ServerException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Taxonomy.ImportTermGroupFromXml
> 

Module versions:

> PS C:\temp\RollUpSite> get-module | ft Version,Name -a
> 
> Version     Name
> -------     ----
> 16.0.6008.0 Microsoft.Online.SharePoint.PowerShell
> 3.1.0.0     Microsoft.PowerShell.Management
> 3.0.0.0     Microsoft.PowerShell.Security
> 3.1.0.0     Microsoft.PowerShell.Utility
> 2.14.1704.0 SharePointPnPPowerShell2013

**Comment by jchilde** [comment]
I am seeing a similar error with web.ApplyProvisioningTemplate when run from an Azure Function.  
Using 2.14.1704 and CSOM 16.1.6323.1200.

I am not using any term groups.

Error: Exception while executing function: Functions.AttorneySite. Microsoft.SharePoint.Client.Runtime: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'Microsoft.SharePoint.Client.Taxonomy.TermStore'.
