### ISSUE TITLE
ListExtension GetListByTitle

### ISSUE THREAD

**Issue by ypcode** [SharePoint/PnP-Sites-Core#1156]
Issue with the GetListByTitle extension method
==============================

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I wanted to use the Get-PnPList or Get-PnPListItem cmdlets with a user account that has limited permissions on the site but sufficient permissions on the target list.

#### Observed Behavior
Using the PowerShell cmdlet Get-PnPList -Identity "MyList" or Get-PnPListItem -List "MyList", I realized that I run into a System.UnauthorizedAccessException,
The user has Edit permissions on the library yet.
After investigation, I noticed the exception is raised at the call to the GetListByTitle() extension method

#### Steps to Reproduce
I have a user in the default visitors SP Group, that has basic read access on almost every assets in the site and Edit permissions on the target list.
When using GetListByTitle() extension method, an Access Denied is thrown

I copied the code of the Get-PnPList cmdlet in a test app, and duplicated the GetListByTitle extension method and used another way of loading the List object to make sure it is working,

```
public static List MyGetListByTitle(Web web, string listTitle, params Expression<Func<List, object>>[] expressions)
        {
            var baseExpressions = new List<Expression<Func<List, object>>> { l => l.DefaultViewUrl, l => l.Id, l => l.BaseTemplate, l => l.OnQuickLaunch, l => l.DefaultViewUrl, l => l.Title, l => l.Hidden, l => l.RootFolder };

            if (expressions != null && expressions.Any())
            {
                baseExpressions.AddRange(expressions);
            }

            // ... Other check here

            // Code replacement
            List list = web.Lists.GetByTitle(listTitle);
            web.Context.Load(list, baseExpressions.ToArray());
            web.Context.ExecuteQueryRetry();
            return list;

            // Original code
            //var query = web.Lists.IncludeWithDefaultProperties(baseExpressions.ToArray());
            //var lists = web.Context.LoadQuery(query).Where(l => l.Title.Equals(listTitle, StringComparison.InvariantCultureIgnoreCase));
            //web.Context.ExecuteQueryRetry();
            //return lists.FirstOrDefault();
        }

```
This code is achieving what I was looking for.
However, before submitting it as a a Pull Request, I was wondering if there was something the original code is supposed to do more or better
The original code is traversing all the lists, including the ones my user has no permissions on, which, I suppose causes this trouble.

Kind regards,
Yannick

**Comment by ypcode** [comment]
After reviewing this issue, I realized the code is supposed to fetch the list by its name in a case insensitive way. However the issue remains even if I pass the list title with accurate casing. Should we go for a try and retry the other way when the exception is raised?

**Comment by RafalUrbanski** [comment]
I have also encountered Access Denied problem when trying to call GetListByTitle() extension method with a user who belongs to Visitors group only. What I found out during tests is that one of the baseExpressions , exactly l.RootFolder, is causing the issue. Removing this property from Includes list solved the issue.
When I tried your version @ypcode  it worked with l.RootFolder as well. 
Any chance of updating/modyfing code so that it works with both power users and regular ones?

**Comment by RafalUrbanski** [comment]
I have checked the code with fiddler and it seems that this line of code causes issues:
`var lists = web.Context.LoadQuery(query).Where(l => l.Title.Equals(listTitle, StringComparison.InvariantCultureIgnoreCase));`
Unfortunatelly the **_Where_** part is outside of the **_LoadQuery()**_ and is not a part of query sent to the SharePoint. If user do not have Super User privileges, it must happen that he does not have rights to RootFolder of one of the lists, which causes Access Denied error.
