### ISSUE TITLE
403 Forbidden when Extracting template from mixed authentication web application using Windows Credentials

### ISSUE THREAD

**Issue by josvanvlimmeren** [SharePoint/PnP-Sites-Core#1157]
#### Category
Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x ] SharePoint 2016
[x ] SharePoint 2013

I am using SharePoint 2016 on a web application with NTLM and a custom Claims Provider (ADFS) enabled. To make this work with windows credentials, the "X-FORMS_BASED_AUTH_ACCEPTED" header has to be added with a value of "f".

#### Expected or Desired Behavior
When logging in on a mixed mode authentication web application. I expect the extraction proces to use the web object on which I call the "GetProvisioningTemplate" method.

#### Observed Behavior
I have created a ClientContext object with an eventhandler for adding the required "X-FORMS_BASED_AUTH_ACCEPTED" header. And this is working fine. However when extracting the template in SiteToTemplateConversion.cs, Method: GetRemoteTemplate, Line 118, the ClientContext get's cloned (with the same URL as my own context) and this proces does not copy the eventhandler.

Code for adding the event handler as reference:

```
context = new ClientContext(url);
context.Credentials = new System.Net.NetworkCredential(username, password);
context.ExecutingWebRequest += new EventHandler<WebRequestEventArgs>(RequestHandler);

        private static void RequestHandler(object sender, WebRequestEventArgs e)
        {
            //Add the header that tells SharePoint to use Windows authentication.
            e.WebRequestExecutor.RequestHeaders.Remove("X-FORMS_BASED_AUTH_ACCEPTED");
            e.WebRequestExecutor.RequestHeaders.Add("X-FORMS_BASED_AUTH_ACCEPTED", "f");
        }
```

#### Steps to Reproduce
Extract a template from a mixed authentication, on premise site, using Windows Credentials.

#### Possible solution
Not cloning the context

**Comment by biste5** [comment]
See #615

**Comment by josvanvlimmeren** [comment]
@biste5 You're right, it's the same problem and I also used the same workaround.
