### ISSUE TITLE
Update workflow subscription

### ISSUE THREAD

**Issue by SuleymanA** [SharePoint/PnP-Sites-Core#1159]
#### Category
[X] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I have build SPD 2013 workflow and exported using PnP. I am now provisioning the workflow definition with subscriptions. Provisioning now works fine. I was having issues with duplicate subscription but was able to fix it by including "SharePointWorkflowContext.Subscription.Name". Now the provisioning engine is able to find existing subscription and deletes it. This works as expected but I don't think this is the correct way to do it. Normally when using SPD and a new version of the workflow is published a new subscription is created and the old one is set to "No new instances" (subscription enabled property set to false). 

#### Observed Behavior
When a new version of the workflow definition with the same subscriptions is provisioned it removes the existing subscription and adds it again to the list, resulting is running workflows being terminated. New version of the workflow is available when a new workflow instance is started. 

When only the workflow definition is provisioned (without subscriptions) the workflow instances on the lists are not terminated. When a new workflow instance is started it shows the old version of the workflow.

#### Steps to Reproduce
- Create a SPD workflow
- Export it
- Include the workflow definition and subscription (with minimal number of properties) in a provisioning template
- Provision the workflow definition and subscriptions
- Start a workflow on a list item
- Change workflow definition (change a write to history text)

Issue 1 (running workflows terminated):
- Provision the changes using the same template
- Check running workflows (expected: workflows are terminated)
- Start a new workflow instance (expected: change made to WF definition visible)

Issue 2 (changes not visible): 
- Provision the changes using a different template without workflow subscriptions
- Check running workflows (expected: still running)
- Start a new workflow instance (expected: change made to WF definition not visible)

I am not sure whether this is a bug, enhancement or just a question. I am looking for a way to update WF definition without terminating running workflows (similar to SPD behavior). I expect that this is possible by including the old subscription and setting it to disabled and including a new subscription with a different name but I don't want to rename the workflow on every update. Ideally PnP should update the existing subscription (similar to opening and saving workflow association in SharePoint U) instead of removing and readding the subscription (I can't image a scenario where this is the desired behavior).  

Suggested change to workflow objecthandler:
- Remove the part that removes the existing workflow subscription
- Don't create a new workflow subscription
- Update existing subscription properties
- Publish existing updated workflow subscription (not sure how CSOM handles this, as an update or as new subscription). 

Looking forward hearing your thoughts on how to handle workflow definition updates for list workflows.

---------------------------
There is also a bug in workflow object handler, including it here because it is related to my overall question of how to update exisiting subscriptions:
Query used to find existing subscription (workflowSubscription = existingWorkflowSubscriptions.FirstOrDefault((s => s.PropertyDefinitions["SharePointWorkflowContext.Subscription.Name"] == subscriptionName && s.DefinitionId == subscription.DefinitionId));) will always return the first subscription match on name and WF definition ID. When the workflow subscription is used on multiple lists (for example a review workflow that is added to all libraries) the subscription found first in the subscriptions list is removed (on one library) all others are not touched. This will probably work fine with a site workflow but it doesn't for list workflows. It should also include list id (EventSourceId) in the query for list workflows.

**Comment by SuleymanA** [comment]
Additional test done:
- Update the subscription by setting it to enabled to false. This also resulted in the subscription being deleted and running workflows terminated. So as far as I can see there is no way to update a subscription using the provisioning template.

**Comment by amirkhanRC** [comment]
Any new information or updates regarding this issue?

**Comment by PaoloPia** [comment]
Hi,
We updated the engine to support workflow definitions updates. Can you give it a try in the DEV branch. Thanks. In case of any further issue/need, please feel free to open a new issue here.
