### ISSUE TITLE
Issue with Provisioning Templates for Global Navigation

### ISSUE THREAD

**Issue by CharlieDLee** [SharePoint/PnP-Sites-Core#1173]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected Behavior
I am using OfficeDevPnP.Core (latest release) in order to synchronise the top nav bar across multiple site collections.  The site collections are created as classic sites and not modern group sites (e.g. through admin interface not through SharePoint homepage).  Though the homepage of each is a modern page (don't think this has any impact anyway).

Each of the navigation nodes in the root site will either point to an explicit url (e.g. https://tenantname/sites/sitecollection or an external resource e.g. https://mywebsite.co.uk)

I am extracting the navigation by saving a template using Web.GetProvisioningTemplate() and only specifying the Navigation handler.

My expectation is that all nodes would be replicated to the other Site Collections when applied with Web.ApplyProvisioningTemplate().

#### Observed Behavior
What I am actually seeing is that all nodes which reference explicit site collection urls are incorrect when the template is applied.  This seems to be because the template rewrites the navigation node url to {site}/sites/sitecollection.  This is incorrect and results in the /sites/sitecollection element being applied after the full url to the site itself (e.g. https://tenantname.sharepoint.com/sites/site1/sites/site2).

Any node which references an external resource (e.g. https://www.google.co.uk) also fails when the template is applied.  This time there is an error thrown by ApplyProvisioningTemplate.  The error message is:

_Microsoft.SharePoint.Client.ServerException: 'The URL format was invalid.'_

#### Steps to Reproduce

- Create a new site collection from https://tenantname-admin.sharepoint.com
- Use the team site template
- Add a new modern page and set as homepage
- Create some Navigation nodes in the top nav bar as described above
- In a console application (or similiar) use OfficeDevPnP.Core to extract just the navigation as a template
```
ProvisioningTemplateCreationInformation ptci =
                new ProvisioningTemplateCreationInformation(web);
ptci.HandlersToProcess = Handlers.Navigation;

ProvisioningTemplate template = web.GetProvisioningTemplate(ptci);
```
- Apply this template with console application to another new site collection created in the same way
```
ProvisioningTemplateApplyingInformation ptai =
                new ProvisioningTemplateApplyingInformation();
ptai.ClearNavigation = true;
ptai.HandlersToProcess = Handlers.Navigation;
            
web.ApplyProvisioningTemplate(template, ptai);
```

**Comment by KbWorks** [comment]
do you use xml to provision or hardcoded? if xml please provide it

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
