### ISSUE TITLE
NavigationNode removes querystring

### ISSUE THREAD

**Issue by ndepaoli** [SharePoint/PnP-Sites-Core#1174]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
In the Navigation tag of my template I have something like this:

<pnp:NavigationNode Title="Link1" Url="{sitecollection}/Lists/List1/EditForm.aspx?ID=1"/>

I'm expecting that in my QuickLaunch menu I can find a navigation node that redirects me in the EditForm of the item with ID=1.

#### Observed Behavior
For some reason the query string part of my URL is removed from the link in the QuickLaunch menu, so the link redirects me to {sitecollection}/Lists/List1/EditForm.aspx.

#### Steps to Reproduce
Use this xml template
[TestTemplate.txt](https://github.com/SharePoint/PnP-Sites-Core/files/989445/TestTemplate.txt)

**Comment by KbWorks** [comment]
Hi I think it is not the problem of PnP have you tried it manually? i did and found out that when added manually it removes the parameter id as well.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”

**Comment by PedroMordeP** [comment]
Hi, 
This issue is still present on the latest version 3.7.1903.0 of the SharePoint PnP PowerShell Online on Modern sites.
If I add the item manually the link keep the querystring on the site.
Doesn't work if:
- Executing the command
Add-PnPNavigationNode -Title "Contoso" -Url "https://tenant.sharepoint.com/sites/sitecollection/Si
tePages/mypage.aspx?playlist=1" -Location "QuickLaunch"

- Or if defined on the template
<pnp:NavigationNode Title="Kick-start your Office 365 usage" Url="https://tenant.sharepoint.com/sites/sitecollection/Si
tePages/mypage.aspx?playlist=1" />

**Comment by jsmileyb** [comment]
I've experienced this, too. Attempting to add navigation from CSV (with children) - does not work. However, when I add them individually, it works fine if you include -External.

**Comment by PedroMordeP** [comment]
Correct if using IsExternal="true" attribute the query string remains

Example
`<pnp:NavigationNode Title="My Page Title" Url="{site}/SitePages/mypage.aspx?playlist=15" IsExternal="true"/>`

**Comment by jsmileyb** [comment]
Thank you for the reply @PedroMordeP. Not sure where I fouled up, but it's working. 

Much Appreciation!
