### ISSUE TITLE
The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by tom-daly** [SharePoint/PnP-Sites-Core#1175]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Attempting to run PnP-PowerShell commands to get webpart xml from a page (this was working a month ago).

#### Observed Behavior
403 error with Get-PnPWebPartXml command. I watched the output from fiddler and get this. I was looking into this and it seems that powershell doesn't have a user agent in the web request which causes it to fail?

X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.

**the get request [this works copy/paste in a browser]**
/sites/cf8/_vti_bin/exportwp.aspx?pageurl=https://bandrdev.sharepoint.com:443/sites/cf8/Lists/NavBoxList/AllItems.aspx&guidstring=e0e1abe8-3f0b-423f-823b-caed92b5ca1b

PS C:\Windows\system32> Connect-PnPOnline -Url "https://bandrdev.sharepoint.com/sites/cf8" –Credentials (Get-Credential)
$wpLocation = "/sites/cf8/Lists/NavBoxList/AllItems.aspx" 
$allWebParts = Get-PnPWebPart -ServerRelativePageUrl $wpLocation
$wp = Get-PnPWebPart -ServerRelativePageUrl $wpLocation -Identity $allWebParts[0].Id
$wpXml = Get-PnPWebPartXml -ServerRelativePageUrl $wpLocation -Identity $wp.Id
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Get-PnPWebPartXml : The remote server returned an error: (403) Forbidden.
At line:5 char:10
+ $wpXml = Get-PnPWebPartXml -ServerRelativePageUrl $wpLocation -Identi ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPWebPartXml], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.WebParts.GetWebPartXml
 

PS C:\Windows\system32> $error[0].Exception.StackTrace
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.PageExtensions.GetWebPartXml(Web web, Guid webPartId, String serverRelativePageUrl)
   at SharePointPnP.PowerShell.Commands.WebParts.GetWebPartXml.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()

PS C:\Windows\system32>

#### Steps to Reproduce
Commands that I ran trying to export webpart off a page.

`Connect-PnPOnline -Url "https://bandrdev.sharepoint.com/sites/cf8" –Credentials (Get-Credential)
$wpLocation = "/sites/cf8/Lists/NavBoxList/AllItems.aspx" 
$allWebParts = Get-PnPWebPart -ServerRelativePageUrl $wpLocation
$wp = Get-PnPWebPart -ServerRelativePageUrl $wpLocation -Identity $allWebParts[0].Id
$wpXml = Get-PnPWebPartXml -ServerRelativePageUrl $wpLocation -Identity $wp.Id`

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
