### ISSUE TITLE
GetProvisioningTemplate fails on formula errors in Calculated Columns

### ISSUE THREAD

**Issue by oyvindam** [SharePoint/PnP-Sites-Core#1176]
#### Category
[ ] Bug
[ x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

When a Calculated Field contains an erroneous formula the framework throws an error and execution stops. This specifically happens when a column referenced in the formula no longer exists.

The behaviour occurs in [ObjectField.cs](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs#L217).

When fieldRefs in the formula are iterated on a missing field will result in a null value and subsequently a NullReferenceException.
`var referencedField = fields.GetFieldByInternalName(fieldInternalName);`

The issue also applies to PnP PowerShell, but errors thrown here only result in "object reference not found" and the code exits with no clear error message for the user.

A proper error message would really help. 
The formula has errors anyway, so maybe just inform the user, insert a dummy formula and continue execution.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
