### ISSUE TITLE
Error using PnPDev for SP 2013

### ISSUE THREAD

**Issue by jpcostach** [SharePoint/PnP-Sites-Core#1178]
When I follow the tutorial https://github.com/SharePoint/PnP/blob/master/Samples/Provisioning.Framework.Console/Provisioning.Framework.Console/Program.cs to get the provisioning template, I get the following error:

Field or property "Audit" does not exist.

#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug

#### Environment
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4569.1506

#### Expected or Desired Behavior
To get the XML provisioning template.

#### Observed Behavior
It starts to get the information running successfully step 1 and 2 but the code crashes in step 3 with: "An unhandled exception of type 'Microsoft.SharePoint.Client.ServerException' occurred in Microsoft.SharePoint.Client.Runtime.dll"

#### Steps to Reproduce
Just execute the code from the sample, using network credentials and it crashes in step 3. The output message is: Field or property "Audit" does not exist.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
