### ISSUE TITLE
AddJsLink - CustomAction ScriptLink ( on premise )

### ISSUE THREAD

**Issue by showenx** [SharePoint/PnP-Sites-Core#1181]
Which PnP repository should you use to report the issue?

PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
Category

[ ] Bug
[x ] Enhancement

Environment

[] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

Expected or Desired Behavior

pnp core offers options to refer js link as script tag format.

Observed Behavior

for PnP Core solution, in JavaScriptExtensions class, function AddJsLink, currently the javascript reference is implemented via dynamic loading using js

scripts.Append(@"
if (scriptsSrc.indexOf('{1}') === -1)  {  
    var newScript = document.createElement('script');
    newScript.id = '{0}';
    newScript.type = 'text/javascript';
    newScript.src = '{1}';
    headID.appendChild(newScript);
    scriptsSrc.push('{1}');
}".Replace("{0}", key).Replace("{1}", link));
is it possible to have an option to render the js reference in traditional way as a script tag
<script type='text/javascript' src='[ref_url]'></script>

The change has been updated in SharePoint online , can we please also have this update applied in SharePoint 2013, 2016?

related issue: https://github.com/SharePoint/PnP-Sites-Core/issues/963

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
