### ISSUE TITLE
Sharepoint o365 Webpart added multiple time even if Overwrite false

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/PnP-Sites-Core#1188]
Please refer to this item: https://github.com/SharePoint/PnP-Provisioning-Schema/issues/180

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
