### ISSUE TITLE
Web Part titles are not set and localized correctly on a Web Part Page

### ISSUE THREAD

**Issue by DennisJantos** [SharePoint/PnP-Sites-Core#1193]
#### Which PnP repository should you use to report the issue? 
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I have a Web Part Page with two zones (“Body” and “LeftColumn”). The first zone (“Body”) includes three Web Parts and the second (“LeftColumn”) includes four Web Parts. All of the Web Parts in the PnP template file have a zone and an order specified, e.g.  
<pnp:WebPart Title="{resource:PageHomeSiteInfoTitle}" Zone="RightColumn" Order="1">
I use resource files (English and German) to localize the artifacts in the PnP template file.
If I create a new Site Collection and apply the template afterwards, I expect the Web Part titles to be set and localized correctly.

#### Observed Behavior
If I create a new Site Collection and apply the template afterwards, all of the Web Part titles have been set and localized correctly except the first Web Parts of each zone.

#### Steps to Reproduce
1. Create a PnP Template including a Web Part Page, e.g.
<pnp:File Src="SitePages\HomeTest.aspx" Folder="{site}/SitePages" Overwrite="true" Level="Published">
          <pnp:Properties>
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:Web Part Page}" />
            <pnp:Property Key="HTML_x0020_File_x0020_Type" Value="SharePoint.WebPartPage.Document" />
          </pnp:Properties>
		   <pnp:WebParts>
		   ...
		   </pnp:WebParts>
The Web Part Page should include at least two zones with at least two Web Parts each. Use localization for the Web Part titles with ressource files and at least two languages.

2. Apply the template two a Site Collection.

Expected result: The title of the first Web Part of each zone is not set and localized correctly. All other Web Part titles are set correctly.

#### First analysis results
I tried to analyze the behavior and found the following code in line 65 – 69 of file LocalizationExtenstion.cs:
https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/LocalizationExtensions.cs

#if !SP2016
                    var partOnPage = allParts.FirstOrDefault(w => w.ZoneId == webPart.Zone && w.WebPart.ZoneIndex == webPart.Order);
#else
                    var partOnPage = allParts.FirstOrDefault(w => w.WebPart.ZoneIndex == webPart.Order);
#endif

Since my environment is SP2016 these lines of code might be causing the issue.

It seems that SharePoint sets the ZoneIndex to 0 by default for the first Web Part added to a zone, which means I have two Web Parts with ZoneIndex = 0 on my page. Because the ZoneId is not taken into account when using SP2016, the first Web Part of each zone cannot be determined correctly in the following line: 
var partOnPage = allParts.FirstOrDefault(w => w.WebPart.ZoneIndex == webPart.Order);
therefore the title of the Web Parts cannot be set and localized correctly.

Why is there a difference between SP2016 and all other versions?

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
