### ISSUE TITLE
Provision .WebPart file is not working in templateprovisioning

### ISSUE THREAD

**Issue by khha** [SharePoint/PnP-Sites-Core#1198]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
.WebPart file is uploaded to the webpart gallery

#### Observed Behavior
The .WebPart file is not uploaded to the webpart gallery

#### Steps to Reproduce
Connect to the sitecollection. Add .WebPart file in the same directory as where the xml template is located. Start provisioning (Apply-PnPProvisioningTemplate -Path "D:\template.xml").

This is inside my template.xml file:
```
<pnp:Files>
        <pnp:File Src="logo.png" Folder="Style%20Library" Overwrite="true" Level="Published"/>
        <pnp:File Src="Yammer.webpart" Folder="Web%20Part%20Gallery" Overwrite="true" Level="Published"/>
      </pnp:Files>
```

The logo is provisioned succesfully, the .WebPart file not. I do not get any errors in the powershell console. When I debug I see here is throwed an exception:

Method: 
`public static File UploadFile(this Folder folder, string fileName, Stream stream, bool overwriteIfExists)`

Code snipped: 
```
var file = folder.Files.Add(newFileInfo);
            folder.Context.Load(file);
            folder.Context.ExecuteQueryRetry();
```

This is the error when I debug the core.

`The object specified does not belong to a list.`

**Comment by KbWorks** [comment]
i think it is due that your web part gallery is not the folder but it is _catalogs/wp have you tested it with that?

**Comment by khha** [comment]
Yes, now it is working fine. Thank you.
