### ISSUE TITLE
Usage of relative paths in PnP Provisioning templates

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-Sites-Core#1199]
#### Category
[x] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
We because we deliver multiple site templates to our customers per projects, we have multiple templates per repository.  
Some templates share the same files, so we'd like to have these common files in a folder and reference those from both templates in a structure that looks like that.  
```
-repo--commonresources--files  
     |--template1--template1.xml (and some other files)  
     |--template2--template2.xml (and some other files)  

```
The reference looks like that ..\commonresources\file1.ext

#### Observed Behavior
Convert-PnPProvisioningTemplate works but the Apply-PnProvisioningTemplate from the .pnp file fails stating the file is missing

#### Steps to Reproduce
- replicate the same file structure
- have relative references for files
- convert the template to a .pnp file
- apply to a site collection the .pnp template

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
