### ISSUE TITLE
No way to remove permissions from an existing RoleDefinition

### ISSUE THREAD

**Issue by sebastianmattar** [SharePoint/PnP-Sites-Core#1201]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
If I define a RoleDefinition in my pnp template I would expect the framework to set the RoleDefinition permissiosn exactly as specified. 

#### Observed Behavior
This is not the case, the pnp framework adds the specified permissions to the existing permissions of the role definition. I found no way to change this behaviour (e.g. to remove permissions from a RoleDefinition)

#### Steps to Reproduce
1. Apply a pnp template with a role definition
2. Apply a pnp template with fewer permissions for the same role definitions

**Comment by hyankov** [comment]
It's not a bug, it's [by design](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs#L211). You should consider clearing/removing the `RoleDefinition` yourself, before (re)applying the second template.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
