### ISSUE TITLE
WebExtensions.WebExistsFullUrl return true when site collection does not exists

### ISSUE THREAD

**Issue by josvanvlimmeren** [SharePoint/PnP-Sites-Core#1202]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I have a Clientcontext for https://xxx.sharepoint.com/teams/team1 (this sitecollection does not exists yet. I use this to call context.WebExistsFullUrl("https://xxx.sharepoint.com/teams/team1") and expect te get false in return. 

#### Observed Behavior
The context is cloned with the url parameter. However the cloned context had a web for https://xxx.sharepoint.com, the root site which does exist. A check is done whether the Title of the site can be retreived and true is returned. 

So this method tells me a higher level site exists, not the site i requested.

#### Steps to Reproduce
Call context.WebExistsFullUrl(...) with a url for a site collection which does not exist.

#### Workaround
In stead of checking whether the Title can be retreived, check wheter context.Web.Url equals the requested url parameter of the function on line 242.

OLD:
.....
testContext.Load(testContext.Web, w => w.Title);
testContext.ExecuteQueryRetry();
exists = true;
.....

NEW:
testContext.Load(testContext.Web, w => w.Url);
testContext.ExecuteQueryRetry();
if (webFullUrl.Equals(testContext.Web.Url, StringComparison.CurrentCultureIgnoreCase))
{
     exists = true;
}

**Comment by johannesekstrand** [comment]
I was experiencing the same thing a couple of weeks ago (in on-prem). My conclusion was that the behaviour was dependent on how you create the clientcontext. If I just created it by doing new ClientContext(<siteurl>) it would as you say tell me if a site collection higher up existed. The same thing happened when I used PnP AuthenticationManager with the help of GetAppOnlyAuthenticatedContext() method. 

Strangely the same thing is not happening when I create an AppOnly client context using the TokenHelper provided by Microsoft, as in:

var appOnlyAccessToken = TokenHelper.GetS2SAccessTokenWithWindowsIdentity(webUri, null);
return TokenHelper.GetClientContextWithAccessToken(webUri.AbsoluteUri, appOnlyAccessToken);

In this case the cloned context in the WebExistsFullUrl extension points to the url I am trying to perfom the check on.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
