### ISSUE TITLE
Does PnPSite Core support asp.net core?

### ISSUE THREAD

**Issue by jckh1234** [SharePoint/PnP-Sites-Core#1203]
#### Category
[ ] Bug
[X ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
Expect SharePointPnPCore2013 can use on ASP.NET core project

#### Observed Behavior
Project throw error on build. Dependency cannot resolve.

#### Steps to Reproduce
I created a ASP.NET Core project in VS2015. (ASP.NET Core Web Application (.NET Framework) template) Then add an Nuget package of SharePointPnPCore2013.

However the project cannot resolve following dependency:
Microsoft.SharePoint.Client.Runtime
Microsoft.SharePoint.Client.Tamonomy
Microsoft.SharePoint.Client.UserProfile
.... and more

Then I tried to install the Microsoft.SharePoint.Client.Runtime in Nuget, I got following 
The depnedency Microsoft.SharePoint.Client.Runtime.dll 15.0.4859.1000 does not support framework .NETFramework, Version v4.6.1

**Comment by VesaJuvonen** [comment]
Unfortunately, native CSOM does not support .NET Core, so we can't move to there with PnP CSOM Core either. Would suggest to vote following item in the UserVoice - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/16585795-support-net-core-with-csom.
