### ISSUE TITLE
Replace GUIDs with tokens in the exported workflows. Remove exported properties that may cause errors when provisioning to a different site collection. Update Workflow related samples and documentation.

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Sites-Core#1206]
#### Category
 * Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x] SharePoint 2016, May 2017 CU
[ ] SharePoint 2013

Most likely, the behaviors are not environment-dependant.

#### Observed Behavior

The exported XML replaces a few GUIDs with tokens (TaskListId, HistoryListId), but it still is filled with many GUIDs like *WebId, SiteId, ParentUniqueId, ParentContentTypeId, ContentTypeId, ScopeId, WSGUID, etc.*

Currently, provisioning of SharePoint 2013 workflows exported from one environment to another environment (e.g. DEV to UAT) does not work. I am currently investigating the cause, but most likely that is due to mis-matched GUIDs (e.g. SiteId, WebId, etc.). On the other hand, @jansenbe [commented](https://github.com/SharePoint/PnP-Sites-Core/issues/1001) that export/import of SharePoint 2013 workflows is supported.

Some of the exported properties do not carry significant information that is used in provisioning and can be removed, (e.g. *vti_modifiedby, vti_author, vti_foldersubfolderitemcount, vti_folderitemcount, Definition.EditorLogin, Definition.AuthorLogin, Definition.AuthorId, Definition.CreatedDate, etc.*). Perhaps, we need to add  [Handler](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Handlers.cs) `WorkflowProperties` to be used in [Get-PnPProvisioningTemplate](https://github.com/SharePoint/PnP-PowerShell/blob/master/Documentation/GetPnPProvisioningTemplate.md)/[GetProvisioningTemplate](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs) and [ProvisioningTemplateCreationInformation](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateCreationInformation.cs).

[Sample templates](https://github.com/SharePoint/PnP-Provisioning-Schema/tree/master/Samples) contain commented out Workflows section.
[Workflows](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#workflows) documentation section appears to be incomplete([WorkflowDefinitions](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#workflowdefinitions) and [WorkflowSubscriptions](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#workflowsubscriptions) are missing any attributes or nested elements in Markdown documentation, but schema annotations [exist](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2016-05.xsd)). 
Incorrect export and missing documentation make workflow migration a challenging and time consuming task.

#### Expected or Desired Behavior

* ***Environment-specific GUIDs should be always exported as tokens*** to prevent from provisioning errors in different site collections, and to avoid creating orphaned objects. 
The list of properties is as follows, but not limited to: 
*WebId, SiteId, ParentUniqueId, ParentContentTypeId, ContentTypeId, ScopeId, WSGUID (ScopeId?)*
* Remove properties that do not carry significant values or contain default values to produce cleaner output. Alternatively, add a handle to include/exclude workflow properties in the export. My sample export contains 190 lines (over 24K characters) of XML. A large number of the exported properties may be useful for inventory purposes, but they have no value for provisioning purposes. 
The list of properties is as follows, but not limited to: 
*CheckedOutTitle, CheckedOutUserId, ContentVersion, Definition.AuthorId, Definition.AuthorLogin, Definition.CreatedDate, Definition.CreatedDateUTC, Definition.EditorId, Definition.EditorLogin, Definition.ModifiedDate, Definition.ModifiedDateUTC, DocConcurrencyNumber, DocIcon, Edit, FileSizeDisplay, File_x0020_Size, File_x0020_Type, FolderChildCount, FSObjType, IsCheckedoutToLocal, ItemChildCount, ModifiedBy, owshiddenversion, SharePointWorkflowContext.Subscription.AuthorId, SharePointWorkflowContext.Subscription.AuthorLogin, SharePointWorkflowContext.Subscription.CreatedDate, SharePointWorkflowContext.Subscription.CreatedDateUTC, SharePointWorkflowContext.Subscription.EditorId, SharePointWorkflowContext.Subscription.EditorLogin,  SharePointWorkflowContext.Subscription.ModifiedDate, SharePointWorkflowContext.Subscription.ModifiedDateUTC, SPDConfig.LastEditMode, StatusColumnCreated, StreamHash, UniqueId, VirusStatus, vti_author, vti_folderitemcount, vti_foldersubfolderitemcount, vti_modifiedby, vti_parserversion, vti_privatelistexempt, WorkflowVersion, WSPublishState, _CheckinComment, _EditMenuTableEnd, _EditMenuTableStart, _EditMenuTableStart2, _IsCurrentVersion, _Level, _ModerationStatus, _UIVersion, _UIVersionString*
* Update Workflows related documentation and samples. 
Indicate that SharePoint 2010 workflows currently are not supported or add support for SharePoint 2010 Workflows.

#### Steps to Reproduce

* Create a List-based SharePoint 2013 workflow
* Publish the workflow
* Export site template (make sure to include handle Workflows)
* Examine exported XML template
	* Locate workflow definition and workflow subscription
	* Find all GUIDs and determine if they can/should be replaced with tokens
	* Find workflow design-time and runtime properties and properties that are irrelevant for site provisioning
* Do not make any changes in the exported template.
* Provision template into another SharePoint site collection, another web application and another SharePoint farm. 
Confirm that the workflow got provisioned and is functional in the associated lists/libraries on the target sites.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
