### ISSUE TITLE
Add app (spfx, app) to a site from AddinCatalog

### ISSUE THREAD

**Issue by patrick-blanc** [SharePoint/PnP-Sites-Core#1209]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Would it be possible to add a functionality that will allow user to add an app (spfx, app) to a site from the AddinCatalog and not from a path ? I tried to do it but as written by Chris O'Brien, this is actually not possible (point 3 at http://www.sharepointnutsandbolts.com/2017/03/provisioning-modern-pages-and-spfx-web-parts.html).

A such functionnality would be really appreciated (CSOM or PowerShell : example Add-PnPAppInstance {AppTitle in the AddinCatalog})

Thanks for your effort 👍

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
