### ISSUE TITLE
Get-SPOProvisioning is not exporting the contents of Lists,Webparts,Custom forms and  files 

### ISSUE THREAD

**Issue by gcgithub16** [SharePoint/PnP-Sites-Core#1210]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
I am trying to provisioning the my production site including contents to development environment using Get-SPOProvisioningTemplate -Out "C:\Users\Documents\test.xml".but it is exporting only site schema but we also need the content also please tell me is there any way to get site contents and sub sites of the site collection in sp2013 online.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
