### ISSUE TITLE
Apply-PnPProvisioningTemplate : Method not found: 'Void Microsoft.SharePoint.Client.UserCustomAction.set_ClientSideComponentId(System.Guid)'

### ISSUE THREAD

**Issue by michelsmitimaes** [SharePoint/PnP-Sites-Core#1212]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Apply template to SharePoint online site using Apply-PnPProvisioningTemplate.

#### Observed Behavior
Apply-PnPProvisioningTemplate -Path C:\temp\ca.xml raises the error:

Method not found: 'Void
Microsoft.SharePoint.Client.UserCustomAction.set_ClientSideComponentId(System.Guid)'

After several minutes. Other objects are applied succesfully. 

#### Steps to Reproduce
Attached the pnp template. Latest version of SPO management shell and PnP powershell is used.

Apply-PnPProvisioningTemplate -Path C:\temp\ca.xml
[ca.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1067466/ca.txt)

**Comment by baywet** [comment]
We ran into the exact same issue on our end with version 2.16.1706.0, rolling back to 2.16.1705.0 fixed the issue.

**Comment by MikkoCodes** [comment]
I can confirm that 2.16.1705.0 works, 2.16.1706.0 is having this issue.

**Comment by Megamannen** [comment]
I can also confirm this, and it's also affecting Enable-PnPResponsiveUI

Workaround is downgrading, as mentioned. I'm no powershell expert, but this is a way of doing it:
```
PS > Uninstall-Module SharePointPnPPowerShellOnline
PS > Install-Module SharePointPnPPowerShellOnline -MaximumVersion 2.16.1705.0 -SkipPublisherCheck -AllowClobber
```

**Comment by afsandeberg** [comment]
This affects all cmdlets and extensions that ties to set UserCustomAction.

Seems like the latest nuget package didn’t ship with the correct CSOM version. Perhaps a new release is pending, @VesaJuvonen , @jansenbe ?

Another workaround (other than downgrading) is to download the latest CSOM assemblies from this repo and replacing them at your local install.

**Comment by VesaJuvonen** [comment]
FYI @erwinvanhunen. Sorry for the small delay on this. This seems to be indeed a CSOM version issue in the PowerShell setup configuration. We seem to be shipping the June release with 16.1.6216.1200 version, which is relatively old. Since ClientSideComponentId property was introduced with later CSOM version, code fails due unknown property access. We'll absolutely need to get updated release out for this. Thanks  everyone for your input around this. We'll work on shipping updated setup for PowerShell.

**Comment by erwinvanhunen** [comment]
I can confirm that we shipped the latest build of the PowerShell cmdlets with an older version of CSOM, for which we apologize. I just release version 2.16.1706.1 as an intermediate release for June which fixes this. Please update your installation and it should work as expected.

**Comment by PedroDutra** [comment]
Hi @erwinvanhunen 
I went to the https://github.com/SharePoint/PnP-PowerShell/releases/tag/2.16.1706.1
 as you refered and downloaded the SharePointPnPPowerShellOnline.msi

but i still getting the :
Name                          Version    
----                          -------    
SharePointPnPPowerShellOnline 2.16.1706.0

I check it by using 
Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending


any word of advise ?

PS- thanks for the fantastic work that your gyus are doing :)
