### ISSUE TITLE
GlobalNav - Navigation Heading with no URL not rendered on site using Apply-PnPProvisioningTemplate

### ISSUE THREAD

**Issue by scubasteveb** [SharePoint/PnP-Sites-Core#1215]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When using Apply-PnPProvisioningTemplate -Handlers Navigation it should deploy global navigation headings that don't have a URL in the site template file. (i.e. <pnp:NavigationNode Title="Business" Url="" IsExternal="true">)

#### Observed Behavior
When running the Apply-PnPProvisioningTemplate -Handlers Navigation command, it process the template file but any global navigation nodes (Navigation Heading) that didn't have a URL specified don't appear on the site or in site settings under global navigation.
When I run Get-PnPProvisioningTemplate against the site it shows the global navigation nodes exist, and have a Url="{site}"

#### Steps to Reproduce
Create a site that has a parent global navigation heading with no URL and then run the Get-PnPProvisioningTemplate to get the XML template. Then run Apply-PnPProvisioningTemplate against a new site collection using the XML from the previous step. The navigation heading with no URL will not render in the new site.

**Comment by luismanez** [comment]
yeah, seems a bug on the ObjectNavigation Handler, as it's not considering Empty urls, and always add the {site} token:
```c#
var result = new Model.NavigationNode
            {
                Title = node.Title,
                IsExternal = node.IsExternal,
                Url = web.ServerRelativeUrl != "/" ? node.Url.Replace(web.ServerRelativeUrl, "{site}") : $"{{site}}{node.Url}"
            };
```
I'll try to reproduce the issue and make a new PR to fix it in the next release.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
