### ISSUE TITLE
Exception provision CT: the Content Type "Page Layout" is selaed

### ISSUE THREAD

**Issue by capugino** [SharePoint/PnP-Sites-Core#1220]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Sealed Content types should be skipped

#### Observed Behavior
I downloaded the latest version of PnP core, in which there is a fix for this issue. However I have noticed that the content type "Page Layout" is not marked as sealed in the xml, nor when I check it via Powershell / CSOM. See screenshots.

![14-06-2017 20-57-33](https://user-images.githubusercontent.com/22930851/27215393-3aa0df34-5271-11e7-9b7a-00e96765dd69.png)
![14-06-2017 20-57-51](https://user-images.githubusercontent.com/22930851/27215398-455064ea-5271-11e7-9d96-a40ae4a20a9c.png)
![16-06-2017 8-55-27](https://user-images.githubusercontent.com/22930851/27215457-940c2cae-5271-11e7-8ed2-76623cc1f2c3.png)

#### Steps to Reproduce
The description of the content type differs in the template xml and the destination site. This site is a newly created site.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
