### ISSUE TITLE
Metadata Navigation and Filtering in lists are not handled by PNP provisionning engine

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/PnP-Sites-Core#1224]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
It would be a good thing to have the Metadata Navigation and Filtering settings of list exported and imported using the PNP provisioning engine.

#### Some investigations
It seems that these settings are stored in the property bag of the root folder of the list. Specifically, the key `client_MOSS_MetadataNavigationSettings` contains something like this (excerpt from one of our environment):

    <MetadataNavigationSettings SchemaVersion="1" IsEnabled="True" AutoIndex="True">
    <NavigationHierarchies>..... Truncated ......</ManagedIndices></MetadataNavigationSettings> 

#### Some thoughts around a possible solution
At this point, I have some ideas that may solve the issue. However, as I'm discovering the code, I'm sure what's the best way:

1. handle specifically these settings and outputs a new model object related to this settings (looks like a short term solution, because other keys may also have interest to be exported)
2. extend the PropertbagHandler to take care of the whole object hierarchy

thanks

**Comment by ruslanurban** [comment]
Related: [Add support for metadata navigation in lists instances](https://github.com/SharePoint/PnP-Provisioning-Schema/issues/216)

**Comment by stevebeauge** [comment]
As a workaround, I created a custom extensibility handler : https://github.com/solutions-pour-sharepoint/PnP-Provisioning-Extensions/blob/dev/Src/SoSP.PnPProvisioningExtensions/SoSP.PnPProvisioningExtensions.Core/MetadataNavigationHandler.cs

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
