### ISSUE TITLE
Custom Action provisioning & localization

### ISSUE THREAD

**Issue by shravanjoshi88** [SharePoint/PnP-Sites-Core#1225]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

#### Expected or Desired Behavior
I am using below template for provisioning a Custom action. 
For Localisation, SiteCreation.resx and SiteCreation.nl-NL.resx files are used.

`<pnp:CustomActions>
        <pnp:SiteCustomActions>
            <pnp:CustomAction 
                   Name='Nieuw_document' 
                   RegistrationId='101'
                   RegistrationType='List' 
                   Location='CommandUI.Ribbon' 
                   Title='$Resources:SiteCreation,caTitle_Dialog'
                   Sequence='1000' 
                   Rights='AddListItems'>
            <pnp:CommandUIExtension>
              <CommandUIDefinitions>
                <CommandUIDefinition Location='Ribbon.Documents.New.Controls._children'>
                  <Button Id='Ribbon.Documents.New.NewButtonButton'
                          Alt='$Resources:SiteCreation, caTitle_Button'
                          Sequence='12'
                          Command='Invoke_NewButtonRequest'
                          LabelText='$Resources:SiteCreation,caTitle_Button'
                          TemplateAlias='o1'
                          Image32by32='SiteAssets/appicon32x32.png'
                          Image16by16='SiteAssets/appicon16x16.png' />
                </CommandUIDefinition>
              </CommandUIDefinitions>
              <CommandUIHandlers>
                <CommandUIHandler Command='Invoke_NewButtonRequest'
                                  CommandAction='[[REMOTE_ADDIN_URL]]'/>
              </CommandUIHandlers>
            </pnp:CommandUIExtension >
          </pnp:CustomAction>
        </pnp:SiteCustomActions>
      </pnp:CustomActions>`

#### Observed Behavior
* The Custom Action is provisioned as expected, but the localization for Custom action  button name is not applied. 
* The name of the button appears as "$Resources:SiteCreation, caTitle_Button"
Resource files is deployed as farm solution using WSP deployment. 
* Other components like content types and site columns are being localized correctly using the same resource file.

```

**Comment by dominik85HH** [comment]
@shravanjoshi88 : Did you solve this issue? I have the same problem usin pnp provisioning and didn't find a solution yet
