### ISSUE TITLE
"The 'br' start tag on line XXX position XXX does not match the end tag of 'XXX'." error due to not closed BR tag

### ISSUE THREAD

**Issue by hyankov** [SharePoint/PnP-Sites-Core#1227]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ X] SharePoint 2016
[X ] SharePoint 2013

In the [PageExtensions.cs](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs) file, there is the following code segment:

```
// Close all BR tags
var brRegex = new Regex("<br>", RegexOptions.IgnoreCase);
wikiField = brRegex.Replace(wikiField, "<br/>");
```

this is obviously countering the SharePoint issue that it doesn't close `<br>` tags and you need a valid XML to load. However, it doesn't take into consideration that SharePoint can also output BR tags like this:
`<br unselectable="on">`

In that case, PnP will not close it and will consequently fail with an exception like:

> The 'br' start tag on line XXX position XXX does not match the end tag of 'XXX'.

The code needs to be upgraded to handle those BR tags too. I am not an expert on regex and that's why I am not submitting a pull request, but consider [this](https://regex101.com/r/kG5vF1/16) as a starting point maybe.

I have encountered this issue already and currently my work-around is to 'prepare' the `<br unselectable="on">` tag for PnP by replacing it with a `<br>`.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
