### ISSUE TITLE
Not able to limit provisioning to only SiteFields section of provisioning template

### ISSUE THREAD

**Issue by johannesekstrand** [SharePoint/PnP-Sites-Core#1229]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4927.1000

#### Expected or Desired Behavior
I am using a ProvisioningTemplate to configure a group of SharePoint sites. Recently I made additions to the SiteFields in the template and therefore wanted to Apply only these changes on all existing sites, and did so by setting the HandlersToProcess to only Handlers.Fields. I expected this to only run the ObjectHandler "ObjectField", which was not the case.

#### Observed Behavior
I found that specifying Handlers.Fields for the HandlersToProcess also runs the ObjectHandler "ObjectListInstanceDataRows" which means that duplicate datarows are added to all lists where the template has some default datarows specified. This is due to conditional logic found in class SiteToTemplateConversion on row 202:

 ```
if (provisioningInfo.HandlersToProcess.HasFlag(Handlers.Fields) || provisioningInfo.HandlersToProcess.HasFlag(Handlers.Lists)) objectHandlers.Add(new ObjectListInstanceDataRows());
 ```

#### Steps to Reproduce
Testing demands a provisioningtemplate containing some sitefields, a list instance and some datarows for the list instance

1. First apply the template while specifying Handlers.All.
2. Make some changes or additions to the SiteFields section.
3. Rerun the apply for the same site while specyfing Handlers.Fields.

Besides the changes to the SiteFields duplicate datarows will have been added to the list.

**Comment by johannesekstrand** [comment]
Any thoughts on this @VesaJuvonen @erwinvanhunen?

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
