### ISSUE TITLE
ObjectHandlerFiles adds a version per metadata field update

### ISSUE THREAD

**Issue by cverhelst** [SharePoint/PnP-Sites-Core#1234]
#### Category
[ ] Bug
[ x] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[x ] SharePoint 2016
[x ] SharePoint 2013

#### Expected or Desired Behavior
File is uploaded and metadata is set but only 1 version is created

#### Observed Behavior
File is uploaded as a new version, and for every metadata field set there's an extra version created

#### Steps to Reproduce
Upload files with metadata using 

```
<pnp:Files>
	<pnp:Directory Src="" Folder="" Overwrite="true" MetadataMappingFile="" />
</pnp:Files>
```

MetadataMappingFile contents:

```
{
	"<filepath>": {
		"<textfieldname>": "test",
		"<textfieldname>": "test",
		"<textfieldname>": "test",
		"<multichoicefieldname>": "[\"test\"]"
	}
}
```
![image](https://user-images.githubusercontent.com/1067868/27477500-bffe4252-580c-11e7-8e22-fb2d2e6500b2.png)

#### Presumable Cause

https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs : 343

file.ListItemAllFields.Update();
context.ExecuteQueryRetry();

-> .Update() should be .SystemUpdate()

#### Extra Info
Same behaviour is encountered when using Set-PnPListItem PnP PowerShell Cmdlet with the -Values @{hashtable} parameter (although it's a different implementation)

**Comment by wobba** [comment]
@cverhelst On a note, the cmdlet has a -SystemUpdate switch which should not add a version.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
