### ISSUE TITLE
: The Provisioning Template URI HumaxTemplate1.xml is not valid.

### ISSUE THREAD

**Issue by levalencia** [SharePoint/PnP-Sites-Core#1235]
We connect to our customer tenant and get a .pnp file without errors:
 
 
$tenant = "ourcustomertenant";
$sourceSite = "/sites/ClientesNotaCredito";
$webUrl = "https://{0}.sharepoint.com{1}/" -f $tenant, $sourceSite;
$path = "C:\Templates\HumaxTemplate.pnp"
Write-Output $("Connecting to {0}..." -f $webUrl);
Connect-PnPOnline -Url $webUrl -Credentials WCMStoredCredentials;
Write-Output "Context obtained";
Write-Output "Creating PnP template...";
Get-PnPProvisioningTemplate -Out $path 
Write-Output $("Template saved to {0}" –f $path);
Then we connect to our tenant, to replicate the environment, and we created a site collection with the same publishing template and execute this:
 
 
# Define variables
$tenant = "ourowntenant";
$targetSite = "/sites/DevHumax";
$path = "C:\Templates\HumaxTemplate1.pnp";
$siteTitle = "My Target Site";
$siteDescription = " ";
$siteUrl = "ourowntenant.sharepoint.com";

# Get context
$webUrl = "https://{0}.sharepoint.com/{1}" -f $tenant, $targetSite;
Write-Output $("Connecting to {0}..." -f $webUrl);
Connect-SPOnline -Url $webUrl -Credentials WCMStoredCredentials;
Write-Output "Done";

# Create new subsite
$web = Get-PnPWeb -Identity /sites/DevHumax
# New-SPOWeb -Title "$siteTitle" -Url "$siteUrl" -Description "$siteDescription" -Locale 1043 -Template "STS#1"

# Apply template
Write-Output $("Applying PnP template [{0}] to site [{1} ({2})]..." -f $path, $web.Title, $web.Url);
Apply-PnPProvisioningTemplate $path;
Write-Output "Done";
 
 
However we get this error:
 
Apply-PnPProvisioningTemplate [: The Provisioning Template URI HumaxTemplate1.xml is not valid.]))
At line:2 char:1
+ Apply-PnPProvisioningTemplate $path;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

file is here: 
https://drive.google.com/file/d/0B77YRWgG0ik8bjBlVmFPXzE3MGc/view?usp=sharing

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
