### ISSUE TITLE
TokenParser.cs can contain duplicate tokens

### ISSUE THREAD

**Issue by RobinBreman** [SharePoint/PnP-Sites-Core#1239]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior

Adding a list and corresponding webpart with a ProvisioningTemplate fails if a list with the same name exist on the rootweb.

#### Observed Behavior
When creating a list on a subweb a duplicate token is added to the tokenparser tokens collection.

When initializing TokenParser all posible tokens are added to the collection.
If the context is a subweb, tokenparser (line 86) includes lists from the rootweb.
If a list is provisioned to a subweb, with the same name as a list on the rootweb a duplicate token is added to the collection.
When adding (e.g.) a webpart, the token is resolved incorrectly (not returning the listid of the subweb). 

The bug is introduced in: [TokenParser.cs#L86](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs#L86).

#### Steps to Reproduce
1. Add a list (documentlibrary) to the rootweb named 'DuplicateList'
2. Create a subsite
3. Apply a pnp template to the subsite, include a listdefinition for a list named 'DuplicateList' and a webpart

 ```
  <pnp:ListInstance Title="DuplicateList" Description="" 
                          DocumentTemplate="{site}/DuplicateList/Forms/template.dotx" TemplateType="101" 
                          Url="Vertrouwelijk" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="500" 
                          DraftVersionVisibility="0" TemplateFeatureID="00bfea71-e717-4e80-aa17-d0c71b360101" EnableAttachments="false">
```

```
<pnp:WebPart Title="**This Webpart Wil fail**" Zone="Header" Order="0">
              <pnp:Contents>
                <webParts>
                  <webPart xmlns="http://schemas.microsoft.com/WebPart/v3">
                    <metaData>
                      <type name="Microsoft.SharePoint.WebPartPages.XsltListViewWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" />
                    </metaData>
                    <data>
                      <properties>
                        ...
                        <property name="ListName" type="string">{{listid:DuplicateList}}</property>
                       .....
                      </properties>
                    </data>
                  </webPart>
                </webParts>
              </pnp:Contents>
            </pnp:WebPart>

```
4. Call  web.ApplyProvisioningTemplate(template);

The following excpeption is thrown:
_Microsoft.SharePoint.Client.ServerException: Lijst bestaat niet. De geselecteerde pagina bevat een lijst die niet bestaat. Mogelijk is deze door een andere gebruiker verwijderd. at_ 

#### Resolve
When not executing the following code in [TokenParser.cs ](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs#L86) above will not throw an exception and will work as required.

https://github.com/RobinBreman/PnP-Sites-Core/commit/7304be2af9a10e58d790404261cc2fda82323d32

  ```
 if (web.IsSubSite())
            {
                // Add lists from rootweb
                var rootWeb = (web.Context as ClientContext).Site.RootWeb;
                rootWeb.EnsureProperty(w => w.ServerRelativeUrl);
                rootWeb.Context.Load(rootWeb.Lists, ls => ls.Include(l => l.Id, l => l.Title, l => l.RootFolder.ServerRelativeUrl));
                rootWeb.Context.ExecuteQueryRetry();
                foreach (var rootList in rootWeb.Lists)
                {
                    // token already there? Skip the list
                    if (web.Lists.FirstOrDefault(l => l.Title == rootList.Title) == null)
                    {
                        _tokens.Add(new ListIdToken(web, rootList.Title, rootList.Id));
                        _tokens.Add(new ListUrlToken(web, rootList.Title, rootList.RootFolder.ServerRelativeUrl.Substring(rootWeb.ServerRelativeUrl.Length + 1)));
                    }
                }
            }
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
