### ISSUE TITLE
GetComposedLook method failure

### ISSUE THREAD

**Issue by Bhavesha** [SharePoint/PnP-Sites-Core#1250]
Hello there,

While debugging method GetComposedLook() from "OfficeDevPnP.Core/Extensions/BrandingExtensions.cs", I discovered that code 
**List designCatalog = web.GetCatalog((int)ListTemplateType.DesignCatalog);** 
works fine for site with CompatibilityLevel = 15 but fails for site where CompatibilityLevel value is 14. To fix this issue on 14 enabled sites, mentioned code should be replaced with below.

**List designCatalog = web.GetCatalog(123);**

Thanks,

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
