### ISSUE TITLE
Prevent PnP provisioning from replacing strings that look like tokens

### ISSUE THREAD

**Issue by LarterStyles** [SharePoint/PnP-Sites-Core#1255]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

####
Is there a way to escape a "{site}" or "{sitecollection}" string in a PnP provisioning template so that it doesn't get replaced / treated as a token?

I have such strings in some web part settings (i.e. embedded in the CDATA XML), and don't want them to be replaced during provisioning — in my case, the web part needs to instead processe these strings / tokens at runtime.

**Comment by prawnz** [comment]
Would like to know this as well.. I have some search web parts that needed {site} and {sitecollection} but they kept getting replaced.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
