### ISSUE TITLE
GetAppInstances doesn't return the version of the installed app.

### ISSUE THREAD

**Issue by tchagan** [SharePoint/PnP-Sites-Core#1266]
#### Category
[ ] Bug
[*] Enhancement

#### Environment
[*] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

the GetAppInstances extension returns data concerning the installed app instances on a particular web site, however, it doesn't return the Version of the installed app. In my use case I'd like to retrieve the installed version of apps from sites to compare to the version of the app within the tenant app catalog, in order to see what apps require updating within a site collection.

**Comment by tchagan** [comment]
The app details page has the version, there appears to be a storefront.aspx beneath /_layouts/15 so presumably the version is available somewhere, I agree there isn't anything in the CSOM API that appears to expose it.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
