### ISSUE TITLE
[Get-PnPProvisioningTemplate], MissingMethodException

### ISSUE THREAD

**Issue by dannyfoncke** [SharePoint/PnP-Sites-Core#1267]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version:   December 2016 CU Build Number    15.0.4885.1000

#### Expected or Desired Behavior
Get-PnPProvisioningTemplate should produce a template

#### Observed Behavior
An error is produced : 

PS C:\nodes\Provisioning> Get-PnPProvisioningTemplate -Out template.pnp
Get-PnPProvisioningTemplate : Method not found: 'Microsoft.SharePoint.Client.InformationPolicy.ProjectPolicy Microsoft.SharePoint.Client.InformationPolic
y.ProjectPolicy.GetCurrentlyAppliedProjectPolicyOnWeb(Microsoft.SharePoint.Client.ClientRuntimeContext, Microsoft.SharePoint.Client.Web)'.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Out template.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

#### Steps to Reproduce

- Downloaded and installed SharePoint Server 2013 Client Components SDK from here : https://www.microsoft.com/en-us/download/details.aspx?id=35585

- installed the pnp powershell cmdlets from as described here : https://www.powershellgallery.com/packages/SharePointPnPPowerShell2013/2.16.1706.1
PS C:\nodes\Provisioning> (get-module sharepointpnppowershell2013).version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      16     1706   1

- Connect to the source using :  Connect-PnPOnline 
This command asks for my credentials and connects successfully.

- try command Get-PnPProvisioningTemplate out template.pnp 
 error : 
Get-PnPProvisioningTemplate : Method not found: 'Microsoft.SharePoint.Client.InformationPolicy.ProjectPolicy Microsoft.SharePoint.Client.InformationPolicy.ProjectPolicy.GetCurrentlyAppliedProjectPolicyOnWeb(Microsoft.SharePoint.Client.ClientRuntimeContext, Microsoft.SharePoint.Client.Web)'.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Out template.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

Remark. Other commands do work, for example : Get-PnPProvisioningTemplateFromGallery

thanks for looking into this.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
