### ISSUE TITLE
PNP-Site-Core - ClientSideWebPart.Properties are empty when ClientSidePage.Load is used;

### ISSUE THREAD

**Issue by lordwardall** [SharePoint/PnP-Sites-Core#1269]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Observed Behavior
When ClientSidePage.Load is used, the ClientSideWebPart.Properties in ClientSidePage.Controls are empty.

#### Steps to Reproduce
1. Load an existing page that contains at least one WebPart using the ClientSidePage.Load method;
2. Extrat a ClientSideWebPart from the ClientSidePage.Controls;
3. The extracted ClientSideWebPart.Properties are empty (Also the PropertiesJson);

Note : The private member propertiesJson contains the 
![oups](https://user-images.githubusercontent.com/22706371/28469454-483abefe-6e04-11e7-9575-a7b5d9dc5321.png)
proper properties !

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
