### ISSUE TITLE
Reusable Workflow not provisioned correctly

### ISSUE THREAD

**Issue by NormanMann** [SharePoint/PnP-Sites-Core#1271]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
January 2016 CU

#### Expected or Desired Behavior
Apply-PnpProvisioningTemplate should correctly provision a Reusable SharePoint 2013 workflow for a Content Type

#### Observed Behavior
The workflow is provisioned but the Content Type in the Workflow Information section in SharePoint Designer is set to 'All' instead of the original Content Type  

#### Steps to Reproduce
- Create a Team Site and make sure it is accessible thru the browser
- Open SharePoint Designer -> Select File Tab -> Choose 'Reusable Workflow' from Workflows section
- Make sure you specify a Content Type (e.g. Document)
- Create a simple workflow that just logs a message
- Save and Publish the workflow

Use Get-PnpProvisioningTemplate -Out <Path> to extract the Information
Use Apply-PnpProvisioningTemplate to apply the template (preferable to a different site)

Go to SharePoint Designer and open the workflow. The Content Type in the Workflow Information section now shows 'All' instead of the correct Content Type

Interestingly the workflow seems to work just fine BUT can no longer be modified correctly because of the lost reference to the Content Type. For example the Current Item now only has access to standard fields while before we could access all fields of the Content Type.

![contenttypelost](https://user-images.githubusercontent.com/18259236/28512556-a701afd8-7052-11e7-9214-0b6c6a416004.png)

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
