### ISSUE TITLE
Hidden site fields not extracted

### ISSUE THREAD

**Issue by devenramani** [SharePoint/PnP-Sites-Core#1274]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
-A sub-site in a site collection having root site content type.
-Root site content type having few hidden columns.
-While extracting the template of the sub-site, it should extract those hidden columns in the template XML file of the sub-site.

#### Observed Behavior
-Extracted template does not include hidden columns 

#### Steps to Reproduce
1. Add a few hidden fields in a Root Site Content Type
2. Add this content type to a list of a sub-site
3. Extract template of that site
4. In the extracted template, there is no FieldRef entry of hidden fields under List Instance element

Thanks.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
