### ISSUE TITLE
Missing parameter <targetLibraryPath> in default configuration.xml of Core.ProfilePictureUploader

### ISSUE THREAD

**Issue by rslavey** [SharePoint/PnP-Sites-Core#1278]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
In the configuration.xml of Core.ProfilePictureUpdater, <targetLibraryPath> is a required parameter, but it does not exist in the sample. Suggest adding:

<targetLibraryPath>/User Photos/Profile Pictures</targetLibraryPath>

as this is the default path for SharePoint Online MySites.

#### Observed Behavior
When this value is missing, the system throws an error.

#### Steps to Reproduce
Leave this empty and it throws an error in Program.cs, line 315, when attempting to retrieve value for _appConfig.TargetLibraryPath

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
