### ISSUE TITLE
Do not upscale images in Core.ProfilePictureUploader

### ISSUE THREAD

**Issue by rslavey** [SharePoint/PnP-Sites-Core#1279]
#### Category
[] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When creating the three sizes of images, if the source image is smaller than or the same size as the target size, the image should not resize.

Recommend removing the ResizeImageSmall method altogether and using the ResizeImageLarge method for all three sizes to reduce complexity. Then, add the following to the ResizeImageLarge method:

            if (originalImage.Width <= NewWidth) //if sourceimage size is same or smaller, no point resizing, as it loses quality
            {
                OriginalImage.Seek(0, SeekOrigin.Begin);
                originalImage.Dispose();
                return OriginalImage; //return same image that was passed in
            }

after the line

            Image originalImage = Image.FromStream(OriginalImage, true, true);

#### Observed Behavior
Increasing the size of the image results in a poor quality image.

#### Steps to Reproduce
Use an original image of a size less than 200px and look at the resized Large image.

**Comment by spdevdocs** [comment]
We closed this issue as it had not been any activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to open a new issue and follow the guidance in the issue template related to the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues on the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. “Sharing is caring!”
