### ISSUE TITLE
Error occurred when calling $Resources:List_Pages_UrlName for Spanish sites

### ISSUE THREAD

**Issue by kezack** [SharePoint/PnP-Sites-Core#1282]
The following code is the implementation of Web.GetPublishingPage (...) The List_Pages_UrlName returned is "Pages" but it must be "Paginas" for Spanish. This will cause GetByTitle (...) to throw an exception.

 ```
ClientResult<string> pagesLibraryName = Utility.GetLocalizedString(context, "$Resources:List_Pages_UrlName", "cmscore", (int)web.Language);
context.ExecuteQueryRetry();
var Name = pagesLibraryName.Value; // return Pages it's Paginas
List spList = web.Lists.GetByTitle(pagesLibraryName.Value);
context.Load(spList);
context.ExecuteQueryRetry();
```

**Comment by kezack** [comment]
#1284 see the pull requests which fix my problem but I do not know if this is the right way

**Comment by jansenbe** [comment]
PR was merged, closing this issue.
