### ISSUE TITLE
Default values for taxonomy fields are not set during the initial upload

### ISSUE THREAD

**Issue by lverstrepen** [SharePoint/PnP-Sites-Core#1285]
Hi all, 
our PnP templates for SharePoint 2016 on-premises contain multiple taxonomy fields and we want to set default values on them, so that end users do not have to populate these fields during every upload. Below is an example of the default value on one of the taxonomy fields:

<Default>1;#Confidential|3cc1c58b-ac08-41c3-9848-c1f92d8c65cf</Default>

The template gets correctly applied, but the default value is not set during the first time that a document is uploaded to a site based on this template. Subsequent uploads correctly show the default value for this field.
Is this due to the TaxonomyHiddenList, which is empty when a site is created?
Please let us know if more information is required to investigate this issue.

**Comment by stact** [comment]
Try
`-1;#Confidential|3cc1c58b-ac08-41c3-9848-c1f92d8c65cf`

**Comment by lverstrepen** [comment]
Thanks stact, we implemented this change already. Setting it to -1 ensures the term.
