### ISSUE TITLE
Skip workflow on get PnP provisioning template

### ISSUE THREAD

**Issue by Crispify** [SharePoint/PnP-Sites-Core#1290]
#### Category
[ ] Bug
[x ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ x] SharePoint 2016
[ x] SharePoint 2013

#### Expected or Desired Behavior
I suggest an extra parameter on the function to retrieve a template from a site to skip extracting any workflow related assets from the site. 
I expect such an option must first be made available in the PnP Provisioning Core before the powershell commandlet Get-PnPProvisioningTemplate can be extended.

The result would be something like:
Get-PnPProvisioningTemplate -Out .\template.pnp -ExcludeWorkflow

#### Observed Behavior
I run into some problems while having Nintex Workflows in my SharePoint Online environment. As I can image those are a mix of bugs and not yet supported features that will take some time to be fully supported, I want to skip the workflows altogether when creating a template .pnp file and manually import the workflow after provisioning.

**Comment by PaoloPia** [comment]
Hi,
You can achieve the same result with:

Get-PnPProvisioningTemplate -Out .\template.pnp -ExcludeHandlers Workflow

I will close this item. Thanks.
