### ISSUE TITLE
Provisioning Engine: Unwanted Token Replacement 

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/PnP-Sites-Core#1292]
Hi,

I am using the Provisioning engine to provision some fields. In one of my fields the display name contains the string "{mv}". When I apply the template it seems that my display name section {mv} is interpreted as a token that should be replaced. Is there a way I can escape this so it isn't treaded as a token?

**Comment by dmdj** [comment]
Would also like ability to escape braces (and other characters) in descriptions, etc.  This overlaps with Issue 1255 I think.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
