### ISSUE TITLE
TermSet - Term, wont provision Description if it's set

### ISSUE THREAD

**Issue by RhoninPL** [SharePoint/PnP-Sites-Core#1293]
#### Which PnP repository should you use to report the issue? 
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[x] Bug
[ ] Enhancement

#### Environment // I can check it only for Sharepoint Online
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Added Description if it's filled in Terms.

#### Observed Behavior
All terms with filled Description attribute in my Provisioning Template - is empty in Term Store.

#### Steps to Reproduce
1. Create simple provisioning template with term stores, term sets and terms with Description.
Example:
<pnp:TermSets>
   <pnp:TermSet Name="My term set" Description="">
   <pnp:Terms>
                <pnp:Term Name="My Term" Description="This is ignored" />
  </pnp:Terms>
</pnp:TermSet>
</pnp:TermSet>
2. Provision template
3. In Term Store Management you can check Description is empty.

Even using XMLFileSystemTemplateProvider to load template it returns null/empty string for Description in Term.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
