### ISSUE TITLE
Removing base permissions from role definitions does not work

### ISSUE THREAD

**Issue by dfeuerhake** [SharePoint/PnP-Sites-Core#1294]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

Exact CU version: SharePoint 2013 CU May 2017

#### Expected or Desired Behavior
Role definitions should be provisioned correctly. Adding/removing base permissions from role definitions should be applied correctly.

#### Observed Behavior
If you add base permissions to a role definition in a provisioning template, they will be applied correctly. But if you remove a base permission from a role definition, the framework will not remove this base permission from the role definition in the target system.

#### Steps to Reproduce

1. Create a custom role definition in your XML provisioning template and add some base permissions like e.g. "ViewVersions".
2. Apply the template to a site.
3. Remove a base permission from the role definition in the XML template, e.g. "ViewVersions".
4. Apply the template to the same site again.

#### Solution Approach
In ObjectSiteSecurity.cs, lines 222-224, base permissions for an existing role definition will be updated. 
` if (siteRoleDefinition.BasePermissions != templateBasePermissions)
{
                                    isDirty = true;
                                    foreach (var permission in templateRoleDefinition.Permissions)
                                    {
                                        siteRoleDefinition.BasePermissions.Set(permission);
                                    }
                                }`
Instead of using siteRoleDefinition.BasePermissions.Set(permission) on the existing base permissions object, we should replace the whole instance of the BasePermissions class:
`if (siteRoleDefinition.BasePermissions != templateBasePermissions)
{
	isDirty = true;
	siteRoleDefinition.BasePermissions = templateBasePermissions;
}`

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
