### ISSUE TITLE
EnsureFolder requires FullControl permissions on the web even when ParentFolder is specified

### ISSUE THREAD

**Issue by Chipzter** [SharePoint/PnP-Sites-Core#1295]
#### Category
[IMHO] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Calling the extension method EnsureFolder on a Web object should succeed with only write permission on the web or list if a parent folder is specified.

#### Observed Behavior
Since the EnsureFolder method overload that takes a parent folder as an argument in turn calls EnsureFolderPath that tries to load the RootFolder property of all lists on the web. This fails with a ServerUnauthorizedAccessException when it gets to the Solution Gallery list unless the SharePoint Add-In has FullControl permissions on the web.

#### Steps to Reproduce
Create a new team site collection.
Create a new SharePoint Add-In in Visual Studio 2017.
Give the app Write permissions on the web.
In the code, call Web.EnsureFolder and specify the RootFolder of the "Documents" document library and some sub folder path.
Trust and run the Add-In.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
