### ISSUE TITLE
Include EmailAssigedTo property when extracting/provisioning tasks lists

### ISSUE THREAD

**Issue by Chris-Buildingi** [SharePoint/PnP-Sites-Core#1297]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[ X ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ X ] SharePoint 2016
[ X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
SharePoint 2016: 16.0.4534.1000

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

Tasks lists contain a "E-mail Notification" setting that sends and email notification when ownership is assigned to the task. The setting can be found at: List Settings > Advanced Settings > E-mail Notifications. This setting does not appear to be extracted or provisioned in the provisioning template in the ObjectListInstance handler. 

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
