### ISSUE TITLE
Using the SharePointConnector in combination with the XMLOpenXMLTemplateProvider

### ISSUE THREAD

**Issue by ThreadPitt** [SharePoint/PnP-Sites-Core#1302]
#### Category
[x ] Bug / Open Question
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
August 2017 CU (sts2016-kb4011049-fullfile-x64-glb)

How can I use the SharePointConnector in **combination** with the XMLOpenXMLTemplateProvider and the .pnp file format?

Using the SharePointTemplateProvider on its own works fine, e.g.:
 XMLSharePointTemplateProvider spProvider = new XMLSharePointTemplateProvider(ctx, "http://sp16", "Shared%20Documents");

...and using the XMLOpenXMLTemplateProvider on its own also works fine, e.g.:
XMLTemplateProvider provider = new XMLOpenXMLTemplateProvider(ptci.FileConnector as OpenXMLConnector);

But I can't figure out how to use the XMLOpenXMLTemplateProvider in combination with the SharePointTemplateProvider/SharePointConnector

Thanks!

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
