### ISSUE TITLE
Microsoft.Graph and Microsoft.Graph.Core fix Version dependency

### ISSUE THREAD

**Issue by seriewe** [SharePoint/PnP-Sites-Core#1303]
#### Category
[x ] Bug
[x] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Observed Behavior
OfficeDevPnP.Core.Framework.Graph.UnifiedGroupsUtility has a dependency to Microsoft.Graph but this is not part of the SharePointPnPCoreOnline NuGet Package. So I got the following error:
`Could not load file or assembly 'Microsoft.Graph, Version=1.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.`
when I try to use the CreateUnifiedGroup Method

Installation of the latest Microsoft.Graph package also didn't fix the Problem until I installed explicit Version of Graph and Grap.Code assemblies
`<package id="Microsoft.Graph" version="1.1.1" targetFramework="net452" />
<package id="Microsoft.Graph.Core" version="1.2.1" targetFramework="net452" />`

#### Steps to Reproduce
Install SharePointPnPCoreOnline and default Graph nuget package and use the CreateUnifiedGroup Method

I'm not sure if this is a good practice to use explicit version!? Did I missed something?

**Comment by poikjo** [comment]
We are facing similar issue cause PnP uses bit old versions of Microsoft.Graph and Microsoft.Graph.Core dlls.

**Comment by jansenbe** [comment]
The September nuget package is referencing the graph (1.1) and Microsoft.IdentityModel.Clients.ActiveDirectory (2.18) versions which should fix the build errors. We'll first need to test/update PnP Sites core to work with the latest versions of these nuget packages. Please re-open this issue if it still is there when using the September 2017 or later version.
