### ISSUE TITLE
Missing credentials if using CurrentCredentials when getting WebPart Xml

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/PnP-Sites-Core#1305]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4911.1000

#### Observed Behavior

With on-premise platform, when you want to export a WebPart and you use the default credentials (specifically when passing `-CurrentCredentials` to the `Get-PnPProvisioningTemplate` command), there's an exception when exporting a webpart.

Excerpt:

```
System.Net.WebException: Le serveur distant a retourné une erreur: (401) Non autorisé.
   à System.Net.HttpWebRequest.GetResponse()
   à Microsoft.SharePoint.Client.PageExtensions.GetWebPartXml(Web web, Guid webPartId, String serverRelativePageUrl)

```

Debugging shows that the error occurs in the method `PageExtensions.GetWebPartXml`.

No credentials is supplied to the WebRequest object when using the current user credentials.

#### Steps to Reproduce

Sample code that reproduce the issue (complete repro code : https://github.com/solutions-pour-sharepoint/PnP-Provisioning-Extensions/blob/dev/Src/SoSP.PnPProvisioningExtensions/SoSP.PnPProvisioningExtensions.Core/DocumentSetHomePageHandler.cs) :

```
var webParts = web.GetWebParts(pageUrl);

foreach(var spWp in webParts) {
     web.GetWebPartXml(spWp.Id, pageUrl);
}
```

**Comment by jansenbe** [comment]
Closing since PR has been merged
