### ISSUE TITLE
AuthenticationManager can not use ClientId/Secret from MsStore against German Cloud

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#1315]
Following this Guideline
https://github.com/SharePoint/PnP-Guidance/blob/master/articles/Extending-SharePoint-Online-for-Germany-China-USGovernment-environments.md

#### Category
[x ] Bug

#### Environment
[x ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
We would like to use ClientId/Secret from Ms Store for our Multitenant Hostet SharePoint App against sharepoint.de.  

#### Observed Behavior
We installed our App from Ms Store and normaly can Trust the App inside Sharepoint.de. But inside the App we get 401 Unauthorized error (It's same with TokenHelper) if we use ClientID/Secret from the Ms Store to get a app only token . If i generate a ClientId/Secret with AppRegNew inside one German SP-Tenant then the code work fine (also true for TokenHelper).

As next step i was using Appinv.aspx in [mydomin]-admin.sharepoint.de to lookup our ClientId from MsStore and sharepoint.de can resolve it and shows the correct configuration. I then used this dialog to copy the xml-part with the permision from the manifest directly to this dialog and trust the store app directly. But i'm still getting 401 Error when i try to get the AppOnlyContext inside the App.

#### Steps to Reproduce
I created a Console App for Troubleshooting wich is down to the Line:
AuthenticationManager().GetAppOnlyAuthenticatedContext(siteUrl, acsAppId, 
				acsAppSecret, AzureEnvironment.Germany);
and i'm just changing acsAppId and acsAppSecret between the ones from Ms Store and local created.

I asked Ms Store support since i think this is a trust issue between ms store and sharepoint.de since i can reproduce the same behaivior with a simple http post build like this (sample) - but ms store support denys request and points to programming:

string loginService = "login.microsoftonline.de";
string acsClientID = $"{acsAppId}@{tenantId}";
string AuthUrl = $"https://{loginService}/{tenantId}/tokens/OAuth/2";
string postdata =
                $"grant_type=client_credentials&resource={TokenHelper.SharePointPrincipal}/{tenantName}@{tenantId}&client_id={acsClientID}&client_secret={acsAppSecret}";

**Comment by jansenbe** [comment]
Hi @czullu ,
this seems to be more related to issues with the MS Store in combination with German cloud and not really a PnP issue. Seems there indeed is something wrong at store level (like the store id/secret is not created in the right location). Would recommend keep working with support on this one as PnP can't fix this.

**Comment by czullu** [comment]
Thank you for your answer - it was a long reach with the hope that you would have the connections to get the attention to this issue. I had already a ticket in sellerdashboard open but support refused responsibility since it's code.. even the same code works fine with a local Id/Secret from the german tenant which makes the ID/Secret the only difference.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
