### ISSUE TITLE
GetWebLoginClientContext() does not return all cookies

### ISSUE THREAD

**Issue by PowershellNinja** [SharePoint/PnP-Sites-Core#1317]
#### Category
[] Bug
[x] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4927.1001 - May 2017 CU

#### Expected or Desired Behavior
Currently, the Method GetWebLoginClientContext() does not return all cookies it is provided with. In our environment with a lot of load balancers, webapp firewalls, proxies etc. there are a lot of cookies issued that you need to reach SharePoint. The FedAuth cookie is not enough to get through to the SharePoint server, at least one cookie is missed out and the connection fails. This makes it impossible to use the WebLogin Form to Authenticate to our local SharePoint. My Suggestion is to return all Cookies the WebLoginForm is provided with, not just cookies starting with "FedAuth" or "rtFa".
The part of the code I am referring to is inside 
```C#
GetWebLoginClientContext(string siteUrl, Icon icon = null)
```
specifically:
```C#
cookies.SetCookies(siteUri, string.Join(",", ((IEnumerable<string>) str.Split(chArray)).Where<string>((Func<string, bool>) (c =>
          {
            if (!c.StartsWith("FedAuth", StringComparison.InvariantCultureIgnoreCase))
              return c.StartsWith("rtFa", StringComparison.InvariantCultureIgnoreCase);
            return true;
          }))));
```
I am not entirely sure why the filtering even happens, but I guess there was a reason to implement it like this. Surely this could be solved by just removing the filtering:
```C#
cookies.SetCookies(siteUri, string.Join(",", ((IEnumerable<string>) str.Split(chArray))));
```
but as I don't know the intention behind the filtering first hand, maybe there is a better solution to this than just removing the filter? Or would changing this to allow more cookies to be returned mess up another part of the code?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
