### ISSUE TITLE
HasMinimalServerLibraryVersion() catches only Web Exceptions

### ISSUE THREAD

**Issue by PowershellNinja** [SharePoint/PnP-Sites-Core#1318]
#### Category
[ x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4927.1001 - May 2017 CU

#### Expected or Desired Behavior
The Expected behaviour when calling
```C#
HasMinimalServerLibraryVersion(this ClientRuntimeContext clientContext, Version minimallyRequiredVersion)
```
would be to handle errors internally and return true or false in any case, even when an error happens in the method body.

#### Observed Behavior
When calling the Method
```C#
HasMinimalServerLibraryVersion(this ClientRuntimeContext clientContext, Version minimallyRequiredVersion)
```
while connecting to a SharePoint environment protected by a proxy/web application firewall that returns you a access denied errorpage with status code 200  because you cannot use DefaultAuthentication to connect through the proxy. There is no WebException happening, but a general "Index was out of Array Bounds" Exception because the WebRequest "succeeds" using the DefaultCredentials (Getting the Access Denied Page with a Statuscode 200), but did not get the expected response.
Now the catch block is scoped to WebExceptions - so in the end, an uncaught Exceptions comes through and breaks the execution instead of returning "False".

#### Steps to Reproduce
To reproduce this issue, the target SharePoint Page will need to run behind a proxy/waf that, on authentication errors against the Sharepoint, will provide you with a custom "Access Denied" page with a StatusCode of 200, because Windows Authentication is disabled. When calling the Method against this SharePoint Page (Even with an Authenticated Context) breaks the code as not the WebRequest fails (that would get caught) but the processing of the (unexpected) result.

My suggestion would be to change the Catch block to also catch this type of error, not just the WebExceptions - or just catch and handle the generic Exception in the catch block.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
