### ISSUE TITLE
How to get SP user in WebApi Controller

### ISSUE THREAD

**Issue by cwdata** [SharePoint/PnP-Sites-Core#1320]
Hi there,
our scenario is as follows:
A SPFx Webpart in SharePoint calls a provider hosted Add-In with a WebApi hosted in Azure to do things in SharePoint, the current user itself is not allowed to do. 
There is an example in sp-dev-fx-webparts called react-sp-elevatedprivileges which shows a nice way to do this. It is using the AuthenticationManager class from pnp-sites-core to authenticate to SP with app-only credentials.
The problem we are facing is, that we need to apply some rules based on the current user to allow usage of the elevated actions. So we tried to get a user token in the WebApi controller by using GetWebLoginClientContext. Basically this should work in an Api call because the user is already logged in to SharePoint but it seems that the needed redirect to get the token is not allowed when using Cors.
Does anyone know of a way to get the current logged in user inside the Api controller? Basically we need the User object from SharePoint including id, login name and mail address to determine what he is allowed to do.

Thanks for your help

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
