### ISSUE TITLE
Duplicate views are created for tasks lists

### ISSUE THREAD

**Issue by madrileanu** [SharePoint/PnP-Sites-Core#1321]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online (v2.16.1706)
[ ] SharePoint 2016
[ ] SharePoint 2013

Issue is reproducing also for 2.17.1708.1 

#### Expected or Desired Behavior
Provisioning existing tasks lists in a site should not generate duplicated views.

#### Observed Behavior
I have provisioned several sites based on pnp template. I have observed that duplicated views are created for existing tasks lists: All Tasks,Late Tasks,Upcoming,Completed,My Tasks,Gantt Chart and Calendar.
Please see bellow the list instance xml that i'm using:
`        <pnp:ListInstance Title="Tasks" Description="" DocumentTemplate="" OnQuickLaunch="true" TemplateType="171" Url="Lists/Tasks" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="f9ce21f8-f437-4f7e-8bc6-946378c850f0" ContentTypesEnabled="true" EnableFolderCreation="false">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0108" Default="true"/>
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{0E83412E-383B-461F-A29F-9CE2CDE71817}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Tasks" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <ViewFields>
                <FieldRef Name="Checkmark"/>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
                <FieldRef Name="Duration"/>
              </ViewFields>
              <RowLimit Paged="TRUE">100</RowLimit>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{2C2BEA56-AE05-4809-A412-02DC0510B65D}" MobileView="TRUE" Type="HTML" DisplayName="Late Tasks" Url="latex.aspx" Level="1" BaseViewID="2" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <Query>
                <Where>
                  <And>
                    <Or>
                      <IsNull>
                        <FieldRef Name="PercentComplete"/>
                      </IsNull>
                      <Neq>
                        <FieldRef Name="PercentComplete"/>
                        <Value Type="Number">1</Value>
                      </Neq>
                    </Or>
                    <Lt>
                      <FieldRef Name="DueDate"/>
                      <Value Type="DateTime">
                        <Today/>
                      </Value>
                    </Lt>
                  </And>
                </Where>
                <OrderBy>
                  <FieldRef Name="DueDate"/>
                  <FieldRef Name="Priority"/>
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="Checkmark"/>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
              </ViewFields>
              <RowLimit Paged="TRUE">100</RowLimit>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{5C2D9027-A4AA-4312-A958-6AB6D8C43299}" MobileView="TRUE" Type="HTML" DisplayName="Upcoming" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/Upcoming.aspx" Level="1" BaseViewID="3" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <Query>
                <Where>
                  <And>
                    <Or>
                      <IsNull>
                        <FieldRef Name="PercentComplete"/>
                      </IsNull>
                      <Neq>
                        <FieldRef Name="PercentComplete"/>
                        <Value Type="Number">1</Value>
                      </Neq>
                    </Or>
                    <Geq>
                      <FieldRef Name="DueDate"/>
                      <Value Type="DateTime">
                        <Today/>
                      </Value>
                    </Geq>
                  </And>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="Checkmark"/>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
              </ViewFields>
              <RowLimit Paged="TRUE">100</RowLimit>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{452360F8-F600-4465-9ECC-81D36B22D7D5}" MobileView="TRUE" Type="HTML" DisplayName="Completed" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/completed.aspx" Level="1" BaseViewID="4" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <Query>
                <Where>
                  <Geq>
                    <FieldRef Name="PercentComplete"/>
                    <Value Type="Number">1.0</Value>
                  </Geq>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="Checkmark"/>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
              </ViewFields>
              <RowLimit Paged="TRUE">100</RowLimit>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{425A57D6-CBA1-4395-8E6B-CEFB4792886B}" MobileView="TRUE" Type="HTML" DisplayName="My Tasks" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/MyItems.aspx" Level="1" BaseViewID="5" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issues.png?rev=44">
              <Query>
                <Where>
                  <In>
                    <FieldRef Name="AssignedTo" LookupId="TRUE"/>
                    <Values>
                      <Value Type="Integer">
                        <UserID/>
                      </Value>
                    </Values>
                  </In>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="Checkmark"/>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
              </ViewFields>
              <RowLimit Paged="TRUE">100</RowLimit>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{085E8226-E17A-40E8-8868-10BBF446D612}" Type="GANTT" DisplayName="Gantt Chart" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/gantt.aspx" Level="1" BaseViewID="8" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <ViewFields>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="StartDate"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="PercentComplete"/>
                <FieldRef Name="Predecessors"/>
                <FieldRef Name="AssignedTo"/>
                <FieldRef Name="GUID"/>
              </ViewFields>
              <RowLimit Paged="TRUE">100</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
            <View Name="{150BE9BB-D06E-42B0-8642-0ECC0208AD19}" Type="CALENDAR" TabularView="FALSE" DisplayName="Calendar" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/calendar.aspx" Level="1" BaseViewID="9" ContentTypeID="0x" MobileUrl="_layouts/15/mobile/viewdaily.aspx" ImageUrl="/_layouts/15/images/events.png?rev=44">
              <Query>
                <Where>
                  <DateRangesOverlap>
                    <FieldRef Name="StartDate"/>
                    <FieldRef Name="DueDate"/>
                    <Value Type="DateTime">
                      <Month/>
                    </Value>
                  </DateRangesOverlap>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="StartDate"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="Title"/>
                <FieldRef Name="Description"/>
              </ViewFields>
            </View>
            <View Name="{F3B2C923-2479-4CB7-A752-75F87D225A26}" MobileView="TRUE" Type="HTML" DisplayName="Overdue" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/Overdue.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <Query>
                <OrderBy>
                  <FieldRef Name="DueDate"/>
                  <FieldRef Name="Title"/>
                </OrderBy>
                <Where>
                  <And>
                    <And>
                      <And>
                        <Eq>
                          <FieldRef Name="Checkmark"/>
                          <Value Type="Boolean">0</Value>
                        </Eq>
                        <Leq>
                          <FieldRef Name="DueDate"/>
                          <Value Type="DateTime">
                            <Today/>
                          </Value>
                        </Leq>
                      </And>
                      <IsNotNull>
                        <FieldRef Name="Duration"/>
                      </IsNotNull>
                    </And>
                    <Neq>
                      <FieldRef Name="Duration"/>
                      <Value Type="Text">0 days</Value>
                    </Neq>
                  </And>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
                <FieldRef Name="Duration"/>
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off"/>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{7452D0FE-DEAE-469C-ADFC-AD35D15FC36A}" MobileView="TRUE" Type="HTML" DisplayName="Unassigned" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/Unassigned.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <Query>
                <OrderBy>
                  <FieldRef Name="DueDate"/>
                  <FieldRef Name="Title"/>
                </OrderBy>
                <Where>
                  <And>
                    <And>
                      <And>
                        <Eq>
                          <FieldRef Name="Checkmark"/>
                          <Value Type="Boolean">0</Value>
                        </Eq>
                        <IsNotNull>
                          <FieldRef Name="Duration"/>
                        </IsNotNull>
                      </And>
                      <Neq>
                        <FieldRef Name="Duration"/>
                        <Value Type="Text">0 days</Value>
                      </Neq>
                    </And>
                    <IsNull>
                      <FieldRef Name="AssignedTo"/>
                    </IsNull>
                  </And>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
                <FieldRef Name="Duration"/>
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off"/>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
            <View Name="{1E269628-4579-4E80-A370-CA9683DBDD96}" MobileView="TRUE" Type="HTML" DisplayName="HighPriority" Url="/sites/P00139/0B471DE7D4812C15ACCF8B569D8A4BB1/Lists/Tasks/HighPriority.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/issuelst.png?rev=44">
              <Query>
                <OrderBy>
                  <FieldRef Name="DueDate"/>
                  <FieldRef Name="Title"/>
                </OrderBy>
                <Where>
                  <And>
                    <And>
                      <And>
                        <Eq>
                          <FieldRef Name="Checkmark"/>
                          <Value Type="Boolean">0</Value>
                        </Eq>
                        <IsNotNull>
                          <FieldRef Name="Duration"/>
                        </IsNotNull>
                      </And>
                      <Neq>
                        <FieldRef Name="Duration"/>
                        <Value Type="Text">0 days</Value>
                      </Neq>
                    </And>
                    <Eq>
                      <FieldRef Name="Priority"/>
                      <Value Type="Text">(1) High</Value>
                    </Eq>
                  </And>
                </Where>
              </Query>
              <ViewFields>
                <FieldRef Name="LinkTitle"/>
                <FieldRef Name="DueDate"/>
                <FieldRef Name="AssignedTo"/>
                <FieldRef Name="Duration"/>
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <Aggregations Value="Off"/>
              <JSLink>hierarchytaskslist.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Integer" StaticName="TaskUID" DisplayName="TaskUID" Description="ID of Task." AllowDeletion="FALSE" ShowInDisplayForm="FALSE" ShowInEditForm="FALSE" ShowInNewForm="FALSE" ShowInViewForms="FALSE" ID="{0f8eaca3-d700-4a19-864d-bd9eee94b2b9}" SourceID="{{listid:Tasks}}" Name="TaskUID" ColName="int5" RowOrdinal="0" Version="1"/>
            <Field Type="Text" Name="SyncedProjectGUID" DisplayName="SyncedProjectGUID" Description="GUID of the Synced Project.  Please don't modify or delete." AllowDeletion="FALSE" ShowInDisplayForm="FALSE" ShowInEditForm="FALSE" ShowInNewForm="FALSE" ShowInViewForms="FALSE" ID="{2453a761-2405-48ba-8507-394164d5fb37}" Version="20" StaticName="SyncedProjectGUID" SourceID="{{listid:Tasks}}" ColName="nvarchar5" RowOrdinal="0">
              <Default>{0E2368E8-8273-E611-A2B9-6CC217DB11D0}</Default>
            </Field>
            <Field Type="Text" DisplayName="Duration" Required="FALSE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{818a80cb-aa67-497f-b0c9-409b17a06e52}" SourceID="{{listid:Tasks}}" StaticName="Duration" Name="Duration" ColName="nvarchar6" RowOrdinal="0" Version="1"/>
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c3a92d97-2b77-4a25-9698-3ab54874bc6f" Name="Predecessors" DisplayName="Predecessors"/>
            <pnp:FieldRef ID="a8eb573e-9e11-481a-a8c9-1104a54b2fbd" Name="Priority" DisplayName="Priority"/>
            <pnp:FieldRef ID="c15b34c3-ce7d-490a-b133-3f4de8801b76" Name="Status" DisplayName="Task Status"/>
            <pnp:FieldRef ID="d2311440-1ed6-46ea-b46d-daa643dc3886" Name="PercentComplete" DisplayName="% Complete"/>
            <pnp:FieldRef ID="53101f38-dd2e-458c-b245-0c236cc13d1a" Name="AssignedTo" DisplayName="Assigned To"/>
            <pnp:FieldRef ID="7662cd2c-f069-4dba-9e35-082cf976e170" Name="Body" DisplayName="Description"/>
            <pnp:FieldRef ID="64cd368d-2f95-4bfc-a1f9-8d4324ecb007" Name="StartDate" DisplayName="Start Date"/>
            <pnp:FieldRef ID="cd21b4c2-6841-4f9e-a23a-738a65f99889" Name="DueDate" DisplayName="Due Date"/>
            <pnp:FieldRef ID="d2a04afc-9a05-48c8-a7fa-fa98f9496141" Name="RelatedItems" DisplayName="Related Items"/>
          </pnp:FieldRefs>
          <pnp:FieldDefaults>
            <pnp:FieldDefault FieldName="PercentComplete">0</pnp:FieldDefault>
            <pnp:FieldDefault FieldName="StartDate"/>
          </pnp:FieldDefaults>
        </pnp:ListInstance>`

#### Steps to Reproduce
* Provision tasks lists instances to any team site

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by thunderknot** [comment]
Have you found a solution for this?
