### ISSUE TITLE
OnlyAllowMembersViewMembership="true" is not honored

### ISSUE THREAD

**Issue by prawnz** [SharePoint/PnP-Sites-Core#1323]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
OnlyAllowMembersViewMembership="true" should set Group Members for the "Who can view the membership of the group?" setting on the SharePoint group.

#### Observed Behavior
SharePoint group setting for Who can view the membership of the group? is set to Everyone

#### Steps to Reproduce
1. Create a provisioning template with a similar XML for the Site Groups as such
    `<pnp:SiteGroups>
          <pnp:SiteGroup Title="Business Unit Editor Team" Description="" Owner="Nicholas Ang" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="true">
            <pnp:Members>
              <pnp:User Name="Nicholas Ang" />
            </pnp:Members>
          </pnp:SiteGroup>
 </pnp:SiteGroups>`
2. Use Apply-PnPProvisioningTemplate with template created from step 1.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
