### ISSUE TITLE
web.ApplyProvisioningTemplate in Azure Functions throwing Error

### ISSUE THREAD

**Issue by pmatthews05** [SharePoint/PnP-Sites-Core#1326]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Able to read in an XML PNP Template and provision against a SharePoint Site.

#### Observed Behavior
At the point where web.ApplyProvisioningTemplate is called, the Azure function errors with the error message:

> Error Message: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'Microsoft.SharePoint.Client.Taxonomy.TermStore'.

#### Steps to Reproduce
Create Azure function, with the following dependencies:

- "SharePointPnPCoreOnline": "2.17.1708.1",

- "Microsoft.IdentityModel.Clients.ActiveDirectory":"2.18.0.0",

- "AngleSharp": "0.9.9",

- "Microsoft.AspNet.WebApi.Client" : "5.2.3",

- "Microsoft.AspNet.WebApi.Core" : "5.2.3",

- "Microsoft.Azure.ActiveDirectory.GraphClient":"2.1.0",

- "Microsoft.Azure.KeyVault.Core":"1.0.0",

- "Microsoft.Data.Edm":"5.6.4",

- "Microsoft.Data.OData":"5.6.4",

- "Microsoft.Data.Services.Client":"5.6.4",

- "Microsoft.IdentityModel":"6.1.7600.16394",

- "Microsoft.SharePointOnline.CSOM":"16.1.6621.1200",

- "Newtonsoft.Json":"9.0.1",

- "SharePointPnP.IdentityModel.Extensions":"1.2.2",

- "System.Spatial":"5.6.4",

- "WindowsAzure.Storage":"7.0.0"

```
using OfficeDevPnP.Core;
using OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml;
using OfficeDevPnP.Core.Framework.Provisioning.Model;
using OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers;
using Microsoft.SharePoint.Client; 
using Microsoft.SharePoint.Client.Taxonomy;
using System.Collections.Generic;
using System;
using System.Net;
using System.Configuration;
using System.Security;
using System.Threading;

public static void Run(TimerInfo myTimer, TraceWriter log)
{
   string siteUrl = "https://mytenant.sharepoint.com/sites/Test";
   string userName = "paul.matthews@mytenant.onmicrosoft.com";
   string password = "MyPassword";
   OfficeDevPnP.Core.AuthenticationManager authManager = new OfficeDevPnP.Core.AuthenticationManager();
   var providerPath = Path.Combine(Environment.GetEnvironmentVariable("HOME"), "site\\wwwroot\\TimerTriggerCSharp1\\");
   var doctemplateXML = "demo1.xml";
   try  
   {  
        using (var ctx = authManager.GetSharePointOnlineAuthenticatedContextTenant(siteUrl, userName, password))  
       {  
           log.Info("Got Context");
          
           XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(providerPath, "");
           ProvisioningTemplate template = provider.GetTemplate(doctemplateXML);
 
          ProvisioningTemplateApplyingInformation ptai = new ProvisioningTemplateApplyingInformation(){
               ProgressDelegate = (message, progress, total) => {
                   log.Info(String.Format("{0:00}/{1:00} - {2}",progress, total, message));
               },
               MessagesDelegate = (message, messageType) => {
                   log.Info(String.Format("{0} - {1}", messageType, message));
               }
           };

           log.Info("Applying Template");
           ctx.Web.ApplyProvisioningTemplate(template); //, ptai);
           log.Info("Done with List Name: " + listName);
       }  
   }  
   catch (Exception ex)  
   {  
       log.Info("Error Message: " + ex.Message);  
   }  
}
```

I'm unable to provide a template (security reasons), however I did also get the same error when I created a SharePoint STS#0 teamsite used pnp to create a template for me (tried both using C# code and powershell) and used that template to import.

This is the first time I've used Azure functions so it could quite possibly be me setting something up wrong.

Thanks.

Paul.

**Comment by pmatthews05** [comment]
Hi @jansenbe, is there a chance someone could look at this, or advise?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by richardb52** [comment]
Hi @pmatthews05, I'm curious if you ever figured out the cause of this? I'm hitting a similar issue.

**Comment by pmatthews05** [comment]
Hi @richardb52 ,
 I was last using SharePointPNPCoreOnline 3.2.1810 and haven't seen this issue.
