### ISSUE TITLE
ProvisioningTemplate should expose Parameters as specialized collection

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#1334]
#### Category
- [x] Bug
- [x] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [x] SharePoint 2016
- [x] SharePoint 2013

#### Expected or Desired Behavior
PnP Provisioning Schema supports the possibility to specify if a Parameter object should be Required or not.
[PnP Schema ref](https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2017-05.xsd#L97-L102) (documentation for Parameter isn't available..)
I want to be able to read at runtime, via ProvisioningTemplate class, whether a Parameter is required or not.

#### Observed Behavior
ProvisioningTemplate exposes Parameters as a Dictionary (key=parameter's key, value=parameter's default value), and so it isn't possible to retrieve additional information of a parameter
[ProvisioningTemplate code ref](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ProvisioningTemplate.cs#L105-L112)

#### Steps to Reproduce
Create a template XML with following parameter:

` <pnp:Parameter Key="Yammer Group" Required="False"></pnp:Parameter>`

The information about that Parameter isn't required (mandatory) cannot be retrieved at runtime because it's not exposed by the model class.

Cheers
Massimo

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
