### ISSUE TITLE
Client side "People" web part not exported with Title

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Sites-Core#1336]
#### Category
[x] Bug

#### Environment
[x] Office 365 / SharePoint Online

#### Expected or Desired Behavior
When exporting a client side page with web parts, the title set in the UI should be included in the export.

#### Observed Behavior
The title property is not included, and the error is in the web part itself. As seen in the image below, the title you add is part of the markup, but not part of the properties JSON.

![image](https://user-images.githubusercontent.com/51104/30324874-d923f4e8-97c2-11e7-9787-d5bf1d21ba54.png)

If you manually add a title property to the wp definition in a provisioning template, the title is set just fine.

#### Steps to Reproduce
* Create a client side page and add a people web part.
* Set a title for the webpart
* Extract a template with Pages,PageContent handlers
* Apply the same template, and the web part has no longer a title.

The web part could be fixed, or one could apply a workaround in the prov.engine to pull the title from the markup and set the property.

cc @VesaJuvonen

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
