### ISSUE TITLE
release 1709.1 shows incorrect generator version in extracted template

### ISSUE THREAD

**Issue by kath561** [SharePoint/PnP-Sites-Core#1341]
the powershell repository says that issues with Get-PnPProvisioningTemplate should be logged here.

just updated to latest 1709.1 release and confirmed this in powershell

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 2.18.1709.1

ran

Get-PnPProvisioningTemplate -Out c:\extract4.xml -Schema V201705 

extracted template shows old version number

<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.18.1709.0, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-46FF352BC5BE429EBD139528225E2AF3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-46FF352BC5BE429EBD139528225E2AF3" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">

**Comment by jansenbe** [comment]
That's correct, the binaries have not been upped with the .1 release as there only was an issue with nuget package dependencies. Closing this issue now.
