### ISSUE TITLE
GetProvisioningTemplate does not extract clientsidepages object from modern site

### ISSUE THREAD

**Issue by kath561** [SharePoint/PnP-Sites-Core#1342]
release 1709.1 updated from nuget
executing in in console app 

the ClientSidePages element should be extracted in the Get-GetProvisioningTemplate for at least the home page of a modern site.

executing Web.GetProvisioningTemplate against a classic site retrieves any modern pages into this element. Works as expected.
 The same code against a modern site does not retrieve any of the modern pages into the output template object. The ClientSidePages object remains empty.

**Comment by jansenbe** [comment]
Version 1709.1 only exists for on-premises versions, for SPO we're still at 1709.0 ==> Can you try to install this nuget https://www.nuget.org/packages/SharePointPnPCoreOnline and try again? Assume you're not testing in SP2016 as we've (not yet) added support for modern pages in that version (although it's now possible with feature pack 2).

**Comment by kath561** [comment]
Thanks for the review and clarifying the version numbers. The confusion arises from the release info for the engine for powershell version SharePointPnPPowerShellOnline indicates that 1709.1 applies to all platforms. https://github.com/SharePoint/PnP-PowerShell/releases . Looking again at the Nuget details I am testing against for SharePointPnpCoreOnline I see that it just says 2.18.1709  dated sept 8th and doesn’t mention the point release number. So just the usual confusion, sorry.

 

We are talking SPO exclusively here as I have no on-prem access.

I am testing the same commands against both SharePointPnpCoreOnline from a c# console prog and SharePointPnPPowerShellOnline from powershell.

 

C# console prog: my intention is to reproduce  the sept SIG demo for ClientSidePage element extraction and provisioning.

I have updated the nuget package several times to ensure that it is latest and the template headers appear to confirm that. Also the fact that it will generate the ClientSidePages element successfully from a classic site containing a modern page, confirms that the support is in the module I am executing. But when the same code is run against a modern site then no ClientSidePages are extracted not even the modern home page. However, the module will provision new modern pages no problems from the same code via both the Apply-ProvisioningTemplate and via the Add-ClientSidePage commands.

 

Powershell: the same series of commands executed via powershell show consistent behaviour with above.

 

conclusion

This seems to be a problem in the core module as it is consistent between console program and powershell requests.

 

 

Many thanks

Kath

**Comment by jansenbe** [comment]
Not sure if this is still a problem, but if so please test again with the October package which will be available as of next week.

**Comment by kath561** [comment]
retested with latest V19. all good now. thanks chaps.
