### ISSUE TITLE
GetProvisioningTemplate stuck while extracting lists

### ISSUE THREAD

**Issue by TanmayDharmaraj** [SharePoint/PnP-Sites-Core#1343]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
GetProvisioningTemplate should extract Lists.

#### Observed Behavior
Object list instances do not get exported and get stuck in a deadlock.
The exact place where the deadlock occurs is while extracting webhooks for in ObjectListInstances. 
The code works perfectly fine if you run the tests but in a MVC web project i have encountered deadlocks. 

#### Steps to Reproduce
1. Create a web project
2. include the nuget package (2.18)
3. Write an API that extracts lists. _My APIs are async (may be this is of importance)_

I have a fix for this on my local machine, can raise PR. Do let me know :)

Thanks for the great work.

**Comment by TanmayDharmaraj** [comment]
@jansenbe Hello, I have added a PR and signed the CLA. PR still shows cla-required. Any help?

**Comment by jansenbe** [comment]
If you've signed it's ok, the automation behind this sometimes does not update the labels in the PR. Thanks for the fix, we'll evaluate it.

**Comment by jansenbe** [comment]
Fix has been merged into dev, will be in upcoming October release
