### ISSUE TITLE
Get-PNPProvisioningTemplate : An error occurred while parsing EntityName.

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#1346]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Get-PnPProvisioningTemplate should collect the full site.

#### Observed Behavior
After the navigation was successfully exported the following error message appears:

`PowerShell_ISE.exe Information: 0 : 2017-09-20 10:01:16.3752    [Navigation]    [12]    [Debug]    Code execution scope started    0ms    152b1
f0a-1ab9-4151-80e7-17ee57847af0
PowerShell_ISE.exe Information: 0 : 2017-09-20 10:01:17.0864    [Navigation]    [12]    [Debug]    Code execution scope ended    711ms    152b1
f0a-1ab9-4151-80e7-17ee57847af0
PowerShell_ISE.exe Information: 0 : 2017-09-20 10:01:17.0904    [Retrieve Template Info]    [12]    [Debug]    Code execution scope start
ed    0ms    152b1f0a-1ab9-4151-80e7-17ee57847af0
PowerShell_ISE.exe Information: 0 : 2017-09-20 10:01:17.2845    [Retrieve Template Info]    [12]    [Debug]    Code execution scope ended
    193ms    152b1f0a-1ab9-4151-80e7-17ee57847af0
PowerShell_ISE.exe Information: 0 : 2017-09-20 10:01:17.2845    [Extraction]    [12]    [Debug]    Code execution scope ended    205068ms    15
2b1f0a-1ab9-4151-80e7-17ee57847af0
Get-PNPProvisioningTemplate : An error occurred while parsing EntityName. Line 1, position 285.
At line:1 char:1
+ Get-PNPProvisioningTemplate -Out G:\Production\Teams\Product ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], XmlException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate
 `

#### Steps to Reproduce
Simply run a Get-PnPProvisioningTemplate on the site in question.

We tried just exporting navigation and this works fine. So the problem seems to be in one of these object handlers:
* ImageRenditions
* ObjectLocalizations
* ExtensibilityProviders

There isn't an easy way to exclude/include the above handlers using PowerShell.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
