### ISSUE TITLE
ClientSidePage property PageTitle always null

### ISSUE THREAD

**Issue by kath561** [SharePoint/PnP-Sites-Core#1348]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
property should be populated with page title from sharepoint as appears in the page banner and if altered the new property should be applied during the save.

#### Observed Behavior
value is always null. If altered and saved the property change is ignored and not applied.

#### Steps to Reproduce
                OfficeDevPnP.Core.Pages.ClientSidePage page = OfficeDevPnP.Core.Pages.ClientSidePage.Load(clientcontext, "existingpagename.aspx");
Console.WriteLine(page.PageTitle);
                    page.PageTitle = "title changed";
                    page.Save("existingpagename.aspx");
                OfficeDevPnP.Core.Pages.ClientSidePage page = OfficeDevPnP.Core.Pages.ClientSidePage.Load(cc, "existingpagename.aspx");
Console.WriteLine(page.PageTitle);

 Sharing is caring.

**Comment by jansenbe** [comment]
Page title can now be configured.
