### ISSUE TITLE
Provisioning Engine: NullReferenceException when Provisioning does not contain any ProvisioningTemplate

### ISSUE THREAD

**Issue by mkacena** [SharePoint/PnP-Sites-Core#1357]
#### Category
[ x ] Bug
[ ] Enhancement

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
According to the current provisioning schema, section `Templates` in `Provisioning` is optional. Also, putting a `ProvisioningTemplate` inside `Templates` is optional. One would therefore expect that if the XML file does not contain any `ProvisioningTemplate` element, the PnP Provisioning Engine would just process other defined elements when the template is read.

#### Observed Behavior
The PnP Provisioning Engine crashed with _NullReferenceException_ when `GetTemplate` method was called.

#### Steps to Reproduce
Use `GetTemplate` method on a provisioning template with only required elements.
Even using `ProvisioningTemplateFile` crashes, only if the file contains `ProvisioningTemplate` element, it is processed successfully.

PnP Core NuGet: SharePointPnPCoreOnline 2.18.1709

Template XML:
```xml
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Version="1.0">
  </pnp:Preferences>
</pnp:Provisioning>
```

.NET Code:
```csharp
XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(AppDomain.CurrentDomain.BaseDirectory, "");
ProvisioningTemplate template = provider.GetTemplate("template.xml");
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
