### ISSUE TITLE
Issues with LoadClientSidePage

### ISSUE THREAD

**Issue by Saulius-Laurinaitis** [SharePoint/PnP-Sites-Core#1362]
I'm getting exception when trying to load a page which contains text component:

- ClientSideCanvasControlPosition.ControlIndex should be float, because on my pages I'm getting value "0.5" as well.

- I'm getting exception in class ClientSidePageControls.cs function FromHtml(IElement element) when my text component does not have a wrapping DIV, I would suggest include else block when div is not fount:

internal override void FromHtml(IElement element)
        {
            base.FromHtml(element);

            var div = element.GetElementsByTagName("div").Where(a => a.HasAttribute(TextRteAttribute)).FirstOrDefault();
            if (div != null)
            {
                this.rte = div.GetAttribute(TextRteAttribute);

                // By default text is wrapped in a Paragraph, need to drop it to avoid getting multiple paragraphs on page edits
                if ((div.FirstChild as IElement).TagName.Equals("P", StringComparison.InvariantCultureIgnoreCase))
                {
                    this.Text = (div.FirstChild as IElement).InnerHtml;
                }
                else
                {
                    this.Text = div.InnerHtml;
                }
            }
            else
            {
                this.Text = element.InnerHtml;
            }
            // load data from the data-sp-controldata attribute
            var jsonSerializerSettings = new JsonSerializerSettings()
            {
                MissingMemberHandling = MissingMemberHandling.Ignore
            };
            this.spControlData = JsonConvert.DeserializeObject<ClientSideTextControlData>(element.GetAttribute(CanvasControl.ControlDataAttribute), jsonSerializerSettings);
            this.controlType = this.spControlData.ControlType;
        }

#### Category
[X ] Bug

#### Environment
[X ] Office 365 / SharePoint Online

Thanks
Saulius

**Comment by jansenbe** [comment]
Hi @Saulius-Laurinaitis, both issues are already fixed in the dev branch and will be released as part of the October PnP version, which will be released before October 10th (but most likely already on October 6th). If you need a quick fix then please use our dev branch. Closing this issue now.

**Comment by Saulius-Laurinaitis** [comment]
thanks :)
