### ISSUE TITLE
AuthenticationManager Token Request Failed

### ISSUE THREAD

**Issue by ypcode** [SharePoint/PnP-Sites-Core#1369]
#### Category
[ x ] Bug
[ ] Enhancement

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Get App Only Client Context from Client Id, Client Secret and Realm credentials.

On our DEV tenant, the AuthenticationManager code works properly, but on my customer production tenant, unfortunately, it doesn't, I don't really know on which "Cloud" the customer's tenant is hosted.

#### Observed Behavior
the following code throws the exception below with a particular tenant
```
try
            {
                log.Info("Get app-only context using PnP AuthenticationManager...");
                log.Info($"Credentials: \nSPHostUrl: {AppConfig.Instance.SPHostUrl}\nRealm: {AppConfig.Instance.Realm}\nClient Id:{AppConfig.Instance.ClientId}\nClient Secret:{AppConfig.Instance.ClientSecret}");
                return new AuthenticationManager()
                    .GetAppOnlyAuthenticatedContext(
                    AppConfig.Instance.SPHostUrl,
                    AppConfig.Instance.Realm,
                    AppConfig.Instance.ClientId,
                    AppConfig.Instance.ClientSecret);
            }
            catch (Exception ex)
            {
                log.Error("PnP AuthenticationManager AppOnly context cannot be created. Fallback to TokenHelper...", ex);
                
                // Fallback solution
                Uri siteUri = new Uri(AppConfig.Instance.SPHostUrl);
                var SharePointPrincipalId = "00000003-0000-0ff1-ce00-000000000000";
                var token = TokenHelper.GetAppOnlyAccessToken(SharePointPrincipalId, siteUri.Authority, null).AccessToken;
                return TokenHelper.GetClientContextWithAccessToken(siteUri.ToString(), token);
            }
```

ERROR 2017-09-26 20:22:05,189 [8] MembersController - PnP AuthenticationManager AppOnly context cannot be created. Fallback to TokenHelper...
Microsoft.IdentityModel.SecurityTokenService.RequestFailedException: Token request failed. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at SharePointPnP.IdentityModel.Extensions.S2S.Protocols.OAuth2.OAuth2WebRequest.GetResponse()
   at SharePointPnP.IdentityModel.Extensions.S2S.Protocols.OAuth2.OAuth2S2SClient.Issue(String securityTokenServiceUrl, OAuth2AccessTokenRequest oauth2Request)
   --- End of inner exception stack trace ---
   at SharePointPnP.IdentityModel.Extensions.S2S.Protocols.OAuth2.OAuth2S2SClient.Issue(String securityTokenServiceUrl, OAuth2AccessTokenRequest oauth2Request)
   at OfficeDevPnP.Core.Utilities.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String targetHost, String targetRealm)
   at OfficeDevPnP.Core.AuthenticationManager.EnsureToken(String siteUrl, String realm, String appId, String appSecret, String acsHostUrl, String globalEndPointPrefix)
   at <custom code>

While the "fallback" solution using the TokenHelper class works... using exactly the same credentials.

The strange thing is that, with PnP PowerShell, using the command
Connect-PnPOnline -Url <tenant> -Realm <realm> -AppId <clientId> -AppSecret <clientSecret>

with the exact same credentials , it manages to connect properly.

#### Steps to Reproduce
see code excerpt above

**Comment by jansenbe** [comment]
Hi Yannick,

Can you drop me the customer tenant name via bjansen@microsoft.com?

**Comment by ypcode** [comment]
Hi Bert,

Done via my pro e-mail address.

Thx

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
