### ISSUE TITLE
Provisioning Engine: StructuralLocal Navigation not set in Enterprise Wiki

### ISSUE THREAD

**Issue by mkacena** [SharePoint/PnP-Sites-Core#1370]
#### Category
[ x ] Bug
[ ] Enhancement

#### Environment
[ x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When I apply a provisioning template containing navigation nodes to Enterprise Wiki, I expect the navigation to be set accordingly to the template.

#### Observed Behavior
The current navigation is unchanged.

When I go to Site Settings > Navigation, I see that the nodes from the template are in fact created, but the Current Navigation is set to _Managed Navigation,_ not _Structural Navigation_ as defined in the template.

I also found out that the template (with different navigation links of course) works correctly in a Team Site.

#### Steps to Reproduce
NuGet: SharePointPnPCoreOnline 2.18.1709

Create a new site collection of type Enterprise Wiki in SharePoint Online. 
Apply the following template with PnP Core's `web.ApplyProvisioningTemplate`:

```xml
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">

  <pnp:Preferences>
  </pnp:Preferences>

  <pnp:Templates ID="PNP-TEMPLATES">

    <pnp:ProvisioningTemplate ID="PNP-TEMPLATE" Version="1.0">

      <pnp:Navigation>
        <pnp:CurrentNavigation NavigationType="StructuralLocal">
          <pnp:StructuralNavigation RemoveExistingNodes="true">
            <pnp:NavigationNode Title="Documents PnP" IsExternal="false" Url="Documents" />
            <pnp:NavigationNode Title="Home PnP" IsExternal="false" Url="Pages/home.aspx" />
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>
      </pnp:Navigation>

    </pnp:ProvisioningTemplate>

  </pnp:Templates>

</pnp:Provisioning>
```

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
