### ISSUE TITLE
PnP GetProvisioningTemplate Extract Authorization 401 Error

### ISSUE THREAD

**Issue by johnlewis888** [SharePoint/PnP-Sites-Core#1373]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

15.0.4937.1000

#### Expected or Desired Behavior
_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

When executing Get-PNPProvisioningTemplate command, expect to write xml file to local D:\ directory. Powershell command is being executed on SharePoint server with Farm Account. 

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

When executing Get-PNPProvisioningTemplate command, getting a 401 error. Error is occurring during extraction phase. 

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Issued the following commands 

Connect-PnPOnline -Url http://teamsiteurl.com/sites/sitecollection

*Entered Credentials for Farm account 

*Connect completes without error.

Get-PnPProvisioningTemplate -Out "D:\Definitions\Extraction.xml"

Command executes and does not error out until extraction is taking place.

Error:

PowerShell.exe Information: 0 : 2017-09-28 14:11:11.9240        [Page Contents] [10]    [Debug] Code execution scope end
ed      301ms   259091cc-82c4-4b97-92bf-a222ca989175
PowerShell.exe Information: 0 : 2017-09-28 14:11:11.9240        [Extraction]    [10]    [Debug] Code execution scope end
ed      9145ms  259091cc-82c4-4b97-92bf-a222ca989175
Get-PnPProvisioningTemplate : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Out "D:\Definitions\Extractions.xml"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

**Comment by johnlewis888** [comment]
We were able to determine the 401 error stemmed from our Page Contents. By issuing an exclude handlers for PageContents we were able to execute the extraction successfully. Now to just determine what about the page contents was throwing the 401 error.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
