### ISSUE TITLE
Importing term sets from a provisioning template fails

### ISSUE THREAD

**Issue by jensotto** [SharePoint/PnP-Sites-Core#1375]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
May 2017 and September 2017

#### Expected or Desired Behavior
Applying a provisioning template containing Term Sets should work.

#### Observed Behavior
The Term Group is imported but not the Term Set and it's Terms. 
You get this error: 
Apply-PnPProvisioningTemplate : Specified argument was out of the range of valid values.
Parameter name: lcid
At line:1 char:1
+ Apply-PnPProvisioningTemplate localterms.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

#### Steps to Reproduce
Create a Term Group, add a Term Set with a few terms in it.
Extract terms using Get-PNPProvisioningTemplate -Handlers TermGroup -IncludeAllTermGroups -Out Terms.xml
Delete the created Term Group
Apply the provisioning template.

**Comment by jensotto** [comment]
This is a sample provisioning template that produces the error (change the filename to terms.xml)
[terms.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1346469/terms.txt)

**Comment by jensotto** [comment]
The bug also affects Office365

**Comment by jensotto** [comment]
It works when using schema version 2016-05. 
It fails when using the new 2017-05 schema.

**Comment by mpinuel** [comment]
I have the same error using the new 2017-05 schema. The error apply a Term Group is: Exception: Parameter name: lcid
With a previous schema version, it works fine!

**Comment by PaoloPia** [comment]
Hi, 
Thanks for your feedback. The issue should now be fixed. I just merged the fix in the DEV branch.

**Comment by thunderstorm654** [comment]
Hi @PaoloPia, I just ran into the same bug using the latest PnP Powershell commandlets. I'm using version 2.19.1710.1. I take it the fix isn't into that yet? How do I use the 'dev branch'? Thanks!
