### ISSUE TITLE
Issue in processing site groups when applying provisioning template

### ISSUE THREAD

**Issue by xvanekj** [SharePoint/PnP-Sites-Core#1377]
Groups in templates are processed as they are stored. That can lead to problem when Owner of the group is another yet unprocessed group in template. In this case apply template process crashes with error. 

#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Groups should be processed with respect to their owner group (owner groups should be processed first).

#### Observed Behavior
When there is a group (e.g. A) in template you want to apply that has owner property set to another group (e.g. B) in template that is stored after the A group, the apply process will fail.

#### Steps to Reproduce
Create template file according to Observed Behavior section. In my case such template file was created by GetProvisioningTemplate function.

**Comment by jansenbe** [comment]
Closing issue since fix PR has been merged
