### ISSUE TITLE
StructuralLocal Navigation is skipped for Group sites

### ISSUE THREAD

**Issue by spplante** [SharePoint/PnP-Sites-Core#1384]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Applying a provisioning template with the <pnp:Navigation> node on a Group site (GROUP#0) should provision the specified navigation nodes (quick launch and global nav) as expected just like a classic SharePoint team site (STS#0).

#### Observed Behavior
When applying the provisioning template on a Group site (GROUP#0), the command completes without any error but the navigation is skipped. When refreshing the group site, nothing has changed on the quick launch of the global navigation.

I tried the exact same template on a classic team site (STS#0) and it works without a problem, the quick launch nodes are added and same thing goes for the global navigation.

#### Steps to Reproduce
- Apply the following template using the [Apply-PnPProvisioningTemplate](https://github.com/SharePoint/PnP-PowerShell/blob/master/Documentation/ApplyPnPProvisioningTemplate.md) command :

```xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.18.1709.0, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-4EC31DA6174144B4A9A11EC851909F18">
    <pnp:ProvisioningTemplate ID="TEMPLATE-4EC31DA6174144B4A9A11EC851909F18" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">
      <pnp:Navigation>
        <pnp:GlobalNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="true">
              <pnp:NavigationNode Title="Home" Url="{site}" />
          </pnp:StructuralNavigation>
        </pnp:GlobalNavigation>
        <pnp:CurrentNavigation NavigationType="StructuralLocal">
          <pnp:StructuralNavigation RemoveExistingNodes="true">
            <pnp:NavigationNode Title="Test1" Url="https://www.google.com" IsExternal="true" />
            <pnp:NavigationNode Title="Test2" Url="https://www.google.com" IsExternal="true" />
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>
      </pnp:Navigation>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

```powershell
Connect-PnPOnline -Url "https://yoursite.sharepoint.com" -Credentials $creds
Apply-PnPProvisioningTemplate -Path "[...]\template.xml"
```

Nothing will be changed in the quick launch or global navigation.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
