### ISSUE TITLE
Exporting a site that has a list view webpart with a & in the webpart XML

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/PnP-Sites-Core#1387]
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
Bug
Office 365 / SharePoint Online

When exporting a site template that has a list with a & in the name (like reports & issues) and a listview webpart added on the welcome page an exception is thrown in "XMLPnPSchemaV201605Formatter.cs" on the line: "Contents = XElement.Parse(wp.Contents).ToXmlElement()"

Parsing goes wrong when there is an & in the view webpart XML. For example:

<property name=""ListId"" type=""System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"">{listid:reports & issues}</property>

<property name=""ListName"" type=""string"">{{listid:reports & issues}}</property>

<property name=""TitleUrl"" type=""string"">{site}/reports & issues</property>

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
