### ISSUE TITLE
URL of lists should be updated on applying template.

### ISSUE THREAD

**Issue by TanmayDharmaraj** [SharePoint/PnP-Sites-Core#1390]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
List URLs when changed should get migrated correctly.
Consider a scenario where we have a list name "List A" with URL "Lists/List A". 
After deploying to the target site, if i wish to modify the URL of the list on the target site to "Lists/ListA" (without spaces), there currently is no way to achieve this.

Enhancement is to change the root folder of the list in the ObjectListInstances handler.

#### Observed Behavior
URL modification for lists do not get updated.

#### Steps to Reproduce
1. Create list in source site
2. Apply template to a target site
3. Open SharePoint designer and modify the folder name of the list (thus changing the URL). Ensure that the list title is the same.
4. Reapply template to target site. 

If this is a desired enhancement I can raise a PR :) Do let me know

Cheers,
Tanmay Dharmaraj

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
