### ISSUE TITLE
When provisioning template groups refer to default web groups like Owners or Members and these groups do not exist on target web provisioning fails.

### ISSUE THREAD

**Issue by xvanekj** [SharePoint/PnP-Sites-Core#1395]
When groups in provisioning template refer to default web groups like Owners or Members and these groups do not exist on target web, provisioning fails.

#### Which PnP repository should you use to report the issue? 

- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When missing default groups are identified they should be either also provisioned or provisioning process should stop with clear message.

#### Observed Behavior
When default groups are missing provisioning engine is not able to process values like {associatedownergroup} in the processed template and it fails with NullReference exception. User has no clue what's wrong.

#### Steps to Reproduce
1. Prepare provisioning template with at least one group in the template referencing group by 2.
2. {associatedownergroup} for instance in Owner property of that group
3. Create target web where you want to apply prepared template.
4. Delete Owners group on target web
5. Provision the template.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
