### ISSUE TITLE
Provisioning framework - Home page with web parts error

### ISSUE THREAD

**Issue by PeterHeibrink** [SharePoint/PnP-Sites-Core#1410]
I'm using the provisioning framework via the PowerShell commands and since the last version I've experienced issues with adding WebParts to the home page of a regular web part page.

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When using the PowerShell commands to generate a template and apply a template, I expect the home page to be deployed, including the web parts associated to the home page.

#### Observed Behavior
When the home page is a default (classic) web part page containing web parts, the Get-PnPProvisioningTemplate cmdlet generates a pnp file. Within the embedded manifest, the home page is added, with the correct WebParts.
When using the Apply-PnPProvisioningTemplate cmdlet, most of the provisioning works like a charm, but an error is given when adding the web parts to the home page:

> 
> powershell.exe Information: 0 : 2017-10-18 19:05:14.4827        [Files] [10]    [Debug] Uploading and overwriting existing file SitePages\Default.aspx  2656ms  5bcb3e84-193c-40e6-a98d-21c3c133b11a
> powershell.exe Information: 0 : 2017-10-18 19:05:14.7090        [OfficeDevPnP.Core]     [0]     [Information]   File Default.aspx retrieved from folder SitePages       0ms
> powershell.exe Information: 0 : 2017-10-18 19:05:14.7100        [OfficeDevPnP.Core]     [0]     [Debug] Creating file info with Url 'Default.aspx'      0ms
> powershell.exe Information: 0 : 2017-10-18 19:05:18.8577        [Files] [10]    [Debug] Adding webpart 'Web Part Page Title Bar' to page        7031ms  5bcb3e84-193c-40e6-a98d-21c3c133b11a
> powershell.exe Information: 0 : 2017-10-18 19:05:18.8867        [Files] [10]    [Debug] Code execution scope ended
> 7060ms  5bcb3e84-193c-40e6-a98d-21c3c133b11a
> powershell.exe Information: 0 : 2017-10-18 19:05:18.8867        [Provisioning]  [10]    [Debug] Code execution scope ended      129736ms        5bcb3e84-193c-40e6-a98d-21c3c133b11a
> 
> Apply-PnPProvisioningTemplate : There are multiple root elements. Line 1, position 88.
> At D:\Work\Sources\Macaw\Deployment\Modules\Macaw.SharePoint.Deployment\Sites.ps1:383 char:9
>          Apply-PnPProvisioningTemplate -Path $TemplatePath -ExcludeHan ...
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], XmlException
>      FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

#### Steps to Reproduce
I've created a new WebPart page in the default SitePages library. I've added three WebParts:

- Content editor web part
- Site members web part
- List view webpart

After configuring the page, I've made it the default home page and created a pnp file using the Get-PnPProvisioningTemplate cmdlet. This worked without any issues.

I then created a new site collection based on the default Team site template (classic). The original site collection has the same template. Then I applied the template using the Apply-PnPProvisioningTemplate cmdlet and this fails on adding the web part.

I'm using the latest version of the SharePointPnPPowerShellOnline module (2.19.1710.1) which uses the OfficeDevPnP.Core.dll with version number 2.19.1710.1

I've added my template as attachment

[Portal.zip](https://github.com/SharePoint/PnP-Sites-Core/files/1395636/Portal.zip)

**Comment by VesaJuvonen** [comment]
thx PeterHeibrink, appreciate sharing the needed details for repro with the template file. We'll have a look in upcoming days.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
