### ISSUE TITLE
Use of NoScript check in provisioning

### ISSUE THREAD

**Issue by wobba** [SharePoint/PnP-Sites-Core#1424]
#### Category
[x] Question

#### Environment
[x] Office 365 / SharePoint Online

Several places functionality in the prov code is blocked if the site collection is a NoScript site. I think it's time to revisit these places, as it's blocking functionality which is indeed supported/working.

One example is quicklaunch links. We can add them using PnP Posh or code, but it's blocked in the prov engine.

If there is consensus I think we can do some cleanup on all cases - to see which should indeed stay, and which should be removed.

**Comment by jansenbe** [comment]
Valid points; We'll be transforming the checks spread out across the handlers to a "pre-apply cleanup" step done by https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/NoScriptTemplateCleaner.cs. This way all the logic is centralized and template we'll have to run over will be smaller which will help increase performance. This work is still to be done though.

**Comment by wobba** [comment]
@jansenbe this is excellent news indeed, already thinking of something. Related to #1393, being able to add a pnp:File not which just checks in the file, without pointing to a local file would also be beneficial - as NoScript sites block upload of aspx. But progress is steady and good indeed on the modern things.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
