### ISSUE TITLE
NuGet Inconsistent reference for .NET 4.7.1

### ISSUE THREAD

**Issue by rychlym** [SharePoint/PnP-Sites-Core#1427]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Hello, 
excuse me, please  (thinking the issue is rather  related to the Microsoft.SharePointOnline.CSOM library)  reporting this issue here, but I dam not sure,  where to ask.  I just tried  to install  that library through NuGet repository, but it end up with "Inconsistent reference" at time the project was building. I suppose, it would  end up with same error tying to install the Pnp-Core lib.
So just a question - are you planning to fix it?  (Or at least, could you please forward it to the team working on the Microsoft.SharePointOnline.CSOM?)

Br,
Mojmir.

**Comment by VesaJuvonen** [comment]
Hi Mojmir, 
can you provide more details on the actual exception which you are getting and also details on your solution? What version of .NET it's using etc.

**Comment by rychlym** [comment]
Hi Juha,
Please excuse me, it could probably be a false alarm. I further found out, that I had even some troubles there with more basic things that could finally cause it this issue with CSOM - see the [link](https://github.com/dotnet/standard/issues/560) (there is mentioned also something from also my actual dev environment)
One my project didn't work, but a second one (more important) somehow got to work with the reference to that CSOM and BTW I encountered another newer version of the CSOM library today and  I would concentrate on that one.
So please could you hold a week or two and in the worst case of no reply from me, then please just simply close it.
thanks for the care,
Mojmir

**Comment by rychlym** [comment]
Hi.
The root cause for the must have been the the MSBuild didn't manage build after switching the console project to 4.7.1 having referenced some libraries targeting .net standard 2.0. After applying a workaround (adding   <PropertyGroup><_HasReferenceToSystemRuntime>true</_HasReferenceToSystemRuntime></PropertyGroup> to the project file) the troubles have gone.
