### ISSUE TITLE
AuthenticationManager Examples

### ISSUE THREAD

**Issue by knight1219** [SharePoint/PnP-Sites-Core#1428]
#### Category
[ ] Bug
[ ] Enhancement
[X] Example

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I am trying to build an Azure Function that will take a PDF file and push it into a sharepoint site. Our company manages the tenants this function will try and access. I found the **GetAzureADAccessTokenAuthenticatedContext** method which seems like it would allow my Azure Function to interact with Sharepoint without login credentials. I have looked but I can't seem to find any examples on how to really use this method (like getting the token it says it needs) Any guidance would be wonderful.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
