### ISSUE TITLE
ServerObjectIsNull() extension method returns true when object exits

### ISSUE THREAD

**Issue by rickenberg** [SharePoint/PnP-Sites-Core#1429]
Extension method ServerObjectIsNull() has some unexpected behavior. It returns true when indeed a server object exist but was not loaded.

#### Which PnP repository should you use to report the issue? 
PnP-Sites-Core/Core/OfficeDevPnP.Core/Extensions/ClientObjectExtensions.cs

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
If ClientObject.ServerObjectIsNull == null - it should return false.

#### Observed Behavior
If ClientObject.ServerObjectIsNull == null - it returns true.

#### Steps to Reproduce
In my case I am working with Terms in MMS. When getting a parent term without explicitly loading it via the Client Context object.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
