### ISSUE TITLE
Add support for WriteSecurity on ListInstance object

### ISSUE THREAD

**Issue by stevus1970** [SharePoint/PnP-Sites-Core#1431]
PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
SharePoint CSOM supports ReadSecurity and WriteSecurity but the latest Provisioning schema (http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema) only supports the ReadSecurity property on a ListInstance.  Can WriteSecurity also be included.

**Comment by biste5** [comment]
ReadSecurity and WriteSecurity are both implemented now.
This can be closed

@VesaJuvonen
