### ISSUE TITLE
Workflow Subscription Duplicated instead of Updated

### ISSUE THREAD

**Issue by RedBaaron** [SharePoint/PnP-Sites-Core#1443]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: N/A

#### Expected or Desired Behavior
If I run the PowerShell command "Get-PnPProvisioningTemplate" to extract a template and then "Apply-PnPProvisioningTemplate" to apply that template to another site, I would expect that any workflows with the same subscription ID would be "updated".   Using the older version of the PowerShell script "2.16.1706.0" this works exactly as I would expect, and I see the message in the output "Workflow Subscription '{subscription.Name}' already exists. It will be updated.".

#### Observed Behavior
Using the latest release 2.19.1710.2, I don't see the message that "...already exists. It will be updated", and when I check a new WF subscription has been added with the same name.   Each time I run the "Apply-PnPProvisionTemplate" I get another duplicate subscription.   These are simple List workflows I am testing with.

#### Steps to Reproduce
1.  Create a simple list workflow on any list.  Could have a simple log statement.
2.  Use "Get-PnPProvisioningTemplate" to extract that template.
3.  Use "Apply-PnPProvisioningTemplate" to apply that extracted template to another site.
4.  Now make an update to the workflow in the original site (change the log message), run "Get-PnPProvisioningTemplate" again, and "Apply-PnPProvisioningTemplate" again, and you will get a duplicate.

**Comment by PaoloPia** [comment]
Thanks @RedBaaron I'm fixing this issue right now.

**Comment by PaoloPia** [comment]
Fixed! Thanks again.
