### ISSUE TITLE
ClientSidePage->PromoteAsHomePage Not Updating RootFolder

### ISSUE THREAD

**Issue by dadanepal** [SharePoint/PnP-Sites-Core#1451]
ClientSidePage->PromoteAsHomePage before you call the this.Context.ExecuteQueryRetry() you have to update the root folder. context.Web.RootFolder.Update() for the changes to take effect.
I tried using the PromoteAsHomePage for about 2 hours trying to figure out what I was doing wrong before looking at the implementation.

**Comment by jansenbe** [comment]
nice catch @dadanepal, will be included in December release. Fix is commited to dev branch.

**Comment by jansenbe** [comment]
Closing the issue now, but don't hesitate to re-open if the fix is not working for you.
