### ISSUE TITLE
Issue with PageExtension.GetWebPartXml method

### ISSUE THREAD

**Issue by stevebeauge** [SharePoint/PnP-Sites-Core#1452]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4927.1000

#### Expected or Desired Behavior
Exporting a webpart as Xml should work.

#### Observed Behavior
The resulting Xml actually contains SharePoint error page html instead of the Webpart's xml.

#### Steps to Reproduce
The easiest way to reproduce the issue is to use `Get-PnPWebPartXml` command (targeting a publishing site in my case):

````
Connect-PnPOnline -CurrentCredentials http://myserver/sites/somepublishingsite
Get-PnPWebPart -ServerRelativeUrl /sites/somepublishingsite/pages/default.aspx # List webparts
Get-PnPWebPartXml ServerRelativeUrl /sites/somepublishingsite/pages/default.aspx -id <id of one webpart>
````

**Comment by jansenbe** [comment]
Closing as the proposed fix has been merged
