### ISSUE TITLE
Quick Launch Navigation duplicated

### ISSUE THREAD

**Issue by LouFarho** [SharePoint/PnP-Sites-Core#1454]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Used latest SharePoint PnP PowerShell
Name                          Version    
----                          -------    
SharePointPnPPowerShellOnline 2.20.1711.0
SharePointPnPPowerShellOnline 2.19.1710.2

#### Expected or Desired Behavior
That the quick launch navigation items not be duplicated. I have been able to repeat this behavior.

#### Observed Behavior
Quick launch items for the following were duplicated.
Home
Notebook
Documents
Recent
Site contents

#### Steps to Reproduce
Created a new classic site collection using the Team Site template
Configured the new site:
Add a composed look
Add Asset Library
Created a modern page (added news, quick links, People apps in first section, add document library in second section, add assets library in third section of page)

Generated PnP Template
Get-PnPprovisioningtemplate -Out F:\LapTop\Projects\SPOTemplates\PNPDisciplines.pnp

Connected to target site collection and applied template. Target template out of the box site collection using the Team site
Apply-PnPProvisioningTemplate F:\LapTop\Projects\SPOTemplates\PNPDisciplines.pnp

Attached screenshot of quicklaunch
![quicklaunchduplicated](https://user-images.githubusercontent.com/20116742/32868307-3481ed62-ca37-11e7-8949-ae368ab191e0.png)

Attached log file
[log_DisciplineTemplate.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1476936/log_DisciplineTemplate.txt)

Attached PnP file changed to zip for attaching
[PNPDisciplines.zip](https://github.com/SharePoint/PnP-Sites-Core/files/1476942/PNPDisciplines.zip)

**Comment by stevebeauge** [comment]
The current implementation of the PnP provisioning engine is only able to add navigation links. There's nothing to help the engine to uniquely identify an existing node (as far as I know).

In our usage of the provisioning engine, we add the `ClearNavigation` switch parameter to the `Apply-PnPProvisioningTemplate` command. This will erase any existing links on the target web:

````
Apply-PnPProvisioningTemplate -Path "c:\pnp\myPackage.pnp" -ClearNavigation
````

Of course, this may not be applicable to all cases.

**Comment by LouFarho** [comment]
Thanks Steve! 
I guess I didn't see that switch being used in the various demos I have watched. 
I just reran the commands and the navigation is as expected.

Thanks!
