### ISSUE TITLE
UsernameMixed.GetFedAuthCookie() fails if cookie-lifetime is in days (like 1.00:00:00, without hours and minutes)

### ISSUE THREAD

**Issue by BeniGemperle** [SharePoint/PnP-Sites-Core#1455]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: not relevant

#### Expected or Desired Behavior
UsernameMixed.GetFedAuthCookie() should use correct Cookie-Lifetime returned by the Saml-Token.

#### Observed Behavior
UsernameMixed.GetFedAuthCookie() has an own implementation calculating the lifetime using hours and minutes, but completely ignores days. E.g. if Lifetime is 24 hours (1.00:00:00) it will completely fail as this has 0 hours and 0 minutes.

#### Steps to Reproduce
Need to configure ADFS Cookie-Lifetime to a value like 24 hours.

#### Suggested fix:
```c#
int cookieLifeTime = Math.Min((lifeTime.Hours * 60 + lifeTime.Minutes), logonTokenCacheExpirationWindow);

```
should be changed to
```c#
int cookieLifeTime = Math.Min((int)lifeTime.TotalMinutes, logonTokenCacheExpirationWindow);
```

**Comment by jansenbe** [comment]
Closing since the proposed fix was merged
