### ISSUE TITLE
Properties from ClientSideComponentProperties doesn't get passed on to the SPFx Extension

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Sites-Core#1463]
_From @JonasBjerke89 on September 26, 2017 13:37_

### Reporting an Issue or Missing Feature
Issue with ClientSideComponentProperties (JSON property) when running installed SPFx Extensions. This is tested in a developer tenant on a modern team site connected with an Office 365 Group.

### Expected behavior 
I was expecting the -ClientSideComponentProperties to be serialized and passed into the SPFx Extensions for run-time use.

### Actual behavior 
When debugging the SPFx Extension, the "this.properties.Bottom" is undefined.
![image](https://user-images.githubusercontent.com/21952399/30863084-60189ee6-a2d0-11e7-8079-f20fdccbacc1.png)
![image](https://user-images.githubusercontent.com/21952399/30863090-654db2ac-a2d0-11e7-87b5-8584a82ac9bf.png)

### Steps to reproduce behavior
1. Follow this tutorial: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions
2. Install App Package as Tenant scoped. Resources are loaded from localhost
3. Install Extension using this command:
Add-PnPCustomAction -Name "SPFxExtensionsOne" -Title "SPFxExtensionsOne" -Location "ClientSideExtension.ApplicationCustomizer" -ClientSideComponentId "cc8333ff-1aa9-477d-aa61-a79aedc57163" -ClientSideComponentProperties "{Top : 'Top area of the page', Bottom: 'Bottom area in the page'}"

### Which version of the PnP-PowerShell Cmdlets are you using?
- [ ] PnP PowerShell for SharePoint 2013
- [ ] PnP PowerShell for SharePoint 2016
- [x] PnP PowerShell for SharePoint Online

### What is the version of the Cmdlet module you are running?
2.18.1709.1

### How did you install the PnP-PowerShell Cmdlets? 
- [ ] MSI Installed downloaded from GitHub
- [x] Installed through the PowerShell Gallery with Install-Module
- [ ] Other means

_Copied from original issue: SharePoint/PnP-PowerShell#1111_

**Comment by erwinvanhunen** [comment]
Hi! We think we found the issue in your case. The ClientSideComponentProperties JSON is pretty strict. It requires that your use double quotes in stead of single quotes. If you can confirm that it works with double quotes, please close this issue.

**Comment by JonasBjerke89** [comment]
Hi Erwin. It works, if we use double quotes like this: ```
Add-PnPCustomAction -Name "SPFxExtensionsOne" -Title "SPFxExtensionsOne" -Location "ClientSideEx
tension.ApplicationCustomizer" -ClientSideComponentId "cc8333ff-1aa9-477d-aa61-a79aedc57163" -ClientSideComponentPropert
ies "{Top : ""Top area of the page"", Bottom: ""Bottom area in the page""}"
```. I'm closing this issue!
