### ISSUE TITLE
Bug: ClientSidePage.Load  and ClientSidePage.FromHtml fails when page content contains quotes (")

### ISSUE THREAD

**Issue by artokai** [SharePoint/PnP-Sites-Core#1465]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
If a modern page contains quotation marks (") in it's content then the page *should* be parsed correctly when using either ```ClientSidePage.FromHtml()``` or ```ClientSidePage.Load()```methods. 

#### Observed Behavior
The current implementation will cause a JSON parse error to be thrown if the page contents contains quotation marks.

#### Reason for the error
The JSON parse error happens because ```ClientSidePage.FromHtml``` decodes the ```data-sp-controldata```-attribute **twice** thus breaking the JSON string.

1. First decode: ```&amp;quot;``` --> ```&quot;```
2. Second decode: ```&quot;``` --> ```"```

The attribute is first transparently decoded here:
(https://github.com/SharePoint/PnP-Sites-Core/blob/26c6450841b46c71d34b2c9622fe68e94d5843f6/Core/OfficeDevPnP.Core/Pages/ClientSidePageCanvas.cs#L1156)

And then it's decoded **a second time** inside the ```GetType```-method of ```CanvasControl```:
https://github.com/SharePoint/PnP-Sites-Core/blob/26c6450841b46c71d34b2c9622fe68e94d5843f6/Core/OfficeDevPnP.Core/Pages/ClientSidePageControls.cs#L217

#### Steps to Reproduce

You can easily reproduce this problem with the following piece of code. It will cause a JSON parse error. The page contains just a single ClientSideText-control with the following content:
```"This will break"```

```
var html = @"<div><div data-sp-canvascontrol="""" data-sp-canvasdataversion=""1.0"" data-sp-controldata=""&#123;&quot;controlType&quot;&#58;4,&quot;displayMode&quot;&#58;2,&quot;id&quot;&#58;&quot;609ccd34-3246-4d8b-95d7-95c7f5edca85&quot;,&quot;position&quot;&#58;&#123;&quot;zoneIndex&quot;&#58;1,&quot;sectionIndex&quot;&#58;1,&quot;controlIndex&quot;&#58;1&#125;,&quot;innerHTML&quot;&#58;&quot;&lt;p&gt;&amp;quot;This will break&amp;quot;&lt;/p&gt;\n&quot;,&quot;editorType&quot;&#58;&quot;CKEditor&quot;,&quot;addedFromPersistedData&quot;&#58;true&#125;""><div data-sp-rte=""""><p>&quot;This will break&quot;</p></div></div></div>";
var p = ClientSidePage.FromHtml(html);
```

**Comment by jansenbe** [comment]
Nice catch Arto. The decoding in the GetType method is not needed, so I'll remove it. Will be included in the next release

**Comment by jansenbe** [comment]
Fix submitted to dev branch, closing this now

**Comment by raymondlittle100** [comment]
Same thing applies when the title has quotes in it i.e. This is a title for an "exciting" page

**Comment by jansenbe** [comment]
Just tried to read a page having quotes in the title and that worked fine for me. Can you repro this with the last version?

![image](https://user-images.githubusercontent.com/7451219/43779343-792a11dc-9a58-11e8-9913-b2c982ce8142.png)
