### ISSUE TITLE
Create a .pnp file from a directory

### ISSUE THREAD

**Issue by jonathaneckman** [SharePoint/PnP-Sites-Core#1467]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
I would like to source control an XML provisioning engine template and all of its required assets (js, css, html, etc.) in a Visual Studio project. When the time comes to provision the site, Id like to hand off a .pnp file that was generated from my project. I know I could apply the template to a site using the .xml, then extract a new .pnp from the site, but I would like to simplify this and eliminate the site from this process.

**Comment by artokai** [comment]
The pnp-file is basically just a zip file containing the necessary xml-files and other assets. So you could quite easily add the extracted files to your Visual Studio solution, modify them by hand using VisualStudio (or any other editor) and then zip it back to a pnp-file as part of your build process.

**Comment by erwinvanhunen** [comment]
The risk there is that while it is indeed possible to manage the contents of the PnP file like that, adding new assets to it is a bit more complex. We have a cmdlet for that (Add-PnPFileToProvisioningTemplate, it had a bug, fix for it will be available in the December 2017 release) to make things easier. For an explanation of the format you can see issue #1435. 

We also have a cmdlet called New-PnPProvisioningTemplateFromFolder which might be of use.
