### ISSUE TITLE
ApplyPnPTemplate Access is Denied Vanilla Modern Communication Site

### ISSUE THREAD

**Issue by pdemro** [SharePoint/PnP-Sites-Core#1475]
####Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Apply-PnPProvisioningTemplate fails with Access Denied when reading from a template created with a vanilla Modern Communication site.  Based on spam from verbose output, **this is related to the hidden display template content type.**

Expected behavior is PnP does nothing since the sites are identical.  Per this error, no PnP template will work if it includes the content type handler.

I have attached the pnp template : [template-11-28-2017_10_35_13-vanilla.pnp.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1510652/template-11-28-2017_10_35_13-vanilla.pnp.txt)

#### Observed Behavior
```Powershell
Apply-PnPProvisioningTemplate : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

At C:\Users\pdemro\source\repos\scripts\PnPProvisioner\helpers.ps1:77 char:5
+     Apply-PnPProvisioningTemplate -Path $templatePath -Verbose -Debug
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
```

#### Steps to Reproduce
1. Create a modern team site (/_layouts/15/sharepoint.aspx, create site -> communication site -> topic)
2. Get-PnPProvisioningTemplate targeting the vanilla comm site
3. Create a Communication site using New-PnPSite -Type CommunicationSite
4. Apply-PnPProvisioningTemplate to the new comm site with the vanilla template

#### Verbose Output (truncated)
```Powershell
...
powershell.exe Information: 0 : 2017-11-28 10:54:29.1598        [Content Types] [14]    [Debug] Field f519008d-1b5b-42a8-8dab-e1a642fe5787 exists in content type       2402ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.1618        [Content Types] [14]    [Debug] Field d8225d68-5ddb-4e66-8069-2694e8f628fb exists in content type       2404ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.1638        [Content Types] [14]    [Debug] Field b4ba57c8-ab73-49fa-b6af-a4f824d84c14 exists in content type       2406ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.1658        [Content Types] [14]    [Debug] Field a569e161-e19e-4360-9ae1-20dfda097cb3 exists in content type       2408ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.1678        [Content Types] [14]    [Debug] Field 78eae64a-f5f2-49af-b416-3247b76f46a1 exists in content type       2410ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.3207        [Content Types] [14]    [Debug] Updating existing Content Type: 0x0101002039C03B61C64EC4A04F5361F3851066 - {res:ContentType_Display_Template_Title}     2563ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.6567        [Content Types] [14]    [Debug] Code execution scope ended      2899ms  6f5a62c1-c750-491d-aea3-2635d76a9d75
powershell.exe Information: 0 : 2017-11-28 10:54:29.6572        [Provisioning]  [14]    [Debug] Code execution scope ended      26613ms 6f5a62c1-c750-491d-aea3-2635d76a9d75
Confirm
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
```

**Comment by pdemro** [comment]
I've found that splitting the PnP template into two seems to work around the issue for some reason

```powershell
Get-PnPProvisioningTemplate -out <path> -ExcludeHandlers ContentTypes,Lists,Fields
Get-PnPProvisioningTemplate -out <path> -IncludeHandlers ContentTypes,Lists,Fields
```

Applying these templates separately does not seem to throw the same error.

As a note I am also using a workaround for another issue mentioned in a different thread for another Access denied issue relating to the Style Library.  This is run after creation of the modern site but before the PnP template application

```powershell
$context = Get-PnPContext 
$web = Get-PnPWeb 
$web.Lists.EnsureSiteAssetsLibrary() 
$web.Context.ExecuteQuery()
```

**Comment by jansenbe** [comment]
Hi @pdemro,

I'm looking into this and just noticed that our base template for the communication site was not included, meaning we did not filter out the OOB elements, which most likely is (part of) the reason why you get access denied

**Comment by pdemro** [comment]
@jansenbe Thank you!  Looking forward to it.

**Comment by jansenbe** [comment]
Changes are committed into the dev branch, would be good if you can play around and provide feedback before the upcoming master merge of this week Friday.

**Comment by pdemro** [comment]
This appears to be resolved

SharePointPnPPowerShellOnline 2.21.1712.2

Thank you @jansenbe I am closing this issue
