### ISSUE TITLE
ClientSidePage.AddControl clears page

### ISSUE THREAD

**Issue by LouFarho** [SharePoint/PnP-Sites-Core#1479]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name                          Version    
----                          -------    
SharePointPnPPowerShellOnline 2.20.1711.0
SharePointPnPPowerShellOnline 2.19.1710.2

#### Expected or Desired Behavior
I am calling the Add-PnPClientSideWebPart from the SharePoint PnP Powershell 
Add-PnPClientSideWebPart -Page $homePage -DefaultWebPartType People
It is to add the People web part to the default page of an Office 365 Group site

I expected based on documentation that it would add the new web part at the top of the default section

#### Observed Behavior

When I go back to review the page, all the default web parts are missing from the page and only the added web part is present.

#### Steps to Reproduce
Create a Office 365 Group/Modern Site
Connect-PnPOnline https://mytenant.sharepoint.com/sites/MyO365GroupSite
$homePage = Get-PnPClientSidePage -Identity "Home.aspx"
Add-PnPClientSideWebPart -Page $homePage -DefaultWebPartType People

**Comment by jansenbe** [comment]
When I try your steps I end up with an unconfigured people web part at the end of the page, underneath the other oob web parts. Also best to provide web part properties...note that we had an issue with some of the OOB web parts, which is fixed in the dev branch and will be released in December drop. See also https://t.co/j4azWO7qp6 for latest sig which contains a demo on adding first party web parts on a page.

**Comment by LouFarho** [comment]
Thanks for the fast response. As I was working thru the issue, I realized that the targeted site had had a template applied. I then performed those same actions on a unmodified Office 365 Group site I had just created and again I only have the single web part on the page. I tried it again on an older Office 365 site and same thing.   So, I tried yet with a third Office 365 Group site and switched to adding the BingMap web part. Again same results.


As far as the latest sig call, I did sit in on the call and will review the video to see if there is something I am doing wrong. 
I do remember how one can add the additional web part properties of web parts to a template. 

I intend to just create a new page and add the web parts and then set the new page as the default.

**Comment by jansenbe** [comment]
Can you confirm you see the same issue while using code from our Dev branch?

**Comment by LouFarho** [comment]
@jansenbe 
I may need some direction on how to do that. Is there an article I can use?

**Comment by jansenbe** [comment]
You'll have to pull down the latest from both sites core as PS and then rebuild all. Maybe better to verify this again next week once our December release is out.

**Comment by jansenbe** [comment]
Is this problem still reproducible with the latest release 2.21.1712.2?

**Comment by LouFarho** [comment]
@jansenbe 
Sorry for the slow response. Projects have been hectic with the close of the year.
I am unable to reproduce the problem with the latest release.

Thanks!
