### ISSUE TITLE
Can't create Communication site with app only access

### ISSUE THREAD

**Issue by Maksim-Ilyenia** [SharePoint/PnP-Sites-Core#1481]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Expected or Desired Behavior

 I try to create communication site with certificate app only access. I have 200 OK response and 
`{
	"d": {
		"Create": {
			"__metadata": {
				"type": "SP.Publishing.CommunicationSiteCreationResponse"
			},
			"SiteStatus": 3,
			"SiteUrl": ""
		}
	}
}

My code below:

var clientContext = new OfficeDevPnP.Core.AuthenticationManager().GetAzureADAppOnlyAuthenticatedContext(tenantId, clientId, certificate, siteUrl);
    var siteCreationProperties = new CommunicationSiteCollectionCreationInformation
    {
      Url = "https://myTenant.sharepoint.com/sites/commsite",
        Title = "Comm test site",
        SiteDesign = CommunicationSiteDesign.Topic,
        Owner = "tenantadmin@myTenant.onmicrosoft.com",
        AllowFileSharingForGuestUsers = false,
        Description = "comm site description",
        Lcid = 1033
      };
      var result = context.CreateSiteAsync(siteCreationProperties).Result;

I seems all work fine with SetAuthenticationCookies case.

With request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken); wrong response with status code 3.

It is bug?
Can I create site only with app only access token without authentication cookie?

**Comment by jansenbe** [comment]
Currently creating communication sites with an app-only token is not possible. You need a user context for creating communication sites. A solution would be to pass the user's access token into the async flow and then create a client context based on the user's access token to do the provisioning. Will close this one now, but feel free to re-open.

**Comment by Maksim-Ilyenia** [comment]
@jansenbe It will be support in future?

**Comment by jansenbe** [comment]
It's in the backlog, nothing to share on when for now

**Comment by guillaume-kizilian** [comment]
@jansenbe 
Hi. Is it possible to consult the backlog? Thx.

**Comment by rjaakke** [comment]
@jansenbe
Hi, are there any updates on this topic?

**Comment by dimitertodorov** [comment]
Hello Backlog,

Any possibility to bump this up. Makes it hard to fully automate SPO provisioning when working with Federated AD. There is no way to silently acquire user tokens for us.

Maybe one possibility would be to allow the API to accept a User Context as part of the request? e.g. pass in an User ObjectId?

Or, will this maybe be supported as part of the migration of APIs to the Graph?

**Comment by decapent** [comment]
I am facing the same issue. Any news on  this matter ?

**Comment by silmer** [comment]
I also am facing this issue. Any progress?
