### ISSUE TITLE
Webpart provisioning for newly provisioned List Instance fails

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Sites-Core#1483]
_From @shawnadrockleonard on December 4, 2017 18:10_

Upon including a webpart in the PnP:File or PnP:Page, if the List is a newly provisioned List from the collection of Instances and not an OOTB list provisioned via a Feature I receive the following standard error "The page you selected contains a list that does not exist. It may have been deleted by another user."    If i run the ApplyTemplate a 2nd time the webpart is added correctly.  This is only on the first application of the template that it fails.  I've added a post event process not an ExtensibilityHandler.   The webpart addition during a ExtensibilityHandler would also fail with the same message.   The TokenParser Web Context appears to contain the existing provisioned web context which could not find the "new" List Instance.    

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#269_

**Comment by erwinvanhunen** [comment]
_From @shawnadrockleonard on December 4, 2017 20:2_

Updating comment to focus on the schema versus the provisioning engine functionality.    Is there a portion of the schema which will request "a-new" the collection of Tokens once the object handlers have processed a specific portion of the work?

**Comment by erwinvanhunen** [comment]
There is no way currently to refresh the token cache through means of a property in the schema. This is a scenario that we didn't cover in the engine, but it's relatively simple to fix. I'm working on an update which will refresh/updated the list tokens the moment the features have been activated.

**Comment by shawnadrockleonard** [comment]
Excellent!  Let me know if you want a contribution here.  I can commit and you can evaluate.

**Comment by erwinvanhunen** [comment]
Thank you for finding it issue!. I've merged the fix through PR #1484.
