### ISSUE TITLE
ApplyProvisioningTemplate does not accept parameters within the pnp:CanvasControlProperty

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/PnP-Sites-Core#1486]
#### Category
Query - should it work?

#### Environment
[*] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior

Parameter gets translates by input

#### Observed Behavior
Tokens are not replaced within certain blocks

#### Steps to Reproduce
place a {parameter:SiteTitle} or {sitetitle} within the value block of a WebPartType="Text" type Client Side web part in the provisisioning xml template. 
e.g. 

           <pnp:CanvasControl WebPartType="Text" ControlId="65323e85-78d8-48b3-8871-0a66f46a5cf7" Column="1">
                  <pnp:CanvasControlProperties>
                    <pnp:CanvasControlProperty Key="Text" Value="&lt;h2&gt;Welcome to the {parameter:SiteTitle} group&lt;/h2&gt;&#xA;&#xA;&lt;p&gt;This is a test site for the PnP Engine.&amp;nbsp;&lt;/p&gt;&#xA;&#xA;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&#xA;" />
                  </pnp:CanvasControlProperties>
          </pnp:CanvasControl>
                
Run PnP-PowerShell Apply-PnPProvisioningTemplate with parameters: -Parameters @{SiteTitle="Demo PnP Template";}

![pnp example output-2017-12-05_17-42-32](https://user-images.githubusercontent.com/8781041/33621907-2f7b4bee-d9e4-11e7-8e40-f7cb86e996b8.jpg)

**Comment by jansenbe** [comment]
nice catch. Have added token parsing for the clientsidetext control text value. Will appear in December release (next week)
