### ISSUE TITLE
List fields are not automatically created using November 2017 release - earlier release is automatic

### ISSUE THREAD

**Issue by moontear** [SharePoint/PnP-Sites-Core#1488]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
When using Apply-PnPTemplate for a regular list (custom list) I expect all fields to be added automatically to the default content type (item). This was the default behavior in version 2.14.1704.0 (April 2017). I do not want to explicitly add all fields to the content type (more work, more chance of errors). The provisioning samples provided also do not add the fieldrefs to content types. If there is a new switch within the new schema I couldn't find any reference (like `AutoAddFieldsToContentType`).

#### Observed Behavior
Using Apply-PnPTemplate with version 2.20.1711.0 (I used the MSI version) fields are **not** added automatically to the default item content type. The item content type only has the default field "Title" (see below basic template) - this means that the New/Edit form also only displays the Title field instead of all fields.

#### Steps to Reproduce
* Use version 2.20.1711.0 (installed via MSI) auf PowerShell PnP.
* Use the attached basic template with Apply-PnPTemplate and any SP site ([Missing_Fields_InForm.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1535010/Missing_Fields_InForm.txt)).
* Observe the list `/Lists/Testlist`: The default item content type only has the title field.
* To switch back to the old version, all I'm doing is to use a clean PowerShell and load the old version via `Install-Module`. Exactly the same template XML produces all my desired behavior with the old version - automatically added fields to the default view & correct new/edit forms.  
This does not seem to be related to the schema version used, as I can keep on using 2016/05 instead of 2017/05 and I have the same behavior: Fields are not added to the default content type with the new version of PnP, are added with the old version of PnP.

**Comment by jansenbe** [comment]
This is fixed in the upcoming December release which will be released this on before December 12. Closing this issue now, but don't hesitate to re-open if you still see issues. Also feel free to test with the dev build and let us know.

**Comment by stevebeauge** [comment]
Related to https://github.com/SharePoint/PnP-Sites-Core/pull/1458 I guess
