### ISSUE TITLE
Apply-PnPProvisioningTemplate does not provision navigation on modern sites

### ISSUE THREAD

**Issue by ollij** [SharePoint/PnP-Sites-Core#1492]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
After Apply-PnPProvisioningTemplate the modern sites (Team and Communication Sites) will have same structural navigation as defined in the provisioning schema extracted from source modern site.

#### Observed Behavior
Apply-PnPProvisioningTemplate does not apply structural navigation as defined in the provisioning schema.

#### Steps to Reproduce
1. Create modern site (source) and modify navigation by adding a link, modifying existing link name and reordering the links.
2. Use Get-PnPProvisioningTemplate to extract the schema to XML file.
3. Create modern site (target)
4. Apply the template using Apply-PnPProvisioningTemplate
5. Compare navigation of target site to source site.

This behavior has been tested with two different first release tenants using both modern team sites as well as communication sites.

**Comment by nickvdheuvel** [comment]
Probably because NoScript is enabled. You need to disable NoScript to apply Navigation.

```PowerShell
# Get SharePoint context
Connect-PnPOnline -Url $webUrl -Credentials $spCredential;
$web = Get-PnPWeb;

# Disable NoScript (necessary for Navigation)
Set-PnPTenantSite -Url $webUrl -NoScriptSite:$false;

# Apply PnP template
Apply-PnPProvisioningTemplate -Web $web -Path $pathTemplate;

# Enable NoScript (back to default)
Set-PnPTenantSite -Url $webUrl -NoScriptSite:$true;
```

**Comment by ollij** [comment]
Thank you Nick. Seems to work.
