### ISSUE TITLE
PNP ClientSidePage changes aren't persisted on Classic Site - CSOM, WebJob

### ISSUE THREAD

**Issue by GavinHaak** [SharePoint/PnP-Sites-Core#1501]
Expected Behaviour

This template when applied to a site should provision a new modern page

  <pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="HomeModern.aspx" PromoteAsNewsArticle="false" Overwrite="true">
          <pnp:Sections>
            <pnp:Section Order="1" Type="TwoColumnLeft">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Custom" JsonControlData="{&quot;description&quot;:&quot;Recent Sub Sites&quot;,&quot;queryoverride&quot;:&quot;&quot;,&quot;propertiesoverride&quot;:&quot;&quot;,&quot;additionalquerytext&quot;:&quot;&quot;,&quot;rowlimit&quot;:&quot;8&quot;,&quot;matchids&quot;:true,&quot;onlysubsites&quot;:false}" ControlId="3b7ea704-1417-4618-8f1d-a3fc7dc5c148" Order="1" Column="1" />
                <pnp:CanvasControl WebPartType="Custom" JsonControlData="{&quot;description&quot;:&quot;Information Panel&quot;,&quot;profileProperty&quot;:&quot;&quot;}" ControlId="41813642-8cfd-4efa-a154-8afe4ce15cc7" Order="1" Column="2" />
              </pnp:Controls>
            </pnp:Section>
             <pnp:Section Order="2" Type="OneColumn">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Custom" JsonControlData="{&quot;contentTypeId&quot;:&quot;0x010100CEF17C0E305D7A45BB9FCABAF9C7525F&quot;,&quot;sortingOptions&quot;:&quot;&quot;,&quot;sortingType&quot;:0,&quot;templateType&quot;:0,&quot;refiners&quot;:&quot;[ {\&quot;key\&quot;: \&quot;SPContentType\&quot;, \&quot;text\&quot;: \&quot;Content Type\&quot;},  {\&quot;key\&quot;: \&quot;MBDocumentType\&quot;, \&quot;text\&quot;: \&quot;Document Type\&quot;} , {\&quot;key\&quot;: \&quot;MBCorporateAuthor\&quot;, \&quot;text\&quot;: \&quot;Corporate Author\&quot;}, {\&quot;key\&quot;: \&quot;MBLegalEvidence\&quot;, \&quot;text\&quot;: \&quot;Legal Evidence\&quot;}, {\&quot;key\&quot;: \&quot;LastModifiedTime\&quot;, \&quot;text\&quot;:\&quot;Date\&quot;}]&quot;,&quot;rowLimit&quot;:&quot;20&quot;,&quot;refinersLimit&quot;:8,&quot;newsCenterRelativeUrl&quot;:&quot;https://engagesq.sharepoint.com{site}&quot;,&quot;tagColorListUrl&quot;:&quot;&quot;,&quot;title&quot;:&quot;Document Search&quot;,&quot;imageRenditionWidth&quot;:&quot;&quot;,&quot;imageRenditionHeight&quot;:&quot;&quot;,&quot;timeOffset&quot;:&quot;10&quot;,&quot;useDefaultSorting&quot;:true,&quot;searchCenterLink&quot;:&quot;https://engagesq.sharepoint.com/sites/mbsearchcenter/Pages/results.aspx&quot;,&quot;restrictSearch&quot;:true}" ControlId="13b92221-d166-4263-8ef0-d989c6cf9b29" Order="1" Column="1" />
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>

I've verified this template works fine when using Powershell. It simply does not provision when using CSOM applytemplate (everything else works fine). No page created.

Even attempting to force create page via CSOM fails. 

    // Make this page a "modern" page
                            item["ContentTypeId"] = "0x0101009D1CB255DA76424F860D91F20E6C4118";
                            item["Title"] = "Home";
                            item["ClientSideApplicationId"] = "b6917cb1-93a0-4b97-a84d-7cf49975d4ec";
                            item["PageLayoutType"] = "Home";
                            item["PromotedState"] = "0";
                            item["CanvasContent1"] = "<div></div>";
                            item["BannerImageUrl"] = "/_layouts/15/images/sitepagethumbnail.png";

                            item.Update();
                            web.Context.Load(item);
                            web.Context.ExecuteQuery();
                            Console.WriteLine("Provisioned Page");

  Console.WriteLine("Pnp Page");
                            var page = web.LoadClientSidePage("HomeModern.aspx");
                            Console.WriteLine("Page title retrieved {0}",page.PageTitle);
                            page.AddSection(CanvasSectionTemplate.TwoColumnLeft,1);
                            page.AddSection(CanvasSectionTemplate.OneColumn, 2);
                            page.Save("HomeModern.aspx");
                            Console.WriteLine("PnP Saved");

This code creates a Modern Page (using the OLD method). When I attempt to retrieve the created page, I can get the existing page and view the Title property.

When I save the page, NOTHING happens, no error - but no changes are saved. Same behaviour as ApplyTemplate with the xml schema. Latest version of PnP via Nuget - 2.21.1712.2. 

Powershell PNP Commandlets also latest - unsure why its working via that route?

Anyone else faced this?

**Comment by jansenbe** [comment]
If you want to create a modern client side home page it's recommended to use the 2018-01 schema (in beta now) as that supports the Layout and Publish page properties. I've just used CSOM to add and set a modern client side home page to a classic STS#0 site and this worked as expected.

```CS
            using (var clientContext = TestCommon.CreateClientContext("https://bertonline.sharepoint.com/sites/espctest2"))
            {
                ProvisioningTemplateApplyingInformation ptai = new ProvisioningTemplateApplyingInformation()
                {
                    HandlersToProcess = Handlers.PageContents | Handlers.WebSettings,
                    ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
                    {
                        // Only to output progress for console UI
                        Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                    }
                };

                XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"c:\temp", "");
                ProvisioningTemplate sourceTemplate = provider.GetTemplate("PnPProvisioningDemo201801_load.xml");

                // Execute actual extraction of the tepmplate
                clientContext.Web.ApplyProvisioningTemplate(sourceTemplate);
            }
```
```Xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.22.1801.0, Culture=neutral, PublicKeyToken=null" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-6954599DEBB54A75BDC847EACFDE49DA">
    <pnp:ProvisioningTemplate ID="TEMPLATE-6954599DEBB54A75BDC847EACFDE49DA" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">
      <pnp:WebSettings NoCrawl="false" WelcomePage="SitePages/Home2.aspx" />    
      <pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="Home2.aspx" PromoteAsNewsArticle="false" Overwrite="true" Layout="Home" Publish="true" EnableComments="true">
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumn">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Text" Order="1" Column="1">
                  <pnp:CanvasControlProperties>
                    <pnp:CanvasControlProperty Key="Text" Value="Hi there" />
                  </pnp:CanvasControlProperties>
                </pnp:CanvasControl>
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

**Comment by GavinHaak** [comment]
Thanks Bert - I'll look into that.
