### ISSUE TITLE
System.IdentityModel.Tokens.Jwt fixed to 4.0 in v 2.21.1712.2

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-Sites-Core#1503]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
The dependency should be declared [4.0.5.0) see [the documentation](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) to avoid conflicts with other packages.

#### Observed Behavior
Currently the dependency is fixed to = 4.0.0, which causes issues when maintaining packages for your solution if you have things like a web application (asp.net classic, 4.6.2, OWIN) relying on OAuth via AAD.

#### Steps to Reproduce
Create a ASP.NET MVC Classic web app (4.62/4.7), reference Microsoft.Owin.Security.ActiveDirectory.Jwt@3.1.0 as if you wanted to rely on the authorization infrastructure, reference SharePointPnPCoreOnline@2.21.1712.2.

**Comment by PaoloPia** [comment]
Hi @baywet,
Thanks for your feedback. We're working to fix it.

**Comment by baywet** [comment]
Hi @PaoloPia 
Thanks for looking into that.
Update on that: I noticed version 2.22.1801 requires >= 4.0.0 && <5.0.0
That is a progress, however I can see situations where that's still an issue (anything related to .net standard/core using latest version of assemblies)

**Comment by jansenbe** [comment]
Problem is that the sites core library is not compiling with higher versions, so we're blocking the dependency to stay in the 4 range.

**Comment by baywet** [comment]
what are your plans in terms of dependencies upgrade? currently showing 27 dependencies that could be updated and 8 that have one or more major version difference.

**Comment by pieronegri** [comment]
hello has this been fixed? I am still getting the System.IdentityModel.Tokens.Jwt error.

**Comment by garrytrinder** [comment]
I'm seeing the same error using 2.24.1803, however I am using the PnP Core library in an Azure Function and the error is thrown when calling ApplyProvisioningTemplate(). I've uninstalled and reinstalled the package but still get the same error.

**Comment by garrytrinder** [comment]
Looking into this a little more, I've noticed that a different Nuget package that I am using has increased the version of System.IdentityModel.Tokens.Jwt to 4.0.2.206221351 from , I am assuming that this is the root of the issue.

**Comment by gszdev** [comment]
When do plan to use System.IdentityModel.Tokens.Jwt **5.2.1** (nuget dependency >= 5.0.0)?
Why do you still staying in the Version 4.0 range?

You already implemented it for NETSTANDARD2_0
#if NETSTANDARD2_0
using System.IdentityModel.Tokens.Jwt;
#endif

**Comment by Zhephyr54** [comment]
@VesaJuvonen 
As **gszdev** stated above the **System.IdentityModel.Tokens.Jwt (>= 4.0.0 && < 5.0.0)** dependency is quite annoying because it's conflicting with some ASP.NET Core dependencies and therefore you can't use SharePointPnPCoreOnline in an ASP.NET Core project...
