### ISSUE TITLE
Site security BreakRoleInheritance doesn't work if there are no inner elements

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/PnP-Sites-Core#1509]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I want to use site security to break inheritance for my subweb without the need to add any inner tags

#### Observed Behavior
Inheritance doesn't break when u only use:
```
      <pnp:Security BreakRoleInheritance="true" ClearSubscopes="false" CopyRoleAssignments="false">  
      </pnp:Security>
```
Without any inner elements

#### Steps to Reproduce
Using

```
      <pnp:Security BreakRoleInheritance="true" ClearSubscopes="false" CopyRoleAssignments="false">  
      </pnp:Security>
```

Doesn't break inheritance

using with inner element for site group

```
      <pnp:Security BreakRoleInheritance="true" ClearSubscopes="false" CopyRoleAssignments="false">
        <pnp:SiteGroups>
          <pnp:SiteGroup Title="{sitename} members test" Description="{sitename} Leden" AllowMembersEditMembership="true" AllowRequestToJoinLeave="false" Owner="{siteowner}"/>          
        </pnp:SiteGroups>        
      </pnp:Security>

```
Does brake inheritance

**Comment by paulpascha** [comment]
I agree the behavior you specified would be more convenient. I've just submitted a pull request with a potential fix.
