### ISSUE TITLE
"Expected hex 0x" error when importing managed metadata fields using Provisioning Template

### ISSUE THREAD

**Issue by Akhoy** [SharePoint/PnP-Sites-Core#1511]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[X] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: November 2017 CU

#### Expected or Desired Behavior
Managed metadata site fields are properly imported

#### Observed Behavior
`Error "Expected hex 0x in {0} at at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(S
tream responseStream)  at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()  at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)  at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.CreateField(Web web, XElement templateFieldElement, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml)   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	26691ms	18795007-2afc-47f0-8687-955e64e33118
PowerShell_ISE.exe Information: 0 : 2017-12-22 09:17:52.7127	[Fields]	[11]	[Debug]	Code execution scope ended	26694ms	18795007-2afc-47f0-8687-955e64e33118 PowerShell_ISE.exe Information: 0 : 2017-12-22 09:17:52.7147	[Provisioning]	[11]	[Debug]	Code execution scope ended	28385ms	18795007-2afc-47f0-8687-955e64e33118`

#### Steps to Reproduce
1. I used `Get-ProvisioningTemplate -Handler Fields` to get all site fields' XML from an O365 site. Managed Metadata columns have a placeholder `{sitecollectiontermstoreid}` for SSPId and a similar placeholder for termset Id. 
2. When importing those fields using the same XML to an on premise site using `Apply-Provisioning`, it fails with the above error since format of Id's are not proper. I tried replacing SspId with the correct values but same error occurs. Once that happens, the Manage Site Fields page in the site becomes inaccessible. Should I replace the placeholders with the proper values for every managed metadata field in the PnP template file? If there are a lot of managed metadata fields, this will be very tedious.

**Comment by pcopley** [comment]
@Akhoy What was the solution to this?

**Comment by Akhoy** [comment]
@pcopley, I had to clone the repository and debug to fix the issue. Forgot to post the solution. It was a long time ago so don't exactly remember how I fixed it.

**Comment by schneika** [comment]
Actual State is, that it is not possible to apply an PnPProvisioningTemplate from one web to another web (Tenant) due to this Managed Metadata Taxononmy specific Provisioning Bug. Any Updates or planned Fixes?
Related to
https://github.com/pnp/PnP-Sites-Core/issues/2604
