### ISSUE TITLE
PNP-Site-Core - ClientSideWebPart.HtmlPropertiesData is missing after load and then save

### ISSUE THREAD

**Issue by iLuffy** [SharePoint/PnP-Sites-Core#1513]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
The File Viewer WebPart display well when using the ClientSidePage Load and ToHtml method.

#### Observed Behavior
The File Viewer WebPart display empty after using the ClientSidePage class.

#### Steps to Reproduce
1. Create a Modern Page, and insert a FileViewer WebPart.
2. Associated a document with the FileViewer WebPart, and then save the page.
3. Using the following code to load the FileViewerWebPart, and then save it.
`var columnValue = file.ListItemAllFields[ClientSidePage.CanvasField].ToString();
ClientSidePage page = ClientSidePage.FromHtml(columnValue);
var output = page.ToHtml();
file.ListItemAllFields[ClientSidePage.CanvasField] = output;
file.ListItemAllFields.SystemUpdate();
context1.ExecuteQuery();`
4. Then refresh the page again, the FileViewerWebPart displays empty.

**Comment by jansenbe** [comment]
Good catch @iLuffy. This has been fixed in the dev branch, updated January 2018 nuget packages will be available early next week. I'm closing this issue now, but feel free to re-open if the January 2018 version is not fixing the problem
