### ISSUE TITLE
Apply-PnPProvisioningTemplate fails on a tenant without App Catalog site

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#1522]
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

#### Expected or Desired Behavior
I have a simple XML defining some custom objects to be applied as template: few custom site fields, one custom content type using these fields, one custom list using this content type.
I have a blank site, and I want to provision these custom objects in my template to my site, using Apply-PnPProvisioningTemplate 

#### Observed Behavior
Getting an error:

> Apply-PnPProvisioningTemplate : {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."}}}

#### Steps to Reproduce
My tenant doesn't have a App Catalog site collection associated yet. If I create a new App Catalog site for the tenant via Admin center, the error goes and my template is applied correctly.

Still, I don't see any reason of having an explicit dependency on the app catalog, in this case; so I think it's a bug.

Massimo

**Comment by PaoloPia** [comment]
Hi @biste5,
Can you share the template that you are applying? Moreover, just to help me figure out the issue, can you try to apply the template skipping the ALM handler?

I mean:

Apply-PnPProvisioningTemplate -Path template.xml -ExcludeHandlers ApplicationLifecycleManagement

Thanks,
Paolo

**Comment by biste5** [comment]
Ciao Paolo,

it used to happen also with an empty XML template file

```xml
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2017/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.21.1712.2, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-6F3D3B0B8888448D89F2377D3BF42904">
    <pnp:ProvisioningTemplate ID="TEMPLATE-6F3D3B0B8888448D89F2377D3BF42904" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

and also if I include _-ExcludeHandlers ApplicationLifecycleManagement_ as you suggested, I get the same error

Massimo

**Comment by PaoloPia** [comment]
Hi @biste5,
The issue should now be fixed (https://github.com/SharePoint/PnP-Sites-Core/pull/1525) and the fix should be included in the upcoming master merge with the January 2018 release.
Thanks for letting us know about the bug.

**Comment by Didichoune** [comment]
Get-PnPProvisioningTemplate : {"error":{"code":"-1,
Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the
request SP.RequestContext.current/web/tenantappcatalog/."}}}
At line:1 char:9
+ $file = Get-PnPProvisioningTemplate -Out ".\parent.xml" -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

**Comment by Didichoune** [comment]
NOT RESOLVED !!!

**Comment by Didichoune** [comment]
And please remove by default in the PnP XML Schema this below 👎 
 <pnp:Webhooks>
            <pnp:Webhook ExpiresInDays="0" />
          </pnp:Webhooks>

**Comment by Didichoune** [comment]
Because I have always this error 👎 
Apply-PnPProvisioningTemplate : The provided template is not valid!
At line:1 char:9
+ $file = Apply-PnPProvisioningTemplate -Path ".\cwrker.xml"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ApplicationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by Didichoune** [comment]
I  have to remove it for everything works well

**Comment by Didichoune** [comment]
Thanks and best regards

**Comment by Didichoune** [comment]
I love also these messages 👎 
Apply-PnPProvisioningTemplate : Invalid Web Part tag.
At line:1 char:9
+ $file = Apply-PnPProvisioningTemplate -Path ".\cwrker.xml"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by Didichoune** [comment]
Apply-PnPProvisioningTemplate : The underlying connection was closed: An unexpected error occurred on a receive.
At line:1 char:9
+ $file = Apply-PnPProvisioningTemplate -Path ".\cwrker.xml"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by Didichoune** [comment]
Apply-PnPProvisioningTemplate : Cannot recognize the XML namespace of this Web Part.
At line:1 char:9
+ $file = Apply-PnPProvisioningTemplate -Path ".\cwrker.xml"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by Didichoune** [comment]
I would like to know what namespace is correct to write. I don't have any ?????

**Comment by fperre** [comment]
@PaoloPia: I still have the same issue using the February 2018 release. Is there something I'm missing?
Thank you for your support!

**Comment by PaoloPia** [comment]
We're double-checking the issue again. @Didichoune about the webhooks issue, please open another issue to not loose control of it. Thanks.

**Comment by PaoloPia** [comment]
Fixed by #1595

**Comment by ymihir** [comment]
I am getting similar issue while adding app to app catalog. Any leads?

**Comment by nicholas-morris** [comment]
HI,
I am getting this error while attempting to deploy the new sp-starter-kit.
Any reason why this might be?

Apply-PnPProvisioningTemplate : {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown."}}}
At C:\Users\Nick.Morris\Desktop\sp-starter-kit-master\sp-starter-kit-master\provisioning\deploy.ps1:95 char:5
+     Apply-PnPProvisioningTemplate -Path "$PSScriptRoot\solution.xml"  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by nicholas-morris** [comment]
@Tstiebug  have you checked prerequisites like tenant in targeted release? and that you have created an app catalogue and allowed 24hours after creating before provisioning the solution.
Better off posting in the issues page below.
https://github.com/SharePoint/sp-starter-kit/issues

**Comment by tstiebig** [comment]
@nicholas-morris : How could you solve this issue. In your post above you described the same Problem.
Yes, I have done all the steps for the prerequisites:

- Setting up my tenant for target release and waiting 24 hours
- Created the app catalog and uploaded the app package
- I am Tenant Global Administrator
- Add used tenant administrator account as Term Store Administrator in the Taxonomy Term Store
- Created the Custom Property in the User Profile Service
- Requested a custom API key to Alpha Vantage

Thorsten
