### ISSUE TITLE
GetAllUniqueRoleAssignments for just single user on a given web

### ISSUE THREAD

**Issue by RamyaNeela** [SharePoint/PnP-Sites-Core#1524]
#### Category
[ ] Bug
[*] Enhancement

#### Environment
[* ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I had seen the method "GetAllUniqueRoleAssignments" in OfficeDevPnP dll which is very useful to get all the role assignments of a web. 
My requirement is to get role assignments of a particualr user on a given web and its descendents. So i thought of using this method. when i tried executing it, it is taking lot of time because my web is very bigger with many childs.
So i tried for a method which will take Principal (i.e.,user or group) and web as arguments and returns only corresponding user or group web role assignments which will take less time than the earlier one, but i couldn't find this method in the package. I think it will be a very useful method.

Thanks in advance.

**Comment by wobba** [comment]
Fixed with #1687
