### ISSUE TITLE
Apply-PnPProvisioningTemplate - The provided template is not valid - CommunicationSite

### ISSUE THREAD

**Issue by shivask** [SharePoint/PnP-Sites-Core#1550]
[LandingSite.zip](https://github.com/SharePoint/PnP-Sites-Core/files/1663922/LandingSite.zip)
#### Which PnP repository should you use to report the issue? 
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[X] Bug

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
To be able to apply template on a newly created site collection based on an existing communication site.

#### Observed Behavior
I am unable to apply communication site template that I generated using Get-PnPProvisioningTemplate  on an existing O365 communication site. I get "**Apply-PnPProvisioningTemplate : The provided template is not valid!**" message always.
Attached is the template I am trying to apply.

#### Steps to Reproduce
1. Create a communication site collection
2. Try to apply attached template using "Apply-PnPProvisioningTemplate"

**Comment by jansenbe** [comment]
Think you've an XML error in the file, your missing the <pnp:ClientSidePages> node:

![image](https://user-images.githubusercontent.com/7451219/35451648-3f51f2e4-02c4-11e8-8f40-f18c5ef6efb2.png)
