### ISSUE TITLE
loading webparts from page, Potential Null Reference exception in ClientSidePageControls 

### ISSUE THREAD

**Issue by mdissel** [SharePoint/PnP-Sites-Core#1555]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
No null reference exception should occur when a Text webpart is empty.

#### Observed Behavior
Null reference exception on this line
https://github.com/SharePoint/PnP-Sites-Core/blob/9b271a892a4a204b2c87bd6f219d1385a4fde78f/Core/OfficeDevPnP.Core/Pages/ClientSidePageControls.cs#L496

#### Steps to Reproduce
Create new page
Add empty text webpart
Load webparts via ClientSidePage.Load(..)

**Comment by jansenbe** [comment]
Thanks for reporting this Marco. Will have a look

**Comment by jansenbe** [comment]
Reproed and fixed in dev branch. Closing the issue now, this will be part of the upcoming Feb 2018 release
