### ISSUE TITLE
Not able to create Communication Site using PowerShell 

### ISSUE THREAD

**Issue by JaiPrakashCox** [SharePoint/PnP-Sites-Core#1569]
I am trying below powershell to create Communication site but getting error
Connect-PnPOnline "https://domain-admin.sharepoint.com" -Credentials $credential

# Create the new "modern" communication site
$communicationSiteUrl = New-PnPSite -Type CommunicationSite -Title "TestCommunicationSite" -Url "https://domain-admin.sharepoint.com/sites/MyModernCommSite" -Description "description" -Classification "classification" -SiteDesign Showcase

# Connect to the modern site using PnP PowerShell SP cmdlets
# Since we are connecting now to SP side, credentials will be asked
Connect-PnPOnline $communicationSiteUrl

# Now we have access on the SharePoint site for any operations
$context = Get-PnPContext
$web = Get-PnPWeb
$context.Load($web, $web.Title)
Execute-PnPQuery
$web.Title

Error:
New-PnPSite : {"d":{"Create":{"__metadata":{"type":"SP.Publishing.CommunicationSiteCreationResponse"},"SiteStatus":0,"SiteUrl":""}}}
At D:\SPOPowerShellScripts\CreateCommunicationSiteSPO.ps1:7 char:25
+ ... onSiteUrl = New-PnPSite -Type CommunicationSite -Title "TestCommunica ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-PnPSite], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.NewSite

**Comment by gautamdsheth** [comment]
Change the url to `https://domain.sharepoint.com/sites/MyModernCommSite`.

The PS should be as below:
`Connect-PnPOnline "https://domain-admin.sharepoint.com" -Credentials $credential`

and then 

`$communicationSiteUrl = New-PnPSite -Type CommunicationSite -Title "TestCommunicationSite" -Url "https://domain.sharepoint.com/sites/MyModernCommSite" -Description "description" -Classification "classification" -SiteDesign Showcase`

**Comment by JaiPrakashCox** [comment]
thanks it worked, I dint notice that I am passing tenant URL

**Comment by VesaJuvonen** [comment]
Thanks for following up and confirming.

**Comment by NavaneethaDev** [comment]
Can i create a new **sub site** as a communication site?

**Comment by JaiPrakashCox** [comment]
not, its not supported yet

**Comment by seaSide974** [comment]
Hi is it supported now ?
