### ISSUE TITLE
BannerImageUrl property in Modern Pages  is not provisioned

### ISSUE THREAD

**Issue by marki27** [SharePoint/PnP-Sites-Core#1579]
#### Category
[x] Bug
[x] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Properties BannerImabeUrl and BannerImageOffset are not processed on export and on import.

**Comment by jansenbe** [comment]
Adding support for BannerImage handling is on our todo list

**Comment by lelgouacem** [comment]
Hello. Can you please provide an update on this? It is still showing up as Open. We have a client requesting the banner image as part of the PNP script. It is not carrying over for their modern site.

**Comment by jansenbe** [comment]
This was implemented in May release as part of the page header support we introduced

**Comment by lelgouacem** [comment]
Thanks - can you point us to where the release notes are?

**Comment by jansenbe** [comment]
https://dev.office.com/blogs/pnp-may-2018-update

**Comment by lelgouacem** [comment]
We have opened a new ticket here: https://github.com/SharePoint/PnP-Sites-Core/issues/1836
