### ISSUE TITLE
Apply_PnPProvisioningTemplate Fails on ListInstance Title="Tasks" - cannot find RedirectToEditForm.aspx

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#1600]
#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 2.23.1802.0

#### Expected or Desired Behavior
        <pnp:ListInstance Title="Tasks" Description="Task list for workflow." DocumentTemplate="" TemplateType="107" Url="Lists/Tasks" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-a83e-497e-9ba0-7a5c597d0107" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Lists/Tasks/RedirectToEditForm.aspx" DefaultEditFormUrl="{site}/Lists/Tasks/EditForm.aspx" DefaultNewFormUrl="{site}/Lists/Tasks/NewForm.aspx" ImageUrl="/_layouts/15/images/ittask.png?rev=44" IsApplicationList="false" ValidationFormula="" ValidationMessage="">

Should Work

#### Observed Behavior
Fails :- Creating list Tasks failed: Unable to find an SPForm matching URL /sites/<mysite>/Lists/Tasks/RedirectToEditForm.aspx.

#### Steps to Reproduce
Created Template includes Tasks List using Get-PnPProvisioningTemplate
Apply_PnPProvisioningTemplate -> fails

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
@NPrice99 Can you please provide a full template for testing?

**Comment by NPrice99** [comment]
@wobba Which bits do you want ? Its quite a big template ?

**Comment by NPrice99** [comment]
@Wobba - The actual template is 5000 lines long.  I have cut it down to a more manageable length - let me know if you need more ?
[Tasks.txt](https://github.com/SharePoint/PnP-Sites-Core/files/1752015/Tasks.txt)

**Comment by wobba** [comment]
I'll let you know once I've tested it.

fre. 23. feb. 2018 kl. 15:41 skrev Nigel Price <notifications@github.com>:

**Comment by NPrice99** [comment]
powershell.exe Information: 0 : 2018-02-23 16:23:21.0403        [List instances]        [9]     [Debug] Updating list Ta
sks failed: Unable to find an SPForm matching URL /sites/Jigsaw/Lists/Tasks/RedirectToEditForm.aspx.
Parameter name: path :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext,
 Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.UpdateList(Web web, List existingList,
ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)      83339ms f427215c-32f7-480e-a1e5-9b5894ba5d96
powershell.exe Information: 0 : 2018-02-23 16:23:21.0453        [List instances]        [9]     [Debug] Code execution scope ended      83343ms f427215c-32f7-480e-a1e5-9b5894ba5d96
powershell.exe Information: 0 : 2018-02-23 16:23:21.0463        [Provisioning]  [9]     [Debug] Code execution scope ended      122600ms        f427215c-32f7-480e-a1e5-9b5894ba5d96
Apply-PnPProvisioningTemplate : Unable to find an SPForm matching URL
/sites/Jigsaw/Lists/Tasks/RedirectToEditForm.aspx.
Parameter name: path
At C:\Users\price\OneDrive\Documents\PowerShell Scripts\SharePointOnline\Tenant
Migration\Modules\MyModules\Modules\My.PowerShell.PnPTemplates\Nigel.PowerShell.PnPTemplates.psm1:1146 char:29
+ ...             Apply-PnPProvisioningTemplate -Web $web -Path $templateFi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by wobba** [comment]
Thank you. Might be over the weekend and I can work with that template. For future reference, including a minimal template for repro makes it easier for the tester :)

**Comment by wobba** [comment]
@NPrice99 Where does `RedirectToEditForm.aspx` come from? I can't seem to find a reference to this being an OOB form. I'm checking in my SPO tenant. If I add a Tasks list to the site, this form is not there.

If you point to a form, you need to ensure it's also there in the views definition. Seems the easy approach is to replace `RedirectToEditForm.aspx` with `EditForm.aspx` in your template and it should work.

**Comment by NPrice99** [comment]
@Wobba This is an OOTB list called Tasks (Description - Task list for Workflow) .  I have not added or deleted anything from it.  I have no control over it.  I have enclosed a screenshot of the List Settings.
![workflow](https://user-images.githubusercontent.com/8484048/36669143-cb9db398-1aeb-11e8-8f8d-9981a84df09b.jpg)

**Comment by wobba** [comment]
@NPrice99 So to repo I create a 2013 workflow on the site which logs to a task list? Hard to troubleshoot without repro steps :)

**Comment by NPrice99** [comment]
@wobba  I can understand your problem - The problem I have is that I have done nothing to this site just run Get-PnPProvisioningTemplate . I don't know what has triggered {site}/Lists/Tasks/RedirectToEditForm.aspx. being used rather than the usual "{site}/Lists/Tasks/EditForm.aspx" in the <pnp:ListInstance line  It turns out that SharePoint Designer was used to create a workflow.  I wonder if that is the problem.

**Comment by wobba** [comment]
@NPrice99 Can you check if the RedirectToEditForm is hidden?

**Comment by NPrice99** [comment]
@wobba - How do I do that ?

**Comment by wobba** [comment]
@NPrice99 You could use `Get-PnPView` and see if it lists the view using RedirectToEditForm.aspx on the site where you know that view works.

**Comment by NPrice99** [comment]
Hi @wobba RedirectToEditForm  is not used in a View, but is on the actual ListInstance line - see initial post.  I have checked the rest of the generated XML and RedirectToEditForm does not appear anywhere else.  Here is the output from Get-PnPView  -
cmdlet Get-PnPView at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
List: Tasks

Title                          Id                                     Default Personal
-----                          --                                     ------- --------
All Tasks                      f7220450-aa18-455f-90c0-216500109a16   True    False
My Tasks                       2656b796-ce2f-48f9-9ab5-a13022f77bc4   False   False
AdminOnly                      39784f43-04c3-41d1-83cd-02080d19d84c   False   False

**Comment by wobba** [comment]
@NPrice99 Are you fine with changing your template to point to the other form, or should I invest more time into trying to repro this? As it seems to be an edge case easily fixed manually :)

**Comment by NPrice99** [comment]
I am using PowerShell to generate the template so I should be able to replace RedirecttoEditForm.aspx with the usual editform.aspx   I am just surprised no one else has come across this problem.  I would of thought other people would have hit this problem.  But hey ho we all have the day job - so we cannot spend all day on this.  So lets park it for the mean time and see if anyone else hits the problem.  Thanks for your efforts.  Much Appreciated.

**Comment by wobba** [comment]
We've conversed enough to be reminded if it comes up again :)

**Comment by SBajonczak** [comment]
Hey I gotta the same problem, but I use the c# implementation of it. 

Here is my Template:

```
<pnp:Provisioning
  xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Author="John Black" Version="1.0" Generator="Human being :-)">
    <pnp:Parameters>
      <pnp:Parameter Key="Title" Required="true">Test Provisionierung</pnp:Parameter>
      <pnp:Parameter Key="Description"></pnp:Parameter>
      <pnp:Parameter Key="PageLayoutContentTypeName">Seitenlayout</pnp:Parameter>
      <pnp:Parameter Key="PagesLibName">Seiten</pnp:Parameter>
    </pnp:Parameters>
  </pnp:Preferences>
  <pnp:Templates ID="SAMPLE-TEMPLATES">
    <pnp:ProvisioningTemplate ID="SPECIALTEAM" 
    Version="1.0" BaseSiteTemplate="STS#0" DisplayName="TestTemplate" Scope="RootSite" TemplateCultureInfo="1040">
      <pnp:SitePolicy>HBI</pnp:SitePolicy>
      <pnp:WebSettings RequestAccessEmail="nobody@company.de" NoCrawl="false" Title="{parameter:Title}" Description="{parameter:Description}"/>
      <pnp:ContentTypes>
 
      </pnp:ContentTypes>
      <pnp:Lists>
        <pnp:ListInstance Title="Inbox" Description="Inbox" ContentTypesEnabled="true" " DefaultNewFormUrl="{site}/lists/inbox/Forms/CustomNewForm.aspx" ListExperience="ClassicExperience" DocumentTemplate="" OnQuickLaunch="true" 
        TemplateType="101" Url="Lists/inbox"
         EnableVersioning="true" RemoveExistingContentTypes="true">
          
        </pnp:ListInstance>
      <pnp:Features>
        <pnp:SiteFeatures>
          <!-- Liste ist unter http://www.spsdemo.com/lists/features/all%20sharepoint%20features.aspx einsehbar -->
          <pnp:Feature ID="f6924d36-2fa8-4f0b-b16d-06b7250180fa" Description="SharePoint Server Publishing Infrastructure" />
          <pnp:Feature ID="b50e3104-6812-424f-a011-cc90e6327318" Description="Document ID Service (DocID) site collection feature" />
          <pnp:Feature ID="9c0834e1-ba47-4d49-812b-7d4fb6fea211" Description="Search Server Web Parts and Templates (SearchMaster) site collection feature" />
          <pnp:Feature ID="0af5989a-3aea-4519-8ab0-85d91abe39ff" Deactivate="true" Description="Workflows (Workflows) site collection feature" />
        </pnp:SiteFeatures>
        <pnp:WebFeatures>
          <pnp:Feature ID="94c94ca6-b32f-4da9-a9e3-1f3d343d7ecb" Deactivate="false" Description="SharePoint Server Publishing" />
          <pnp:Feature ID="7201d6a4-a5d3-49a1-8c19-19c4bac6e668" Deactivate="false" Description="Metadata Navigation and Filtering (MetaDataNav) site feature" />
          <pnp:Feature ID="4aec7207-0d02-4f4f-aa07-b370199cd0c7" Deactivate="true" Description="Getting Started (GettingStarted) site feature" />
        </pnp:WebFeatures>
      </pnp:Features>
      <pnp:Files>

        <pnp:File Src="Pages\CustomNewForm.aspx" Folder="{site}/lists/inbox/Forms" Overwrite="true" Level="Published">
        </pnp:File>
        <pnp:Directory Src="Content" Folder="SiteAssets" Overwrite="true" Recursive="true" IncludedExtensions="*.png" ExcludedExtensions="*.xml,*.json" />
      </pnp:Files>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

With this template I got the following error:


> Es wurde kein 'SPForm' gefunden, das mit der URL '/sites/0001/lists/inbox/Forms/CustomNewForm.aspx' übereinstimmt.\r\nParameter name: path

This is the same error message that was initially thrown. Mybe I do s.th. wrong in the file definition?

**Comment by wobba** [comment]
@SBajonczak might be a catch 22. You cannot upload the custom form before the list is there, and the list fails due to the form not being present. Can you split into two/three templates. One which creates the list, then one which uploads the form and sets it.

Sounds tricky to make this work in the engine itself, as it would have to process a File upload in the middle of the list creation/config.

**Comment by SBajonczak** [comment]
Hi, 
thx for the advice, but that didn't worked :(

What did I do:

1. Run the Template only with the list creation
2. Run the Template with upload the custom form Only 
3. Runt the Temtpate with the list createion and the DefaultNewFormUrl set

That produced the same error. 

When I removed in step three the attribute for the new Form url, it don't throw me an error. 

Also I figured out the the files will be uploaded as last step in the provisioning procedure.

Maybe I missing something?

**Comment by wobba** [comment]
I'll see if there is a good solution for this.

**Comment by rsavioli** [comment]
Any solution?

**Comment by geynen** [comment]
Is there any solution?

**Comment by wobba** [comment]
It has not been prioritized yet. Anyone can have a go at it :)

**Comment by wobba** [comment]
The workaround is to create the list, and upload the form, then change the form Url for the list. Requires two templates. Or look at the new sequence part of the schema which allows multiple templates in one. The issue is still open.
