### ISSUE TITLE
Extractng a Person field value from a list gives Microsoft.SharePoint.Client.FieldUserValue rather than the Person themselves.

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#1603]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
                           foreach($fieldValue in $listItem.FieldValues.GetEnumerator())
                           {
                                  $fieldName = $fieldValue.Key 
                                    if ($fieldName -ne "" -and $fieldName -ne $null)
                                    {                                        

                                        $dataXml += "<pnp:DataValue FieldName=""$fieldName"" >" 
                                        $dataXml += $fieldValue.Value
                                        $dataXml += "</pnp:DataValue>"
                                
                                    }
                                }
If field is such as Approver person then I would expect $dataXml to include a person.
#### Observed Behavior

$dataXml is actually Microsoft.SharePoint.Client.FieldUserValue

#### Steps to Reproduce
run above PowerShell segment against a list which has a person field.

Sharing is caring.

**Comment by NPrice99** [comment]
This is a dump of the list Item -

Values Displayed on the Form

Payee Name						Nigel

Reason for Payment / Cheque		initial payment

Cheque Value					£99.99

Job Number / Cost Centre		123456

Division						Design

Approver						Fred Bloggs

Cheque approval workflow		Pending Manager Approval

These are the Field Values (both $fieldValue.Value and $ListItem[$fieldname])
FieldName =  Title FieldValue =  Nigel ListItem[fieldName] =  Nigel
FieldName =  Reason_x0020_for_x0020_Cheque FieldValue =  initial payment ListItem[fieldName] =  initial payment
FieldName =  Job_x0020_number FieldValue =  123456 ListItem[fieldName] =  123456
FieldName =  Division FieldValue =  Design ListItem[fieldName] =  Design
FieldName =  Cheque_x0020_Value FieldValue =  99.99 ListItem[fieldName] =  99.99
FieldName =  Approver FieldValue =  Microsoft.SharePoint.Client.FieldUserValue ListItem[fieldName] =  Microsoft.SharePoint.Client.FieldUserValue
FieldName =  Cheque_x0020_approval_x0020_work FieldValue =  Microsoft.SharePoint.Client.FieldUrlValue ListItem[fieldName
] =  Microsoft.SharePoint.Client.FieldUrlValue


So why are users (eg Approver) Not a Name but a Microsoft.SharePoint.Client.FieldUserValue

and why are urls (eg Cheque_Approval_Workflow ) not a url but a Microsoft.SharePoint.Client.FieldUrlValue

**Comment by erwinvanhunen** [comment]
Can you explain what you mean with 'Person'? What do you expect to be returned? SharePoint stores user info in a FieldUserValue object. There is no such thing as a 'Person' in SharePoint behind the scenes, sure, in the User Interface it might be rendered as a Person, but internally it's all UserFieldValues.

Have a look at https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.fielduservalue_properties.aspx to see what the possible properties of that value are.

**Comment by NPrice99** [comment]
Hi Erwin

I meant FieldUserValue – I need to get the value of this field either the username or the email address.

How can I check if the current field is a FieldUSerVAlue ?

Regards

Nigel

**Comment by erwinvanhunen** [comment]
Based up on the data in the field you can find more details about that user in the SiteUserInfoList. That is a list containing all users with access to the site. The SiteUserInfoList can be retrieved from the Web property. The Id property of the FieldUserValue points to the item id of the user in the list. If you use PnP PowerShell you can simply do 

```powershell
$value = <your fielduservalue>
$user = Get-PnPUser -Identity $value.Id
$email = $user.Email
$username = $user.LoginName
$fullname = $user.Title
```

**Comment by NPrice99** [comment]
Thanks Erwin – that works a treat.

I will close the issue

Regards

Nigel

**Comment by KamranMasroor** [comment]
@erwinvanhunen:
$value = <your fielduservalue>
$user = Get-PnPUser -Identity $value.Id

**$value.Id** its not returning any value back instead of displaying "Approver" details its listing out all users ($user = Get-PnPUser -Identity $value.Id)

I believe functionality is breaking in SharePointPnPPowerShell2013.

Below is the code snippet:
function RetrieveListItems(){  
$listItems = Get-PnPListItem -List "Test Tasks" -Id 1 -Fields "Title","Assigned_x0020_to" 
foreach($listItem in $listItems){
	Write-Host "Subject : " $listItem["Title"]
	$value = $listItem["Assigned_x0020_to"]
	$user = Get-PnPUser -Identity $value.Id
	$email = $user.Email
	$username = $user.LoginName
	$fullname = $user.Title
	Write-Host "Email : " $email
	Write-Host "User Name : " $username
	Write-Host "Full Name : " $fullname
        Write-Host "------------------------------------"  
}
}  
RetrieveListItems
