### ISSUE TITLE
Error getting a site template - Field or property "NoCrawl" does not exist.

### ISSUE THREAD

**Issue by benjamingournay2** [SharePoint/PnP-Sites-Core#1606]
#### Category
[ X ] Bug

#### Environment
[ X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
October 2017
15.0.4971.1002
15.0.4569.1506

#### Expected or Desired Behavior
With powershell, I am using the following command to generate a xml template from a site:
 Get-PnPProvisioningTemplate 
but i get the following error:

_Get-PnPProvisioningTemplate : Field or property "NoCrawl" does not exist.
At F:\Scripts\HUGCHUV\ApplyTemplate.ps1:36 char:5
+     Get-PnPProvisioningTemplate -Out "F:\Scripts\HUGCHUV\22022018\Cur ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate_

THe following versions of PnPPowerShell are installed:

Name                          Version    
----                          -------    
SharePointPnPPowerShell2013   2.23.1802.0
SharePointPnPPowerShellOnline 2.23.1802.0

#### Observed Behavior
I expect a xml template file to be generated

**Comment by jansenbe** [comment]
The NoCrawl property should at least exist in all 2013 CSOM versions as of version 15.0.4801.1000. Can you cross check in your Microsoft.SharePoint.Client.dll to see if the List object has a NoCrawl property?

Also cross check you're not loading a CSOM version from an old installed SharePoint Online redist

**Comment by nddipiazza** [comment]
this is because CSOM doesn't actually allow you to return that property, even though it is part of the object on the c# side.

**Comment by nddipiazza** [comment]
https://social.technet.microsoft.com/Forums/office/en-US/ecc93123-14b1-48de-aba7-81b29aeaaca5/unable-to-load-nocrawl-property-of-a-web-using-csom-api?forum=sharepointgeneral

**Comment by jansenbe** [comment]
Closing this issue...feel free to re-open if you still feel this is blocking you.
