### ISSUE TITLE
Can I Create a GeoLocation Field using Add-PnPFieldAsXml

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#1616]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I expect to be able to create a GeoLocation Field using Add-PnPFieldasXml having got a Key from Bing and set it up in the Property Bag - Set-PnPPropertyBagValue -Key
“BING_MAPS_KEY” -Value “<My Bing Key>” -Web $web
#### Observed Behavior
PS C:\documents\PowerShell Scripts\SharePointOnline\Tenant Migration> $FieldXml = “<Field Type='Geolocation' DisplayName='Geolocation' Name='geolocation' />”

PS C:documents\PowerShell Scripts\SharePointOnline\Tenant Migration> Add-PnPFieldFromXml -FieldXml  $FieldXml -List $list
Add-PnPFieldFromXml : Object reference not set to an instance of an object.
At line:1 char:1
+ Add-PnPFieldFromXml -FieldXml $FieldXml -List $list
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPFieldFromXml], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Fields.AddFieldFromXml

PS C:\documents\PowerShell Scripts\SharePointOnline\Tenant Migration> $error[0].Exception.ToString(
)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.SharePoint.Client.FieldAndContentTypeExtensions.CreateField(Web web, String fieldAsXml, Boolean executeQuery)
   at SharePointPnP.PowerShell.Commands.Fields.AddFieldFromXml.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
PS C:\documents\PowerShell Scripts\SharePointOnline\Tenant Migration> $error[0].Exception.InnerExce
ption.ToString()
#### Steps to Reproduce
Run the following PowerShell Script
`$FieldXml = “<Field Type='Geolocation' DisplayName='Geolocation' Name='geolocation' />”`

Add-PnPFieldFromXml -FieldXml $FieldXml -List $list    (I also tried without the List parameter)

Sharing is caring.

**Comment by andikrueger** [comment]
Without having tested it myself: Did you pass an valid xml into the function? In your example you are using an empty string - this would correlate with the null ref you are seeing. 
Could you try something like this:

`$FieldXml = "<Field Type='Geolocation' DisplayName='Geolocation Column Name' />"`

**Comment by NPrice99** [comment]
@andikrueger Thanks for answering so quickly, Sorry the Markup Gremlins decided to attack my post.  Now Corrected.

**Comment by erwinvanhunen** [comment]
The name property is a required property in the XML, E.g.

$fieldXml = "<Field Type='Geolocation' Display="GeolocationColumnName' Name='Location' />"

**Comment by NPrice99** [comment]
Hi Erwin - I have the Name property in my Xml.
`$FieldXml = “<Field Type='Geolocation' DisplayName='Geolocation' Name='geolocation' />”`

**Comment by erwinvanhunen** [comment]
Are you still having the issue? As I am using snipped below am able to create the field :

```powershell
$xml = "<Field Type='Geolocation' DisplayName='Location' Name='Location' />"
Add-PnPFieldFromXml -List MyList -FieldXml $xml
```

**Comment by erwinvanhunen** [comment]
are you 100% sure that the list exists? As the error message you receive seems to indicate that the list does not exist.

**Comment by NPrice99** [comment]
Yes - your PowerShell Snippet has just worked.

**Comment by NPrice99** [comment]
@erwinvanhunen Thanks for your help
