### ISSUE TITLE
Deadlocks everywhere in PnP Core!!

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/PnP-Sites-Core#1617]
#### Category
[X] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
PnP Core methods should work no matter if they are called from an MVC or Console or whatever application...

#### Observed Behavior
Many of the newer methods in PnP Core library do not work when using them from an application that has an UI Thread. So putting it the other way, it only works from a console application and that includes the unit tests....
Newer methods in PnP Core that use the Rest API (/_api/XXX) instead of csom are using PnPHttpProvider or a different HttpClient and make async requests using await httpClient.SendAsync(...
But higher up the stack, those are often beeing called within a Task.Run(() => ....
This can lead to deadlocks when using PnP Core with applications that have an UI thread.
You can read more about this here for example: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

#### Steps to Reproduce
Call the new AvailbleClientSideComponents() method from an MVC Application for example. Try to make multiple Calls and test it within a sync and also an async MVC Action. You will see that some requests will never bring there response back and end up in a deadlock.

```
            var page = new ClientSidePage(ctx);
            var components = page.AvailableClientSideComponents();
```

#### Possible Fix

Use httpClient.SendAsync().ConfigureAwait(false) or use async all the way up the stack and let us call the async methods directly!

**Comment by seriewe** [comment]
Same Issue https://github.com/SharePoint/PnP-Sites-Core/issues/1537

**Comment by jansenbe** [comment]
@OliverZeiser , @seriewe , @biste5 : I've updated the dev version to (hopefully) handle these deadlocks via https://github.com/SharePoint/PnP-Sites-Core/commit/5dc3e51ebb66c4c55f6f059a2dae0de03a9891ed. This is based on the work described in https://blogs.msdn.microsoft.com/benwilli/2017/02/09/an-alternative-to-configureawaitfalse-everywhere. Combined with that I've added some additional Async method versions as well.

Please give the dev branch version a try and see if fixes the issue in your applications. Thanks for testing.

**Comment by OliverZeiser** [comment]
@jansenbe It seems to work, but there is one major issue now. I think you forgot to add the `await new SynchronizationContextRemover();`

**Comment by asumner** [comment]
It appears as though this issue was resolved, why is it still open? @jansenbe

**Comment by jansenbe** [comment]
Closing as this is resolved
