### ISSUE TITLE
Setting a url field with no value causes error Object Not Ste to an Instance of an Object

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#1630]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
If I set a Url to null so -               <pnp:DataValue FieldName="BannerUrl" ></pnp:DataValue>  I expect to put a Null url in the field.
#### Observed Behavior
If I set a Url to null so -               <pnp:DataValue FieldName="BannerUrl" ></pnp:DataValue>  I get a failure Object Not Set to an Instance of an Object

If I set a url so - If I set a Url to null so -               <pnp:DataValue FieldName="BannerUrl" >""</pnp:DataValue>  I get a failure  -  Creating listitem failed: Invalid URL: "". :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)

If I set a Url field  to Null so - <pnp:DataValue FieldName="BannerUrl" >Null</pnp:DataValue>
I get an failure  -  Creating listitem failed: Invalid URL: Null. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)

  Creating listitem failed: Invalid URL: "". :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)

#### Steps to Reproduce
Use this Template fragment - 
```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.23.1802.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-F8BEC8CB1F544566AD5CF8EC5BF9BEF3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-F8BEC8CB1F544566AD5CF8EC5BF9BEF3" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
      <pnp:WebSettings RequestAccessEmail="someone@example.com" NoCrawl="false" WelcomePage="SitePages/Home.aspx" SiteLogo="{site}/SiteAssets/cards tile.jpg" AlternateCSS="" MasterPageUrl="{masterpagecatalog}/seattle.master" CustomMasterPageUrl="{masterpagecatalog}/seattle.master" />
      <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="Gregorian" Collation="25" FirstDayOfWeek="Monday" FirstWeekOfYear="2" LocaleId="2057" ShowWeeks="false" Time24="true" TimeZone="2" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />
      <pnp:Lists>
        <pnp:ListInstance Title="Events" Description="" DocumentTemplate="" TemplateType="106" Url="Events" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-ec85-4903-972d-ebe475780106" ContentTypesEnabled="true" EnableFolderCreation="false" DefaultDisplayFormUrl="{site}/Events/DispForm.aspx" DefaultEditFormUrl="{site}/Events/EditForm.aspx" DefaultNewFormUrl="{site}/Events/NewForm.aspx" ImageUrl="/_layouts/15/images/itevent.png?rev=44" IsApplicationList="false" ValidationFormula="" ValidationMessage="">
          <pnp:DataRows xmlns:pnp="http://schemas.dev.office.com/PnP/2018/01/ProvisioningSchema">            <pnp:DataRow>
<!-- Row 7 -->
              <pnp:DataValue FieldName="Title">Royal Wedding</pnp:DataValue>
              <pnp:DataValue FieldName="Location">Windsor Castle, Windsor, Berkshire, United Kingdom</pnp:DataValue>
              <pnp:DataValue FieldName="EventDate">19/05/2018 00:00:00</pnp:DataValue>
              <pnp:DataValue FieldName="Description">&lt;p&gt;Harrys getting married&lt;/p&gt;</pnp:DataValue>
              <pnp:DataValue FieldName="fAllDayEvent">False</pnp:DataValue>
              <pnp:DataValue FieldName="fRecurrence">False</pnp:DataValue>
              <pnp:DataValue FieldName="EventType">0</pnp:DataValue>
              <pnp:DataValue FieldName="Duration">86340</pnp:DataValue>
<!--              <pnp:DataValue FieldName="ParticipantsPicker" />   -->
              <pnp:DataValue FieldName="Category" />
<!--              <pnp:DataValue FieldName="Participants" />  -->
              <pnp:DataValue FieldName="BannerUrl" >Null</pnp:DataValue>
            </pnp:DataRow>
           </pnp:DataRows>
        </pnp:ListInstance>
      </pnp:Lists>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

```
Sharing is caring.

**Comment by erwinvanhunen** [comment]
This is not a bug unfortunately.

Specifying a text value as 'Null' will not put the value to null, as you noticed. To the engine that's just text and not some magic value. If you want to leave the field as null, simply don't specify it as a datavalue row, e.g. leave it out. If you are generating this data automatically, consider putting a test in your code that generates the DataValue elements and do not generate the line for those values which are null/empty.

**Comment by erwinvanhunen** [comment]
Having said that, we can update the engine to accept empty nodes. If an empty node is encountered we will empty the value of the field. This applies specifically to cases where your DataRow UpdateBehaviour setting is set to Overwrite and you want to remove values from an already existing listitem.

**Comment by NPrice99** [comment]
Hi @erwinvanhunen that would be great ! Thanks Nigel
