### ISSUE TITLE
Cannot set title for some Client-side Web Parts through CSOM

### ISSUE THREAD

**Issue by vhilliard** [SharePoint/PnP-Sites-Core#1637]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: unknown

#### Expected or Desired Behavior
Title of a ContentRollup ("Highlighted Content") web part should be able to be set through CSOM.

#### Observed Behavior
Title is instead used in edit-mode properties panel.

Title of the actual web part is not accessible from code, since ServerProcessedContent is read-only in the CSOM model and is instantiated as null for a new WebPart. For automated customisation of a SharePoint page, the Title of a client side web part will not be able to be changed through CSOM.

#### Steps to Reproduce
[[ code to load clientSidePage object ]]

var wp = clientSidePage.InstantiateDefaultWebPart(DefaultClientSideWebParts.List);
wp.Title = "Foo";
clientSidePage.AddControl(wp);

[[ code to save clientSidePage ]]

Open SharePoint site page, edit the modern web parts, the title has not been set on the actual web part in the page, but is set as the title for the properties panel of the web part.

**Comment by vhilliard** [comment]
After a few days, it didn't make sense to apply serverProcessedContent to PropertiesJson, but okay that worked. Wish it was a little more clear, though.

**Comment by jansenbe** [comment]
Agreed...the latest version does extract serverProcessedContent so that already help. If you create a more complex control from scratch using code it's best to first define, grab it's JSON  properties including serverProcessedContent and then alter the JSON
