### ISSUE TITLE
Method implementation is not atomic.

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Sites-Core#1640]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ x] SharePoint 2016
[ x] SharePoint 2013

https://github.com/sharepoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs#L1672

Code sets field on listitem, however never commits this change through update and ExecuteQueryRetry. While it is to be assumed that the user will do this later in the calling flow, this is an assumption which is not guaranteed, especially given that methods in PnP are atomic, if not otherwise stated.

**Comment by TeodoraI** [comment]
@wobba, @erwinvanhunen I believe this can be closed now.
