### ISSUE TITLE
Error when creating Modern Comm Site

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/PnP-Sites-Core#1654]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
We have several dev tenants for dev purpose and for one of them we suddenly got the following error, preventing us to create any new Comm Site...
This is the piece of code we use (it works an all of our dev tenants but one...

ctx.Web.EnsureProperty(w => w.Language);
var urlRet = ctx.CreateSiteAsync(new 
   OfficeDevPnP.Core.Sites.CommunicationSiteCollectionCreationInformation
                {
                    Title = titre,
                    Owner = owner,
                    Lcid = ctx.Web.Language,
                    Description = description,
                    AllowFileSharingForGuestUsers = fileSharing,
                    Url = url
                }).GetAwaiter().GetResult().Url;

#### Observed Behavior
This is the error we got : 
System.Exception: {"d":{"Create":{"__metadata":{"type":"SP.
Publishing.CommunicationSiteCreationResponse"},"SiteStatus":3,"SiteUrl":""}}}
   at OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<CreateSiteAsync>d__16
.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

#### Steps to Reproduce
Hard to tell as it only appears on one of our tenants...

**Comment by BraunJonathan** [comment]
Just to add, the problem suddenly appended on another of our tenants without any change on tenant config...

**Comment by jansenbe** [comment]
Have seen this as well and reason was that a site with the same URL still existing in the recycle bin. Can you verify with Get-SPODeletedSite that the site url you want to use is free for use?

**Comment by BraunJonathan** [comment]
Yes, i found out that this was indeed the problem !!
Forgot to mention it here .
Thanks !!
