### ISSUE TITLE
Error: Cannot add a role assignment with empty role definition binding collection.

### ISSUE THREAD

**Issue by rfjschouten** [SharePoint/PnP-Sites-Core#167]
I extracted a template using web.GetProvisioningTemplate. The web use has some lists with broken permissions. The extracted template, when saved as xml, contains the correct security tag with role assignments. When I try to apply the template to a new web, I get an exception:

Cannot add a role assignment with empty role definition binding collection.

**Comment by jakobnotseth** [comment]
I get the same error with the latest released powershell commands. Is it misreading the extracted template?

**Comment by PaoloPia** [comment]
Hi, thanks for your feedbacks. We updated and improved the handling of security settings in the latest builds of the engine. Are you still experiencing this kind of issues? Or can I close this one? Thanks.

**Comment by barbiturx** [comment]
Hi, I'm still experiencing this issue using CSOM.
My template Web has broken inheritance, as well as some lists in my Web. Template is exported just fine, but throws the "Cannot add a role assignment with empty role definition binding collection" Exception when I try to apply it to a new, freshly created web.

**Comment by barbiturx** [comment]
After some manipulations, I narrowed my issue down to a specific case in my template.
In this template, I have a list with broken inheritance, and custom RoleDefinitions. In my target sitecollection, I do not have these custom Role Definitions, and this seems to trigger the exception throwing.

**Comment by statto1974** [comment]
This is to do with the code in SecurableObjectExtensions.cs (OfficeDevPnp.Core > Framework > Provisioning > ObjectHandlers > Extensions)

The code below 
```
var roleDefinitionBindingCollection = new RoleDefinitionBindingCollection(context);
var roleDefinition = webRoleDefinitions.FirstOrDefault(r => r.Name == roleAssignment.RoleDefinition);

if (roleDefinition != null)
{
    roleDefinitionBindingCollection.Add(roleDefinition);
}

securable.RoleAssignments.Add(principal, roleDefinitionBindingCollection);
```

Should be 
 
```
var roleDefinition = webRoleDefinitions.FirstOrDefault(r => r.Name == roleAssignment.RoleDefinition);

if (roleDefinition != null)
{
  var roleDefinitionBindingCollection = new RoleDefinitionBindingCollection(context);
   roleDefinitionBindingCollection.Add(roleDefinition);
  securable.RoleAssignments.Add(principal, roleDefinitionBindingCollection);
}
```

Before if it couldn't find the RoleDefinition in the target web it was still creating a RoleDefinitionBindingCollection, but adding it as empty which is throwing the error.

Not sure why the RoleDefinition doesn't exist and that may need to be investigated further, but this worked for me.

**Comment by JBoman32768** [comment]
I can reproduce this issue - obviously removing all the <pnp:Security> tags seems to workaround this functionality for now.

**Comment by jansenbe** [comment]
Implemented fix proposed by @statto1974 . Closing this issue for now, feel free to re-open when it can be reproduced with the latest dev build.
