### ISSUE TITLE
ExecuteQueryRetry is not working in Web Application

### ISSUE THREAD

**Issue by chinthamahesh** [SharePoint/PnP-Sites-Core#1690]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core - March 2018 version (v2.24.1803)

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
ExecuteQueryRetry should be executed without an issue 

#### Observed Behavior
It seems recently async/await functionality has been introduced in ExecuteQueryRetry method. This change is causing issues with ExecuteQueryRetry when used in Web Applications/PHAs. The application is getting hung at ExecuteQueryRetry line and there is no response  from this line of code. ExecuteQueryRetry is a synchronous method and the ExecuteQueryImplementation is an asynchronous method. This sync/asyn method combination seems to be causing an issue.

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._
1. Add the OfficeDevPnP.Core.dll March 2018 version (v2.24.1803) to a web application or a Provider Hosted Add-In. 
2. Run the code

Application will be hung at ExecuteQueryRetry line. Currently, it is working in console app but not in Web App/PHA

**Comment by jansenbe** [comment]
Can you try with the dev branch? We did several changes related to this that should help

**Comment by chinthamahesh** [comment]
Thank you Bert, It works with Dev branch
