### ISSUE TITLE
Error 403 is returned when I tried to get web template list via PnP-PowerShell

### ISSUE THREAD

**Issue by tsekityam** [SharePoint/PnP-Sites-Core#1692]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
A list of web template that I can used would be printed

#### Observed Behavior
Error 403 was returned when I executed `Get-PnPWebTemplate`, however, other cmdlet, i.e. `Get-PnPList` and `Get-PnPWeb`, were working fine.

#### Steps to Reproduce
```
PS C:\Users\tsekityam> Connect-PnPOnline -Url https://aaa.sharepoint.com/sites/bbb/ccc -UseWebLogin
PS C:\Users\tsekityam> Get-PnPConnection


ConnectionType     : O365
MinimalHealthScore : -1
RetryCount         : 10
RetryWait          : 1
PSCredential       :
Url                : https://aaa.sharepoint.com/sites/bbb/ccc
TenantAdminUrl     :
Context            : OfficeDevPnP.Core.PnPClientContext



PS C:\Users\tsekityam> Get-PnPWebTemplates
Get-PnPWebTemplates : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Get-PnPWebTemplates
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PnPWebTemplates], WebException
    + FullyQualifiedErrorId : System.Net.WebException,SharePointPnP.PowerShell.Commands.GetWebTemplates
```

**Comment by gautamdsheth** [comment]
`Get-PnPWebTemplates` returns `Microsoft.Online.SharePoint.TenantAdministration.SPOTenantWebTemplateCollection` object.

So, you need to connect to the SharePoint admin site. You need to be a SharePoint admin to run this command. It comes under tenant/sharepoint admin commands

Modify the code as below:

`Connect-PnPOnline -Url https://aaa-admin.sharepoint.com/ -UseWebLogin`

Check [this](https://github.com/SharePoint/PnP-Guidance/blob/master/powershell/GetPnPWebTemplates.md) documentation.

**Comment by tsekityam** [comment]
Templates are returned if I am connected to admin site.
