### ISSUE TITLE
Site security provisioning performance vastly different between POSH and C#

### ISSUE THREAD

**Issue by MattPPMConsultant** [SharePoint/PnP-Sites-Core#1713]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behaviour
Provisioning Timings to be comparable between executing with POSH versus C#

#### Observed Behavior
When applying an xml provisioning template via POSH the security elements take 14020ms
When applying the same template via our Azure app running the C# commands it taking circa 20-30mins.

We previously saw this long provisioning time in POSH, see issue   #1516 but it has since been resolved which is wonderful but lead to the strange question of why doesn't it reflect in C#.

#### Steps to Reproduce
Apply the following template in the repro steps of #1516 via the two commands:
`Apply-Pnpprovisioningtemplate` and  `web.ApplyProvisioningTemplate(template, applyingInformation);`

Thanks all for any help as its keeping us awake at night.

**Comment by pwmather** [comment]
Runs as expected from a C# console app locally, this seems to be down to the Azure App specs.

**Comment by MattPPMConsultant** [comment]
I'm closing the issue but for anyone's future info, after further investigation we have found that it was the Azure function's app service plan specs that were causing the issue; we were running on an S1 plan (1 core, 1.75GB RAM), switching to the S2 plan (2 cores, 3.5 GB RAM)  resolved out issue, reducing the security provisioning down to  a few minutes.
