### ISSUE TITLE
ClientSidePage.InstantiateDefaultWebPart is not working in Web Application

### ISSUE THREAD

**Issue by Stanislav-F** [SharePoint/PnP-Sites-Core#1715]
#### Which PnP repository should you use to report the issue? 

- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core - April 2018 version (v2.25.1804)

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
`InstantiateDefaultWebPart` method of the `ClientSidePage` class should be executed without an issue

#### Observed Behavior
The web application code is getting hung at `InstantiateDefaultWebPart` most times. Sometimes occasionally it passes through but in most cases it is stuck on `InstantiateDefaultWebPart` line.
Looks like it's related to the issue [1690](https://github.com/SharePoint/PnP-Sites-Core/issues/1690) with async/await calling.
 
#### Steps to Reproduce
1. Use April 2018 version (v2.25.1804) of OfficeDevPnP.Core.dll

2. Add the code to ASP.NET MVC web application solution to add Image web part to the modern page:
`var page = new ClientSidePage(context);`
`var imageWebPart = page.InstantiateDefaultWebPart(DefaultClientSideWebParts.Image);`

Code will stuck on calling `InstantiateDefaultWebPart` method in most occurrences.
Note that it always works fine in Console application.

**Comment by jansenbe** [comment]
Can you try with May release? We fixed a deadlock in the GetClientSideWebParts call, which is called in InstantiateDefaultWebPart.

**Comment by Stanislav-F** [comment]
Thank you @jansenbe . I can confirm that the issue is resolved.
