### ISSUE TITLE
Add strongly name to the latest nuget package

### ISSUE THREAD

**Issue by Maksim-Ilyenia** [SharePoint/PnP-Sites-Core#1717]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ ] Bug
[ X] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ X] SharePoint 2016
[X ] SharePoint 2013

#### Expected or Desired Behavior
Please, add strongly name (public key)  to the latest nuget package

**Comment by IlyeniaMaksim** [comment]
Fixed. Can be close
