### ISSUE TITLE
Missing negation

### ISSUE THREAD

**Issue by TomekPi** [SharePoint/PnP-Sites-Core#1720]
I guess there is a negate operator missing here inside condition.

https://github.com/SharePoint/PnP-Sites-Core/blob/dd9f547302d8f7b65b4b908adacf5a9a94bcd8cc/Core/OfficeDevPnP.Core/ALM/AppManager.cs#L110-L113

**Comment by erwinvanhunen** [comment]
Good catch! Gautam was so kind to create a PR on that one and I just merged it.
