### ISSUE TITLE
Cannot change modern Client Side page title - LayoutWebpartsContent

### ISSUE THREAD

**Issue by watters888** [SharePoint/PnP-Sites-Core#1731]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior

Currently we cannot change modern Client Side page title via the core pnp and also the powershell pnp.  This is something so trivial, but we can not do it. 

#### Observed Behavior

There is a PnP CSOM method called clientSitePage.PageTitle, but it just changes the Title within the list item of the page, but that does not reflect the page title itself.

#### Additional information

When I try to change the page title from the UI it calls an api on that endpoint `/sites/site1/_api/sitepages/pages(21)/SavePage` with the following payload 

```
{,…}
BannerImageUrl
:
"/_layouts/15/images/sitepagethumbnail.png"
CanvasContent1
:
"[{"webPartId":"d326218b-07de-4653-a001-525639980661","controlType":3,"id":"609c46ab-86a5-42b1-87b5-a9b7ae1ca478","position":{"controlIndex":1,"zoneIndex":1,"sectionIndex":1,"sectionFactor":12},"displayMode":2,"addedFromPersistedData":true,"webPartData":{"id":"d326218b-07de-4653-a001-525639980661","instanceId":"609c46ab-86a5-42b1-87b5-a9b7ae1ca478","title":"My Information and Events","description":"My Information and Events","serverProcessedContent":{"htmlStrings":{},"searchablePlainTexts":{},"imageSources":{},"links":{}},"dataVersion":"1.0","properties":{"description":"myInformationEvents"}}}]"
LayoutWebpartsContent
:
"[{"id":"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788","instanceId":"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788","title":"Title Region","description":"Title Region Description","serverProcessedContent":{"htmlStrings":{},"searchablePlainTexts":{},"imageSources":{},"links":{}},"dataVersion":"1.4","properties":{"title":"News & Information 1","imageSourceType":4,"textAlignCenter":true,"layoutType":"FullWidthImage","textAlignment":"Left","showKicker":false,"showPublishDate":false,"kicker":""}}]"
__metadata
:
{type: "SP.Publishing.SitePage"}
type
:
"SP.Publishing.SitePage"
```

Seems that the page title is saved in page object called LayoutWebpartsContent, but that object is not present in the ClientSidePage object within the PnP Core Sites dll.

**Comment by jansenbe** [comment]
can you try with the dev version? We added support for configuring the page header which relates to the the title configuration as well.

**Comment by watters888** [comment]
Thanks Bert will try this :)

**Comment by jansenbe** [comment]
We in the meantime released support for this in the May release, closing the issue

**Comment by jansenbe** [comment]
It's inside in our PnP Sites core library which is used by PnP PS...so if you use the latest (July) release via either PnP PS or our core library via the nuget package you should be good.
