### ISSUE TITLE
web parts are not adding to the page from some machines

### ISSUE THREAD

**Issue by ymihir** [SharePoint/PnP-Sites-Core#1748]
I have created a code which will create new modern site collection add the modern web parts to the page. When I test from my machine and from my co-developer machine it is working fine.
But when we try the same thing from client machine then code is building successfully and new modern site collection is creating but, web parts are not being added to the page, at the same time it is not giving any error as well.
Client is also having VS 2017 with latest .net framework. 
What could the anticipated reason that web parts are not adding to the page?
Are we missing any dependencies?

**Comment by gboraiah** [comment]
Adding to what Mihir reported:
We noticed that when we run the tool from C:\ the web parts wont show up in the newly provisioned modern site.
But if we copy the executable to any drive other than C:\ (Where windows is installed) the solution works perfect and the web parts show up in the newly provisioned site.
