### ISSUE TITLE
{sitename} token is not translated when used in ClientSidePage tag in provisioning schema

### ISSUE THREAD

**Issue by prawnz** [SharePoint/PnP-Sites-Core#1774]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
{sitename} token translated.

#### Observed Behavior
{sitename} token is not translated when used with <pnp:ClientSidePage Title="{sitename}" > provisioning template.

#### Steps to Reproduce
1. Apply a template with  <pnp:ClientSidePage Title="{sitename}" >

**Comment by jansenbe** [comment]
Title was not yet tokenized. I've fixed this is the dev branch, will be part of the June release
