### ISSUE TITLE
New Client Site Pages Header Tag causes page title to no longer be in the middle.

### ISSUE THREAD

**Issue by prawnz** [SharePoint/PnP-Sites-Core#1775]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Page title should be in the middle
![image](https://user-images.githubusercontent.com/3827044/40276000-aa784110-5c31-11e8-94d0-4c925d410886.png)

#### Observed Behavior
New Client Side Page Header causes Page Title to no longer be in the middle as how it is from the previous version.

#### Steps to Reproduce
1. Create Client Side Page template with <pnp:Header Type="Default" />
2. Apply the template to a site.
3. Edit the page and the page title is on the far left rather than in the middle
![image](https://user-images.githubusercontent.com/3827044/40275884-ebcd4136-5c2e-11e8-8e83-718efa53403c.png)

**Comment by jansenbe** [comment]
Thanks for reporting this. We recently changed the data version for the header from 1.3 to 1.4 which is not yet supported in the PnP May version. We'll update this for the June release

**Comment by prawnz** [comment]
@jansenbe seem like the latest version got even worst
This is how it is from SharePoint default setting
![image](https://user-images.githubusercontent.com/3827044/44727501-c5b91b00-ab0c-11e8-8a7b-b43f8d003f4c.png)

This is what is shown with the new 1.4 on the August Release
![image](https://user-images.githubusercontent.com/3827044/44727628-09ac2000-ab0d-11e8-86d3-a305e597493f.png)

**Comment by jansenbe** [comment]
This should work now. Closing this issue...feel free to re-open if you still feel this is blocking you.
