### ISSUE TITLE
Content TypeId ignored during provisioning of datarows

### ISSUE THREAD

**Issue by tarjeieo** [SharePoint/PnP-Sites-Core#1787]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I'm trying to provision list items with datarows in apply-pnpprovisioningtemplate with different content types. I expect to be able to set the ContentTypeId Fieldname to my content type id, and have the correct Content Type being set on the list item.

#### Observed Behavior
The ContentTypeId is ignored, and the default content type is always set.

#### Steps to Reproduce
This has been tested with the latest version of PnP PowerShell (May 18 intermediate).

I'm using a PnP Provisioning Template with the following setup (only including list instance element)
```
<pnp:ListInstance Title="Diagramkonfigurasjon" ContentTypesEnabled="true" DocumentTemplate="" TemplateType="100" Url="Lists/ChartsConfig" Hidden="true" EnableAttachments="false" EnableFolderCreation="false">
    <pnp:ContentTypeBindings>
        <pnp:ContentTypeBinding ContentTypeID="0x0100FAC6DE5CA35FAB46ABCF3CD575663D9D01" Default="true" />
        <pnp:ContentTypeBinding ContentTypeID="0x0100FAC6DE5CA35FAB46ABCF3CD575663D9D02" />
        <pnp:ContentTypeBinding ContentTypeID="0x0100FAC6DE5CA35FAB46ABCF3CD575663D9D03" />
    </pnp:ContentTypeBindings>
    <pnp:DataRows>
        <pnp:DataRow>
            <pnp:DataValue FieldName="ContentTypeId">0x0100FAC6DE5CA35FAB46ABCF3CD575663D9D03</pnp:DataValue>
            <pnp:DataValue FieldName="GtChrOrder">100</pnp:DataValue>
            <pnp:DataValue FieldName="Title">Økonomioversikt</pnp:DataValue>
            <pnp:DataValue FieldName="GtChrSubTitle">Prosjektets kostnader vs totalbudsjett</pnp:DataValue>
            <pnp:DataValue FieldName="GtChrHeight">1000</pnp:DataValue>
            <pnp:DataValue FieldName="GtChrFields">4,6</pnp:DataValue>
        </pnp:DataRow>
    </pnp:DataRows>
</pnp:ListInstance>
```

Note: I cannot find documentation on how to set the Content Type, but I'm 95% sure that this has worked before (using FieldName="ContentTypeId").

**Comment by wobba** [comment]
This is now fixed and will be included in the next release.
