### ISSUE TITLE
ContentTypeBinding with lowercase ContentTypeID no longer works

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/PnP-Sites-Core#1810]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
When I add a ContentTypeBinding  on my list I want it to be added.

#### Observed Behavior
When I add a ContentTypeBinding in my list instance, the PNP library gives ContentType duplicate or not found error when the ContentTypeId is in lowercase

#### Steps to Reproduce
I have the following listinstance in my template (partial section)

`        <pnp:ListInstance Title="Site Pages" Description="" DocumentTemplate="" TemplateType="119" Url="SitePages" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-c796-4402-9f2f-0eb9a6e71b18" ContentTypesEnabled="true" EnableAttachments="false" EnableFolderCreation="false">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x010108" Default="true"/>
            <pnp:ContentTypeBinding ContentTypeID="0x01010800e1ea00e085ed4afabf9fd3cbb77ddaf0" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>`

As you can see the second ContentTypeBinding  has a lowercase ContentTypeID. In the objecthandler "ObjectListInstance.cs" this code checks the presence of the contenttype on the list

`ContentTypeId existingContentTypeId = list.ContentTypes.BestMatch(ctb.ContentTypeId);`

In the BestMatch method I see:

`var res = contentTypes.Where(c => c.Id.StringValue.StartsWith(contentTypeId)).OrderBy(c => c.Id.StringValue.Length).FirstOrDefault();`

So the check is case sensitive. In several templates we had lowercase ContentTypeID's that worked with previous version (January 2018) and no longer work with the latest version.

**Comment by jansenbe** [comment]
Implemented upcoming July release
