### ISSUE TITLE
Error in ALM API when upgrading app

### ISSUE THREAD

**Issue by RobinDijkstra** [SharePoint/PnP-Sites-Core#1825]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I'm using the PnP-Powershell cmdlet Update-PnPApp to update a Sharepoint Framework app that is in a site collection catalog. It should update the app.

#### Observed Behavior
Update-PnPApp : {"odata.error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":{"lang":"nl-NL","value
":"De app voor SharePoint met id 32c501ab-58b7-453f-abe5-b00163a93bc8 is niet aanwezig in de app-catalogus."}}}
At line:1 char:1
+ Update-PnPApp -Identity $app.Id -Scope Site
    + CategoryInfo          : WriteError: (:) [Update-PnPApp], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Apps.UpdateApp

In English: The app for Sharepoint with id …. does not exist in the app catalog.

The strange thing is that in Fiddler I can see that the following request is made:
`/_api/web/sitecollectionappcatalog/AvailableApps/GetByID('32c501ab-58b7-453f-abe5-b00163a93bc8')/Upgrade`
The response of this request is the error as shown by the cmdlet:
`{"odata.error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":{"lang":"nl-NL","value":"De app voor SharePoint met id 32c501ab-58b7-453f-abe5-b00163a93bc8 is niet aanwezig in de app-catalogus."}}}`

However, if I remove the /Upgrade from the url of the request in the Composer of Fiddler (which is basically a get of the app), the response is correct and the properties of the app are returned:
`"AppCatalogVersion":"1.0.0.1","CanUpgrade":true,"CurrentVersionDeployed":true,"Deployed":true,"ID":"32c501ab-58b7-453f-abe5-b00163a93bc8","InstalledVersion":"1.0.0.0","IsClientSideSolution":true,"Title":"test-app-client-side-solution"}`

So, the app does exists and is upgradable. I think this is a bug in the Upgrade method of the API.

#### Steps to Reproduce

PnP-Powershell version: 2.27.1806.1
This is a follow up on a Pnp-Powershell issue I've reported (and which is fixed in version 2.27.1806.1). Steps to reproduce are the same as in issue [https://github.com/SharePoint/PnP-PowerShell/issues/1519](https://github.com/SharePoint/PnP-PowerShell/issues/1519)

**Comment by KoenZomers** [comment]
@RobinDijkstra, would you mind creating a Premier Support case for this one so we can investigate it on our side? Please mention in the support ticket to have the support engineer contact me so I can give them a heads up from my side. Thanks!

**Comment by RobinDijkstra** [comment]
@KoenZomers, support ticket #10701569 created.

**Comment by KoenZomers** [comment]
@RobinDijkstra. Thanks! My support colleagues will look into this tomorrow by trying to create a repro using your steps.

**Comment by RobinDijkstra** [comment]
The SharePoint Online Product Group has confirmed this is a bug and they have rolled out a solution. I can confirm that this issue is resolved.

**Comment by KoenZomers** [comment]
Thanks for confirming @RobinDijkstra!
