### ISSUE TITLE
Provide high level steps how to register key credentials with Azure AD and add them to the AuthenticationManager code documentation

### ISSUE THREAD

**Issue by nddipiazza** [SharePoint/PnP-Sites-Core#1842]
I tried to ask the following question on tech community but the moderators marked it as spam 1 minute after creating it. Automatic spam filter I guess.

Link to my ticket: https://techcommunity.microsoft.com/t5/SharePoint-Developer/How-to-configure-SPO-to-do-app-only-auth-with-PFX-private-key/m-p/210407#M5268

I am trying to use this login endpoint: https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/AuthenticationManager.cs#L634

It requires `you have a certificate created, and updated the key credentials key in the application manifest in the azure AD accordingly.`

I am looking for steps on how to set up this AD manifest with a key like that. 

How do you set up AD with a certificate so you can log into SharePoint Online with this method I am trying to use this login endpoint: https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/AuthenticationManager.cs#L63 ?

I will be happy to create a PR where we add the high level steps of how to do this into the code documentation of `AuthenticationManager.cs` to help others.

**Comment by ozippy** [comment]
Maybe this is what you are looking for? https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread

I am trying to get this to work with Azure Key Vault and Managed Service Identity. Just struggling with some dependency conflicts at the moment.

**Comment by nddipiazza** [comment]
Yeah! Giving it a look thanks!

**Comment by nddipiazza** [comment]
Worked.
