### ISSUE TITLE
limitedWebPartManager.WebParts returns empty

### ISSUE THREAD

**Issue by tibgcv** [SharePoint/PnP-Sites-Core#1847]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
When using this code:
 var limitedWebPartManager = webPartPage.GetLimitedWebPartManager(PersonalizationScope.Shared);
            web.Context.Load(limitedWebPartManager.WebParts, wps => wps.Include(wp => wp.WebPart.Title));
            web.Context.ExecuteQueryRetry();

we expect to be able to get one of the webparts that are default provisioned on the Home.aspx page of a modern team site.

#### Observed Behavior
limitedWebPartManager.WebParts is empty, always, on all sites we tested in our environment. User we use to execute the code is Site Collection administrator.

same behavior with CSOM and with powershell Get-PnpWebPart 

#### Steps to Reproduce
Just try to use above code to get all webparts of a modern ui page (Home.aspx) from a default modern team site

**Comment by jansenbe** [comment]
Hmm...we're using limitedWebPartManager in our modernization tooling and works great. Some thoughts:
- Are you running this on classic pages? This only works on classic pages, modern pages require you to use the PnP Pages API
- Web parts that live outside of a web part zone cannot be found...there's no API for those, but that should be the exceptional case

**Comment by tibgcv** [comment]
We are working on modern pages. So I guess that's the problem. Could you give an example of "PnP Pages API"?

**Comment by jansenbe** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages#programming-modern-pages

**Comment by tibgcv** [comment]
thanks for the info, but there is nothing here about deleting webparts. And somehow InstantiateDefaultWebPart is not recognized. I'm using SharePointPnPCoreOnline nuget package, version 2.28.1807. The dll used is OfficeDevPnP.Core? this also has version 2.28.1807. 
Strangely, when I download the entire solution from github, i can find InstantiateDefaultWebPart. So should i build that project and use the dll? I would assume the nuget package has the correct dll's??

**Comment by tibgcv** [comment]
never mind, i found the solution, thx
