### ISSUE TITLE
InstantiateDefaultWebPart - DefaultClientSideWebParts does not contain all default webparts

### ISSUE THREAD

**Issue by tibgcv** [SharePoint/PnP-Sites-Core#1850]
#### Category
[ ] Bug
[x ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
While trying to add a new webpart to a modern page, i should be able to instantiate all default webparts, including the "Sites" webpart. Using the PnP methode InstantiateDefaultWebPart.

#### Observed Behavior
Not all default webparts are included in DefaultClientSideWebParts 

Is this going to be added? or is there another way to add these default webparts?

**Comment by SjoerdV** [comment]
I have the same question

**Comment by jansenbe** [comment]
Sites was indeed missing, I've just added that and it will be be part of the April release (released on Friday).

An OOB web part can also be added like a custom one, just grab the ID of the out of the box web part. 

Closing this issue, feel free to re-open if you can't get it to work with the April version.
