### ISSUE TITLE
Fails to provision ClientSidePage

### ISSUE THREAD

**Issue by joelfmrodrigues** [SharePoint/PnP-Sites-Core#1852]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Be able to provision ClientSidePage

#### Observed Behavior
Exception: File Not Found.

   _at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)_

Exception occurs when using CSOM via add-in, but everything works when using PowerShell. Both using latest release version 

#### Steps to Reproduce
Provision template with ClientSidePage

```xml
<pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="Test.aspx" PromoteAsNewsArticle="false" Overwrite="true">
        </pnp:ClientSidePage>
</pnp:ClientSidePages>
```

Same issue also available on a different repository (https://github.com/SharePoint/PnP-Provisioning-Schema/issues/313), but I thought this would be the correct place to raise it

**Comment by jansenbe** [comment]
Weird...PS uses the same code under the hood. Do you have the option to step through the code to get more details?

**Comment by joelfmrodrigues** [comment]
@jansenbe thanks, that's what I'm doing now :) it's a lot of code to go trough and a lot of effort to recreate my scenario, but I just found that the page is indeed being created, but on the root web (this is a subsite - project sites for Project Online). The context is wrong and using the root site. Let me investigate further to see where exactly the bug was introduced and to make sure that I'm passing the correct parameters

**Comment by joelfmrodrigues** [comment]
Seems to me that the problem is here:
![image](https://user-images.githubusercontent.com/19577724/42628038-c76ba3fc-85c6-11e8-8b6b-999c1510d13a.png)

I'm using subsites, and when passing web.Context on line 894, it seems to be defaulting to the root web. Should this work with subsites as well?

**Comment by jansenbe** [comment]
Should work on sub sites...looked at the code and don't see any context recreation...and the fact that PS works make me think somehow the CSOM code is calling the provisioning engine passing in the context of the root web?

**Comment by joelfmrodrigues** [comment]
@jansenbe  the provisioning engine is used via a provider-hosted app and the apply-template is called from a webjob (although I don't think that this would be a problem). Everything works fine, except the ClientSidePages. 
I debugged the code and the context of the web object seems to be referring to the root web from the start. This is how the web object is being retrieved:

Web web = hostWebClientContext.Web.GetWeb(subWebUrl);

And the web information is correctly set, for example, the server relative url is referring to the correct subsite.
The problem is then when a new ClientSidePage is created, we pass the context of the web object, which in this case is the root site.
Am I missing something super basic here? 

Thanks for your help

**Comment by joelfmrodrigues** [comment]
Hi Ravikadri

In my case I believe the issue is down to the context object not being created based on the same web. Unfortunately I haven't been able to test this yet

**Comment by joelfmrodrigues** [comment]
@jansenbe I can confirm that the project I was working on had a bug around the context object from where the Web was retrieved and that was causing other issues (JSLink failed to be set on a list view).
I haven't tested exactly this scenario (it was same code base, but for a different client), but I'm confident that it was also created by the context being created on the root site and the template being applied to a sub web, so will close the issue.

Thanks everyone
