### ISSUE TITLE
Is it possible to Set Property Bag value for Modern Site. ? 

### ISSUE THREAD

**Issue by pavan2920** [SharePoint/PnP-Sites-Core#1865]
Hi Team, 

Is is possible to set the porperty Bag value for Modern Site? If yes could any one help me with solution. 

I tried the below things. 
Connect-PnPOnline MySiteURL
Set-PnPPropertyBagValue -Key CUSTOMValue -Value Test

It shows the below Error. 
![image](https://user-images.githubusercontent.com/10346150/43317946-8e17dee8-91bc-11e8-91ff-9842913c99f6.png)

Tried by disabling the NoScript but no luck. 

Thanks 
Pavan.

**Comment by gurubn** [comment]
Hi Pavan,

Ideally Once you make -NoScriptSite:false, you should be able to set property bag value on Modern team site.
I faced same issue like yours when we run it in Powershell console, but when I opened new instance of Powershell console, Set-PnPPropertyBagValue worked fine. Please find below the screenshot.

![capture](https://user-images.githubusercontent.com/23011566/44309792-50db3800-a3cc-11e8-8db9-57b36587134b.PNG)

Can you please re validate once and check.

Note: In our solution where we have used it, we always made sure to set Site back to -NoScript:true once after property bag value is set.
