### ISSUE TITLE
LoginNames should be compared case insensitive

### ISSUE THREAD

**Issue by tmeckel** [SharePoint/PnP-Sites-Core#1881]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: CU January 2018

#### Expected or Desired Behavior
Sucessfully assigning a `<RoleAssignment>` during provisioning of a List via the `<ListInstance><Security /></ListInstance>` element regardless of the of the casing of the name.

#### Observed Behavior
If the group name in the provisioning template is not exactly cased like the LoginName property of the group in the SharePoint SiteGroups collection. The provisioning engine will try to create a new User via EnsureUser which will fail with an exception because the account obviously cannot be found.

#### Steps to Reproduce

1. Create a group inside a SharePoint Site
2. Create a provisioning template which creates a `<ListInstance />` and assignes special `<Security>` by referencing the group created in (1.) Use another casing in the provisioning template than in the LoginName of the group.
3. Apply the template
4. An exception will be thrown stating that the account cannot be found.

####  Proposed resolution

Find attached a patch file which changes the comparison of LoginNames from the equality operator '==' to .Equals using StringComparison.OrdinalIgnoreCase.

**Comment by tmeckel** [comment]
[bug-LoginNameCaseInsensitive.txt](https://github.com/SharePoint/PnP-Sites-Core/files/2305192/bug-LoginNameCaseInsensitive.txt)

**Comment by jansenbe** [comment]
PR #1895 has been merged and will be part of the October 2018 release. Closing this issue.
