### ISSUE TITLE
ClientSidePageHeader code causing Title in the banner to be not left aligned.

### ISSUE THREAD

**Issue by prawnz** [SharePoint/PnP-Sites-Core#1890]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Title in the banner should be left aligned.
ImageServerRelativeUrl should not throw the error "Server relative urls must start with SPWeb.ServerRelativeUrl"

#### Observed Behavior
Looking at the PnP Code for ClientSidePageHeader method, 
the text alignment is set to center however when a modern page is created, it is set to Left to begin with. I don't think you should be setting it to center if you are not providing a parameter for the user to choose in the provisioning schema. 

#### Steps to Reproduce
1. Export a template of a brand new modern page with a custom banner from another site using Get-PnPProvisioningTemplate
2. Import the template back using Apply-PnPProvisioningTemplate. You will notice the Title centered which is incorrect as the original is left aligned

**Comment by Niekoesj** [comment]
True! same "issue" here!
When you multiple times run the **Apply-PnPProvisioningTemplate** command, the page title is being alinged to center. This is not what we expect. 
This occurs with the latest version of SharePointPnP Module. 
SharePointPnPPowerShellOnline 3.0.1808.1

**Comment by pedropablo** [comment]
I experience the same "issue". It also happens with the **Add-PnPClientSidePage**

It would be great to have this as an option, because my users like it for some pages like a welcome page. 

But right now I need to deploy a new client page in a bunch of sites, and it needs a left aligned title... so I'll have to do it manually :'(

**Comment by BraunJonathan** [comment]
Same here, defintely something you should look at quickly, as once centered, there is no way to make it left aligned again...

**Comment by jansenbe** [comment]
Fixed. Will be in September release which will land on Nuget on Monday
