### ISSUE TITLE
FieldDefaults: Editing metadata on items changing metadata on other items

### ISSUE THREAD

**Issue by migee** [SharePoint/PnP-Sites-Core#1891]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

SharePointPnPPowerShellOnline 3.0.1808.1 (also seeing this on versions older than 5 months)

#### Expected or Desired Behavior
When applying a column default, the column values on items within a list should not be impacted by adjusting metadata on other items.

#### Observed Behavior
Changing metadata on a list item within a list with a column default impacts other columns by applying the selected choice to other items fields, where those fields are set to have list level defaults.

#### Steps to Reproduce
1. Apply the attached template to a modern communications site.
2. Navigate to the pages library
3. Create a new page (use New > 'Custom Page')
4. Within the list view open the edit side panel
5. Set a value for 'My Function' and click away so that it saves
6. Note the value of the pre-existing Test.aspx page for 'My Group'
7. Refresh

**Issue:** The untouched Test.aspx page will inherit the function field value within the group value. Even more odd is that it is not even an appropriate MMS value for this column as it is anchored to a different term set.

**Post PnP Deployment**

![image](https://user-images.githubusercontent.com/10858619/44791212-1feac800-ab6f-11e8-9ef6-1fe5f5077199.png)

**Create a New Page**

![image](https://user-images.githubusercontent.com/10858619/44791276-3f81f080-ab6f-11e8-8770-8f720a672b9f.png)

**Modify Page (Non-Default Value Column)**

![image](https://user-images.githubusercontent.com/10858619/44791315-532d5700-ab6f-11e8-8f70-2e84938f18bf.png)

**Refresh to see other page impacted with invalid value**

![image](https://user-images.githubusercontent.com/10858619/44791498-bf0fbf80-ab6f-11e8-802f-23a15ae721b8.png)

**PnP Template**

[PnPIssue.txt](https://github.com/SharePoint/PnP-Sites-Core/files/2332325/PnPIssue.txt)

**Comment by christopher-walker** [comment]
Hi,
 I was just checking up on an issue I was having: https://github.com/SharePoint/PnP-Sites-Core/issues/1996 and came across your issue.
 Have you moved this code from a different environment? or a different site collection? if so the WSSID could be different (the 2). Maybe you could try something similar but replace the 2 with -1 in that scenario SharePoint **_should_** look up the term by it GUID and then set it correctly. In my case I was just using the Guid of the term rather the pipe separated format, maybe it will make a difference for me to do it this way too.

Chris

**Comment by migee** [comment]
@christopher-walker Thanks, I will try to give this a shot this week or next to see if this is a viable workaround!

**Comment by migee** [comment]
@christopher-walker late reply but thanks! This helped resolve the error without needing to resort to workarounds
