### ISSUE TITLE
Unable to import Taxonomy Hashtag values

### ISSUE THREAD

**Issue by tmeckel** [SharePoint/PnP-Sites-Core#1897]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: CU January 2018

#### Expected or Desired Behavior

Successfully importing Taxonomy Hashtags into an existing Termstore.

#### Observed Behavior

The import process terminates with a ServerException stating that the operation is invalid for the current TermSet (Hashtags).

#### Steps to Reproduce

1. Create (or export `Export-PnPTermGroupToXml`) a provisioning template containing Term definitions for the Hashtags TermSet
2. Import the template using `Import-PnPTermGroupFromXml`
3. Exception of type ServerException will be thrown

**Comment by jansenbe** [comment]
Closing as #1898 has been merged. Will be in October 2018 release. Thx @tmeckel
