### ISSUE TITLE
Object reference not set to an instance of an object on server

### ISSUE THREAD

**Issue by sivamsolai** [SharePoint/PnP-Sites-Core#1905]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

What is the version of the Cmdlet module you are running?
3.1.1809.0

#### Steps to Reproduce
I am getting error below error when apply provisioning template   

Apply-PnPProvisioningTemplate E:\PS-PNP-Test\template.xml -Handlers Lists

powershell.exe Information: 0 : 2018-09-14 04:52:49.2888	[List instances]	[6]	[Debug]	Creating list Calendar failed: Object reference not set to an instance of an object on server. The object is associated with property AssociatedVisitorGroup. :    at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)
   at Microsoft.SharePoint.Client.Principal.get_Title()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenDefinitions.AssociatedGroupToken.GetReplaceValue()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.BuildTokenCache()
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.ParseString(String input, String[] tokensToSkip)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	1861ms	a7d51358-0812-4835-a15e-57d038464f91

**Comment by wobba** [comment]
@sivamsolai can you please provide a simplified xml template file so I can try to reproduce and investigate the error.

**Comment by sivamsolai** [comment]
[Calendar.txt](https://github.com/SharePoint/PnP-Sites-Core/files/2383707/Calendar.txt)
@wobba 
attached the xml template which have the issue

**Comment by sivamsolai** [comment]
@wobba 
Can you able to reproduce the error?

**Comment by wobba** [comment]
@sivamsolai I'll let you know once I've tested as I'm busy doing other work right now.

**Comment by thefacemeltor** [comment]
I have the same issue. Created a Template from a nearly empty site collection and copied it to another. Same Issue again and again...

**Comment by SchauDK** [comment]
@sivamsolai @thefacemeltor Is it the same property that is uninitialized every time?

**Comment by thefacemeltor** [comment]
For me it's every time the same group: Apply-PnPProvisioningTemplate : Object reference not set to an instance of an object on server. The object is associated with property AssociatedVisitorGroup.

**Comment by thefacemeltor** [comment]
@SchauDK I have also tried it now with a normal team site ( not a site collection ) and I have the same Issue there...

**Comment by thefacemeltor** [comment]
I have checked the repository and found this:
`
public SwitchParameter AssociatedVisitorGroup;
[Parameter(Mandatory = false, ParameterSetName = "Owners", HelpMessage = "Retrieve the associated owner group")]
ClientContext.Load(SelectedWeb.AssociatedVisitorGroup);
ClientContext.Load(SelectedWeb.AssociatedVisitorGroup.Users);
`

Then I used the Get-PnPWeb command on my new site and checked if there is as Visitor Group:
`$web.AssociatedVisitorGroup`
But there is no visitor group... maybe we need here a try block?

the $web.AssociatedMemberGroup looks like this:
`
[Parameter(Mandatory = false, ParameterSetName = "Members", HelpMessage = "Retrieve the associated member group")]
public SwitchParameter AssociatedMemberGroup;
[Parameter(Mandatory = false, ParameterSetName = "Visitors", HelpMessage = "Retrieve the associated visitor group")]
else if (ParameterSetName == "Members")
{
ClientContext.Load(SelectedWeb.AssociatedMemberGroup);
....
`

**Comment by sivamsolai** [comment]
@thefacemeltor 
 we used exclude handler , the error is gone. however the custom lists and WebSettings are not applied.        
-ExcludeHandlers Lists, WebSettings, Navigation  
but for our case , the custom lists and WebSettings also need applied during provisioning. So we except the issue will be fix next release

**Comment by thefacemeltor** [comment]
@sivamsolai it's the same for me. I have to deploy also the websettings and lists... I will later install a previous version of pnp and check if there is the same bug..

**Comment by thefacemeltor** [comment]
@wobba @sivamsolai I have tried it in C# and there is the same issue.
`Microsoft.SharePoint.Client.ServerObjectNullReferenceException: "Object reference not set to an instance of an object on server. The object is associated with property AssociatedVisitorGroup."
`

**Comment by wobba** [comment]
Closed as #1921 fixes this.

**Comment by wobba** [comment]
This seems to have been resolved in the latest code which should be in the October release.

**Comment by westerdaled** [comment]
Has this definitely been fixed in ver 3.3.1811.0 on the modules and referencing the current schema . The reason is, I am refreshing some of the provisioning templates we used back in July but I am now not getting passed this error. In my case I want to test out my various site scripts , starting with a very basic one ( see attached txt file, copy of xml)
[ENWLProvisioningSDTemplate.txt](https://github.com/SharePoint/PnP-Sites-Core/files/2640686/ENWLProvisioningSDTemplate.txt)

**Comment by westerdaled** [comment]
Hi @wobba , no problem will do.
