### ISSUE TITLE
SetOpenBySitePolicy always returns false / not working

### ISSUE THREAD

**Issue by marek-mikulcik** [SharePoint/PnP-Sites-Core#1906]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
After web.SetOpenBySitePolicy() on locked site return value should be true and site unlocked.

#### Observed Behavior
web.SetOpenBySitePolicy() on locked site returns false, site keeps locked

#### Steps to Reproduce
Call web.SetOpenBySitePolicy() on locked site

#### Bug fixing 
 [existing code](https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/InformationManagementExtensions.cs) line 563 has wrong ! operator
`
#if ONPREMISES
            if (web.HasSitePolicyAppliedImplementation() && !IsClosedBySitePolicyImplementation(web))
#else
            if (await web.HasSitePolicyAppliedImplementation() && !await web.IsClosedBySitePolicyImplementation())
#endif
`
fix it to 
`
#if ONPREMISES
            if (web.HasSitePolicyAppliedImplementation() && IsClosedBySitePolicyImplementation(web))
#else
            if (await web.HasSitePolicyAppliedImplementation() && await web.IsClosedBySitePolicyImplementation())
#endif
`
Thank you

**Comment by jansenbe** [comment]
Closing this, will be included in October drop that we'll release early next week
