### ISSUE TITLE
Invalid template in a rare situation when Webhook's ServerNotificationUrl is empty

### ISSUE THREAD

**Issue by phawrylak** [SharePoint/PnP-Sites-Core#1907]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Valid template is exported even if some Webhook's ServerNotificationUrl is empty.

#### Observed Behavior
If Webhook's ServerNotificationUrl was empty, template is considered invalid when trying to load it as this property is required in XML Schema.

#### Steps to Reproduce
It was pretty random for me to have webhooks without ServerNotificationUrl and I can't provide any steps to reproduce. It seems to be related to Microsoft Flow webhooks somehow as it was used in sites with this problem. I had to write additional code to remove such wrong webhooks elements from XML to be able to load such template at all (XML schema validation was failing).

I think we should ignore invalid webhooks when exporting template and I will make a pull request that will include this change.

**Comment by jansenbe** [comment]
Closing this, will be included in October drop that we'll release early next week
