### ISSUE TITLE
File Not Found error when applying template exported from modern team site

### ISSUE THREAD

**Issue by phawrylak** [SharePoint/PnP-Sites-Core#1910]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Template exported from modern team site should be valid to apply to another site.

#### Observed Behavior
Applying template exported from modern team site ends with File Not Found exception. It happens when PnP Provisioning Engine tries to fix lookup field _DisplayName (1a53ab5a-11f9-4b92-a377-8cfaaf6ba7be) as it points to non-existing Docs list.

#### Steps to Reproduce
1. Create new site collection using "Team site" template.
2. Create two subsites using "Team site" template.
3. Export template from one subsite using Get-PnPProvisioningTemplate cmdlet.
4. Apply template to another subsite using Apply-PnPProvisioningTemplate cmdlet.
5. File Not Found exception is thrown.

**Comment by dsm0880** [comment]
@phawrylak I'm having the exact same issue. I'll let you know if I find anything. One thing I did notice was that if I extract twice I get additional information in the .xml file, even then the error still occurs.

**Comment by dsm0880** [comment]
@phawrylak Woops...didn't see your commit :) Well I just did a search and replace for that ID and removed the lines...looking at your pull request it is a much more elegant version of that.

**Comment by jansenbe** [comment]
We'll have to investigate this one further....normally the base template filtering will drop this field...but apparently it didn't so we'll have to cross check. If the base template can't do it then we'll look at #1911

**Comment by jansenbe** [comment]
Closing this, will be included in October drop that we'll release early next week

**Comment by ChouguleV** [comment]
@jansenbe  has this fix been pushed to main stream? I am using latest (February 2019 Intermediate Release 2) pnp version, but still getting the error "File not Found" while applying a Modern Team Site (STS#3) template on another site?

**Comment by jansenbe** [comment]
Did you extract the site again? The issue was in the extraction part, not in the apply part
