### ISSUE TITLE
PageName in ClientSidePage cannot use tokens

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/PnP-Sites-Core#1917]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When using {parameter:PageName} on a PnP Template on a ClientSidePage, the parameter token should be parsed and used. 

#### Observed Behavior
Right now, it uses the token name. It replaces {parameter: with blank and uses the rest of the token as the PageName, so PageName}.aspx.

#### Steps to Reproduce
Use the following PnP Template :

`<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.26.1805.1, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-PAGETEMPLATE-SINGLECOLUMN">
    <pnp:ProvisioningTemplate ID="PAGETEMPLATE-SINGLECOLUMN" Version="0" Scope="RootSite">
      <pnp:ClientSidePages>
        <pnp:ClientSidePage Title="{parameter:PageTitle}" PageName="{parameter:PageName}" PromoteAsNewsArticle="false" Overwrite="true" EnableComments="false">
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumn">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Text" ControlId="76a1479f-a1fb-4feb-8cff-b6439b86fcf4" Order="1" Column="1">
                  <pnp:CanvasControlProperties>
                    <pnp:CanvasControlProperty Key="Text" Value="" />
                  </pnp:CanvasControlProperties>
                </pnp:CanvasControl>
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
          <pnp:Header Type="Custom" />
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>`

The question here : Is it the way it's supposed to be or it should support tokens?

**Comment by jansenbe** [comment]
Only page title is tokenized currently, defining a token for the page name is not possible today. Can you verify that page title tokenization works for you?

**Comment by sebastienlevert** [comment]
Title works, but not the name. Is there a specific reason for not allowing tokens in the PageName? Would love to have a "template" for a page and pass in some params to enable this scenario!

**Comment by jansenbe** [comment]
Thanks @gautamdsheth  for the PR! @sebastienlevert: the change will be in the October version
