### ISSUE TITLE
ClientSidePage Page Header is always centered using PnP Provisioning Engine

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/PnP-Sites-Core#1918]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When exporting and important an PnP Template that would create / update a Client Side Page, the title should stay where it is, meaning left aligned.

#### Observed Behavior
When getting a PnP Template with only the -PageContents handler, the template looks OK. When applying this template to the same site (and even same page), the page header changes and shows a centered Title.

#### Steps to Reproduce
Create a page and make it your Welcome Page of your site. Then, generate your PnP Provisioning Template

`Get-PnPProvisioningTemplate -Out C:\_\temp\TestHome.xml -Handlers PageContents -Force`

Then Apply the same template to your site

`Apply-PnPProvisioningTemplate -Path C:\_\temp\TestHome.xml`

The title is now centered on the page

![screenshot-20180921123343](https://user-images.githubusercontent.com/7620955/45893901-c3a84c00-bd9a-11e8-8e5e-380336a5582f.png)

![screenshot-20180921123429](https://user-images.githubusercontent.com/7620955/45893906-c73bd300-bd9a-11e8-90a4-b2bfe4a106de.png)

**Comment by jansenbe** [comment]
This was fixed in the latest release. Can you reproduce this with the September 2018 release?

**Comment by jansenbe** [comment]
Closing for now, feel free to re-open if you can't get it to work with the September 2018 version

**Comment by sebastienlevert** [comment]
Looks all good! Well done!
