### ISSUE TITLE
Changing The Layout Attribute When the Page Is Already Provisioned is not considered

### ISSUE THREAD

**Issue by nikolayyordanov** [SharePoint/PnP-Sites-Core#1944]
#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When provisioning template is applied we expect that the Layout of the ClientSidePage will be updated. 

#### Observed Behavior
Initial provisioning ClientSidePage XML Element:
`<pnp:ClientSidePage PageName="SomePage.aspx" PromoteAsNewsArticle="false" Overwrite="true" EnableComments="true" Title="Homepage">`
The result of the Above is a Page with a header Section
`<pnp:ClientSidePage PageName="SomePage.aspx" **Layout="Home"** PromoteAsNewsArticle="false" Overwrite="true" EnableComments="true" Title="Homepage">`
The result of the above is a Page without header **BUT only** if the page is not already provisioned

**Comment by jansenbe** [comment]
Hi @nikolayyordanov , this feature is currently not supported by the provisioning engine, you can't change the layouttype of a page after is has been created.
