### ISSUE TITLE
Apply-PnPProvisioningTemplate function that "User Information List" does not exist.

### ISSUE THREAD

**Issue by rheid** [SharePoint/PnP-Sites-Core#1946]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
today I get a new error in the Apply-PnPProvisioningTemplate function that "User Information List" does not exist. I same xml template runs last week without any problem. Inside the xml template there is no reference to that list. Anyone got any idea where this might come from?

#### Observed Behavior
Apply-PnPProvisioningTemplate function that "User Information List" 

#### Steps to Reproduce 
Build an Get-PnPProvisioning and Apply-PnPProvisioningTemplate on Teams SharePoint Site Collection 
Get-PnPProvisioningTemplate -Out $templateFile -PersistBrandingFiles -PersistPublishingFiles;
Apply-PnPProvisioningTemplate

#### Submission Guidelines
powershell.exe Information: 0 : 2018-10-22 18:40:13.0000 [List instances] [10] [Debug] Updating list Documents failed: List 'User Information List' does not exist at site with URL 'https://icthdt.sharepoint.com/sites/rheidtempl001'. : at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
at Microsoft.SharePoint.Client.ClientRequest.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientRequest.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientRuntimeContext.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientContext.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientContextExtensions.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenDefinitions.ListIdToken.GetReplaceValue()
at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.BuildTokenCache()
at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser.ParseString(String input, String[] tokensToSkip)
at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.UpdateList(Web web, List existingList, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) 8371ms ee8f4df9-532d-493b-b3e6-5c2bbe3b40cc
powershell.exe Information: 0 : 2018-10-22 18:40:13.0060 [List instances] [10] [Debug] Code execution scope ended 8377ms ee8f4df9-532d-493b-b3e6-5c2bbe3b40cc
powershell.exe Information: 0 : 2018-10-22 18:40:13.0060 [Provisioning] [10] [Debug] Code execution scope ended 24225ms ee8f4df9-532d-493b-b3e6-5c2bbe3b40cc
Apply-PnPProvisioningTemplate : List 'User Information List' does not exist at site with URL
'https://icthdt.sharepoint.com/sites/rheidtempl001'.
At line:1 char:1

Apply-PnPProvisioningTemplate -Path $templateFile
  + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
  + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate 

Thanks for your contribution! Sharing is caring.

**Comment by schoier** [comment]
Hi, 

i get the same error using the command Apply-PnPProvisioningTemplate on a site with an alternate language _matching_ my profile. As a workaround, I can disable the alteranate language while applying the template.
- The Default Language of the site is set English, with Swedish as Alternate Language.
- The site is shown in Swedish (due to my profile settings)
- I get the error message in Swedish "Listan Lista över användarinformation finns inte på webbplatsen med webbadressen https://[...]", "User Information List does not exist at url https://[...]"
- I remove Swedish as alternate language
- I can run the script without errors

**Comment by patrick-blanc** [comment]
Hi 
The problem with disabling the alternate languages is the navigation won't be translated.
I get the exact same problem. I should disable alternate languages on the site before applying the template. But then the navigation was not translated in the alternate languages, but lists titles are translated. 

If I try to apply template for navigation after enabling alternate languages to ensure navigation nodes are translated, I got again "the list .... does not exists" even if my navigation node is external and point on google.

**Comment by patrick-blanc** [comment]
At the end I am not sure this problem comes from PnP. I thought there is a link with SharePoint CSOM because the behavior is different from one tenant to another. 

For example if I apply the tempalte with the workaround you mentionned in my development tenant it works.
If I do the same for my test tenant it failed. 

As the opposite, If I run the template without the workaround on my dev tenant it failed. 
If I do the same on my test tenant it works.

**Comment by joakimhogberg** [comment]
@schoier 

I had this issue for weeks. Both for User Information List, and also for Composed Looks ("Sammansatt Utseende" in swedish). 

Disabling my local language (Swedish) as alternate language solved it immediately, thank you!

**Comment by jimmyalfSoleil** [comment]
Same for me. This issues still exists on 3.4.1812.1

**Comment by patrick-blanc** [comment]
Problem still occured in 3.4.1812.1 on my side.

As explained it here : https://github.com/SharePoint/PnP-PowerShell/issues/1735 it seems to occured when default language set in the provisioning account is different than the default language of the site we want to apply the template.

In our company we have one provisioning account, but site can be created with different default language, this is what occured when you have more than 1 default langauge on your country.

Any update would be appreciate.

**Comment by VesaJuvonen** [comment]
It seems that there has been some underlying oob API change, which might cause this... to be able to however investigate this in detailed, would request exact repro steps with the language scenarios... potentially even a pnp file, which could be used with test tenant to repro the issue.

**Comment by joakimhogberg** [comment]
@VesaJuvonen I got the error this morning on a newly created site (English as default language), with a user profile set to Swedish as language. This didn't happen the first time I provisioned my template, only the second time (no changes to the template were made). After disabling Swedish language as an alternate language, it works again. 

My template only includes 3 fields, 2 lists and 2 content types. That's it. Unfortunatly I can't provide an example template right now.

**Comment by PaoloPia** [comment]
Hi,
Just to let you know that we are working on this issue. We already investigated it, and it came out that it is a server-side issue, but it is easier to work around it in the PnP Core Library rather than on the server-side. Stay tuned and a fix will come out shortly. Thanks!

**Comment by PaoloPia** [comment]
The issue has just been fixed, now the fix will go through automated testing and if the outcome will be positive (tomorrow morning) I will close this item.

**Comment by VesaJuvonen** [comment]
Just to be clear on the situation - we have just released a new version of the NuGet, which should fix this situation. If that's not, however, the case or you see similar issues, please open a new issue, so that we can track the work accordingly. Thanks, everyone for your support and input around this project.

Updated NuGet is already visible in the NuGet gallery - https://www.nuget.org/packages/SharePointPnPCoreOnline/

**Comment by nikolayyordanov** [comment]
> 
> 
> Just to be clear on the situation - we have just released a new version of the NuGet, which should fix this situation. If that's not, however, the case or you see similar issues, please open a new issue, so that we can track the work accordingly. Thanks, everyone for your support and input around this project.
> 
> Updated NuGet is already visible in the NuGet gallery - https://www.nuget.org/packages/SharePointPnPCoreOnline/

For sure this is fixed in the latest SharePointPnPPowerShell version.
