### ISSUE TITLE
Apply-PnPProvisioningTemplate error with PnP PowerShell

### ISSUE THREAD

**Issue by jthin** [SharePoint/PnP-Sites-Core#1948]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Apply a PnP Template to new targeted sites with PnP PowerShell.
PnP PowerShell version : 3.2.1810.0

#### Observed Behavior
Error when trying to apply a PnP template : 

> Apply-PnPProvisioningTemplate : **List 'List Template Gallery' does not exist at site with URL [Url of the targeted site]**

or

> Apply-PnPProvisioningTemplate : **List 'User Information List' does not exist' at site with URL [Url of the targeted site]**

#### Steps to Reproduce
1. Creation of the site template : 
- In Microsoft Teams, create a team without any members.
- When the team is created, go to the SharePoint site related to the team.
- Go to the Home page and edit the Home page (remove the 2 web parts at the top of the page).
- Create a document library. Break security inheritance and give access only to Owner of the site (remove the other SharePoint groups).
- Create the template : `Get-PnPProvisioningTemplate -Out template.xml -Handlers Lists, PageContents`
We only want to apply the "changes" in Home page and create the library for targeted sites.

2. Apply the template to a Targeted site :
- In Microsoft Teams, create a new team without members.
- When the team is created, go to the SharePoint site related to the team.
- Take a 5 minutes break, for real :) **(this is important to reproduce the error)**
- Apply the template : ` Apply-PnPProvisioningTemplate -Path .\template.xml`

For information, if we don't take this 5 minutes break and quickly apply the template, it sometimes works.

**Comment by bjdekker** [comment]
I had the same issue. I have a Dutch communication site. If you connect using Connect-PnPOnline with a user account with the language preference set to English. SharePoint will return the listtitles in English, but requires you pass the Dutch title to the web.Lists.GetByTitle function. 
This goes wrong in the TokenParser, where information about the lists is retrieverd based on the listtitle.
The workaround is to set the language preference of the account you're connecting with to the same language the site you're connected to was created with.

**Comment by jthin** [comment]
Thanks @bjdekker for your help. I have changed the language preference and it works.

**Comment by manoj1201** [comment]
I was also facing similar issue with PnP Provisioning Template. I had Modern Team Site with Spanish Language and Provisioning PnP Schema with English Language,   Later i released the Site Language. As there is no option to change the language. I created new site with English language and Provisioned PnP Schema and Works fine.
