### ISSUE TITLE
AuthenticationManager().GetAppOnlyAuthenticatedContext maximum lease limited to 60 minutes, even if SharePoint allows 8 hours

### ISSUE THREAD

**Issue by koskila** [SharePoint/PnP-Sites-Core#1956]
AuthenticationManager().GetAppOnlyAuthenticatedContext limits token life to 60 minutes (it sets the accesstoken to null after that), even though you might get tokens that are valid for significantly longer. The validity can be between (I think) 1-12 hours, and I think it's depending on the scope and required permissions, so setting the maximum lease to 60 minutes seems a bit limiting.

There have been issues opened about this thing before (like #1758 ), but they seem to focus on the fact that there is a timeout and no refresh tokens (and I don't think refresh tokens are returned for an app authenticating with client id and client secret?), which is only half of the issue. I actually asked about this on Tech Community, but never got any responses:
https://techcommunity.microsoft.com/t5/SharePoint-Developer/Implementing-RefreshToken-for-AuthenticationManager/m-p/128493#M3831

However, **am I missing something obvious here - is there a good reason, why the maximum lease is set to 60 minutes?** AccessToken itself could be valid for 12 hours...

Here's the code:
```
var lease = GetAccessTokenLease(response.ExpiresOn);
lease =
 TimeSpan.FromSeconds(
  Math.Min(lease.TotalSeconds - TimeSpan.FromMinutes(5).TotalSeconds,
  TimeSpan.FromHours(1).TotalSeconds));
```

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When using appregnew.aspx and appinv.aspx to authorize and app to connect to SharePoint Online with just site collection read permission, I'm expecting the token to be valid for 1-12 hours (based on required permissions and scope), but it's always only valid for 60 minutes because of the (kind of smart, but maybe in this case misguided) implementation of AuthenticationManager.

#### Observed Behavior
Access token validity is set to max 60 minutes, after which you start experiencing 401.

#### Steps to Reproduce
Use AuthenticationManager().GetAppOnlyAuthenticatedContext with client id and client secret and try a long-running operation, after 60 minutes it should start returning authentication errors.

#SharingIsCaring

**Comment by jansenbe** [comment]
Fix had been merged, closing this one
