### ISSUE TITLE
DefaultColumnValue has no effect

### ISSUE THREAD

**Issue by schoier** [SharePoint/PnP-Sites-Core#1963]
#### Category
[X ] Bug

#### Environment
[X] Office 365 / SharePoint Online

I'm trying to set a column default value for a folder using DefaultColumnValue. I get no errors applying the template, but there is no column default value for the folder.
<pnp:ListInstance Title="X" OnQuickLaunch="true" TemplateType="101" Url="X" ContentTypesEnabled="true">
<pnp:Folders>
<pnp:Folder Name="Test folder">
<pnp:DefaultColumnValues>
<pnp:DefaultColumnValue Key="testText" Value="lorem" />
</pnp:DefaultColumnValues>
</pnp:Folder>
</pnp:Folders>
</pnp:ListInstance>

I've previously posted about this issue in PnP-Provisioning-Schema, but since I haven't got any replies to that post, I try to post here as well.
[https://github.com/SharePoint/PnP-Provisioning-Schema/issues/344](url)

**Comment by wobba** [comment]
Thank you. @schoier. I’ll try to repro and report back with my findings.

**Comment by Jlopean** [comment]
I also had this issue. i ended up using CSOM
`
var metadataDefaults = new Microsoft.SharePoint.Client.DocumentManagement.MetadataDefaults(context, SPlist);
Microsoft.SharePoint.Client.Folder folder = listToOperate.RootFolder.EnsureFolder("Templates");
                if(folder.Exists)
                {
                    metadataDefaults.SetFieldDefault(folder, "xxx-fieldName", "xxx-defaultValue");
                    metadataDefaults.Update();
                }
`

**Comment by tmeckel** [comment]
Maybe I'm stupid, but the `DefaultColumnValues` are never set because the corresponding extension method is never called internally. Especially not in the class responsible for creating and configuring lists from the provisioning profile

https://github.com/SharePoint/PnP-Sites-Core/blob/4fa4d6a9ab12a8e1c8fbdd811e8ad8817e5741b3/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs#L24

Search:
https://github.com/SharePoint/PnP-Sites-Core/search?utf8=%E2%9C%93&q=SetDefaultColumnValues&type=

**Comment by schoier** [comment]
@tmeckel Thanks for the input!
Can someone give an answer to when this will be implemented?

**Comment by schoier** [comment]
@wobba Any updates on the implementation?

**Comment by wobba** [comment]
@schoier haven't had time to look at this - but we do accept PR's if you have time :)

**Comment by wobba** [comment]
@schoier taking a look right now

**Comment by schoier** [comment]
@wobba I don't know if it's related, but you can take a look at **Set-PnPDefaultColumnValues does not work with nordic letters in -Folder parameter #1706**
Just to make sure we don't get the same problem with this part.

**Comment by wobba** [comment]
It's the same code basically :) Encoding is always an issue it seems.

**Comment by wobba** [comment]
I'll take a look at https://github.com/SharePoint/PnP-PowerShell/issues/1706 while fixing this one.

**Comment by wobba** [comment]
@schoier Default column value support has been added and will be included in next months release.

**Comment by schoier** [comment]
@wobba Great news - thank you!

**Comment by wobba** [comment]
@nigel-dewar which version of PnP PowerShell are you using?

**Comment by offringam** [comment]
Goodmorning, 

Can someone tell me if it's possible to use the </pnp:DefaultColumnValues> element in a xml provisioning template? 

Thx Martin

**Comment by wobba** [comment]
@offringam It should work. If not, please open a new issue and include a sample template and explanation of the type of column etc.
