### ISSUE TITLE
Programatically provisioning custom spfx webpart to classic page on-premises

### ISSUE THREAD

**Issue by JuniorPointer** [SharePoint/PnP-Sites-Core#1969]
#### Category
[ ] Bug
[ ] Enhancement
[x] Question

#### Environment
[ ] Office 365 / SharePoint Online
[x] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Sharepoint 2016 Enterprise Feature Pack 2 August 2018 CU (16.0.4327.1000)
 
#### Expected or Desired Behavior
I need to provision a custom spfx webpart to classic page programatically. As far as i know there are ClientSideWebpart and AvailableClientSideComponents classes that provides desired functionality but they are missing from Pnp Core for on-premises. I have checked page with manually added spfx part using SPLimitedWebPartManager but didn't find anything useful.

Are there any other way to add custom spfx webpart to page? 
Is this even possible?

Thanks in advance!

**Comment by phawrylak** [comment]
I can't check this now, but you should be able to add your webpart in SPFx workbench, click on "Web part data", choose clasic and use this XML in `<pnp:WebPart>` element.

**Comment by JuniorPointer** [comment]
Thanks, I'll check this myself

**Comment by jansenbe** [comment]
Modern pages are not supported on SP2016, hence the API does not work. The approach mentioned by @phawrylak should get you started

**Comment by JuniorPointer** [comment]
@phawrylak  thanks for the tip.
I have got an XML and have tried to add it via ImportWebPart method of SPLimitedWebPartManager - no result, web part adds on page but connect to its properties seems broken.
 
Can you be more specific about <pnp:WebPart> element? I coudn't find any information about this - some link to tutorial will be appreciated

**Comment by gautamdsheth** [comment]
@JuniorPointer - i have written a [blog post](https://gautamdsheth.wordpress.com/2018/10/15/adding-modern-webparts-to-classic-pages-using-pnp-powershell/) few days back which you can refer to. It basically provisions OOTB modern webparts, but it will work for custom SPFx webparts as well.

**Comment by jansenbe** [comment]
Nice blog @gautamdsheth!

**Comment by JuniorPointer** [comment]
it seems WebPartEntity (and its WebpartXml property) and AddWebPartToWikiPage do the trick.

Thanks
