### ISSUE TITLE
link is missing in quicklink webpart while copying modern page

### ISSUE THREAD

**Issue by ParvathySN** [SharePoint/PnP-Sites-Core#1973]
Link is missing in quick link webpart after copying modern page

**Comment by jansenbe** [comment]
How did you copy the modern page? Did you copy across site collections?

**Comment by ParvathySN** [comment]
Yes.Using ClientSidePage AddControl method.

**Comment by ParvathySN** [comment]
> How did you copy the modern page? Did you copy across site collections?

Yes.Using ClientSidePage AddControl method.

**Comment by ParvathySN** [comment]
This is working now.
