### ISSUE TITLE
Apply-pnpProvisioningTemplate with JSLink values in Lists works with POSH but not in C# 

### ISSUE THREAD

**Issue by MattPPMConsultant** [SharePoint/PnP-Sites-Core#1984]
#### Category
[x ] Bug

#### Environment
x] Office 365 / SharePoint Online

Apologies, originally raised the issue here but can't move it:

[https://github.com/SharePoint/PnP-Provisioning-Schema/issues/349#issue-381206091]

Recently we have needed to add JSLink values to a number of views in a site template. This worked successfully when testing and developing using Powershell to apply the template. However, when the template is ran with our azure web app provisioning engine the application of the template fails. We have ensured that the Web app is using the latest version of the NuGet Pnp Core package.

In testing we found that any value in the parameters caused it to fail. Detailed error below but it appears to point to:
SetJSLinkCustomizations(List list, String serverRelativeUrl, String jslink)

Template snippet:

<pnp:Lists>	
<pnp:ListInstance Title="Risks" Description="" DocumentTemplate="" TemplateType="1101" Url="Lists/Risks" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="448e1394-5e76-44b4-9e1c-169b7a389a1b" ContentTypesEnabled="true" EnableFolderCreation="false"> <pnp:ContentTypeBindings> <pnp:ContentTypeBinding ContentTypeID="0x0100303829CD090A794EA6479FA418DE845F" Default="true" /> </pnp:ContentTypeBindings> <pnp:Views> <View Name="{BD974A72-16FB-436D-AF50-9363CF0552E8}" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Items" Url="{site}/Lists/Risks/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/pwsrisks.png?rev=44"> <Query> <OrderBy> <FieldRef Name="ID" /> </OrderBy> </Query> <ViewFields> <FieldRef Name="Attachments" /> <FieldRef Name="ID" /> <FieldRef Name="LinkTitle" /> <FieldRef Name="RiskDescription" /> <FieldRef Name="DateRiskRaised" /> <FieldRef Name="RiskConsequence" /> <FieldRef Name="Owner" /> <FieldRef Name="RiskProbability" /> <FieldRef Name="RiskImpact" /> <FieldRef Name="RiskPriority" /> <FieldRef Name="ActionPlan" /> <FieldRef Name="AssignedTo" /> <FieldRef Name="Status" /> <FieldRef Name="DueDate" /> <FieldRef Name="ResolutionDate" /> <FieldRef Name="RiskCategory" /> <FieldRef Name="Level" /> <FieldRef Name="Highlight" /> <FieldRef Name="Cost" /> </ViewFields> <RowLimit Paged="TRUE">30</RowLimit> <Aggregations Value="On"> <FieldRef Name="ID" Type="COUNT" /> </Aggregations> <JSLink>~sitecollection/_catalogs/masterpage/RiskRAGIndicatorDisplayTemplate.js</JSLink> <Toolbar Type="Standard"/> </View> 
</pnp:ListInstance> 
</pnp:Lists>

Error message:

ExceptionMessage | Exception has been thrown by the target of an invocation.

ExceptionStackTrace | at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream) at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse() at Microsoft.SharePoint.Client.ClientRequest.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRequest.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRuntimeContext.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContext.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContextExtensions.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent) at Microsoft.SharePoint.Client.ListExtensions.SetJSLinkCustomizationsImplementation(List list, File file, String jslink) at Microsoft.SharePoint.Client.ListExtensions.SetJSLinkCustomizations(List list, String serverRelativeUrl, String jslink) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateView(Web web, View view, ViewCollection existingViews, List createdList, PnPMonitoredScope monitoredScope, TokenParser parser, Int32 currentViewIndex, Int32 total) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProcessViews(Web web, TokenParser parser, PnPMonitoredScope scope, ListInfo listInfo) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)

Anyone have any ideas?

**Comment by MattPPMConsultant** [comment]
We've worked this out, It worked in a C consle app but our Web app wasn't quire using the right context and it was causing the error.

**Comment by VesaJuvonen** [comment]
Thanks for following up and providing the answer, appreciated.
