### ISSUE TITLE
UnifiedGroupsUtility.CreateUnifiedGroup: set group's owners and members in single API call to avoid "Resource provisioning is in progress. Please try again" error

### ISSUE THREAD

**Issue by sadomovalex** [SharePoint/PnP-Sites-Core#1987]
#### Category
[ ] Bug
[ x] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When you use UnifiedGroupsUtility.CreateUnifiedGroup for creating groups you may face with the following error:
```
{
"error": {
"code": "ResourceNotFound",
"message": "Resource provisioning is in progress. Please try again.",
"innerError": {
"request-id": "...",
"date": "..."
}
}
}
```

This issue is reported here: [After office 365 group is created, the group site provisioning is pending](https://github.com/microsoftgraph/microsoft-graph-docs/issues/631). Investigation showed that it is caused by the way how groups are created: at first group is created without owners/members and then owners and members are added using UpdateOwners/UpdateMembers methods with separate API calls. When we created support ticket in MS we got the following response of why we should not use PnP solution:

> "The PnP solution is not suggested because it specifically does not pass the owners to the Graph API when creating a group. If you first create the group and then add the owners then the guidelines are not being followed. The scenario is supported as long as the time the group is created at least one owner is provided."

In order to create groups with owners/members with single API call REST may be used with OData binding syntax (see [Create a Group in Microsoft Graph API with a Owner](https://stackoverflow.com/questions/46467617/create-a-group-in-microsoft-graph-api-with-a-owner/53432166)):
```
  "owners@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/{id1}"
  ],
  "members@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/{id1}",
    "https://graph.microsoft.com/v1.0/users/{id2}"
  ]
```

This solution also can be used with Graph API .Net client library. We need to create new class which extends Group class:
```
public class GroupExtended : Group
{
    [JsonProperty("owners@odata.bind", NullValueHandling = NullValueHandling.Ignore)]
    public string[] OwnersODataBind { get; set; }
    [JsonProperty("members@odata.bind", NullValueHandling = NullValueHandling.Ignore)]
    public string[] MembersODataBind { get; set; }
}
```
and then add groups with owners and members with single API call like that:
```
var newGroup = new GroupExtended
{
    DisplayName = displayName,
    Description = description,
    MailNickname = mailNickname,
    MailEnabled = true,
    SecurityEnabled = false,
    Visibility = isPrivate == true ? "Private" : "Public",
    GroupTypes = new List<string> { "Unified" }
};

if (owners != null && owners.Length > 0)
{
    var users = GetUsers(graphClient, owners);
    if (users != null)
    {
        newGroup.OwnersODataBind = users.Select(u => string.Format("https://graph.microsoft.com/v1.0/users/{0}", u.Id)).ToArray();
    }
}

if (members != null && members.Length > 0)
{
    var users = GetUsers(graphClient, members);
    if (users != null)
    {
        newGroup.MembersODataBind = users.Select(u => string.Format("https://graph.microsoft.com/v1.0/users/{0}", u.Id)).ToArray();
    }
}

await graphClient.Groups.Request().AddAsync(newGroup);
...

private static List<User> GetUsers(GraphServiceClient graphClient, string[] owners)
{
 if (owners == null)
 {
  return new List<User>();
 }
 var result = Task.Run(async () =>
 {
  var usersResult = new List<User>();
  var users = await graphClient.Users.Request().GetAsync();
  while (users.Count > 0)
  {
   foreach (var u in users)
   {
    if (owners.Any(o => u.UserPrincipalName.ToLower().Contains(o.ToLower())))
    {
     usersResult.Add(u);
    }
   }
 
   if (users.NextPageRequest != null)
   {
    users = await users.NextPageRequest.GetAsync();
   }
   else
   {
    break;
   }
  }
 
  return usersResult;
 }).GetAwaiter().GetResult();
 return result;
}
```
As result group will be created with owners/members with single API call and will allow to avoid "Resource provisioning is in progress. Please try again" error.

**Comment by wobba** [comment]
@sadomovalex Feel free to create a PR for this one, and have been thinking about this myself as well.

**Comment by gautamdsheth** [comment]
@sadomovalex and @wobba - if you guys don't mind, can i pick this up ? I do have the time to test and debug this :) Also, now that teams API is in GA, can i add the ability to provision MS Teams team post group provisioning ? It will be optional and will be false by default, something like below. I will create the necessary methods for that implementation as well.

`CreateUnifiedGroup(string displayName, string description, string mailNickname,
            string accessToken, string[] owners = null, string[] members = null, Stream groupLogo = null,
            bool isPrivate = false, bool provisionTeam = false , int retryCount = 10, int delay = 500)`

Let me know your thoughts on this :) !
Cheers,
Gautam

**Comment by wobba** [comment]
@erwinvanhunen @PaoloPia you guys ok with adding Teams support? I say it's ok until we rework things.

**Comment by sadomovalex** [comment]
Hello, I've created PR for this feature: https://github.com/SharePoint/PnP-Sites-Core/pull/1991.

**Comment by wobba** [comment]
@gautamdsheth and @sadomovalex I will try to get this processed over the weekend, and pick and choose from both PR's :)

**Comment by smushkat** [comment]
Hello - I'm trying this feature out but am getting an error when I call CreateUnifiedGroup with a list of owners. I set up a C# string array:

string[] ownerNames = new string[2];
ownerNames[0] = "owner1@mytenant.onmicrosoft.com";
ownerNames[1] = "owner2@mytenant.onmicrosoft.com";

var group = UnifiedGroupsUtulity.CreateUnifiedGroup("Group1", "Descr", "Group1", accesstoken, owners: ownerNames)

which comes back with the exception:
"Code: Request_BadRequest\r\nMessage: The value of 'odata.bind' property annotation is an empty array. The 'odata.bind' property annotation must have a non-empty array as its value.\r\n\r\nInner error\r\n"

The users I'm supplying are valid users.

Works great otherwise - creating the team, setting public/private, and setting the site logo. Much appreciated!

Thanks!
Steve

**Comment by wobba** [comment]
@smushkat One, if you query graph directly and filter with user Principal Name does that work? Two, please open a new issue instead of commenting on a closed non-related issue so we can track issues more easily.

**Comment by smushkat** [comment]
@wobba yes, direct query worked - will do, opening up a new issue.  Thanks!
