### ISSUE TITLE
PnP Template: Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by blair24** [SharePoint/PnP-Sites-Core#2009]
**Which PnP repository should you use to report the issue**
PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

**Category**
[X ] Bug

**Environment**
[ X] Office 365 / SharePoint Online

***Expected or Desired Behavior***
Retrieve a .pnp template from a SharePoint Online Modern Team Site.

***Observed Behavior***
When running the command below an error is received. Changing -ExcludeHandlers to 'all' the template completes fine.

`Get-PnPProvisioningTemplate -Out C:\Users\***\Desktop\Test.pnp -PersistBrandingFiles -Handlers All`

Error:
`Get-PnPProvisioningTemplate : Object reference not set to an instance of an object.`

***Steps to Reproduce***
Same site replicated on a SharePoint Online Classic Team site works as expected - there is no difference in: Security/Permissions, Lists, Content Types, Managed Metadata.

**Comment by jimmywim** [comment]
@blair24 Unable to reproduce on SharePointPnPPowerShellOnline 3.4.1812.2. What version do you have loaded?

**Comment by blair24** [comment]
@jimmywim looks like version 3.4.1812.2 fixed the issue, was using 3.3.1811.0 before 👍
