### ISSUE TITLE
New throttling guidance is not correctly implemented in OfficeDevPnP

### ISSUE THREAD

**Issue by SchauDK** [SharePoint/PnP-Sites-Core#2014]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
According to the new throttling guidance, we should read the "Retry-After" response header and use that for backing off before retrying a request.

In the OfficeDevPnP ExecuteQueryImplementation the Retry-After value of 120 is assigned the retryAfterInterval. This means that the thread will sleep 120ms instead of 120 seconds.
For each retry (default 10) the backoff interval will not increase.

I think you should revert back to use the "old" backoff structrure starting at 500ms and multiplying by 2 for each iteration. Waiting 2 minutes between each retry doesn't make sense, if this was the intention of the guidance change (besides using RetryQuery).

**Comment by jansenbe** [comment]
Hi @SchauDK ,

The recommendation is to use the wait time provided by the service... the service should increase the wait time if needed. Do you see failures after being throttled with the returned timeout for max 10 times?

**Comment by SchauDK** [comment]
Hi @jansenbe 

The Retry-After value is 120 (**in seconds**).
The Thread.Sleep(120) waits 120 milliseconds. I don't believe this is the intention??

Secondly, the Retry-After value will never change. At least I have never seen a value different from the default 120. 

So, in my case it is retrying 10 times and only waiting 120ms between the retries.

**Comment by jansenbe** [comment]
If the retry-after is never changing then this indeed is not good. I'll check that first.

**Comment by jansenbe** [comment]
Did talk with our devs and the header indeed is in seconds, I made a mistake with that one and will adjust

**Comment by jansenbe** [comment]
Adjusted. Let me know if you're ok with closing the issue?

**Comment by SchauDK** [comment]
I've reviewed your change.
There's a lot of code out there depending on this OfficeDevPnP library, so I think it's dangerous to change the delay parameter from milliseconds to seconds. If someone is using this parameter, the delay could potentially be VERY long.
Also, even though the official guidance says to use the response header (which is 120 seconds), I still think that this delay between each retry is long. I'd rather still use incremental delays. 500ms, 1000ms, 2000ms, 4000ms, 8000ms etc.

You also need to change the Log.Warning to log the correct backoffInterval.

FYI, the Retry-After value isn't something that will change depending on load on the SharePoint tenant. Maybe someone from the SharePoint Product team can elaborate on this and explain why it is always 120 seconds.

**Comment by jansenbe** [comment]
Fair feedback. Received more feedback and there's different places in SPO where the retry-header is set and some should adjust the default 120...some don't...but agree with you that 120 seconds is really long if we're not dynamically adjusting. On the other hand being throttled most likely will also not be resolved in 500ms. If we would assume 10x120 seconds for a static retry-after header we end up with 1200 seconds before failure. If we would flip back to our old model but use 1 second to start (iso 0,5) we would up end up with 1023 seconds before failure...The waits between our last 3 retries would then have a wait time over 120 seconds, so compliant with the header. Thoughts?

**Comment by SchauDK** [comment]
Thanks @jansenbe. Sounds good.

Would it be possible to get more information about where the Retry-After header is fixed and where it is adjusted?

**Comment by jansenbe** [comment]
I'll see if I can find something that can be shared. In the meanwhile, I'll close this issue.

**Comment by jansenbe** [comment]
Was thinking about this and realized that changing to see timeout in seconds instead of milliseconds was bad as folks could have been using the method with custom timeouts specified in milliseconds. I now reverted back to the original system...so exactly what you were proposing :-) Sorry for all the hassle.
