### ISSUE TITLE
Get-PnPProvisioningTemplate : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by suz7777** [SharePoint/PnP-Sites-Core#2024]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
```
Get-Module | Select-Object name,version

Name                                   Version    
----                                   -------    
Microsoft.Online.SharePoint.PowerShell 16.0.8316.0
Sharegate                              9.0.2.0    
SharePointPnPPowerShellOnline          3.4.1812.2 
```

#### Expected or Desired Behavior
--create a new site with powershell (communications site)
--modify the home page - or any page - change the zone columns, add a few OOB web parts like sites and documents.
--run the following command to get a provisioning template.
**`Get-PnPProvisioningTemplate -Out $templatefile -ExcludeContentTypesFromSyndication #-IncludeAllTermGroups`** 

#### Observed Behavior
**create a site**
```
**`New-PnPSite -Type CommunicationSite -Title "IW Hub Site" -Url $hubUrl
$newPage=Add-PnPClientSidePage -Name "IW-Home" -CommentsEnabled:$false -Publish:$true 
$newPage=Add-PnPClientSidePage -Name "IW-File-Upload" -CommentsEnabled:$false -Publish:$true 
$p=Get-PnPClientSidePage -Identity IW-File-Upload                                        
$p.set_PageTitle("IW File Upload")                                                       
$p.Publish()                                                                                   

Register-SPOHubSite -Site $hubUrl -Principals $null

NOTE: this runs fine...
Get-PnPProvisioningTemplate -Out $templatefile -ExcludeContentTypesFromSyndication #-IncludeAllTermGroups
 `**
```

**next steps**

- Modify the home page - or any page - adding columns OOB web parts, etc.
- attempt to re-execute the get template command
`Get-PnPProvisioningTemplate -Out $templatefile -ExcludeContentTypesFromSyndication #-IncludeAllTermGroups`

**error:**
```
Get-PnPProvisioningTemplate : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-PnPProvisioningTemplate -Out $templatefile -ExcludeContentTypesFr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProvisioningTemplate], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioning 
   Template
```

tracelog
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:33.7270	[Extraction]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:33.7290	[Extraction]	[77]	[Debug]	Base template available: SITEPAGEPUBLISHING0template	1ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:33.7295	[Extraction]	[77]	[Debug]	ProgressDelegate registered	2ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:33.7295	[Extraction]	[77]	[Debug]	MessagesDelegate registered	2ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.2515	[Regional Settings]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.3526	[Regional Settings]	[77]	[Debug]	Code execution scope ended	101ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.3536	[Supported UI Languages]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.4537	[Supported UI Languages]	[77]	[Debug]	Code execution scope ended	100ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.4557	[Audit Settings]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.5457	[Audit Settings]	[77]	[Debug]	Code execution scope ended	89ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.5457	[Site Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9316	[Site Security]	[77]	[Debug]	Skipping OOTB role definition Full Control	385ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9316	[Site Security]	[77]	[Debug]	Skipping OOTB role definition Design	385ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9316	[Site Security]	[77]	[Debug]	Skipping OOTB role definition Edit	385ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9316	[Site Security]	[77]	[Debug]	Skipping OOTB role definition Contribute	385ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9316	[Site Security]	[77]	[Debug]	Skipping OOTB role definition Read	385ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9316	[Site Security]	[77]	[Debug]	Skipping OOTB role definition Limited Access	385ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9841	[Site Security]	[77]	[Debug]	Processing Role Assignment Microsoft.SharePoint.Client.RoleAssignment	437ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9841	[Site Security]	[77]	[Debug]	Processing Role Assignment Microsoft.SharePoint.Client.RoleAssignment	438ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9841	[Site Security]	[77]	[Debug]	Processing Role Assignment Microsoft.SharePoint.Client.RoleAssignment	438ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9841	[Site Security]	[77]	[Debug]	Processing Role Assignment Microsoft.SharePoint.Client.RoleAssignment	438ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9841	[Site Security]	[77]	[Debug]	Code execution scope ended	438ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:34.9841	[Fields]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.0218	[Fields]	[77]	[Debug]	Code execution scope ended	3036ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.0413	[Content Types]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.5701	[Content Types]	[77]	[Information]	Content type DWP_Terms excluded from export because it's a syndicated content type.	529ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.5821	[Content Types]	[77]	[Information]	Content type 3M-Important-Links excluded from export because it's a syndicated content type.	540ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.5911	[Content Types]	[77]	[Information]	Content type 3M-Windows-Links excluded from export because it's a syndicated content type.	550ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.6201	[Content Types]	[77]	[Information]	Content type 3M-Document excluded from export because it's a syndicated content type.	578ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.6226	[Content Types]	[77]	[Information]	Content type 3M-Document-LegalERM excluded from export because it's a syndicated content type.	581ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.6612	[Content Types]	[77]	[Information]	Content type 3M-Site-MetaData-Page excluded from export because it's a syndicated content type.	620ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.6632	[Content Types]	[77]	[Information]	Content type 3MWikiPage excluded from export because it's a syndicated content type.	622ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.6952	[Content Types]	[77]	[Information]	Content type Workflow Task (SharePoint 2013) excluded from export because it's a syndicated content type.	654ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.7172	[Content Types]	[77]	[Information]	Content type 3M_Folder excluded from export because it's a syndicated content type.	676ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.7192	[Content Types]	[77]	[Information]	Content type 3M_Folder_LegalERM excluded from export because it's a syndicated content type.	677ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.7432	[Content Types]	[77]	[Debug]	Adding content type to template: 0x0108003365C4474CAE8C42BCE396314E88E51F - Workflow Task (SharePoint 2013)	702ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.7432	[Content Types]	[77]	[Debug]	Code execution scope ended	702ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:38.7762	[List instances]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:43.7897	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:43.8938	[Get Security]	[77]	[Debug]	Code execution scope ended	103ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:43.8948	[List instances]	[77]	[Debug]	Adding list: Apps for SharePoint - AppCatalog	5117ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:45.4342	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:45.5062	[Get Security]	[77]	[Debug]	Code execution scope ended	72ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:45.5072	[List instances]	[77]	[Debug]	Adding list: Documents - Shared Documents	6730ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:46.6483	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:46.7364	[Get Security]	[77]	[Debug]	Code execution scope ended	87ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:46.7393	[List instances]	[77]	[Debug]	Adding list: Events - Lists/Events	7962ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:48.7035	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:48.8075	[Get Security]	[77]	[Debug]	Code execution scope ended	103ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:48.8095	[List instances]	[77]	[Debug]	Adding list: Form Templates - FormServerTemplates	10032ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:50.1993	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:50.2983	[Get Security]	[77]	[Debug]	Code execution scope ended	98ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:50.2983	[List instances]	[77]	[Debug]	Adding list: Site Assets - SiteAssets	11521ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:52.8854	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:52.9755	[Get Security]	[77]	[Debug]	Code execution scope ended	90ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:52.9765	[List instances]	[77]	[Debug]	Adding list: Site Pages - SitePages	14199ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.3742	[Get Security]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.4553	[Get Security]	[77]	[Debug]	Code execution scope ended	81ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.4563	[List instances]	[77]	[Debug]	Adding list: Style Library - Style Library	15679ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.4563	[List instances]	[77]	[Debug]	Code execution scope ended	15679ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.4843	[Features]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.6784	[Features]	[77]	[Debug]	Code execution scope ended	193ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.6784	[Page Contents]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.8496	[Page Contents]	[77]	[Debug]	Code execution scope ended	170ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:54.8506	[Client Side Page Contents]	[77]	[Debug]	Code execution scope started	0ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:55.1497	[Client Side Page Contents]	[77]	[Debug]	Code execution scope ended	299ms	caba7f88-1133-4526-9077-1bf7db698547
ScriptEditor.exe Information: 0 : 2018-12-27 16:24:55.1497	[Extraction]	[77]	[Debug]	Code execution scope ended	21422ms	caba7f88-1133-4526-9077-1bf7db698547

**Comment by suz7777** [comment]
not sure what happened today - seems like i can't reproduce this behavior... I will watch it closely for a day or so and close if not an issue.

**Comment by erwinvanhunen** [comment]
I followed the exact scenario as described above on a targeted release tenant, but cannot reproduce the issue with the latest (upcoming) build. If possible, can you try to reproduce the issue and the moment it occurs enter:

```powershell
Get-PnPException
```

And paste the result of that cmdlet her? It shows in more detail what where goes wrong.

**Comment by erwinvanhunen** [comment]
short update: we did more testing and this issue has been fixed in the latest December release. We were able to reproduce it in the November release and we did an intermediate release in December to fix this. I will close this issue, but if you feel the issue is still present, do not hesitate to reopen it.
