### ISSUE TITLE
Get-PnPClientSidePage null reference error

### ISSUE THREAD

**Issue by jesseve** [SharePoint/PnP-Sites-Core#2029]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I have two SharePoint Online tenants, one with tenant language set to english and the other is finnish. I am trying to get the home page of a site using Get-PnPClientSidePage and it works fine in the english tenant. The finnish tenant gives this error message when the command is executed: Get-PnPClientSidePage : Object reference not set to an instance of an object.

And here is the code I have executed.
`Connect-PnPOnline -Url "https://$tenant.sharepoint.com/sites/mysite/mysubsite/"

$pageName = "Home"
$page = Get-PnPClientSidePage $pageName`

I've made sure the Connect command has been successful and both tenants have the site I try to connect to. Also I checked that the page is not checked out to any user and it is published. I tried to get the home page from multiple sites but all of them gave the same error in the finnish tenant.

**Comment by GeoffE1e6** [comment]
+1

If you add a new page using Add-pnpClientSidePage, then immediately edit and save without changes, you will get Object reference not set to an instance of an object.

Version is: SharePointPnPPowerShellOnline 3.6.1902.2

Add-PnPClientSidePage  -Name “Home Page1” -LayoutType Home


PageTitle           :
Sections            : {}
Controls            : {}
LayoutType          : Home
KeepDefaultWebParts : False
Context             : OfficeDevPnP.Core.PnPClientContext
PagesLibrary        : SitePages
PageListItem        : Microsoft.SharePoint.Client.ListItem
DefaultSection      : OfficeDevPnP.Core.Pages.CanvasSection
CommentsDisabled    : False



Get-PnPClientSidePage -Web $web -Identity "Home Page1.aspx"
Get-PnPClientSidePage : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-PnPClientSidePage -Web $web -Identity "Home Page1.aspx"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPClientSidePage], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.GetClientSidePage

However, if you create the page, then immediately Get it there are no problems.
Add-PnPClientSidePage  -Name “Home Page1” -LayoutType Home
PageTitle           :
Sections            : {}
Controls            : {}
LayoutType          : Home
KeepDefaultWebParts : False
Context             : OfficeDevPnP.Core.PnPClientContext
PagesLibrary        : SitePages
PageListItem        : Microsoft.SharePoint.Client.ListItem
DefaultSection      : OfficeDevPnP.Core.Pages.CanvasSection
CommentsDisabled    : False

Get-PnPClientSidePage -Web $web -Identity "Home Page2.aspx"
PageTitle           : Home Page2
Sections            : {}
Controls            : {}
LayoutType          : Home
KeepDefaultWebParts : False
Context             : OfficeDevPnP.Core.PnPClientContext
PagesLibrary        : SitePages
PageListItem        : Microsoft.SharePoint.Client.ListItem
DefaultSection      : OfficeDevPnP.Core.Pages.CanvasSection
CommentsDisabled    : False

This is also refered in this
https://github.com/SharePoint/PnP-PowerShell/issues/1801

Presumably this was supposed to fixed - can anyone please advise?

Thanks

**Comment by rwytrwal** [comment]
+1 
Same problem as @GeoffE1e6 describe, even if you edit and save.

**Comment by niravnvs** [comment]
Same issue I am facing as well. This happens with get-PnpPage, PnpPageComponents

**Comment by PowershellNinja** [comment]
+1
Having the same Issue, but with Add-PnPClientSidePage, using version 3.7.1903.0 of the module.
Is there an update to this?

**Comment by jesseve** [comment]
I noticed that my version of SharePointPnPPowerShellOnline was <3.6.1902.2 (Not sure what it was because I checked it a few weeks ago). I updated the module to 3.7.1903.0 and the Get-PnPClientSidePage command works fine in all tenants I am using. 

@PowershellNinja I tried the Add-PnPClientSidePage command too and it worked.
