### ISSUE TITLE
Are tokens like ~site no longer allowed

### ISSUE THREAD

**Issue by waaromikniet** [SharePoint/PnP-Sites-Core#2034]
#### Category
[ ] Bug
[ ] Enhancement
[x] Question

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: Any

#### Expected or Desired Behavior
Be able to use ~site

#### Observed Behavior
I updated to the latest version of PnP-Sites Core and in one of my templates I provision a list form with this line:

<pnp:File Folder="~site/Lists/Special" Level="Published" Overwrite="true" 
Src="lists/Special/Form.aspx" TargetFileName="DispForm.aspx" />

With my old version I can deploy this template. With the new version I have to replace ~site with {site}
I can't find this in the change log. Was this removed from the current version?

#### Steps to Reproduce
Deploy a template with a listinstance containing

<pnp:File Folder="~site/Lists/Special" Level="Published" Overwrite="true" 
Src="lists/Special/Form.aspx" TargetFileName="DispForm.aspx" />

**Comment by jansenbe** [comment]
Yes, this was removed several months ago due to performance optimizations done in the tokenparser. The workaround is replace the ~tokens in your template(s).
