### ISSUE TITLE
After updating, ApplyProvisioningTemplate takes twice as long to complete

### ISSUE THREAD

**Issue by imthecritic** [SharePoint/PnP-Sites-Core#2053]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[X] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Security Update for Microsoft SharePoint Enterprise Server 2016 (KB4018340) 64-Bit Edition 16.0.4351.1000 Installed

#### Expected or Desired Behavior
Application of a provisioning template should take less or the same amount of time.

#### Observed Behavior

We currently have a provisioning template with about 20 lists, with 12-30 fields in each list, and multiple views. In the past we have been able to create a new site and apply the provisioning template in 25 minutes. 

Since upgrading from version 2.23.1802.0 to version 3.4.1812.1 of SharePointPnPCore2016, applying the provisioning template takes 50 minutes to complete. 

We have noticed the list instances now take 3 times longer. On the previous version a list with 26 fields took 15 seconds, after the update the list takes  45 seconds. 

Is there anything we can do to speed up the lists provisioning?

#### Steps to Reproduce
Apply a provisioning template created and applied using version 2.23.1802.0, apply a provisioning template created and applied using version 3.4.1812.1, and compare the performance.

**Comment by erwinvanhunen** [comment]
Hi,

Indeed, the speed of provisioning a site has slowed down when compared to the 1802 version (February 2018). The December 2018 (version 3.4.1812.1) version has much more functionality and we also made a change to the handling of lists, both which are slowing down the engine when compared to older builds. We changed the handling of lists to ensure that all fields/views/contenttypes where correctly associated with the lists being provisioned as in some scenarios this was not done correctly. There is unfortunately not much we can do about that at this time. 

We are on a daily basis improving the functionality of the PnP Provisioning Engine, and that includes performance tweaks where possible. A slowing factor is the handling of tokens in the engine. When you export a template you'll notice that we add {tokens} to the template. At provisioning time those tokens are then translated back to the actual value. At initialization time of the provisioning engine we build a dictionary of those tokens that we use during the provisioning run. This part is slow, and among others depending on the complexity of the farm. The more artifacts already present in a site (content types, fields, taxonony terms, etc.) the slower it will be to apply a template. We are aware of this and we are prototyping a change in the way the token parser is being used which should seriously increase the performance of the engine.

My advice right now: only provisiong those artifacts that you really want to provision, e.g. clean up your templates and remove any redudant artifacts (e.g. artifacts that are already present and will only be applied again): we compare artifacts in a template with those already present to see if things need to be updated. This process will slow down a provisioning run too.

I will close this issue as we unfortunately cannot do much about your issue right now. Please keep an eye on future releases of the provisioning engine.

/Erwin
