### ISSUE TITLE
Create ClientSidePage with double quotes in Title generates wrong LayoutWebpartsContent

### ISSUE THREAD

**Issue by RobinAgten** [SharePoint/PnP-Sites-Core#2058]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When a page is created using the Web.AddClientSidePage() method and the title of the page contains double quotes, the page property 'LayoutWebpartsContent' should be correctly formatted

#### Observed Behavior
When a page is created using the Web.AddClientSidePage() method and the page title is set to a title with double quotes, the page listitem field 'LayoutWebpartsContent' is not correct. the JSON of the data-sp-controldata is not formatted correctly. It ends with the first double qoute of the page title.

This is what I should expect for the value of ClientSidePage.PageListItem["LayoutWebpartsContent"]: 
`<div><div data-sp-canvascontrol="" data-sp-canvasdataversion="1.4" data-sp-controldata="&#123;&quot;id&quot;&#58;&quot;cbe7b0a9-3504-44dd-a3a3-0e5cacd07788&quot;,&quot;instanceId&quot;&#58;&quot;cbe7b0a9-3504-44dd-a3a3-0e5cacd07788&quot;,&quot;title&quot;&#58;&quot;Title Region&quot;,&quot;description&quot;&#58;&quot;Title Region Description&quot;,&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1.4&quot;,&quot;properties&quot;&#58;&#123;&quot;title&quot;&#58;&quot;\&quot;Double Quotes\&quot;&quot;,&quot;imageSourceType&quot;&#58;4,&quot;layoutType&quot;&#58;&quot;FullWidthImage&quot;,&quot;textAlignment&quot;&#58;&quot;Left&quot;,&quot;showTopicHeader&quot;&#58;false,&quot;showPublishDate&quot;&#58;false,&quot;topicHeader&quot;&#58;&quot;&quot;,&quot;authorByline&quot;&#58;[&quot;agtenr@agtenrdev.onmicrosoft.com&quot;],&quot;authors&quot;&#58;[]&#125;&#125;"></div></div>`
And this is what I observe:
`<div><div data-sp-canvascontrol="" data-sp-canvasdataversion="1.4" data-sp-controldata="&#123;&quot;id&quot;&#58;&quot;cbe7b0a9-3504-44dd-a3a3-0e5cacd07788&quot;,&quot;instanceId&quot;&#58;&quot;cbe7b0a9-3504-44dd-a3a3-0e5cacd07788&quot;,&quot;title&quot;&#58;&quot;Title Region&quot;,&quot;description&quot;&#58;&quot;Title Region Description&quot;,&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1.4&quot;,&quot;properties&quot;&#58;&#123;&quot;title&quot;&#58;&quot;"></div></div>`

You can see that the JSON value of the 'data-sp-controldata' is wrongly formatted and is cut of at the first ".

#### Steps to Reproduce

1. Create a ClientSidePage using the Web.AddClientSidePage method
2. Update the PageTitle property of the ClientSidePage object with a string with double quotes
3. Save the ClientSidePage Object
4. Observe the value of the PageListItem["LayoutWebpartsContent"] property of the ClientSidePage

`var pageName = "TestDoubleQuotes.aspx";`
`var pageTitle = "\"Double Quotes\"";`
`var newPage = clientContext.Web.AddClientSidePage(pageName, true);`
`newPage.PageTitle = pageTitle;`
`newPage.Save();`
`Console.WriteLine(newPage.PageListItem["LayoutWebpartsContent"]);`

**Comment by jansenbe** [comment]
Hey @RobinAgten ,

A fix has been checked in the dev branch. Will be part of the March drop.
