### ISSUE TITLE
Can we run provision the site using the old template with the new engine?

### ISSUE THREAD

**Issue by Ravikadri** [SharePoint/PnP-Sites-Core#2063]
This may be a very basic question. Is it possible to provision a  site with the latest PnP engine where the template is created using old version of the PnP?  

Below is the template (scheme version 2016/05) and I want to use the latest PnP engine(2018/07) while provisioning the site? Is it backward compatible? If not what are the options we have for the old template.

![image](https://user-images.githubusercontent.com/9435596/51768468-44eb5480-2095-11e9-9473-0f17c6e36b6c.png)

**Comment by VesaJuvonen** [comment]
The engine is by default backward compatible and old templates should work without any issues. There might be however some SharePoint related changes, which could cause challenges. If you have issues with the old templates, please do share details in a new issue. Thx.
