### ISSUE TITLE
OfficeDevPnP.Core.Pages.DefaultClientSideWebParts does not include all webparts available OOB

### ISSUE THREAD

**Issue by JMyner** [SharePoint/PnP-Sites-Core#2072]
#### Category
Enhancement

#### Environment
[ ] Office 365 / SharePoint Online

#### Expected or Desired Behavior
OfficeDevPnP.Core.Pages.DefaultClientSideWebParts does not include all of the webparts which are now available OOB.

Expected behaviour would be to include all of the OOB webparts, at the moment it only includes ThirdParty, ContentRollup, BingMap, ContentEmbed, DocumentEmbed, Image, ImageGallery, LinkPreview, NewsFeed, NewsReel, PowerBIReportEmbed, QuickChart, SiteActivity, VideoEmbed, 
YammerEmbed, Events, GroupCalendar, Hero, List, PageTitle, People, QuickLinks, CustomMessageRegion, Divider, MicrosoftForms, Spacer, ClientWebPart, PowerApps

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

**Comment by jansenbe** [comment]
Hey @JMyner, which web parts are you missing? 

You can always handle the missing web parts as "custom" and used them like that. Does require that you grab the ID for the OOB web part, but besides that things should give you the same end result.

**Comment by JMyner** [comment]
Couple off the top of my head were recent documents and weather although i'm not sure that's all.

No problem, i'm doing that for now, just expected them to be on the default web part list.

**Comment by jansenbe** [comment]
Hi @JMyner ,

Did check this and actually I did add the new web parts on Jan 9th (see https://github.com/SharePoint/PnP-Sites-Core/commit/8d1b8ec8f3facba9df0a5e9403e239a9aed69453). Might be that you were looking on an older version of the source.
