### ISSUE TITLE
TokenParser ParseString fails to replace tokens when to tokens after each other

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2098]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
if in template we have {hosturl}{site} we would expect the tokens to be replaced for apply template.
the issue is with links of webparts beeing absolute.

#### Observed Behavior
The Regex(@"(?:(\{(?:\1??[^{]*?\}))+)" does recognize the tokens but match.Groups[0].Value will return them as {hosturl}{site} and therefore the TokenDictionary.TryGetValue(tokenString, out string val) will not find and replace the tokens.

![image](https://user-images.githubusercontent.com/31336529/54087990-3dd48900-4359-11e9-8b4c-ad5e92b36ddd.png)

String input to ParseString:
[stringToParse.txt](https://github.com/SharePoint/PnP-Sites-Core/files/2949723/stringToParse.txt)

#### Steps to Reproduce
create a clientSidePage with a hero WebPart and add two pictures to the areas. extract this as template - you should see in xml content[0].link":"{hosturl}{site}/SiteAssets/ and content[1].link":"{hosturl}{site}/SiteAssets/
For some reason content[0].link":"{hosturl}{site}/SiteAssets/ gets replaced but not content[1].link":"{hosturl}{site}/SiteAssets/. 
Debuging shows the first call from ObjectClientSidePages ->ProvisionObjects to parser at Line 290 does not replace {hosturl}{site} at all.

**Comment by czullu** [comment]
If i change the RegEx from (?:({(?:\1??[^{]*?}))+) to (?:(\{(?:\1??[^{]*?\}))) it works for me - all tokens are separate then and therefore found and replaced.

**Comment by jansenbe** [comment]
Fix was merged
