### ISSUE TITLE
ClientSidePage Description not set during apply Template

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2105]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
If in XML unter pnp:ClientSidePage -> pnp:FieldValues 
<pnp:FieldValue Key="Description" Value="Hello you" />
we would expect the Site Description under PageDetails to be set after Provisioning.

#### Observed Behavior
The Description Field is not set since it's readonly on SitePages Library and therefore ignored in ListItemUtilities.UpdateListItem.

#### Posible Solution
Add the Description Field to WriteableReadOnlyFields in ListItemUtilities

**Comment by jansenbe** [comment]
PR that fixes this has been merged
