### ISSUE TITLE
RatedBy and Ratings make Apply Template fail 

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2110]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Fields RatedBy and Ratings should be exported and Imported

#### Observed Behavior
RatedBy and Ratings have not been correct exported - they have been in the ViewFields as
<FieldRef Name="RatedBy" Explicit="TRUE" />
<FieldRef Name="Ratings" Explicit="TRUE" />
but not in <pnp:FieldRefs> section.

#### Steps to Reproduce
Create a Document Library with Ratings on Extract & Apply Template - the Apply will Fail because the Ref in View is there but the Fields on the List are missing.

**Comment by jansenbe** [comment]
fix merged
