### ISSUE TITLE
Connect-PnPOnline UseWebLogin parameter returns 403 on Apply-PnPProvisioningTemplate

### ISSUE THREAD

**Issue by 2toLeadMike** [SharePoint/PnP-Sites-Core#2119]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

**Note:** Tried with PnP PowerShell 3.6.1902.2 and again with 3.7.1903.0 (latest at this time) with same results.

#### Expected or Desired Behavior
Should be able to deploy PnP Provisioning Templates with same reliability when using -UseWebLogin parameter with Connect-PnPOnline in order to deploy within an MFA account.

#### Observed Behavior
When deploying certain tenant configuration adjustments via Provisioning XML (i.e. `<pnp:Tenant>`) everything works well. But when -UseWebLogin is used to connect (regardless of whether or not MFA is enabled) it will fail on many of our templates.

It returns the following error:

> Apply-PnPProvisioningTemplate : The remote server returned an error: (403) Forbidden.
> At line:1 char:1
> + Apply-PnPProvisioningTemplate .\PnP_TenantApp.xml -Handlers Tenant
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
>     + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate

We have found ways around this in some cases by connecting to the admin URL (i.e. tenant-admin.sharepoint.com) however this only seems to help in certain cases.

#### Steps to Reproduce

Run the following:

1. Connect via `Connect-PnPOnline -Url "https://tenant.sharepoint.com" -UseWebLogin`
2. Run `Apply-PnPProvisioningTemplate .\Test.xml` (See below for XML)

**Test.xml**
`<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.6.1902.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Tenant>
    <pnp:StorageEntities>
      <pnp:StorageEntity Key="TEST" Value="TEST" />
    </pnp:StorageEntities>
  </pnp:Tenant>
  <pnp:Templates ID="CONTAINER-PORTAL_TENANT_SETTINGS">
    <pnp:ProvisioningTemplate ID="PORTAL_TENANT_SETTINGS" Version="1" ImagePreviewUrl="https://preview.png" DisplayName="Tenant Configuration" Description="" TemplateCultureInfo="1033" Scope="RootSite" />
  </pnp:Templates>
</pnp:Provisioning>`

**Comment by jansenbe** [comment]
Does Connect-PnPOnline -Url yoururl **-SPOManagementShell -ClearTokenCache** not work?

**Comment by 2toLeadMike** [comment]
@jansenbe I think this what I was looking for earlier! This is the modern authentication approach, correct? I ran it and was able to go through MFA and still be able to deploy. Thanks!

Does this make UseWebLogin obsolete? This seems odd as #1924 had a similar issue and the fix was going from SPOManagementShell to UseWebLogin (vice versa)

**Comment by jansenbe** [comment]
Well...kind off, we did some optimization work for SPOManagementShell + did improve the context cloning which is required to work properly before you can clone a template. Glad to hear it works now.

**Comment by 2toLeadMike** [comment]
@jansenbe Actually hm. Today I am trying to upgrade the script and getting the 401 again. Odd. I closed down everything and booted up a fresh PS and tried the following:

```
Connect-PnPOnline -Url "https://mytenant.sharepoint.com" -SPOManagementShell -ClearTokenCache
Apply-PnPProvisioningTemplate -Path .\test.xml
```
> Apply-PnPProvisioningTemplate : The remote server returned an error: (401) Unauthorized.

```
Connect-PnPOnline -Url "https://mytenant.sharepoint.com/sites/app" -SPOManagementShell -ClearTokenCache
Apply-PnPProvisioningTemplate -Path .\test.xml
```
> Apply-PnPProvisioningTemplate : The remote server returned an error: (401) Unauthorized.

```
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -SPOManagementShell -ClearTokenCache
Apply-PnPProvisioningTemplate -Path .\test.xml
```

>WARNING: Tenant app catalog doesn't exist. Provisioning of storage entities will be skipped!

Any thoughts?

**Comment by wkwolff** [comment]
Did you ever figure this out?

I'm receiving the same error when trying to apply template and we have MFA on here.

Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this
resource.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path teamSite.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
+ FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate

**Comment by 2toLeadMike** [comment]
@wkwolff No right now we are having to enforce deployments with MFA temporary turned off. @jansenbe any idea as to the above issues?
