### ISSUE TITLE
The file OfficeDevPnP.Core.resources is not found when executing ConvertTo-PnPClientSidePage

### ISSUE THREAD

**Issue by boby5555** [SharePoint/PnP-Sites-Core#2122]
#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
I tried with both **_february_** release and _**march**_ release

# Connect to the web holding the pages to modernize
Connect-PnPOnline -Url https://*****.sharepoint.com/

# Get all the pages in the site pages library. SitePages is the only supported library for using modern pages
$pages = Get-PnPListItem -List sitepages

# Iterate over the pages
foreach($page in $pages) 
{ 
    # Optionally filter the pages you want to modernize
    if (-not $page.FieldValues["FileLeafRef"].StartsWith(("Previous_")))
    {
        # No need to convert modern pages again
        if ($page.FieldValues["ClientSideApplicationId"] -eq "b6917cb1-93a0-4b97-a84d-7cf49975d4ec" ) 
        { 
            Write-Host `Page $page.FieldValues["FileLeafRef"] is modern, no need to modernize it again`
        } 
        else 
        { 
            # Create a modern version of this page
            Write-Host `Modernizing $page.FieldValues["FileLeafRef"]...`
            $modernPage = ConvertTo-PnPClientSidePage -Identity $page.FieldValues["FileLeafRef"] -Overwrite -TakeSourcePageName
            Write-Host "Done" -ForegroundColor Green
        }
    }  
}

**Comment by jansenbe** [comment]
Hmm...weird issue. Can you after you get the error with the March release run Get-PnPException and provide the output from that command here?
