### ISSUE TITLE
Why not use the ootb sitepages api?

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/PnP-Sites-Core#2132]
#### Category
[ ] Bug
[X] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
This is more a question. Why are you not using _api/sitepages/... API to work with modern pages in ClientSidePage but instead parse all the HTML manually? The MS API supports all new features like webpart connections and things that are not working with PnP yet and it looks like it is easy to use and much easier to read for sure.
@jansenbe any comments on that?

**Comment by jansenbe** [comment]
Hi @OliverZeiser ,

There are 2 main reasons for now using the _api/sitepages:

- It's an undocumented API and it's not supported to be used by third party: the team owning the pages infrastructure can make breaking changes to this one without upfront notice...
- We are building an official API for this (already announced for Ignite timeframe) that will replace this API, also for internal usage

You can argue that the generated HTML is also version dependent, which is true...but server side we'll upgrade the html whenever there's newer data models for the web parts on the page. This is an expected upgrade path...I'm not sure how that will work with the sitepages API when you provide a JSON properties element for an older version of a web part.

The current version of the API does not yet support connected web parts, but there's PR pending that I'll process for the April release. Is there anything else in particular that you're missing?

**Comment by OliverZeiser** [comment]
Thank you Bert, I was hoping this is already the official API. There are a few more things like support for page templates and folders inside of side pages library but I think most things are fixed or beeing worked on already and we did a few pull requests ourselve. So I was just wondering about the api. I will close this issue. Thanks again :)

**Comment by jansenbe** [comment]
Folders should be supported now (just name your page folder1/folder2/page.aspx), page templates will be part of the next schema (part of April drop) and implemented for the May release.
