### ISSUE TITLE
ClientSidePage Save breaks RepostPage 

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2143]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Create a RepostPage with ClientSidePage.

#### Observed Behavior
If you navigate to the Page with Query Parameter ?stay=true the Page will not show the Preview Content with the "Try Link". However when the Fields "_originalsourceitemid", "_originalsourcelistid", "_originalsourcesiteid", "_originalsourcewebid", "_originalsourceurl" + ContentType are set, the redirect will work when called without ?stay=true.

The Reason for this behavior is that ClientSidePage on Save always stores html to LayoutWebpartsContent - this Field and CanvasContent1 have to be null in order to have Preview working. 

#### Steps to Reproduce
Create a RepostPage and after save try to see Preview - it will not work
Then do:
                       if (clientSidePage.LayoutType == OfficeDevPnP.Core.Pages.ClientSidePageLayoutType.RepostPage)
                                    {
                                        clientSidePage.PageListItem["CanvasContent1"] = null;
                                        clientSidePage.PageListItem["LayoutWebpartsContent"] = null;
                                        clientSidePage.PageListItem.Update();
                                        ctx.ExecuteQueryRetry();
                                    }
Check again - now Preview will work.
["CanvasContent1"] = null; is optional since this is supported to be null by ClientSidePage.

@jansenbe : Probably would have to extend ClientSidePageHeaderType Enum with Empty in order to handle this in // Persist the page header of ClientSidePage.cs

**Comment by jansenbe** [comment]
Did commit a change (https://github.com/SharePoint/PnP-Sites-Core/commit/89b0bd3d5952e5e05d4b6b3007647370160eca98) that ensures that when a repost page was loaded it again is saved as one. If you're copying the repost page you still need to copy the actual repost fields, but at least now the contenttype, CanvasContent1 and LayoutWebpartsContent are set correctly. Let me know if that unblocks you.

**Comment by czullu** [comment]
Hi Bert,
Thank you for the quick fix. I can confirm that the fix is good and RepostPage is now working.
