### ISSUE TITLE
Schema 2019/03 - Provisioning Issue when Footer has no existing elements 

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2183]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Provisioning FooterNavigation on new created CommunicationSite - Test with current DEV Branch.

#### Observed Behavior

ObjectSiteFooterSettings.cs ->Methode ProvisionObjects fails at:
web.Context.Load(n1, n => n.Children.IncludeWithDefaultProperties());
web.Context.ExecuteQueryRetry();

Cannot invoke method or retrieve property from null object. Object returned by the following call stack is null. "GetNodeById
Navigation
"
It only happens on a page where not Footer has been configured before ...

#### Steps to Reproduce
Create new CommunicationPage - do not navigate to it - apply Template with FooterSettings.

@erwinvanhunen : As is the Dev Branch and code is from you i'm not sure if should make a pull request as it could be work in progress - so i just let you know, that the StartNodeKey does not exist if you had no Footer set before.

**Comment by jansenbe** [comment]
Already fixed
