### ISSUE TITLE
Schema 2019/03 - Provisioning Issue when additional administrators etc. have no child elements

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/PnP-Sites-Core#2188]
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

**LATEST DEV BRANCH BUILD**

#### Expected or Desired Behavior
A template file should provision with the following (partial) content:

```
    <pnp:ProvisioningTemplate ID="TEMPLATE-F6E7ECB2634143318E7F6769250F5BF1" Version="1" BaseSiteTemplate="STS#0" Scope="Undefined">
      <pnp:Security RemoveExistingUniqueRoleAssignments="false">
        <pnp:AdditionalAdministrators />
        <pnp:AdditionalOwners />
        <pnp:AdditionalMembers />
        <pnp:AdditionalVisitors />
        <pnp:Permissions />
      </pnp:Security>
```

#### Observed Behavior
Provisioning fails with the following error which is thrown during schema validation in XmlSchemaBaseSerializer:

> The element 'AdditionalAdministrators' in namespace 'http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema' has incomplete content. List of possible elements expected: 'User' in namespace 'http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema'.

I assume this will also fail for empty AdditionalOwners, Members etc.

(There seems to be a similar error relating empty elements here: #2183 - possibly more?)

#### Steps to Reproduce
I wanted to use `Add-PnPDataRowsToProvisioningTemplate` to add list elements to a template file. Which fails due to the schema validation error.

The schema version namespace uri is: http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema

I can confirm that using an older schema works.

**Comment by heinrich-ulbricht** [comment]
This blocks me from fixing the failing unit tests for `Add-PnPDataRowsToProvisioningTemplate` 😞

**Comment by heinrich-ulbricht** [comment]
Did you change something? It seems that the current dev branch state does not create empty `Additional*` elements anymore.

**Comment by jansenbe** [comment]
@heinrich-ulbricht , yes we changed this to not emit these empty elements anymore.
