### ISSUE TITLE
ClientSidePage Header not at all correctly provisioned

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/PnP-Sites-Core#2196]
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

#### Expected or Desired Behavior
ClientSidePages should be provisioned with correct custom page header, including header properties like ShowTopicHeader etc. (see here for more of them: https://github.com/SharePoint/PnP-Sites-Core/blob/ad62f01f06c9bddfba19b9760bdb62eb3ed1599b/Core/OfficeDevPnP.Core/Pages/ClientSidePageHeader.cs#L87)

#### Observed Behavior
Most header properties are not properly provisioned.

There seem to be multiple problems with page header provisioning, here are a few I spotted:
- `TopicHeader` is missing in the exported template file
- provisioning the header does not provision most of the properties from the template file, even the `Type` seems to be wrong after provisioning.

(Futhermore I sometimes get a "versioning conflict" error when provisioning a page. But only sometimes. This does not increase my confidence in the overall current state of affairs arount client side pages.)

#### Steps to Reproduce
- set up and export ClientSidePage with type `Custom` and the following configuration:
```
Type                   : Custom
ImageServerRelativeUrl : here-was-a-url.jpg
TranslateX             : 51,0752688172043
TranslateY             : 23,2456140350877
LayoutType             : NoImage
TextAlignment          : Left
ShowTopicHeader        : True
ShowPublishDate        : False
TopicHeader            : AUF EINEN BLICK
AlternativeText        : 
Authors                : []
AuthorByLine           : 
AuthorByLineId         : -1

```
- provision ClientSide Page from template
- look at the header not being provisioned correctly

**Comment by jansenbe** [comment]
Hi @heinrich-ulbricht ,

Are you here testing with the provisioning engine or with the API? The provisioning engine implementation was just recently added (last Friday)...can you recheck your scenario?

**Comment by heinrich-ulbricht** [comment]
@jansenbe I initially used the engine and finally found #2199 to be the cause of my problems. So since you merged https://github.com/SharePoint/PnP-Sites-Core/pull/2199 the problem should be gone.
