### ISSUE TITLE
Intermittent "Version conflict." error when creating ClientSidePages

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/PnP-Sites-Core#2203]
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

Latest dev build.

#### Expected or Desired Behavior
ClientSidePages should provision correctly.

#### Observed Behavior
When provisioning ClientSidePages that are _not_ the home page I often get this error:

```
Apply-PnPProvisioningTemplate : Version conflict.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path $templatePath -IgnoreDuplicateDat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate

```
Provisioning stops at this point. This happens on first provisioning of pages (so they are newly created) as well as on updating them.

#### Steps to Reproduce
Unfortunately I have no rock-solid repro steps as it does not always happen. For now I'm creating this issue to raise awareness and to see if somebody else suffers from this issue.

**Comment by heinrich-ulbricht** [comment]
After doing some more tests I'm convinced the error is triggered by having a `Header` element inside the `ClientSidePage` element. Like this:

`          <pnp:Header Type="Custom" ServerRelativeImageUrl="{site}/SiteAssets/SitePages/Kunden-News/image.jpeg" LayoutType="FullWidthImage" TextAlignment="Center" ShowTopicHeader="false" ShowPublishDate="false" AuthorByLineId="0" />
`

Is there something modifying the page in the backend while it is being processed? Or the item? Not sure what's modifying what.

**Comment by heinrich-ulbricht** [comment]
Commenting out this line makes the version conflict go away:

https://github.com/SharePoint/PnP-Sites-Core/blob/ad62f01f06c9bddfba19b9760bdb62eb3ed1599b/Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs#L802

The hunt continues.

**Comment by heinrich-ulbricht** [comment]
Halleluja - it's the call to ResolvePageHeaderImage that causes the problem. But only when provisioning two pages in a row that both have the `ServerRelativeImageUrl` set.

**Comment by jansenbe** [comment]
Closing as this fix has been merged
