### ISSUE TITLE
XML serializer for 201903 schema doesn't (de)serialize pnp:SiteGroup members

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/PnP-Sites-Core#2217]
#### Category
[x] Bug

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
XML serializer correctly saves/extracts site group members information. 

#### Observed Behavior
Site group members are ignored.

#### Steps to Reproduce
Below code demonstrates the issue: 

```
var provider = new XMLFileSystemTemplateProvider($@"{AppDomain.CurrentDomain.BaseDirectory}\..\..\Resources", "Templates");

var serializer = new XMLPnPSchemaV201903Serializer();
var template = provider.GetTemplate(TEST_TEMPLATE, serializer);
var security = template.Security;
var group = security.SiteGroups.FirstOrDefault(g => g.Title == "TestGroup1");
Assert.IsNotNull(group.Members);  <-- fails here, despite schema xml contains members entries
```

**Comment by PaoloPia** [comment]
This one is now fixed and closed.
