### ISSUE TITLE
Apply-PnPProvisioningTemplate: An item with the same key has already been added

### ISSUE THREAD

**Issue by tarjeieo** [SharePoint/PnP-Sites-Core#2223]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I want to apply a PnP template without errors.

#### Observed Behavior
Applying any template to a certain site collection throws error "An item with the same key has already been added". The stacktrace shows the error is coming from the TokenParser class.

![image](https://user-images.githubusercontent.com/1837390/57128844-fab0f800-6d94-11e9-99f1-dbe39809f422.png)

#### Steps to Reproduce
I found that the issue appears if you have multiple lists with the same name. In my case, in this site, SharePoint had for some reason created "Sharing Links" (Delingskoblinger in my case - norwegian) twice. I renamed one of the lists, and after that everything worked fine again. I.e. in my case this is no longer an issue.

CC @PaoloPia

**Comment by OliverZeiser** [comment]
I am seeing the same issue. This is clearly a bug in the engine. Multiple lists with the same title should be supported as long as the url is different.

**Comment by erwinvanhunen** [comment]
Thank you for reporting this. We will fix this in the upcoming release.
