### ISSUE TITLE
Not possible to specify Security for ClientSidePage programmatically

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/PnP-Sites-Core#2224]
#### Category
[x] Bug

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016

#### Expected or Desired Behavior
You should be able to set security for ClientSidePage using code object model:
```
var result = new ProvisioningTemplate();
result.ClientSidePages.Add(new Core.Framework.Provisioning.Model.ClientSidePage({...}));
// set security
result.ClientSidePages[0].Security.ClearSubscopes = true;
// etc.
```

#### Observed Behavior
Null reference exception is thrown at line `result.ClientSidePages[0].Security` because `Security` is null. `Security` property has a private `set` modifier and it's not possible to create an instance using the constructor. 

#### Steps to Reproduce
Mentioned in "Expected or Desired Behavior" section

**Comment by jansenbe** [comment]
fix merged
