### ISSUE TITLE
PNP js is now working in IE browser

### ISSUE THREAD

**Issue by Nagarajan1605** [SharePoint/PnP-Sites-Core#2238]
Hi,
 
I am doing CRUD operation using pnp.js in sharepoint site through custom page. I am able to perform all the actions in EDGE and Chrome browser. 
 
But when i try to do the same in IE browser its not working. 
 
Getting the error as 401. 
 
I received Request header: Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*Accept-Encoding: gzip, deflateAccept-Language: en-USAuthorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAKAO5CAAAADw==Connection: Keep-AliveCookie: WSS_FullScreenMode=falseHost: portaldev.ibx.comIf-Modified-Since: Mon, 13 May 2019 12:09:39 GMTUser-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Zoom 3.6.0) 
 
 
Response header:  
Content-Length: 0
Date: Mon, 13 May 2019 12:13:30 GMT
MicrosoftSharePointTeamServices: 16.0.0.4822
request-id: 9934dc9e-a935-0049-b7d0-2c747ec5a0ba
Server: Microsoft-IIS/10.0
SPIisLatency: 0
SPRequestDuration: 1
SPRequestGuid: 9934dc9e-a935-0049-b7d0-2c747ec5a0ba
WWW-Authenticate: NTLM TlRMTVNTUAACAAAAEAAQADgAAAAFgomiUcK1cn/yL0oAAAAAAAAAAIoAigBIAAAACgA5OAAAAA9MAEEATgBHAFIATwBVAFAAAgAQAEwAQQBOAEcAUgBPAFUAUAABABAAVwBTAFMAUABMAE4AMAAxAAQADgBpAGIAeAAuAGMAbwBtAAMAIABXAFMAUwBQAEwATgAwADEALgBpAGIAeAAuAGMAbwBtAAUAGABhAGQAZgBvAHIAZQBzAHQALgBjAG8AbQAHAAgAGR2VR4UJ1QEAAAAA
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-Powered-By: ASP.NET
 
Herewith i have attached the error screenshot.  
 
![PNP Notworking in IE browser](https://user-images.githubusercontent.com/21313599/57621341-d03b1800-75a8-11e9-86c8-6033df276c62.jpg)

**Comment by wobba** [comment]
@Nagarajan1605  did you take a look at https://pnp.github.io/pnpjs/documentation/polyfill/ ?

**Comment by Nagarajan1605** [comment]
I have added polly fills. I am getting syntax error 
var sourceitem = sourcelist.items.getById(16);
sourceitem.attachmentFiles**.get().then(v=>{**
for(var k in v)
{
filename = v[k].FileName;
sourceurl=v[k].ServerRelativeUrl;

$("#attachmentdata").append('<div id='+k+'><a href='+sourceurl+'>'+filename+'</a></div>');
attachmentdata
}
});

in the above code i have bold the section right there its throwing error. "=>" this is throwing error in IE

**Comment by wobba** [comment]
Debug your loop and check the values of v in the for loop, and you'll figure it out most likely. I'll close this issue as IE issue is resolved. And if you follow the tutorial docs https://pnp.github.io/pnpjs/sp/docs/attachments/ it should work. Then build from there.
