### ISSUE TITLE
Missing attribution in "May 2019 update" blog post

### ISSUE THREAD

**Issue by lafe** [SharePoint/PnP-Sites-Core#2243]
It appears that my contribution #2232 was missed while compiling the list of contributors in the ["May 2019 update" blog post](https://developer.microsoft.com/en-us/sharepoint/blogs/sharepoint-development-community-pnp-may-2019-update/) or is there a cutoff regarding number or length of PRs?

**Comment by VesaJuvonen** [comment]
Sorry for that - absolutely my mistake. I've updated the blog post and it will be visible in the pages within next 3 hours after the cache will expire. Sorry for that.

**Comment by lafe** [comment]
Thanks!
