### ISSUE TITLE
ApplyProvisioningTemplate error occured when apply Site Security

### ISSUE THREAD

**Issue by OTV64** [SharePoint/PnP-Sites-Core#2245]
Hi,

I try to create a SharePoint Online site collections a TeamSite template (LCID:1036) ; to do that, I use the SharePointPnPCoreOnline 3.9.1905.2 version, and the Microsoft.SharePointOnline.CSOM 16.1.8715.1200.

The error occured at site security step of the ApplyProvisioningTemplate method :
"The specified user {associatedowneridgroup} could not be found."

When I check the Template, I have the Security properties bellow :
- AssociatedGroups = Null
- AssociatedMemberGroup = "{sitetile} Members"
- AssociatedOwnersGroup = "{sitetile} Owners"
- AssociatedVisitorsGroup = "{sitetile} Visitors"

If I exclude the Site Security step, know I get an error on Files :
"The format of the input string is incorrect."

Thanks in advance.

**Comment by gautamdsheth** [comment]
Can you share a minimal template for us to reproduce the issue ?

**Comment by OTV64** [comment]
Please find attached the site template.
Thank you


De : msftbot[bot] <notifications@github.com>
Envoyé : jeudi 16 mai 2019 17:21
À : SharePoint/PnP-Sites-Core <PnP-Sites-Core@noreply.github.com>
Cc : TRAN VAN Olivier <oliviertv@exakis.com>; Author <author@noreply.github.com>
Objet : Re: [SharePoint/PnP-Sites-Core] ApplyProvisioningTemplate error occured when apply Site Security (#2245)


Thank you for reporting this issue. We will be triaging your incoming issue as soon as possible.

**Comment by jansenbe** [comment]
The problem is that during extraction time we inserted the wrong token: {associatedowneridgroup} instead of {associatedownergroupid}. This has just been fixed in the engine, so if you're using the dev version please update and extract your template again.

If you're not using a dev version then you'll need to update the template XML file manually and replace {associatedowneridgroup} with {associatedownergroupid}. Same also applies to the respective member and visitor group tokens.

**Comment by OTV64** [comment]
hi jansenbe,

I tested your suggestion to replace the tokens, and now I have the following error:
"The specified user 5 could not be found."

which version are you referring to, is this the OfficeDevPnP.Core (I have 3.9.1905.2)?

**Comment by jansenbe** [comment]
Can you share the template, we would need to see where the token then is used? Are you applying the template to a modern site or to a classic site?

**Comment by OTV64** [comment]
[TeamSiteTemplate.txt](https://github.com/SharePoint/PnP-Sites-Core/files/3192181/TeamSiteTemplate.txt)

**Comment by jansenbe** [comment]
You still have the wrongly named tokens in your template:

```XML
          <pnp:RoleAssignments>
            <pnp:RoleAssignment Principal="{associatedowneridgroup}" RoleDefinition="Advanced" />
            <pnp:RoleAssignment Principal="{associatedowneridgroup}" RoleDefinition="{roledefinition:Administrator}" />
            <pnp:RoleAssignment Principal="{associatedvisitoridgroup}" RoleDefinition="{roledefinition:Reader}" />
            <pnp:RoleAssignment Principal="{associatedmemberidgroup}" RoleDefinition="{roledefinition:Editor}" />
            <pnp:RoleAssignment Principal="{associatedmemberidgroup}" RoleDefinition="{roledefinition:Contributor}" />
          </pnp:RoleAssignments>
```

**Comment by gszdev** [comment]
@jansenbe 
Do you plan to release another intermediate release for 3.9.1905.x to resolved the issues (SiteSecurity, ...) related to current version 3.9.1905.2?
The dilemma I have to use version 3.9.1905.2 to get the workaround for the content type reorder issue on Server side. But this version cannot resolve the ID for the group in the SiteSecurity section.

See your commit in dev branch:
[Allow for retrieval of principal based upon it's ID value](https://github.com/SharePoint/PnP-Sites-Core/commit/091f5dbd1e1aaa43a3451303ec9ea7e4cdf5c8a5)

**Comment by jansenbe** [comment]
I've committed a change that allows group id's to be used in role assignments, that previously did fail. With this change in place and when using the correct formatted token this should now work. Can you confirm by testing with the current developer release?

**Comment by jansenbe** [comment]
@gszdev : most likely we'll release a .3 version this week. The content type problem should be handled server side, so we're removing our temporary fix. You could optionally also switch back to the April release for now, that should work as well now that the server side issue is fixed.

**Comment by gszdev** [comment]
@jansenbe 
Thanks. I'm testing now with the developer release. My tests will take some time. I'll give feedback when I finished with the tests.

**Comment by gszdev** [comment]
@jansenbe 
Your changes works.
I tested it with the current developer branch.
Thanks.

[Allow for retrieval of principal based upon it's ID value](https://github.com/SharePoint/PnP-Sites-Core/commit/091f5dbd1e1aaa43a3451303ec9ea7e4cdf5c8a5)
