### ISSUE TITLE
Provisioning template: {sitecollectionid} is not replaced.

### ISSUE THREAD

**Issue by olemp** [SharePoint/PnP-Sites-Core#2258]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
{sitecollectionid} is replaced with the actual ID of the site.

#### Observed Behavior
{sitecollectionid} is not replaced.

#### Steps to Reproduce

See attached template:

[PnP-Template.txt](https://github.com/SharePoint/PnP-Sites-Core/files/3207073/PnP-Template.txt)

**Comment by olemp** [comment]
Using May 2019 Intermediate Release 2 of https://github.com/SharePoint/PnP-PowerShell

**Comment by jansenbe** [comment]
Was fixed with the June release
