### ISSUE TITLE
🐞 Missing parser.ParseString in UpdateListItem

### ISSUE THREAD

**Issue by zumiek** [SharePoint/PnP-Sites-Core#2259]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Using {parameter:Name} in provisioning template should use the correct token/stringValue

#### Observed Behavior
When creating DataRows in a list, the value of the field is {parameter:Name} instead of the actual parameter value.

#### Steps to Reproduce
Provision a list with data where a field is using a parameter value:
.....
<pnp:Parameters>
      <pnp:Parameter Key="TermName" Required="true"/>
.....
          <pnp:DataRows KeyColumn="Title" UpdateBehavior="Overwrite">
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">{parameter:TermName}</pnp:DataValue>
              <pnp:DataValue FieldName="Overall">Red</pnp:DataValue>
            </pnp:DataRow>
          </pnp:DataRows>
        </pnp:ListInstance>

#### Link to code
https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs#L447

**Comment by gszdev** [comment]
Maybe have a look at the following pull request:
[Fix DataRow parameters replacement](https://github.com/SharePoint/PnP-Sites-Core/pull/2248)  #2248 

see also #2258

**Comment by jansenbe** [comment]
This was fixed in the June release
