### ISSUE TITLE
Bug in PnP Core when using HTML in serverProcessedContent

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/PnP-Sites-Core#2260]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
PnP should be able to provision custom ClientSideWebParts that are using custom HTML data in serverProcessedContent content. E.g. like this

```
"serverProcessedContent": {
    "htmlStrings": {
      "htmlString": "<div><span><b>HTML Demo Content</b></span></div>"
    },
    "searchablePlainTexts": {},
    "imageSources": {},
    "links": {}
  }
```

#### Observed Behavior
PnP Engine and core is extracting and reading the properties correctly. But when adding it via code to a new page, it seems to have some encoding issue and the HTML gets stripped out.
There was a pull request tackeling this problem, but it did not get accepted:
https://github.com/SharePoint/PnP-Sites-Core/pull/2159

#### Steps to Reproduce
I have created a sample webpart and provisioning file to reproduce the issue. You can find the repo here: https://github.com/OliverZeiser/htmlSample
Note: there is a provisionining file and ready to use sppkg file in the "setup" folder.

In the WebPart there is a textbox in the propertypane that contains HTML. This HTML is made searchable via propertiesMetadata. Thus the HTML ends up in the serverProcessedContent.

Try to add the webpart to a page, publish the page and then extract the page via PnP and try to provision it again. You will see, that the HTML gets lost.

@jansenbe It looks like there is an encoding issue in your html parser. Ping me if you have further questions. I will also be at the europeancollaboration summit in Wiesbaden.

**Comment by jansenbe** [comment]
Hi @OliverZeiser , let's indeed talk about this next week in Wiesbaden.

**Comment by jansenbe** [comment]
@OliverZeiser , @czullu : can you test if the dev branch commit https://github.com/SharePoint/PnP-Sites-Core/commit/905ac5631fe772b90bd2df2cc212128251b550c7 does solve things for you? 

**Note:** I had to update the https://github.com/OliverZeiser/htmlSample/blob/master/setup/htmlsample.xml file slightly: it somehow contained {site} instead of a forward slash (/). Might be a tokenization issue, will see if I can reproduce that

**Comment by czullu** [comment]
Hello Bert
Thank you for the fix. My first test with the Test webpart have been successfull. I will run some more test tomorrow but I expect them to be OK as well.

Freundliche Grüsse
Christian

________________________________
