### ISSUE TITLE
SharePointPnPCoreOnline Nuget Package has a dependency on Newtonsoft.Json >= 11.0.1 that leads to multiple issues

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/PnP-Sites-Core#2262]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
This is more a question, but why does the SharePointPnPCoreOnline Nuget Package have a dependency on Newtonsoft.Json 11 now?
Since SharePointPnPCoreOnline Nuget Package also has a dependency to System.IdentityModel.Tokens.Jwt which internally has a hard dependency to Newtonsoft.Json 10 certain methods of PnP Core are not working anymore.
In addition it is a blocker for us in many scenarios to move to a newer version of PnP because we are also using System.IdentityModel.Tokens.Jwt in our solutions.

#### Observed Behavior
See your own tests here: https://testautomation.sharepointpnp.com/Testsummary/AllTests/17673?outcome=2&branch=dev
OfficeDevPnP.Core.Tests.Framework.Functional.LocalizationTest.SiteCollectionsLocalizationTest threw exception: System.ArgumentException: IDX12729: Unable to decode the header '[PII is hidden]' as Base64Url encoded string. jwtEncodedString: '[PII is hidden]'. ---> System.TypeInitializationException: The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

#### Steps to Reproduce
No need to reproduce the issue, it is clear as you can see in the testautomation above.

**Comment by jansenbe** [comment]
The unit test did require an update in the assembly bindings redirect as shown below. For PnP PS we've added this to all cmdlets. This should solve the issues.

```XML
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.4.0" newVersion="5.8.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.4.0" newVersion="5.8.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.4.0" newVersion="5.8.4.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by jansenbe** [comment]
@OliverZeiser : does the above get you unblocked?

**Comment by OliverZeiser** [comment]
Yes, sorry I forgot to close this issue. We had to do it slightly different because we had this issue in an azure function where there is no web.config but it is working using the same idea of bindings redirect.

**Comment by IlyeniaMaksim** [comment]
@OliverZeiser I have the same issue for azure function. Could you help me? Could you provide more details with bindings redirect?

**Comment by OliverZeiser** [comment]
Yup, in the link is the same approach we are using and that is working for us

**Comment by decapent** [comment]
Using the latest version of the PnP PowerShell Online and when trying to create a New-PnPSite, i stumble upon the same error.

The weird thing is that the error does not show on some environment and is shown in production environment. 

How can i solve my problem ?
