### ISSUE TITLE
The specified user {associatedownergroupid} could not be found.

### ISSUE THREAD

**Issue by StaffanNelemans** [SharePoint/PnP-Sites-Core#2281]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
If using associatedownergroup as sitegroupowner, the provisioning should work and not give a exception

#### Observed Behavior
The extracted template contains: 
<pnp:SiteGroup Title="xxx" Description="xxx" Owner="{associatedownergroupid}" ....
If you then provisioning this SiteGroup you get the exception: "The specified user 6 could not be found." This extracted Owner tag should be the "{associatedownergroup}" or the code for ProvisioningObject should be updated to handle the "{associatedownergroupid}".

#### Steps to Reproduce
- Add a sitegroup with the Associated Owner group as Owner.
- Extract a template
- Provision this template

**Comment by StaffanNelemans** [comment]
I think a solution could be to add the logic of Groupid to line 301:
```
Principal ownerPrincipal = allGroups.FirstOrDefault(gr => gr.LoginName.Equals(parsedGroupOwner, StringComparison.OrdinalIgnoreCase));
if (ownerPrincipal == null)
                    {
                        if (Int32.TryParse(parsedGroupOwner, out int roleAssignmentPrincipalId))
                        {
                            ownerPrincipal = allGroups.FirstOrDefault(g => g.Id.Equals(roleAssignmentPrincipalId));
                        }
                    }
                            if (ownerPrincipal == null)
                            {
                                ownerPrincipal = web.EnsureUser(parsedGroupOwner);
                            }
                            group.Owner = ownerPrincipal;
```

As this code is also used in the OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Extensions.SecurableObjectExtensions.SetSecurity

**Comment by jansenbe** [comment]
Are you using the latest version or dev branch to repro this?

**Comment by StaffanNelemans** [comment]
We used the latest version, but code check was done in the dev branch.

**Comment by StaffanNelemans** [comment]
OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectSiteSecurity should be updated at line 302 add

>  if (ownerPrincipal == null)
>                     {
>                         if (Int32.TryParse(parsedGroupOwner, out int roleAssignmentPrincipalId))
>                         {
>                             ownerPrincipal = allGroups.FirstOrDefault(g => g.Id.Equals(roleAssignmentPrincipalId));
>                         }
>                     }

**Comment by jansenbe** [comment]
Added this fix, thx @StaffanNelemans for pointing this out.
