### ISSUE TITLE
Apply-PnPProvisioningTemplate access denied at setting the property bag value

### ISSUE THREAD

**Issue by nextdarius** [SharePoint/PnP-Sites-Core#2322]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[x] SharePoint 2019
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: June 2019

#### Expected or Desired Behavior
Apply provisioning template on modern experience sites.

#### Observed Behavior
Applying provisioning template on modern sites fails:
```
Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this
resource.
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path .\lists.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate
```

I ran `Get-PnPException` to see where exactly this fails and I got:
```
Message          : Access denied. You do not have permission to perform this action or access this resource.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext
                   clientContext, Int32 retryCount, Int32 delay, String userAgent)
                      at Microsoft.SharePoint.Client.WebExtensions.SetPropertyBagValueInternal(Web web, String key,
                   Object value)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectPersistTemplateInfo.ProvisionObj
                   ects(Web web, ProvisioningTemplate template, TokenParser parser,
                   ProvisioningTemplateApplyingInformation applyingInformation)
                      at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTe
                   mplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation
                   provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
                      at SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1
```
The exact same thing worked on classic sites so it seems related to modern experience ones.

#### Steps to Reproduce
Create a modern experience site, export a provisioning template and try to apply it and you'll get access denied.

**Comment by gszdev** [comment]
I think your a applying the provisioning template to a site has NoScript enabled (e.g. Modern team site, ...).
Maybe the following links are helpful.

[Customizing "modern" team sites](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites)

When you design your solutions, consider these key areas related to the NoScript setting:
...
- Ability to access or update site property bag entries.
...

[Allow or prevent custom script](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script)

**Comment by nextdarius** [comment]
Hi @gszdev and thanks for you reply.

I don't know if I'm right but, from what I see this only applies for SharePoint Online. Do you know if there's an alternative way of doing this for SharePoint 2019 On Premises?

**Comment by gszdev** [comment]
Hi @nextdarius,
did you check it?

It's also available for SharePoint 2019. See [SiteProperties.DenyAddAndCustomizePages property](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/dn174826(v=office.15))

You can use CSOM or PowerShell to check and change the value.

**Comment by nextdarius** [comment]
@gszdev I've tried it again and you're right. There's a small [difference](http://blog.konffaaja.com/2018/11/sharepoint-2019-and-2019-denyaddandcustomizepages/) for On-Premises though. It seems like the equivalent of the _DenyAddAndCustomizePages_ from SharePoint Online is _DenyPermissionsMask_ in SharePoint 2019.
Running the following powershell did the trick:
```
$site = Get-SPSite -Identity "<<SiteCollectionUrl>>"
$site.DenyPermissionsMask = [Microsoft.SharePoint.SPBasePermissions]::EmptyMask
```

I will close the issue. Thank you very much ! 👍
