### ISSUE TITLE
ClientSitePage Header is centered by default and when TextAlignment="Left"

### ISSUE THREAD

**Issue by HeToC** [SharePoint/PnP-Sites-Core#2332]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
1. When Left alignment specified TextAlignment="Left" page header should be aligned to the left side instead of being centered
            <pnp:Header Type="Custom" LayoutType="FullWidthImage"
                        ServerRelativeImageUrl="{site}/SiteAssets/DefaultPageHeaderImage.png" 
                        TranslateX="91.9007184846506" TranslateY="51.0714285714286"
                        TextAlignment="Left" />
   
2. When header text should be centered TextAlignment="Center" page header should be centered 
            <pnp:Header Type="Custom" LayoutType="FullWidthImage"
                        ServerRelativeImageUrl="{site}/SiteAssets/DefaultPageHeaderImage.png" 
                        TranslateX="91.9007184846506" TranslateY="51.0714285714286"
                        TextAlignment="Center" />

#### Observed Behavior
1. Page header is Centered (but not aligned to left side)
2. Page header is not centered

#### Steps to Reproduce

<?xml version="1.0"?>
<pnp:ProvisioningTemplate ID="SitePages" xmlns:pnp="http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema" Version="1" Scope="Web">
    <pnp:ClientSidePages>
        <pnp:ClientSidePage PageName="Content Page.aspx" Title="{PageTitle}" Overwrite="true" PromoteAsNewsArticle="false" EnableComments="false">
            <pnp:Sections>

            </pnp:Sections>
            <pnp:Header Type="Custom" LayoutType="FullWidthImage"
                        ServerRelativeImageUrl="{site}/SiteAssets/DefaultPageHeaderImage.png" 
                        TranslateX="91.9007184846506" TranslateY="51.0714285714286"
                        TextAlignment="Left" />
        </pnp:ClientSidePage>
    </pnp:ClientSidePages>
</pnp:ProvisioningTemplate>

#### versions
Generator="OfficeDevPnP.Core, Version=3.11.1907.0, Culture=neutral, PublicKeyToken=5e633289e95c321a

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 3.11.1907.0
SharePointPnPPowerShellOnline 3.2.1810.0

**Comment by jansenbe** [comment]
This used to be a bug in older version, can you ensure you use PS version 3.11.1907 or higher when you apply the template?

**Comment by jansenbe** [comment]
Closing per no feedback
