### ISSUE TITLE
Updating/Changing WebParts

### ISSUE THREAD

**Issue by peni4142** [SharePoint/PnP-Sites-Core#2345]
#### Category
[ ] Bug
[ ] Enhancement
[X] Questionable (I know not your category)

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Hi for the business model of my company I need to know how to update/change all webparts programmatically (c#).
The problem is every webpart is a black box and the behavior of each black box is different. If I learn something about one webpart, I don' know more about a second webpart. If I make the PropertiesJson same as a webpart created by hand, it doesn't work. If I make the ServerProcessesContent the same too, it does not work.
If I set Properties, which are not set by hand created webparts, it does work.
I can't find an API or Source Code for the standard webparts.

At this point, it seems there are endless possibilities to eventually update a webpart or maybe nonpossibility at all.

Sry for my broken English :-)

**Comment by jansenbe** [comment]
There's no native API for working with modern pages and web parts. The PnP Sites core library does have a modern page API that allows you to read a page, access it's information (sections, web parts), update it and persist it again. See https://www.youtube.com/results?search_query=sharepoint+pnp+modern+page+api for some PnP videos on that topic.

When it comes to understanding the needed web part syntax the best option is to configure the needed web part in the workbench (e.g. https://contoso.sharepoint.com/sites/mysite/_layouts/workbench.aspx) and then click on "Web part data" in the toolbar and copy the needed json.
