### ISSUE TITLE
[ProvisioningEngine] Possibility to specify FieldRef by Name

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#235]
Hi PnP team,

I'm looking at provisioning engine by XML, and trying to overcome some serious slowness I encounter with provisioning list instances. I'm converting `pnp:Field` into `pnp:FieldRefs` seen fields to reference are available at site level.
For what I can see in the source code, `FieldRef` elements must specify a valid ID in XML, because it's always retrieved by Id (_ContentType_ and _ListInstance_).
I would like to be able to specify a `FieldRef` element and provide the internal name of a field using `Name` attribute, without specifying an explicit id.

``` xml
...
<pnp:ListInstance Title="...">
  <pnp:FieldRefs>
    <pnp:FieldRef Name="Priority" />
...
```

Massimo

**Comment by PaoloPia** [comment]
Hi Massimo,
Thanks for your feedback. We will consider this proposed new capability for an upcoming release of the engine. However, it first requires a schema change. Thus, I created an issue in the schema repository. When the schema will be updated, we will be able to consider this new capability. In the meantime I will close this issue and keep open the one on the schema side. Thanks.

**Comment by biste5** [comment]
Paolo, I'm not sure it will require a schema change, and I'm not sure the current schema definition is 100% correct about this. I'll look into that and come back to you eventually asking for a quick heads-up.

Ciao
Massimo

**Comment by PaoloPia** [comment]
Massimo,
I just realized that we already support @Name for FieldRef elements. Thus, we simply need to add support in the engine. No need to change the schema.

**Comment by biste5** [comment]
Hi Paolo,

yes, for what I recap about the situation:
Schema supports fully FieldRef element already, but in the object handler it expects to find the ID correctly valued
https://github.com/OfficeDev/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs#L238

It would be nice that if I could express for _ListInstance _or _ContentType _definitions, the _FieldRef _elements just by their _InternalName_, so that I can make my provisioning less ID specific dependant (related to fields in this case).

Is this a good idea?

**Comment by PaoloPia** [comment]
Hi Massimo, 
Thanks for your feedback. We are in the process of supporting the new PnP Provisioning Schema and we will keep this suggestion in account. Thanks.

**Comment by PaoloPia** [comment]
Hi Massimo,
Sorry for the long wait. The capability is now implemented for FieldRefs of Content Types. Thanks.
