### ISSUE TITLE
Specific empty ComposedLook makes provisioning fail

### ISSUE THREAD

**Issue by heinrich-ulbricht** [SharePoint/PnP-Sites-Core#2353]
#### Category
- [x] Bug
- [ ] Enhancement

#### Environment
- [x] Office 365 / SharePoint Online
- [ ] SharePoint 2016
- [ ] SharePoint 2013

#### Expected or Desired Behavior
The following line was generated by a call to Get-PnPProvisioningTemplate on a STS#3 site:

`<pnp:ComposedLook Name="" ColorFile="" FontFile="" BackgroundFile="" Version="0" />`

When applying the template this line should not make problems.

#### Observed Behavior
Provisioning fails with above line. A null check is triggered:

PowerShell output:
![image](https://user-images.githubusercontent.com/3469970/62779557-d495a500-bab3-11e9-838a-5c4298e32f89.png)

BrandingExtensions.cs:

![image](https://user-images.githubusercontent.com/3469970/62779523-c051a800-bab3-11e9-912a-d2f500fba2ce.png)

#### Steps to Reproduce
In a template right between "Features" and "ClientSidePages" insert this:

`<pnp:ComposedLook Name="" ColorFile="" FontFile="" BackgroundFile="" Version="0" />`

Then apply the template.

**Comment by jansenbe** [comment]
fix merged, closing the issue
