### ISSUE TITLE
Client Side Page Header Issue - Image hosted in another site

### ISSUE THREAD

**Issue by bcameron1231** [SharePoint/PnP-Sites-Core#2355]
#### Category
[x] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

PnPPowerShell Version 3.11.1907.0
#### Expected or Desired Behavior

When specifying an image from an Organizational Assets library on another site collection, I expect I should be able to define the path to that image in the PnP Template. I am looking to standardize the deployment of new sites in a Hub Site configured Intranet. I want all sites to use the same image from an Organizational  Assets library

This works when setting the picture using the SharePoint Interface.

#### Observed Behavior

When specifying an image outside the current site, the client side page will not be deployed with the page header.

#### Steps to Reproduce

1. Create a PnP Template that deploys a client side page
2. Specify the <PnP:Header> node ServerRelativeImageUrl to be on another site collection
3. Page will  be created but header will be blank

```
 <pnp:Header 
            Type="Custom" 
            ServerRelativeImageUrl="/sites/HubSite/Organizational Assets/Banner.jpg" 
            TranslateX="50" 
            TranslateY="70.3571428571429" 
            LayoutType="FullWidthImage" 
            TextAlignment="Center" 
            ShowTopicHeader="false" 
            ShowPublishDate="false" 
            TopicHeader="" 
            AlternativeText="" 
            Authors="*sanitized*" 
            AuthorByLineId="-1" 
          />
```

However, referencing an image within the site I am deploying (also deploying file using PnP:File) does work.
```
 <pnp:Header 
            Type="Custom" 
            ServerRelativeImageUrl="{site}/SiteAssets/Banner.jpg" 
            TranslateX="50" 
            TranslateY="70.3571428571429" 
            LayoutType="FullWidthImage" 
            TextAlignment="Center" 
            ShowTopicHeader="false" 
            ShowPublishDate="false" 
            TopicHeader="" 
            AlternativeText="" 
            Authors="*sanitized*" 
            AuthorByLineId="-1" 
          />
```

I would prefer to use the Organizational Assets library.

**Comment by jansenbe** [comment]
fix merged
