### ISSUE TITLE
SharePoint Multiselect Choice field Saving using PnPjs

### ISSUE THREAD

**Issue by Nagarajan1605** [SharePoint/PnP-Sites-Core#2357]
Hi 

I want to save multiselect dropdown in sharepoint field. I already referred few results in this site. 
Choice values in SharePoint : Test1,Test2,Test3,Test4,Test5.

From the custom dropdown choice field user will select multiple values i want to save the data in multiselect choice field in sharepoint list. 

Now am getting results as
var testvalue="'Test1','Test2'";

$pnp.sp.web.lists.getByTitle("TestList").items.add({
Testchoicefield:{results:[testvalue]},
LastModifiedByDisplayName:_DisplayUserName,
LastModifiedByUserId:_CurrentUserID,
LastModifiedOn:_modifiedon

}).then(function(resultdata) {
idvalue = resultdata.data.Id;
ShowMsgaddupdate("Data Saved Successfully", "", "Ok");

But am not able to save the item. Its throwing error. could you please help me.

**Comment by ganeshsanap120694** [comment]
You are passing Choices array in wrong way.

You can create your choices array as given below:

`var choicesArray = ["Test1", "Test2"];`

Then pass it in the items.add() function as:
```
$pnp.sp.web.lists.getByTitle("TestList").items.add({
    Testchoicefield: { results: choicesArray },
    LastModifiedByDisplayName: _DisplayUserName,
    LastModifiedByUserId: _CurrentUserID,
    LastModifiedOn: _modifiedon
}).then(function (resultdata) {
    idvalue = resultdata.data.Id;
    ShowMsgaddupdate("Data Saved Successfully", "", "Ok");
});
```

**Comment by Nagarajan1605** [comment]
Thanks Ganesh

**Comment by ganeshsanap120694** [comment]
Welcome. Is it working for you now?

**Comment by Nagarajan1605** [comment]
yes its working

**Comment by jansenbe** [comment]
closing since issue is resolved. Also please create PnPJS issues in the PnP JS issue list next time: https://github.com/pnp/pnpjs/issues
