### ISSUE TITLE
CanvasControl->GetType fails to deserialize zoneEmphasis because "undefined"

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2369]
## Category
[x ] Bug related to #2318 
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Load ClientSidePage to read control data

#### Observed Behavior
ClientSidePage Load fails in CanvasControl->GetType to deserialize zoneEmphasis since data structure changed and mapping to int fails for "undefined".

Sample controlDataJson from new Page which creates the issue:
{"controlType":4,"displayMode":2,"id":"6f9230af-2a98-4952-b205-9ede4f9ef548","position":{"zoneIndex":1,"sectionIndex":1,"controlIndex":1,"sectionFactor":8,"layoutIndex":1},"emphasis":{"zoneEmphasis":"undefined","sectionEmphasis":"undefined","controlEmphasis":"undefined"},"anchorComponentId":"6f9230af-2a98-4952-b205-9ede4f9ef548","editorType":"CKEditor","addedFromPersistedData":true}

#### Steps to Reproduce
Create new Page on Tenant with new Feature for sectionEmphasis and controlEmphasis. Add Text WebPart and set nothing for Emphasis.

@jansenbe - Mention you because you assigned the #2318 to yourself and this belongs to same section but i have included the whole JSON

**Comment by czullu** [comment]
I close this one since for "zoneEmphasis":"undefined" we have already a pull request 
 and i can not reproduce the "sectionEmphasis":"undefined","controlEmphasis":"undefined" with the Text-WebPart today.
Sorry for inconvenience - might better just wait a few days and see if things disappear by them self in future..

**Comment by jansenbe** [comment]
Thx for explaining the repro steps @czullu . Will look into the open PR for this.
