### ISSUE TITLE
GetTemplate does not Escape " in Values of jsonControlData

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2370]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Use GetTemplate to extract ClientSidePages and try to apply to new site

#### Observed Behavior
If you have a App with a Description like "This "Super" Cool App" you will find in Pnp-XML 
pnp:CanvasControl ->JsonControlData -> that the inner " are not escaped.

In ApplyTemplate you will fail in ObjectClientSidePages.ProvisionObjects because the resulting control.JsonControlDatais not valid.

#### Steps to Reproduce
You need a Custom App with Title or Description with " in it.

**Comment by jansenbe** [comment]
PR merged. Closing issue
