### ISSUE TITLE
ssue in Apply-PnPProvisioningTemplate - The specified user 3 could not be found.

### ISSUE THREAD

**Issue by in8rakhi** [SharePoint/PnP-Sites-Core#2385]
Issue in Apply-PnPProvisioningTemplate - The specified user 3 could not be found.
Observed Behavior
After updating the pnp provisioning powershell version 3.9.1905.3, we are getting below error:
Apply-PnPProvisioningTemplate : The specified user 3 could not be found.
Microsoft.SharePoint.Client.Runtime: The specified user 3 could not be found.

Here are below steps to reproduce the issue:
Create a SharePoint group on a team site . Any custom group other than default three groups.
Go to groups settings and change the newly created group's owner as site's owners group
Get the new provisioning xml using Get-PnPProvisioningTemplate command
When we apply the template using apply provisioning command, custom group will not get created on the newly provisioned site and provisioning fails giving below error:
"The specified user 3 not found"

**Comment by NicolajHedeager** [comment]
Is this related the issue #2281?
It should have been fixed in the commit for the issue or the newly PR #2444

**Comment by PaoloPia** [comment]
I will close this item, because the related PR has just been merged into DEV.
