### ISSUE TITLE
Provision template default values for unspecified attributes 

### ISSUE THREAD

**Issue by jensotto** [SharePoint/PnP-Sites-Core#2413]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2019
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
All

#### Expected or Desired Behavior
When a provisioning template is applied that does not specify one or more attributes, the value of those attributes should not be set to the hard coded default value specified in the provisining engine/template.

#### Observed Behavior
Many attributes that are not specified in the template are set to a template hard coded default value or cleared/set to an empty value.

#### Steps to Reproduce
Not specifying the NoCrawl attribute will set the site NoCrawl property to false.
Not specifying the description attribute for a list will clear any existing description for that list.

These are just examples. Almost all of the template attributes behaves in this maner, and makes it difficult to use provisioning templates for much else than provisioning new unused sites. Modifying existing sites using templates can result in lost data, or unwanted/unintended changes.

**Comment by PaoloPia** [comment]
Hi @jensotto,
Thanks for your contribution. We're processing this issue and the PRs related to this, so I will close this item.
