### ISSUE TITLE
Import Error with Office365GroupsSettings based on 201909 Schema

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Sites-Core#2434]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Try to Import Template XML created before with October PnP release to apply to SIte. 

#### Observed Behavior
@PaoloPia : On Import of PnP-XML by GetTemplate i have the Error:
2019-10-07 22:01:01.5441	[SchemaFormatter]	[0]	[Error]	Template is not valid: The element 'Office365GroupsSettings' in namespace 'http://schemas.dev.office.com/PnP/2019/09/ProvisioningSchema' has incomplete content. List of possible elements expected: 'Property' in namespace 'http://schemas.dev.office.com/PnP/2019/09/ProvisioningSchema'.	0ms	

In XML from the Export i find the section which to my opinion should not be there as long as it's not a Tenant Template.
  <pnp:Tenant>
    <pnp:Office365GroupsSettings />
  </pnp:Tenant>
At least removing this section manually does solve the Problem.

#### Steps to Reproduce
use ctx.Web.GetProvisioningTemplate(ptci) to create a Template from Site and XMLOpenXMLTemplateProvider to save Template to file. Use same provider to read from Template using GetTemplate will fail.

**Comment by czullu** [comment]
Simplified solution to the issue - if no Entries in List set Office365GroupsSettings to null before calling SaveAs
ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);
if(!template.Tenant.Office365GroupsSettings.Any()) template.Tenant.Office365GroupsSettings=null;
XMLTemplateProvider provider3 = new XMLOpenXMLTemplateProvider(ptci.FileConnector as OpenXMLConnector);
provider3.SaveAs(template, "PnPConfig.xml");

**Comment by PaoloPia** [comment]
Hi @czullu,
Thanks for your feedback. Quick question for you: what is the schema version of the template that you're reading, and what is the version that you are using to save it? Thanks.

**Comment by PaoloPia** [comment]
Hi @czullu,
I think that I managed to find the issue, it is now merged into DEV. Could you please give it a try and let me know? Thanks.

**Comment by czullu** [comment]
Hi @PaoloPia,
i can confirm that this does fix the issue. Thanks.

**Comment by ryujinjakka** [comment]
Same error found for the SP2016 version (SharePointPnPPowerShell2016 3.14.1910.0). 
Waiting for your answer, I solved by removing the "pnp: Tenant" node from the XML file.
