### ISSUE TITLE
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

### ISSUE THREAD

**Issue by Ofer-Gal** [SharePoint/PnP-Sites-Core#2452]
OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I am developing an Azure Function to apply an XML template to new sites.
The template is stored in a SharePoint library and I can tell that the stream includes all the lines of the file.
So running 
`  ITemplateFormatter formatter = XMLPnPSchemaFormatter.GetSpecificFormatter("http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema"); //Use the same version as the PnP template
                    template = formatter.ToProvisioningTemplate(streamX.Value);` 
should work fine.

#### Observed Behavior

I get an error:
`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`
I don't know how to  "Retrieve the LoaderExceptions property"

Thanks for the help

**Comment by mkorek** [comment]
Not sure if this will help but....we got this error the other day and it was caused by a mismatch of dll versions between projects in our solution.  So to fix the issue we updated the dll's to use the same version across the solution, cleared the web job in azure, and redeployed.

**Comment by Ofer-Gal** [comment]
Thanks.
Recreating the project, solved it.
