### ISSUE TITLE
Setting a Lookup Column to have a default value

### ISSUE THREAD

**Issue by hbash2020** [SharePoint/PnP-Sites-Core#2502]
I have a list with a lookup column.  The lookup list has a value of "None".  I am trying to set the list's lookup default value to be the value "None".

I have tried the following: 

Set-PnPDefaultColumnValues -List Documents -Field Category -Value "None"

This fails.  The error message is:

Set-PnPDefaultColumnValues : Error applying default column values
At line:1 char:1
+ Set-PnPDefaultColumnValues -List Documents -Field Category -Value "No ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPDefaultColumnValues], Exception
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Lists.SetDefaultColumnValues

Any suggestions would be greatly appreciated.

**Comment by jackpoz** [comment]
I was able to set a default value to a Lookup column by using Set-PnPField, in particular
```powershell
Set-PnPField -List $list -Identity $lookupfield -Values @{DefaultValue=$noneItemFormatted}
```
The DefaultValue has to be specified in the usual format "ID;#Value", for example "4;#None"

Here is a script with how to reproduce steps using version 363df50e95bff6aa111f33db7296f201669c9b6c
```powershell
# Connect to the site
Connect-PnPOnline $siteUrl -Credentials $credential

# Setup child list
New-PnPList -Title "ChildList" -Template GenericList
$childList = Get-PnPList "ChildList"
Add-PnPListItem -List $childList -Values @{Title="Empty"}
$noneItem = Add-PnPListItem -List $childList -Values @{Title="None"}
Add-PnPListItem -List $childList -Values @{Title="Something else"}

# Setup the parent list
New-PnPList -Title "ParentList" -Template GenericList
$parentList = Get-PnPList "ParentList"
Add-PnPField -List $parentList -DisplayName "Lookup to ChildList" -InternalName "lookuptochildlist" -Type Lookup -AddToDefaultView
Set-PnPField -List $parentList -Identity "lookuptochildlist" -Values @{LookupList=$childList.Id.ToString(); LookupField="Title"}

# Set the default value
$noneItemFormatted = "$($noneItem.Id);#$($noneItem['Title'])"
Set-PnPField -List $parentList -Identity "lookuptochildlist" -Values @{DefaultValue=$noneItemFormatted}

# Try adding a new item and check the lookup value
$newItem = Add-PnPListItem -List $parentList -Values @{Title="Testing the lookup"}
$newItem["lookuptochildlist"].LookupValue

```

**Comment by hbash2020** [comment]
That's very cool.  Thanks!!!
