### ISSUE TITLE
OfficeDevPnP is no longer there

### ISSUE THREAD

**Issue by Andrewsimmans** [SharePoint/PnP-Sites-Core#2539]
From Version 3.17 onwards of SharePointPnPCoreOnline the namespace OfficeDevPnP is no longer there and I cannot find any reference to GetWebLoginClientContext or similar - what is the equivalent of these now?

**Comment by VesaJuvonen** [comment]
Since there has not been any changes on used namespace, can you be slightly more specific on how you use the code, what you use the imports and how the code is referenced. Most likely as a NuGet package, but all details helping to understand your setup would be useful, as we cannot repro this.

Are you having an issue when you reference OfficeDevPnP in your code or having issues when using this code base? Or?

thanks for the details advance, so that we understand how to provide you assistance.

**Comment by Andrewsimmans** [comment]
Hi,

What happens is that I have installed 3.16.1912 via Nuget and followed an example of the web to include in my code the following:

When I upgrade to 3.18.2002 (or any release after 3.16.1912) my code fails to compile and it says "The type or namespace name 'OfficeDevPnP' could not be found (are you missing a using directive or an assembly reference?"

When I search using the object browser for "GetWebLoginClientContext" it appears when I have version 3.16.1912 - but not for later versions.

I am writing in C# using Visual Studio 2019.
My code is:
 var authenticationManager = new OfficeDevPnP.Core.AuthenticationManager();
                ClientContext context = authenticationManager.GetWebLoginClientContext(SharePointSite);

 
I enclose some screen shots - showing the same code with the two different Nuget packages installed.

I hope that helps as it is really confusing me why something should suddenly "disappear".

![Nuget 3 18 2002 Installed](https://user-images.githubusercontent.com/20963675/74133812-4eccf080-4be1-11ea-85c8-2baaa1c26ee9.png)
![Object Browser with 3 16 1912 Installed](https://user-images.githubusercontent.com/20963675/74133814-4f658700-4be1-11ea-81e2-abeb7a34eeb3.png)
![Code with 3 16 1912 Installed](https://user-images.githubusercontent.com/20963675/74133816-4ffe1d80-4be1-11ea-9cdf-42e6b599dea4.png)
![Nuget 3 16 1912 Installed](https://user-images.githubusercontent.com/20963675/74133817-5096b400-4be1-11ea-97d1-829be4e8fb38.png)
![Code with 3 18 2002 Installed](https://user-images.githubusercontent.com/20963675/74133819-5096b400-4be1-11ea-8862-df510e9f93a4.png)
![Object Browser with 3 18 2002 Installed](https://user-images.githubusercontent.com/20963675/74133820-512f4a80-4be1-11ea-8062-d76bbf47e1c8.png)

**Comment by Tanddant** [comment]
How did you resolve this, I'm stuck with the same issue, I feel like I'm missing the obvious.

**Comment by Andrewsimmans** [comment]
For anyone else struggling with this - the problem is the .net version - .net framework 4.6 does not work on 3.16.1912 and later - you have to go for a later .net version (sorry I don't know what is the minimum - but it does work on 4.7.2).
