### ISSUE TITLE
GetProvisioningTemplate stucked in Site Footer

### ISSUE THREAD

**Issue by Brank** [SharePoint/PnP-Sites-Core#2564]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version:  

#### Expected or Desired Behavior
The next line should return a valid ProvisioningTemplate
`ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);`

#### Observed Behavior
The script get stucked while executing, it doesn't return any exception and it doesn't stop the application it just get stucked like if it still working:, specifically in Site Footer step

`ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);`

#### Steps to Reproduce
1) Create a new Windows Forms Application using Visual studio
2) Install nuget package "SharePoint PnPCoreOnline"
3) Use the example code using here: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/provisioning-console-application-sample
4) Execute de application

The application that I am working on is using .NET Framework 4.7.2, SharePointPnPCoreOnline v3.18.2002.

¿Am I missing something?

Best regards,

**Comment by jimmywim** [comment]
Which type of site did you create/which template did you use for your source site?

**Comment by Brank** [comment]
> Which type of site did you create/which template did you use for your source site?

Hi,
It is a communication site, I've created it using blank template. It has few pages with few OOB webparts.

The weird thing is that I don't have any problem if I get the provisioning template with Powershell, but I am trying to get it with a Winform application.

Best regards,

**Comment by RihardsVla** [comment]
Same here.
This is first time attempting to use provisioning engine.
Hangs on 12/19 - SiteFooter
Site: modern communication site.
Also very slow (10 minutes) on 07 - Lists instances step, site itself has no custom lists at all.
Site is Hub site.,
Same result with different comunictaion site, not hub, no customization except modified first page.

**Comment by RihardsVla** [comment]
.net 4.8, windows Form app. installed the nuget yesterday (with whatever version was latest)

**Comment by RihardsVla** [comment]
and in my case this SharePoint online

**Comment by RihardsVla** [comment]
This is an issue with current version of either PNPCore or CSOM.
How I know:
I created identical (exact same code) WinForms app but instead added these nugets:
SharePointPnpCore 3.4.1812.1
SharpointOnline.Csom 16.1.8924.1200

**Everything** (getting  pnp template from same site) **worked**.

Note: attempting to downgrade nugets after todays version has already been applied to project DOES not help. Apearantly something does not downgrade correctly. I noticed that assambly overides in config does not downgrade, but even fixing them manually do not help (or I did not find all of them). Something else also does not downgrade.

**Comment by Brank** [comment]
> This is an issue with current version of either PNPCore or CSOM.
> How I know:
> I created identical (exact same code) WinForms app but instead added these nugets:
> SharePointPnpCore 3.4.1812.1
> SharpointOnline.Csom 16.1.8924.1200
> 
> **Everything** (getting pnp template from same site) **worked**.
> 
> Note: attempting to downgrade nugets after todays version has already been applied to project DOES not help. Apearantly something does not downgrade correctly. I noticed that assambly overides in config does not downgrade, but even fixing them manually do not help (or I did not find all of them). Something else also does not downgrade.

Hi RihardsVla,
Thanks for your feedback. May I know if you have the same issue while applying the provisioning template? I get stucked as well in Site Footer while Apying Provisioning Template.

Is it posible that maybe the Object Handler of Site Footer has something wrong?
I will check it in the code to see if I can get it fixed.

Regards,

**Comment by Brank** [comment]
Hi I think I make it work.
I was debugging the library and I saw that it got stucked in ExecutePost and ExecuteGet from RestUtilities.cs. I've seen that probably the cause was a deadlock between the thread that runs the UI and the threads behind that executes the code.

For make it work I basically change this:

`request.Headers.Add("X-RequestDigest", await (web.Context as ClientContext).GetRequestDigest());`

to this:

```
var requestDigest = await (web.Context as ClientContext).GetRequestDigest().ConfigureAwait(false);
request.Headers.Add("X-RequestDigest", requestDigest);
```

Hope someone can check this out and see if this is the correct solution or not.

Best regards,

**Comment by Brank** [comment]
I put the changes in this fork so someone can see the fix I made for it.

https://github.com/Brank/PnP-Sites-Core/commit/fbac57f232109c81da83e79193121e84e54c5057

I've tested it using GetProvisioningTemplate and ApplyProvisioningTemplate and it seems working.

Best regards,

**Comment by Sarah4x** [comment]
@Brank Thanks for figuring this out! I hope they get this fix implemented soon! It's kinda a big deal not being able to create templates from communication sites.

**Comment by jackpoz** [comment]
@Brank could you please open a pull request with the fix (and without the "&& true" condition) ?
