### ISSUE TITLE
Lookup field on hidden list is not possible (?)

### ISSUE THREAD

**Issue by tberst** [SharePoint/PnP-Sites-Core#292]
I wanted to provision a lookupfield between two hidden lists, and this is somehow prevented by the provisioning framework.
In the ObjectLookupFields class / ProcessLookupFields(...) method, hidden list are deliberately ignored.

For instance, at line 84 : 

```
        web.Context.Load(web.Lists, lists => lists.Include(l => l.Id, l => l.RootFolder.ServerRelativeUrl, l => l.Fields).Where(l => l.Hidden == false));
        web.Context.ExecuteQueryRetry();
```

If you remove the `Where(l => l.Hidden == false)`, the lookup column is created and fully functionnal.

I'd be glad to know if there is something i should care about when provisioning lookups on hidden lists.

**Comment by PaoloPia** [comment]
Hi Tberst,
Thanks for using PnP. As far as I know the aren't real side effects of using an hidden list for a lookup column. However, by default we exclude hidden lists from the query just to avoid "noise" potentially coming from a bunch of out of the box or infrastructural hidden lists. If you really need the capability to rely on hidden lists for lookups, we can keep in account the request to change the native behavior. Or - if you like - you can submit a PR to change this behavior. In the meantime I will close this issue. Thanks.
