### ISSUE TITLE
View-Id Token for Provisioning Enginge

### ISSUE THREAD

**Issue by retostadelmann** [SharePoint/PnP-Sites-Core#309]
We provision Wiki Pages with Web Parts through the PnP Provsionoing Engine and need to implement a custom view in XML Webpart Definition. There is currently no Token available to get the View ID as a token, f.e. {viewid:ListTitle,ViewName}

**Comment by PaoloPia** [comment]
Hi,
I implemented the new capability in #925. I will close this item. Thanks for your feedback.
