### ISSUE TITLE
[Suggestion] Allow forwardslash separator in FileSystemConnector

### ISSUE THREAD

**Issue by spcfran** [SharePoint/PnP-Sites-Core#357]
I've getting this exception while trying to apply a XML PnP template to a site:

```
Unhandled Exception: System.ArgumentException: The argument must be a single file name and cannot contain path characters.
Parameter name: fileName
   at Microsoft.SharePoint.Client.FileFolderExtensions.UploadFile(Folder folder, String fileName, Stream stream, Boolean overwriteIfExists)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectFiles.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, Prov isioningTemplateApplyingInformation applyingInformation)
   at [...etc...]
```

because I've mistakenly used forwardslashes in the `Src` attribute of a file while using a `FileSystemConnector`

``` xml
<pnp:File Src="path/to/file.txt" [...] />
```

Obviously being a local file in windows, a path delimited with `\` would be expected. But:
- The AzureStorage and SharePoint connectors use `/`. If you decide to change from one of those to FileSystem, you'd have to rewrite any file references.
- Unlike the `Path` attribute in traditional SharePoint modules which uses `\`, the `Src` attribute in html typically refers to URLs with `/`. I guess this is why I got confused at the first time.

Since adding `/` support for FileSystem connectors along with the existing `\` wouldn't break anything (you can't use `/` in files in any case), I thought it could be worth considering applying the "Open in what you accept" principle and support either character as a separator, to prevent people from getting this exception in the future (or from rewriting XML upon changing the connector type)

**Comment by jansenbe** [comment]
Makes sense and good enhancement suggestion

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
