### ISSUE TITLE
TokenizeWebPartXml

### ISSUE THREAD

**Issue by braegelno5** [SharePoint/PnP-Sites-Core#359]
the same as before seen by another tokenizer; if i run the code on a uri http://sub.sld.tld/SitePages/Homepage.aspx i get for the current web.ServerRelativeUrl a slash and now all slashes in the web part xml will be replaced with {site} and in the end the pnp xml schema builder is crashing, a PR will follow

**Comment by VesaJuvonen** [comment]
Thx Torsten, this is actually the same issue as #329 or due similar reasons. Things work fine if you work on sub site collections. Root site collections in tenant or web applications have now small issues. This seems to be for on-premises - right?

**Comment by braegelno5** [comment]
No Vesa ;) The same not so good message comes on SP15/16/Online without a managed path. But mostly we will run the pnp save as template and create site from template on a managed path web. But in the end it must also work on the root of a sp webapplication  host.

**Comment by braegelno5** [comment]
The tokenize method in object base has similar problems on root webs, but there we get a template, that's not working on the target root or sub, because the {site} ist not added before the /. My last PR for this was blown in the wind;)

**Comment by braegelno5** [comment]
The fix for the web part tokenizer will be, to do nothing on the line where the server relative url is used if this url is only a /

**Comment by erwinvanhunen** [comment]
Hi Torsten,

Does this issue still stand?

**Comment by PaoloPia** [comment]
Hi Torsten,
Can we consider this issue closed? Thanks.

**Comment by erwinvanhunen** [comment]
I just checked the tokenizer in the PageContents handler and the correct code to handle tokenization is there. In case this issue still stands, do not hesitate to reopen it.
