### ISSUE TITLE
Workflow custom content type task doesnt show the approve/reject button through site provisioning engine.

### ISSUE THREAD

**Issue by srirams007** [SharePoint/PnP-Sites-Core#363]
Tried with custom workflow content type for my application. observed that when I create a custom content type of "workflow task" through engine, UI doesn't show the approve/reject button. The same is working as expected if I create the content type manually.

**Comment by PaoloPia** [comment]
Hi srirams007,
Happy New Year! Can you share the XML of the template that you are using to create the custom worklow task content type? Thanks.

**Comment by PaoloPia** [comment]
Hi srirams007,
I don't see any answer. In the meantime I will close this issue. Feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.
