### ISSUE TITLE
[Provisioning Engine] The BackgroundUrl is not downloaded, but an entry is created in the Files collection

### ISSUE THREAD

**Issue by sureshbooms** [SharePoint/PnP-Sites-Core#368]
When the BackgroundUrl is set in a SharePoint theme, the file itself is not extracted to the FileConnector location, but an entry for this file is created in the Files collection

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. You should provide the PersistBrandingFiles flag during template extraction, in order to download those files. I will close this item.

**Comment by sureshbooms** [comment]
Hi,

I have doubled checked, but the PersistBrandingFiles flag is set to 'true' and the file configured as the backgroundUrl is not downloaded. So, I have reopend this item.

**Comment by PaoloPia** [comment]
Sure :) ... but I need much more context. Can you describe the exact steps that you made? Can you eventually share the template? Thanks.

**Comment by sureshbooms** [comment]
As part of the SharePoint theme, I have set the BackgroundUrl on the site collection where I would like to extract the template from.

Then I have used the following code-snippet:


Then I have used the GetProvisioningTemplate method to extract the template, but before executing this method, I have set the PersistBrandingFiles = true. I have saved the extraction to disk using the The extraction includes BackgroundUrl

Met vriendelijke groet / Kind Regards,

Suresh Booms
Solution Architect
v-suresb@microsoft.com<mailto:v-suresb@microsoft.com>
+31 (0)6 46 284 213

**Comment by sureshbooms** [comment]
As part of the SharePoint theme, I have set the BackgroundUrl on the site collection where I would like to extract the template from.

Then I have used the following code-snippet:

ProvisioningTemplateCreationInformation ptci
                        = new ProvisioningTemplateCreationInformation(ctx.Web);

                // Create FileSystemConnector, so that we can store composed files temporarely somewhere
                ptci.FileConnector = new FileSystemConnector(string.Format(@"c:\temp\{0}", templateName), "");
                ptci.PersistBrandingFiles = true;
                ptci.ProgressDelegate = delegate(String message, Int32 progress, Int32 total)
                {
                    // Only to output progress for console UI
                    Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
                };

                // Execute actual extraction of the tepmplate
               ProvisioningTemplate template = ctx.Web.GetProvisioningTemplate(ptci);

                // We can also serialize this template for future usage if we want, not really needed
               if (saveToDisk)
               {
                   XMLTemplateProvider provider =
                       new XMLFileSystemTemplateProvider(string.Format(@"c:\temp\{0}", templateName), "");
                   provider.SaveAs(template, string.Format("PnPProvisioningDemo_{0}.xml", templateName));
               }


The extraction includes the BackgroundUrl, the Files collection includes an entry of this file as well, but the file is not downloaded to the FileConnector location.

Met vriendelijke groet / Kind Regards,

Suresh Booms
Solution Architect
v-suresb@microsoft.com<mailto:v-suresb@microsoft.com>
+31 (0)6 46 284 213

**Comment by erwinvanhunen** [comment]
I investigated this issue and found out that when you customize a composed look with a custom image by dragging and dropping it onto the apply composed look form, the engine will not extract that file. However, when you create a new composed look through the engine, and subsequently you extract that template, the engine will extract and download the file if you specify the PersistBrandingFiles switch. I will investigate if we can retrieve and download the image if its uploaded through modifying the composed look in the browser.

**Comment by jansenbe** [comment]
The engine allows you to have the files in the template without downloading them. We recently declined a PR for changing this behavior. See #960 for more details on the reasoning. Closing this issue now.
