### ISSUE TITLE
MINIMUMZONEIDREQUIREDSERVERVERSION constants.cs

### ISSUE THREAD

**Issue by braegelno5** [SharePoint/PnP-Sites-Core#377]
on SP15 my farm shows Configuration database version:
15.0.4797.1000
on csom clientContext.ServerLibraryVersion gets:
15.0.4763.1000
and the  MINIMUMZONEIDREQUIREDSERVERVERSION for CLIENTSDKV15 is defined to
15.0.4787.1000

i'm a little bit confused.. a bug in the farm patches?

**Comment by erwinvanhunen** [comment]
It's an issue with the on-prem CSOM SDK. We are aware of it and it has been reported to the product group.

**Comment by bturkenburg** [comment]
Hi @erwinvanhunen is there already a solution for this? I'm getting the warning: "Page content export requires a server version.... Server version is 15.0.4763.1000, minimal required is 15.0.4787.1000" When using the command: Get-SPOProvisioningTemplate

**Comment by PaoloPia** [comment]
This PR #1005 completely fixed the issue, while waiting for a fix from PG in CSOM.
