### ISSUE TITLE
Provisioning engine does not implement "Manage content types" setting

### ISSUE THREAD

**Issue by LenCardinal** [SharePoint/PnP-Sites-Core#379]
The provisioning engine does not set the "Allow management of content types" setting on a document library, even if it is specified in XML.
The XML below:

<pnp:ListInstance Title="Documents" Description="" DocumentTemplate="{site}/Shared Documents/Forms/template.dotx" OnQuickLaunch="true" TemplateType="101" Url="Shared Documents" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-e717-4e80-aa17-d0c71b360101" **ContentTypesEnabled="true"** EnableAttachments="false">

does not result in content types being enabled

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This issue has been fixed a few months ago. Thus, I will close this item. If you will still experience any issue, please feel free to re-open this item and to let us know. Thanks.
