### ISSUE TITLE
Apply-SPOProvisioningTemplate fails But Does Not Say Which List has failed

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#393]
Hi 

It is not clear what value is out of range below - how do I find out (I think the offending entry is a view in each case)  :-

PS C:\WINDOWS\system32> Apply-SPOProvisioningTemplate

cmdlet Apply-SPOProvisioningTemplate at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Path: C:\Users\Nigel\Documents\Visual Studio 2015\Projects\CSOM\provisioningtemplate01112015_4.xml
Apply-SPOProvisioningTemplate : /Lists/Nonxx Persons : Value does not fall within the expected range.
/Lists/Responsibilities : Value does not fall within the expected range.
/Lists/Services : Value does not fall within the expected range.
/Pages : Value does not fall within the expected range.
At line:1 char:1
- Apply-SPOProvisioningTemplate
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ServerException
  - FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

Thanks

Nigel

**Comment by mrpullen** [comment]
Use:
Set-SPOTraceLog -On -LogFile "provisioning-log.txt" -Level Debug should help

**Comment by PaoloPia** [comment]
Hi Nigel,
Is the above feedback enough? Can we consider this issue/request closed? Thanks.

**Comment by PaoloPia** [comment]
Hi Nigel,
Happy New Year. Since there was no answer in the last 25 days, I will close this item. Feel free to re-open it if it is not yet completed. Thanks.
