### ISSUE TITLE
DocIcon gets falsely added to view

### ISSUE THREAD

**Issue by retostadelmann** [SharePoint/PnP-Sites-Core#396]
We are using two provisioning templates. One is for creating the site structure with fields, content types and lists. This operation is working as expected, everything gets created as defined in the template. 

The other template is used to seed data into the created lists. While the site structure template can be applied more than one time, the data should only be seeded once into the lists, as there would be duplicated data, if applied more than one time. Thats why we can't include the data rows into the template, where the lists are created.

So, i copied the list instances and removed all the not requierd properties and added the data rows in the second template:

`<pnp:ListInstance Title="Fahrzeugkategorien"
                          TemplateType="100"
                          Url="Lists/Fahrzeugkategorien">
          <pnp:DataRows>
            <pnp:DataRow>
              <pnp:DataValue FieldName="Title">Gelenkautobus</pnp:DataValue>
              <pnp:DataValue FieldName="VehicleCategoryDescription">GA</pnp:DataValue>
            </pnp:DataRow>
</pnp:DataRows>
</pnp:ListInstance>`

Once this template is applied, it adds the DocIcon Column to the already provisioned view, even if its not specified in either one of the templates:

![2016-02-18_15-44-32](https://cloud.githubusercontent.com/assets/10433328/13146530/8b789e6c-d656-11e5-9efd-d80b6982721b.png)

Everything else stays untouched and the data is added, so this might be a bug in the core.

**Comment by PaoloPia** [comment]
Hi,
Can you share the two templates so that we can do proper testing? Thanks.

**Comment by retostadelmann** [comment]
Hi @PaoloPia 

Please find the files attached.
[InitialData.xml.txt](https://github.com/SharePoint/PnP-Sites-Core/files/645256/InitialData.xml.txt)
[MasterData.xml.txt](https://github.com/SharePoint/PnP-Sites-Core/files/645255/MasterData.xml.txt)

**Comment by retostadelmann** [comment]
Hi @PaoloPia 
As this issue is quite old now, it might was fixed in the meantime anyway. But i could not figure out the issue either back then, looking at how the templates are built.
You could reproduce this issue easily by creating one template with the list structure, and one with only the list items in it. We had the issue even with simple lists, like one custom field. When applying the listitemdata template, the docicon column was added.

**Comment by PaoloPia** [comment]
Hi,
I investigated the issue and it is not really an engine issue. You simply need to add the following attribute to the <pnp:ListInstance /> element:

EnableFolderCreation="false"

Otherwise the default value for that property will be true and SharePoint (by itself) will automatically add the DocIcon field to the "All Items" view. Thus, I will close this item. Thanks for using PnP.
