### ISSUE TITLE
{site} again

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#406]
I'm using the mid February release.

The welcome page is now exported and the {site} is exported incorrectly in the publishing page layout. I'm exporting from the root site. and every '/' is now replaced. This issue is very similar to the issue that I logged a while back where this happens in different parts of the engine. See #329 

 < pnp:File Src="home.aspx" Folder="{site}/Pages" Overwrite="true">
          < pnp:Properties>
            < pnp:Property Key="ContentTypeId" Value="{contenttypeid:Welcome Page}" />
            < pnp:Property Key="Title" Value="Home" />
            < pnp:Property Key="PublishingPageLayout" Value="https:{site}{site}meggitt.sharepoint.com{site}_catalogs{site}masterpage{site}My%20Home%20Page.aspx, MyHome Page" />
            < pnp:Property Key="PublishingIsFurlPage" Value="False" />
            < pnp:Property Key="RobotsNoIndex" Value="False" />
            < pnp:Property Key="PublishingPageContent" Value="&lt;p&gt;​​​​&lt;br&gt;&lt;{site}p&gt;" />

For subsites {masterpagecatalog} is appearing. It looks like for the root site things are going wrong only.

**Comment by PaoloPia** [comment]
Hi Pieter,
As you can argue, we're trying to process the backlog of issues. This should have been fixed (as far as I know) can you confirm? Thanks.

**Comment by PaoloPia** [comment]
Hi Pieter,
in the meantime, I will close this one. Feel free to re-open it if needed. Thanks.
