### ISSUE TITLE
File provisioning does not support parameter replacement

### ISSUE THREAD

**Issue by warrenroscoe** [SharePoint/PnP-Sites-Core#410]
I have tried the following in a provisioning template:
&lt;pnp:Parameter Key="filesrootpath" Required="true" /&gt;
and
 &lt;pnp:File Overwrite="true" Src="{parameter:filesrootpath}\siteLogo.png" Folder="{site}/SiteAssets" /&gt;
I am setting the filesrootpath parameter in my PowerShell script and passing it in with the -Parameters Parameter.
This causes an exception with message "The given path's format is not supported.".
This seems to be because the parameter replacement is not happening.

**Comment by LenCardinal** [comment]
I've seen this as well

**Comment by PaoloPia** [comment]
Hi,
So far we do support tokenization of the Folder attribute, but not of the Src one. We will think about supporting tokenization for Src, too. Thanks for the feedback.

**Comment by Pieter-Veenstra** [comment]
Yes, this one can be closed

**Comment by PaoloPia** [comment]
Pieter, are you referring to this one or to something else? Thanks

**Comment by Pieter-Veenstra** [comment]
Yes, I think this occurence of the site token is working in the latest version

**Comment by PaoloPia** [comment]
Ok, Thank you. I will close this one.
