### ISSUE TITLE
Site Policies are not applied after provisioning

### ISSUE THREAD

**Issue by sivakishorejvv** [SharePoint/PnP-Sites-Core#417]
Created a site policy. In ObjectSitepolicy.cs  below line of code is always returning null, so the site policies are not created.
if (web.GetSitePolicyByName(template.SitePolicy) != null) // Site Policy Available? 
Here the web refers to the target site web, it always returns null because the sitepolicies are not created in the target site yet.

FYI
pnp:SitePolicypolicy01/pnp:SitePolicy
<pnp:PropertyBagEntry Key="PolicyCTId" Value="0x010085EC78BE64F9478AAE3ED069093B99630053B372F61B21EC4E9D0333011B045081" />
<pnp:ContentType ID="0x010085EC78BE64F9478AAE3ED069093B99630053B372F61B21EC4E9D0333011B045081" Name="policy01" Description="policy01" Group="_Hidden" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          pnp:FieldRefs
            <pnp:FieldRef ID="b0227f1a-b179-4d45-855b-a18f03706bcb" Name="_dlc_Exempt" Hidden="true" />
            <pnp:FieldRef ID="74e6ae8a-0e3e-4dcb-bbff-b5a016d74d64" Name="_dlc_ExpireDateSaved" Hidden="true" />
            <pnp:FieldRef ID="acd16fdf-052f-40f7-bb7e-564c269c9fbc" Name="_dlc_ExpireDate" />
          /pnp:FieldRefs
        /pnp:ContentType

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, the purpose of the object handler (ObjectSitePolicy.cs) is to apply an already existing site policy to the target site. Thus, if the site policy does not exist it is ok to skip it. I will close this item, but feel free to re-open it in case of any further need. Thanks.
