### ISSUE TITLE
ObjectFeatures.cs excludes site scoped features on sub sites

### ISSUE THREAD

**Issue by lanegoolsby** [SharePoint/PnP-Sites-Core#423]
Title basically says it all, on line 24 there is an explicit check if the current context is a sub site or not. This causes issues when trying to provision a sub site that uses the Publishing features and the PE is not in charge of provisioning the root web for the site collection (e.g. the site collection already exists and need to provision a sub site). Is there a reason behind the exclusion?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback, but I have to close this one because it is related to a closed PR.
