### ISSUE TITLE
Files are not copying from site assets while provisioning

### ISSUE THREAD

**Issue by sivakishorejvv** [SharePoint/PnP-Sites-Core#424]
As part new template creation we need some js and css files. we uploaded those cs and jss files to the site assets folder. But when we are doing savesiteasprovisioning template corresponding structure was not generated in the xml.
pnp:File...... etc

The existing framework mandates that all the script and js files which are used in the templates need to be placed under infrastructure site.  Otherwise the files are not copying to the target site. Apart from this pnp:File also not generated for each of the file under site assets.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. However, we intentionally do not export files from the source site. If you like, you can write a custom extension for the provisioning engine or you can add them manually to the template file. I will close this item.
