### ISSUE TITLE
Publishing site exports

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#425]
When a root site of the publishing site is exported a few problem may occur:
1. My page is called home.aspx. During the import with PowerShell I needed to create a copy of my page next to the xml file. Home.aspx is not created by the export. The export also includes all my page layouts, however the page layout files are failing to upload as they do not exist with the template xml.
2. Within the exported xml I had to correct the page layout {site} token was used all over the palace in the Url. (known issue, but I'm listing it here to complete the whole story)
3. Read only properties are exported and causing problems during the import:
   < pnp:Property Key="_CheckinComment" ...
   < pnp:Property Key="MetaInfo" ...
   < pnp:Property Key="_HasCopyDestinations" Value="False" />

**Comment by PaoloPia** [comment]
Hi, 
Thanks for this feedback. In May and June we greatly improved the support form publishing sites and as far as I know those issues were fixed. Thus, I will close this item. If you are still experiencing the those issues, please feel free to re-open this item and let me know. Thanks.
