### ISSUE TITLE
Custom sort order on global navigation

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#430]
When exporting a global navigation with custom sort order I can see the custom sort order in the xml. When I then try to import this global navigation the custom sort order seems to be lost.

**Comment by PaoloPia** [comment]
Hi Pieter,
In July 2016 we completely refactored the navigation settings handler. From a schema perspective the NavigationNode element (https://github.com/SharePoint/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#navigationnode) for structural navigation does not have the sort order. Meanwhile, the managed navigation nodes rely on the taxonomy and they have the sort order, which is correctly implemented using the CustomSortOrder attribute of the term. Thus, I think this issue has been solved and I will close this item. If you are still experiencing any issue related to this topic, please let me know and I will re-open the item for further investigation.
