### ISSUE TITLE
Unable to get Composed looks (SPcolor) files.

### ISSUE THREAD

**Issue by bhanuprakash857** [SharePoint/PnP-Sites-Core#453]

**Comment by bhanuprakash857** [comment]
I'm writing below code to generate xml file.

ProvisioningTemplateCreationInformation ptci
                        = new ProvisioningTemplateCreationInformation(sourceSiteWeb);

            // Create FileSystemConnector to store a temporary copy of the template 
            ptci.FileConnector = new FileSystemConnector(string.Format(@"{0}\..\..\",       AppDomain.CurrentDomain.BaseDirectory), "");
            ptci.PersistBrandingFiles = true;
            ptci.PersistComposedLookFiles = true;
            ptci.PersistPublishingFiles = true;
            ptci.IncludeNativePublishingFiles = true;
            ptci.IncludeSiteGroups = false;
            ptci.ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
            {
                // Only to output progress for console UI
                Console.WriteLine("{0:00}/{1:00} - {2}", progress, total, message);
            };

            // Execute actual extraction of the template
            ProvisioningTemplate template = sourceSiteWeb.GetProvisioningTemplate(ptci);

Below are my issues with the above code:

- SPCOLOR files are not downloaded

- ComposedLooks fileds are empty.

<pnp:ComposedLook ColorFile="" FontFile="" BackgroundFile="" Version="0" />


Could you please help me here.


Thanks,
Bhanu

**Comment by bhanuprakash857** [comment]
Did anybody get the chance to look into this?

**Comment by PaoloPia** [comment]
Hi,
Sorry for being late on this, but we have quite a huge backlog. Are you using a custom .SPCOLOR file or an out of the box one? Are you on-premises or in SPO? Thanks.

**Comment by jansenbe** [comment]
Internal testing showed this as non-reproducible, closing the issue

**Comment by jansenbe** [comment]
Adding internal test results:
**Test1: Manually**: Source:
- Created new site. Created new color file by downloading OOB color file. Uploaded new color file to themes gallery and changed the look and feel.

Failed: Online & On-Prem
- Downloaded template using engine.
- No color file download.
- No <pnp:file> tag in download xml
- Empty ColorFile="" property in <pnp:ComposedLook>

**Test2: Thru Engine:** Source:
- Created new site. Changed look and feel by provisioning color file.

Success: Online & On-Prem
- Engine successfully downloaded color file. Template has file and composed look tag with proper data

So issue is with manually updated themes, themes applied using engine are correctly extracted. Will flag this one as enhancement request.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
