### ISSUE TITLE
Apply-SPOProvisioningTemplate : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by PieterVeenstra** [SharePoint/PnP-Sites-Core#455]
One way to get this error is as follows:
Create a publishing site 
create a new page
Set the welcome page url to the new page.
Get the template.xml for this site with Get-SPOProvisioing template

Create a new publishing site. 
Apply the template ( the template now creates a page with the same name however it remains checked out) and you get the error: "Apply-SPOProvisioningTemplate : Exception has been thrown by the target of an invocation."

The workaround (not really great as it involves manual steps):

Manually check in the page that was created
Restart PowerShell (otherwise you are likely to get a Safe conflict error)
Reapply the template and all is working as expected.

https://www.yammer.com/itpronetwork/users/1554838634#/Threads/fromUser?type=from_user&feedId=1554838634

**Comment by PaoloPia** [comment]
Hi Pieter,
I guess this issue got fixed by the fix for #414 . Is it true? If that is the case, I can close this item. Thanks.

**Comment by PaoloPia** [comment]
Hi Pieter,
I will close this item in the meantime. Please let me know, in case of any further issue, and I will re-open it.

**Comment by jansenbe** [comment]
Internal testing showed this as non reproducable
