### ISSUE TITLE
Additional information: A duplicate field name xxx was found.

### ISSUE THREAD

**Issue by ILoveITScience** [SharePoint/PnP-Sites-Core#461]
Hi,

I got the following exception: {"A duplicate field name \"xxx\" was found."}

The SiteColumn xxx exists already in the source SiteCollection. It exists also in the template.
Is it still possible to provision the template? Or do I have to remove the SiteColumn from the template?

The source SiteCollection is a new SharePoint Team Site with a few SiteColumns, ContentTypes and Lists.
The target SiteCollection is a new, fresh and empty standard SharePoint Team Site - but it contains some of the SiteColumns already (inherited from the CTH).

Information: 
OffiveDevPnP.Core: Runtime Version: v4.0.30319
OffiveDevPnP.Core: 2.2.1603.0
SharePoint On Premise (2013, Enterprise, CU: 2015 December)

If you need the template as xml, please write a Email to: ILoveItScience@outlook.de

Thx

**Comment by ILoveItScience** [comment]
When I remove the duplicate SiteColumns from the xml-file and provision the template again I get the Exception:

"Additional information: A list, survey, discussion board, or document library with the specified title already exists in this Web site.  Please choose another title."

The exception is not very helpful as it does not say which list it is. After a quick research (there are only 4 lists in the template) I found it. Its the "Documents" list. Why is it in the template? Its a standard SharePoint list.

If you need the template as xml, please write a Email to: ILoveItScience@outlook.de

**Comment by erwinvanhunen** [comment]
Hi!

First of all, apologies for the very very long delay. Content Types and connected artifacts that are being 'consumed' from a content type hub end up as being sealed in the site. Basically this means that they cannot be changed. Which explains the error messages you describe. We are considering a change to the engine were unseal the item first, do the update, and reseal it.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
