### ISSUE TITLE
Provisioning Engine: Required not set for content type

### ISSUE THREAD

**Issue by pascalberger** [SharePoint/PnP-Sites-Core#469]
In a provisioning template I create a new lookup field like this:

```
<Field Type="Lookup"
    DisplayName="MyLookup"    
    EnforceUniqueValues="FALSE"    
    List="{{listid:Fahrzeuge}}"
    ShowField="Title"    
    UnlimitedLengthInDocumentLibrary="FALSE"
    Group="My Group"
    ID="{f759aaa7-aec6-4b75-a080-9cdb0da70097}"
    StaticName="MyLookup"
    Name="MyLookup"/>
```

Also I create a content type containing this field, but set it as required:

```
<pnp:FieldRef ID="f759aaa7-aec6-4b75-a080-9cdb0da70097"
    Name="MyLookup"
    Required="true" />
```

After provisioning the State of the field in the content type is "Optional". Since I set `Required="true"` I would expect it to set the field in the content type to required.

**Comment by PaoloPia** [comment]
Hi,
Sorry for the delayed answer. As far as I know, based on the code base, we properly support the Required attribute for FieldRef in content types. Are you still experiencing this issue? I will close this issue in the meantime, but feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.
