### ISSUE TITLE
The group description cannot be null or greater than 500 characters.

### ISSUE THREAD

**Issue by lanegoolsby** [SharePoint/PnP-Sites-Core#470]
This may actually be a bug in SP that was fixed in a CU. The environment I ran into this issue was quite behind on patches and I am fairly confident I covered this test case during development but can't say for certain. However, the fix is pretty benign. 

When provisioning a template, if a group description is not specified in the template it causes an error in SP that the group description cannot be null or over 500 characters. This only happens if the group already exists and the code is trying to modify the group instead of creating the group

**Comment by PaoloPia** [comment]
Hi,
This one has been fixed by #471 and I will close it. Thanks for your contribution.
