### ISSUE TITLE
Bug in GetFieldByName method (Microsoft.SharePoint.Client.FieldAndContentTypeExtensions)

### ISSUE THREAD

**Issue by kierunb** [SharePoint/PnP-Sites-Core#474]
I think i found a bug in implementation of GetFieldByName method in Microsoft.SharePoint.Client.FieldAndContentTypeExtensions class.

Package version: OfficeDevPnP.Core (on-premises) 2.2.1603
SharePoint 2013

First of all condition below evaluates to false even if field collection is not loaded:

```
    if (!fields.ServerObjectIsNull.HasValue || fields.ServerObjectIsNull.Value)
    {
        fields.Context.Load<FieldCollection>(fields, new Expression<Func<FieldCollection, object>>[0]);
        fields.Context.ExecuteQueryRetry(10, 500);
    }

```

Second issue is related to fact that, field name is searched by StaticName:
`Field field = fields.FirstOrDefault((Field f) => f.StaticName == internalName);`

While in many other similiar methods like: FieldExistsByName, FieldExistsByNameInContentType etc field is searched by **InternalName**.

It easy to reproduce this bug. Just use a field name with blank space like "Sample name" to find out that this method will not work unless you'll use a static name of course (it will be different though, due to encoding). Also without FieldsCollection loaded before invoking of this method, you'll get an exception.

**Comment by dmdj** [comment]
We have found in some cases, ServerObjectIsNull = false.  For example:

    context.Site.RootWeb.Fields.GetFieldByName<FieldLookup>("MyLookup")

results in ServerObjectIsNull = false.

This could be resolved by adding an IsObjectPropertyInstantiated check as follows:
     if (!fields.ServerObjectIsNull.HasValue ||
          fields.ServerObjectIsNull.Value ||
         **!fields.IsObjectPropertyInstantiated("Count")** )

Other approach might be handling CollectionNotInitializedException.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. In April 2016 we added the following extension method:

public static bool ServerObjectIsNull<T>(this T clientObject) where T : ClientObject

which does all the magic for you. You should use it to test the existence of a property.

I will close this issue, but feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.
