### ISSUE TITLE
Provisioning Engine: site corrupted after provisioning incorrect Field XML

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#488]
I am using a ProvisioningTemplate to provision site columns (Fields). I am using an XML file to describe my ProvisioningTemplate based on the current ProvisioningSchema. Some of my Fields are of type TaxonomyField. I'm using replacement tokens for replacing the termstore ID  and termset ID inside of the Field's "Customization" element.

If replacement (for whatever reason) does not succeed and the Provisioning Engine fails to replace the tokens with the correct values, the replacement tokens are part of the Field XML submitted to SharePoint's API resulting in corrupted fields being created. These corrupted fields effectively break the entire site (collection) because every operation against Web.Fields results in an Exception. I even wasn't able to remove the corrupt TaxonomyFields and was forced to remove my entire site collection and recreate it.

**Comment by erwinvanhunen** [comment]
Hi Paul,

Thank you for reporting this. We are aware of the issue and have pushed a fix for this issue in the dev branch by means of PR #464. 

/Erwin

**Comment by PaoloPia** [comment]
Hi Paul,
I will close this issue, because it is solved AFAIK. But feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.
