### ISSUE TITLE
Provisioning Engine: Token Replacement on-premises Taxonomy

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#490]
I am using ProvisioningSchema XML to provision Taxonomy Fields against an on-premises SharePoint 2013 environment. In Field XML I'm making use of Replacement Tokens in order to reference the correct Term Set to associate with my Field.

The Token Replacement code (OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser) gets a reference to the Term Store making use of TaxonomySession.GetDefaultSiteCollectionTermStore. For SharePoint Online environment this will always work since the one available Term Store is configured to be "the  default storage location for column specific term sets", but in our on-premises environment the Term Store I'm using is not configured to be "the default storage location for column specific term sets". This causes Token Replacement not to succeed which ultimately results in a corrupt site (collection) as described in #488 

Maybe resolve this by changing the existing token to something like below or provide a new token?
{termsetid:<Store>:<Group>:<Set>}

**Comment by PaoloPia** [comment]
Hi Paul,
Sorry for being late on this. We do have a TermSetIdToken handler and you can use it with the following syntax:

{termSetId:[GroupName]:[TermSetName]}

I think it should work for your purpose. Does it work for you? Thank you.

**Comment by PaoloPia** [comment]
Hi Paul,
I will close this item, because I think it is no more an open issue. In case of any further need, feel free to let me know and I will be more than happy to re-open it. Thanks.
