### ISSUE TITLE
[Provisioning Engine]: Allow Path in Files Src property.

### ISSUE THREAD

**Issue by MarkStokes-outlook** [SharePoint/PnP-Sites-Core#496]
This may not be a Provisioning Schema issue, but a Provisioning Engine issue, so I will duplicate this issue in both locations.

I would like to be able to add a local path to a file that needs to be provisioned by the Files section.
https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2015-12.md#file

Since the provisioning engine can "provision" Files into our site I would like to be able to structure my provisioning folder to replicate this structure.  For example, I would like to create a local folder called "_catalogs/masterpage" for my master pages and page layouts, then create local folders at "SiteAssets/Images", SiteAssets/css", "Pages", "Documents", "Pictures/Banners", etc.

This will help me to manage my deployable files, rather than a single flat file structure that will likely breakdown if I have files of the same filename that exist in different folders of my site.

At present, if I put a path in the Src property I get an error message that path names are not allowed, only filenames.

**Comment by luismanez** [comment]
I've been using relative paths in the SRC attribute for a while:
```xml
        <pnp:File Src="..\Assets\Scripts\jquery.js" Folder="{site}/Style%20Library/js/" Overwrite="true" />
```

not sure about Full paths though, but works fine with relative paths. Just ensure you set the Connector of the Template, pointing to any folder, and then, the relative paths are relative to that folder.

**Comment by jbranders** [comment]
@luismanez Can you give an example of your directory on the file system and what must i exactly do with the Connector? How can i let it point to any folder?

**Comment by luismanez** [comment]
Something like this:

+pnp
++ProvisioningTemplate.xml

+src
++ Style Library
+++MyProject
++++Scripts
+++++Project.Core.js

And when you load the template and Apply it:

```c#
XMLFileSystemTemplateProvider provider = new XMLFileSystemTemplateProvider("Path_To_Pnp_folder", "");

var template = provider.GetTemplate("ProvisioningTemplate.xml");
template.Connector = new FileSystemConnector("Path_To_Pnp_folder", "");
```

and then, in the PnP XML file:

```xml
<pnp:File Src="..\Style Library\MyProject\Scripts\Project.Core.js" Folder="{site}/Style%20Library/myproject/scripts" Overwrite="true" />
```

If you are pointing your connector to the PnP folder, then the Src should be relative to that PnP folder.

Hope it helps.

**Comment by bartdonninger** [comment]
Hello,

I encountered the same problem as @MarkStokes-outlook did. For me the problem was that I was using forward slashes '/' in the src attribute. When I changed them to backward slashes '\' it worked like a charm.

**Comment by artokai** [comment]
Currently there seems to be a bug in the PnP Provisioning engine which prevents you from using folders in the `Src`-attribute if you're using the `SharePointConnector` to fetch your files. 

The reason for this is that the `SharePointConnector` supports only forward slashes (`/`) as the path separator but the Files-handler always adds a  backslash (`\`) in the path if the `Src`-attrbute contains folders. ([source](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs#L375))

I' submitted a pull request (#807) which adds support for backslashes (´\`) in the `SharePointConnector` which should fix this problem.

**Comment by PaoloPia** [comment]
Hi,
The PR #807 has been merged a while ago. Thus, I will close this issue, but feel free to drop me a message if you have any new feedback and I will be more than happy to re-open it and support you. Thank you.
