### ISSUE TITLE
Bug in SiteSearch(this Web web, string keywordQueryValue, bool trimDublicates = true)

### ISSUE THREAD

**Issue by kierunb** [SharePoint/PnP-Sites-Core#497]
There is a bug in implementation of method below:

```
// Microsoft.SharePoint.Client.WebExtensions
public static List<SiteEntity> SiteSearch(this Web web, string keywordQueryValue, bool trimDublicates = true)
```

Parameter trimDuplicates is not used inside method:

```
try
    {
        Log.Debug("OfficeDevPnP.Core", "Site search '{0}'", new object[]
        {
            keywordQueryValue
        });
        List<SiteEntity> list = new List<SiteEntity>();
        KeywordQuery keywordQuery = new KeywordQuery(web.Context);
        keywordQuery.TrimDuplicates = false;
```

KeywordQuery TrimDuplicate property has hardcoded value set to false, which is opposite to what default value of trimDuplicate parameter is set to.

There is also a typo in parameter name: Should be 'trimDuplicates' instead of 'trimDublicates'.

**Comment by erwinvanhunen** [comment]
Hi!

First of all: big apologies for the long wait for us to pick this one up. I've submitted a change to the core library, but as it's a potentially breaking change, we will have to review this with the other core team members.

We will create a fix nevertheless. I will close this issue but not hesitate to reopen if you feel it is relevant.
