### ISSUE TITLE
Term Reuse

### ISSUE THREAD

**Issue by lmscheuerman** [SharePoint/PnP-Sites-Core#506]
Term reuse causes error "Failed to read from or write to database"

**Comment by PaoloPia** [comment]
Hi Loren,
We are working on this issue. We already fixed it partially, but we're still on the go to fix it completely. As a workaround, in the meantime, you can change the ID of the Reused Term. I guess you are applying a local Site Collection Term Group to another Site Collection. Is it right? Thanks.

**Comment by jansenbe** [comment]
The engine is supporting reused terms as of February release. Will close the issue, but feel free to re-open in case you still are facing this issue and can reproduce using the latest PnP version.
