### ISSUE TITLE
Provisioning Engine: "Site Assets" are created as default document library

### ISSUE THREAD

**Issue by lafe** [SharePoint/PnP-Sites-Core#512]
We are currenlty trying to deploy a slightly customized "Publishing Portal" using the Provisioning Engine. The source Site contains a normal "Site Assets" library (created when uploading a site image). This "Site Assets" library uses the Document Template "SiteAssets/Forms/template.doc" and this setting is stored in the exported XML file.
When the Provisiong engine deploys the Site to a new Site Collection, the "SiteAssets" library is also created as a default document library with template 101 (as defined in the exported XML file).
Unfortunately, SharePoint internally seems to use the "[EnsureSiteAssetsLibrary](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.splistcollection.ensuresiteassetslibrary.aspx)" function which creates a slightly different kind of document library than the default 101 template (this can be reproduced using PowerShell by manually running the "EnsureSiteAssetsLibrary" command). The main difference we discovered is that the document template is linked to "SiteAssets/Forms/template.doc" whereas a default document library uses the document template "SiteAssets/Forms/template.dotx". 
The Provisioning engine correctly detects a difference between the document template in the newly created "Site Assets" library and the value stored in the XML file and tries to change it. Without the "template.dotx" present this change fails and therefore the complete process fails.

We used SharePoint 2016 RTM OnPrem to detect this issue.

**Comment by PaoloPia** [comment]
Hi,
This one has been fixed by your PR #513 so I will close this item. Thanks.
