### ISSUE TITLE
Provisioning Engine: Files with spaces not uploaded correctly

### ISSUE THREAD

**Issue by lafe** [SharePoint/PnP-Sites-Core#514]
We have a Site Image with a space in its name (e.g. "My Logo.png"). The export stores the file correctly as "My Logo.png" on the disk but the "pnp:Files" segment of the exported XML file uses "My%20Logo.png". 
During import, the Provisioning Engine tries to read the "My%20Logo.png" from the harddisk but fails as only "My Logo.png" is present.

**Comment by PaoloPia** [comment]
Thanks Lars, this one has been fixed by your PR #515. I will close this item.
