### ISSUE TITLE
Provisioning Engine: MasterPageURL incorrect if Root Site Collection is source

### ISSUE THREAD

**Issue by lafe** [SharePoint/PnP-Sites-Core#516]
If a Root Site Collection is exported, the MasterPageURL and CustomMasterPageUrl are stored incorrectly (e.g. "{masterpagecatalog}{site}seattle.master").
I was able to trace this behavior to the Tokenize-Method in ObjectHandlerBase. The Tokenize method is executed with the values "/_catalogs/masterpage/seattle.master" for url and "http://webApp.development.local" for webUrl. Afterwards the "/_catalogs/masterpage" is replaced with "{masterpagecatalog}" and the new url is "{masterpagecatalog}/seattle.master". Unfortunately, the webUrlPathAndQuery is "/" for the Root Site Collection and afterwards the remaining slash is replaced with "{site}".

**Comment by spsguru** [comment]
I'm seeing this as well, although in my case, the MasterPageURL and CustomMasterPageURL are stored as "{masterpagecatalog}/Yourmasterpage.master" regardless of the source site for the template (I am using the Partner  Pack to provision subwebs)

**Comment by erwinvanhunen** [comment]
Tokenization has been fixed throughout the engine. If you feel this issue still stands, do not hesitate to reopen this issue.
