### ISSUE TITLE
Overwrite-property on PropertyBagEntry doesn't kick in

### ISSUE THREAD

**Issue by olemp** [SharePoint/PnP-Sites-Core#519]
Overwrite="true" on a PropertyBagEntry element doesn't update the PropertyBagEntry.

It skips the PropertyBagEntry, even with Overwrite set to TRUE.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Are you providing the OverwriteSystemPropertyBagValues switch to the Apply-PnPProvisioningTemplate cmdlet, or the OverwriteSystemPropertyBagValues flag on the ProvisioningTemplateApplyingInformation object?

**Comment by jansenbe** [comment]
This scenario is part of our nightly testing. See https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Implementation/PropertyBagImplementation.cs. You'll need to specify the overwrite flag as specified by @PaoloPia .

Closing the issue now.
