### ISSUE TITLE
Lookup site column does not work in Word

### ISSUE THREAD

**Issue by tberst** [SharePoint/PnP-Sites-Core#522]
Hi :)

When a lookup is provisionned through the provisionning engine, the xml schema for the field is lacking curly braces around the GUID for the 'List' attribute: 
`<Field Type="Lookup" .... List="609436ab-27d1-44b0-90a2-34b004e3b268" ... />`
The column is actually working in sharepoint, but when you try to use it in Word through the document panel, the dropdownlist shows random entries.

The root cause is in the ObjectLookupField.cs file (line 166) 
`isDirty = UpdateFieldAttribute(existingFieldElement, "List", listGuid.ToString(), false);`
(in the ProcessField method).

Proposed fix : 
`isDirty = UpdateFieldAttribute(existingFieldElement, "List", listGuid.ToString("B"), false);`

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The proposed fix has been applied by @okms on May 2016. Thus, I will close this item.
