### ISSUE TITLE
Get-SPOProvisioningTemplate

### ISSUE THREAD

**Issue by kameronberget** [SharePoint/PnP-Sites-Core#533]
I am running Get-SPOProvisioningTemplate -Out <filepath -Handlers Lists and getting the following.

**Get-SPOProvisioningTemplate : The underlying connection was closed: An unexpected error occurred on a receive.**

This worked fine up until we added a few custom lists to the empty site and now it is failing.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Are you still experiencing this issue? If that is the case, can we have much more details about the context. Are in SharePoint on-premises or SPO? If on-premises we need the build version/patch level. Can you share a trace of the execution? Thanks.

**Comment by jansenbe** [comment]
Non reproducible in internal testing. Pretty sure this has been an temporary glitch in networking at either SPO side or customer side. Closing the issue now
