### ISSUE TITLE
SetDefaultPageLayoutForSite(web, "layoutname")	 -> System.NullReferenceException

### ISSUE THREAD

**Issue by jcostach** [SharePoint/PnP-Sites-Core#535]
Using SetDefaultPageLayoutForSite(web, "layoutname") I always get System.NullReferenceException.
Tried to use it with the file extension: SetDefaultPageLayoutForSite(web, "layoutname.aspx") and still nothing.
Am I missing here something? do i need to load something prior to use the SetDefaultPageLayoutForSite?
Thank you

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I think that this issue is related to issue #382, which has been fixed and close a few weeks ago. Thus, I will close this item, too. In case of any further need, please let me know and I will be happy to re-open it.
