### ISSUE TITLE
[Improvement] Persist site assets

### ISSUE THREAD

**Issue by sdaly2107** [SharePoint/PnP-Sites-Core#538]
We have some sites with some jslink and aspx pages which we store in site assets.  When getting a template from an existing site, these are not pulled down.  I guess they are data, but they do form part of the solution - would it be possible to add this option to persist site assets and then re-populate when applying?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We intentionally do not include any content (JS, ASPX, etc.) during templates extraction. We just and simply support extraction of the home page, of the custom master page (if any), and of the page layouts, if we are in a publishing site and there is proper switch to include them. There is no plan to add other content files. Nevertheless, you are free to write your own engine extension to do that, or you can simply manually write a .XML template that provisions those files. Thanks.
