### ISSUE TITLE
Extensibility Token Provider never called ?

### ISSUE THREAD

**Issue by tberst** [SharePoint/PnP-Sites-Core#541]
I have a custom token provider declared like that : 
`<pnp:Providers>
...
        <pnp:Provider Enabled="true" HandlerType="Company.MyTokenProvider, Company.Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
        </pnp:Provider>
...`
but the custom provider is never executed.

I narrowed it down to the ObjectExtensibilityHandlers which is iterating over the '**Provider's** in the ExtensibilityHandler collection : 
ObjectExtensibilityHandlers::AddExtendedTokens
`foreach (var handler in template.ExtensibilityHandlers.Union(template.Providers)).OfType<**Provider**>())`

My token provider is not of type Provider.

One possible fix is to change the type in ExtensibilityManager.cs : 
-- `public IEnumerable<TokenDefinition> ExecuteTokenProviderCallOut(ClientContext ctx, Provider provider, ProvisioningTemplate template)
++    public IEnumerable<TokenDefinition> ExecuteTokenProviderCallOut(ClientContext ctx, ExtensibilityHandler provider, ProvisioningTemplate template)`

Is this legit?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedbacks. This issue is the same as #698 and has been fixed by #699. Thus, I will close this item.
