### ISSUE TITLE
ObjectListInstance.cs Setting/getting versioning properties

### ISSUE THREAD

**Issue by niklasosth** [SharePoint/PnP-Sites-Core#542]
Having problems both extracting current versioning settings on an existing list as well as setting the values on a new/updated list.

Seems that it has been added a check if the property is instantiated (...IsObjectPropertyInstantiated("MajorVersionLimit") and ...IsObjectPropertyInstantiated("MajorWithMinorVersionsLimit")) but that returns false even if there is a value.

![image](https://cloud.githubusercontent.com/assets/9033181/15105064/9930122c-15be-11e6-9bed-20e497c414d3.png)

Can be related to this: https://github.com/OfficeDev/PnP-Sites-Core/pull/73/files

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This issue should have been already fixed a while ago. Thus I will close this item. In case you will experience this issue in the future, please do not hesitate to let me know. Thanks.
