### ISSUE TITLE
Provisioning : Taxonomy Fields are added again when using the GetSPOTemplate cmdlet

### ISSUE THREAD

**Issue by wizneeraj** [SharePoint/PnP-Sites-Core#543]
We have a site which gets its content types from a Content Type hub. One of the content type from the hub is used in library. This content type uses Taxonomy fields. While extracting a template, the taxonomy fields are added again in the "Fields" section. Due to this, when the extracted template is applied on a new site, the library gets created, but when saving an item with metadata, we get the error  - "The SPListItem being updated was not retrieved with all taxonomy fields". I removed the Taxonomy Fields from the xml and then the applied the modified template and it is working as expected.

A check needs to be added in the code to ensure that if the metadata are coming from a custom Contenttype, then based on it the fields need not be there in the xml being generated.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Are you still experiencing this issue? Thanks.

**Comment by jansenbe** [comment]
Internal test results:
Source:
- Published content type with terms in content type hub. Download template.

Success:
- Provisioned content type template in new site collection and added to library. Created new item successfully.

Closing issue now
