### ISSUE TITLE
Error when trying to Get-SPOProvisioningTemplate -IncludeAllTermGroups

### ISSUE THREAD

**Issue by ianwaites** [SharePoint/PnP-Sites-Core#552]
I keep receiving an error when trying to Get-SPOProvisioningTemplate while using -IncludeAllTermGroups from a SPOnline page I am working on. I am able to complete the Get-SPOProvisiongTemplate process as long as TermGroups are not included, so it seems the problem is directly related to them. 

I was able to successfully complete this process back in April on the same site, but as of now I am unable to achieve the same outcome. 

I downloaded the latest PnPPowershell.msi package, so I am using the May version. 

![screen shot 2016-05-12 at 10 08 58 am](https://cloud.githubusercontent.com/assets/18404611/15223531/ce188a1a-1829-11e6-85a0-09e3cd1a26bf.png)

Any help would be much appreciated!

Thanks.

**Comment by erwinvanhunen** [comment]
In order to find out what is causing this issue, can you, immediately after the error occured enter this powershell line:

```powershell
$error[0].Exception.Stacktrace
```

Please paste in the result as a reply to this issue.

Also, before you start the Get-SPOProvisioningTemplate cmdlet, execute this:

```powershell
Set-SPOTrace -On -Level Debug -Outfile c:\temp\log.txt 
```
Then execute the Get-SPOProvisioningTemplate cmdlet as normal.

Replace c:\temp\log.txt with path and filename that is suitable for your environment.

This is will generate a log file that _might_ contain information about what is causing your issues.

**Comment by ianwaites** [comment]
Hi @erwinvanhunen - I really appreciate your quick response!

So, I got an error when trying to use Set-SPOTrace -On -Level Debug -Outfile c:\temp\log.txt and included that in my screenshot. 

<img width="985" alt="screen shot 2016-05-12 at 10 31 00 am" src="https://cloud.githubusercontent.com/assets/18404611/15224124/a272dc78-182c-11e6-9be7-65692ea60a52.png">

**Comment by erwinvanhunen** [comment]
Sorry, that was my mistake. It's not Outfile but Logfile that you need to specify as a parameter.

**Comment by ianwaites** [comment]
Ok, ill give that a shot - thanks!

**Comment by ianwaites** [comment]
Hi there, 

I have attached the log with hopes that you recognize anything that could be causing the problem. 

<img width="1083" alt="screen shot 2016-05-12 at 10 37 31 am" src="https://cloud.githubusercontent.com/assets/18404611/15224315/82e34cb6-182d-11e6-9463-4cda2dd508f5.png">
[log.txt](https://github.com/OfficeDev/PnP-Sites-Core/files/261935/log.txt)

**Comment by ianwaites** [comment]
@erwinvanhunen - wondering if you have any ideas to what could be causing this error? Do you think I should try to uninstall the May version of the PnP.msi and reinstall the April one?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Are you still experiencing this issue? As far as I know the term groups extraction works pretty well right now. Thanks.

**Comment by jansenbe** [comment]
Internal testing showed this to be working as expected. Will close this issue now
