### ISSUE TITLE
Add method GetTermSet or GetTermSetById

### ISSUE THREAD

**Issue by ruslanurban** [SharePoint/PnP-Sites-Core#557]
Often, I need to load list of terms by the `TermSetId` value defined in the _field schema_. Unfortunately, the `SPTaxonomySession` does not expose the method `GetTermSet` or `GetTermSetById`, where I would be able to pass the `TermSetId` value. The PnP extensions seem to be missing this method as well. Would it be possible to add it to a future release of PnP?

**Comment by rroman81** [comment]
@ruslanurban You should be able to retrieve a default site collection term store and then use the GetTermSet(Guid guid) then
`TermStore store = session.GetDefaultSiteCollectionTermStore();`
`store.GetTermSet(_termsetId)`
