### ISSUE TITLE
Delta handling provisioning terms fails with ampersands in term names

### ISSUE THREAD

**Issue by jeroenvanlieshout** [SharePoint/PnP-Sites-Core#569]
When provisioning terms with encoded ampersands `&amp;` in the XML, the second time provisioning the template will fail. The delta handling doesn't recognize it as already existing, as SharePoint converts the ampersand to an Unicode ampersand. In the delta handling comparison, the TaxonomyItem.NormalizeName method should be used to prevent issues with ampersands in term names.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedbacks, which is really great! I've just merge PR #1012 and now the feature is included. Thanks.
