### ISSUE TITLE
Template with taxonomy field based in site collection term store fails

### ISSUE THREAD

**Issue by andikrueger** [SharePoint/PnP-Sites-Core#572]
#### Category

[x] Bug
#### Environment

[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4805.1000
#### Expected or Desired Behaviour

Term groups residing in the site collection term store get exported into the template. These term groups should be restored in a new site collection.
#### Observed Behaviour

The restore of the template in a new site collection fails in the method:
OfficeDevPnP.Core.dll!OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectHandlerBase.IsFieldXmlValid(string fieldXml, OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser parser, Microsoft.SharePoint.Client.ClientRuntimeContext context)
#### Steps to Reproduce
1. create a new team site
2. create a new field: type: Taxonomy
3. select the radio button: customize a term set.
4. create a new template
5. restore the template to a new site collection (web.ApplyProvisioningTemplate())

Please find attached the xml template file.
[template_err.txt](https://github.com/OfficeDev/PnP-Sites-Core/files/277654/template_err.txt)

**Comment by PaoloPia** [comment]
Hi Andi,
Thanks for your feedback. This issue should have been fixed in late May 2016, as you can see above. Thus, I will close this item. Thanks.

**Comment by ravick4u** [comment]
I am using SP2016 and getting the similar issue.

In my case, it's not replacing below token in my MMD Column and provisioning fails

<Property>
<Name>TermSetId</Name>
<Value xmlns:p4="http://www.w3.org/2001/XMLSchema-instance" p4:type="q2:string" xmlns:q2="http://www.w3.org/2001/XMLSchema">{termsetid:{sitecollectiontermgroupname}:MMDColumn}</Value>
</Property>
