### ISSUE TITLE
Document Set Settings => WelcomePage Settings => Select View is the default View not the one on the original site

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#600]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[X ] Bug
[ ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Document Set Settings Welcome Page View =>Select View  View displayed  should be the same as the original  site.
#### Observed Behavior

Welcome Page not set up correctly - Welcome Page View => Select View not set up - uses default library view rather than the one selected.
#### Steps to Reproduce

Get-SPOProvisioningTemplate followed by Apply-SPOProvisoingTemplate

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Currently we've no CSOM support for setting/retrieving a custom document set welcome page and welcome page view. The schema does support the custom welcome page, but as long as there's no CSOM API we can't implement it.

**Comment by jansenbe** [comment]
Closing this issue as we've no API to support this request

**Comment by NicolajHedeager** [comment]
Please vote for this on SP Dev Uservoice: [Add CSOM support for Document Set settings on content type](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33730567-add-csom-support-for-document-set-settings-on-cont)
