### ISSUE TITLE
Apply-SPOProvisioningTemplate FAils - The specified user Records Center Web Service Submitters could not be found.

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#601]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[X ] Bug
[ ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Observed Behavior

Apply-SPOProvisioningTemplate : The specified user Records Center Web Service Submitters could not be found.
 At line:1 char:1
- Apply-SPOProvisioningTemplate -Path C:\Temp\innovateuk.xml
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- CategoryInfo : WriteError: (:) [Apply-SPOProvisioningTemplate], ServerException
- FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

The Group 'Records Centre Web Service Submitters' is in the original site with no members.

 This is part of the Provisioing Template with Records Center Web Service Submitters in it :-

 pnp:Permissions
 pnp:RoleDefinitions
 <pnp:RoleDefinition Name="Records Center Web Service Submitters" Description="Submit content to this site using Web Services.">
 pnp:Permissions
 pnp:PermissionEmptyMask/pnp:Permission
 pnp:PermissionOpen/pnp:Permission
 pnp:PermissionUseRemoteAPIs/pnp:Permission
 /pnp:Permissions
 /pnp:RoleDefinition
 /pnp:RoleDefinitions
 pnp:RoleAssignments
 <pnp:RoleAssignment Principal="Records Center Web Service Submitters" RoleDefinition="Records Center Web Service Submitters" />
 /pnp:RoleAssignments
 /pnp:Permissions

 The Group "Records Centre Web Service Submitters" is not in the pnp:AdditionalMembers section of the file.
#### Steps to Reproduce

Get-SPOProvisioningTemplate  then Apply-ProvsioingTemplate with a sharepoint group in with no members..
#### Submission Guidelines

_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [PnP Yammer Group](http://aka.ms/OfficeDevPnPYammer).
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by PaoloPia** [comment]
Hi Nigel,
Thanks for your feedbacks. AFAIK this issue should have been fixed. Can you confirm? So that I will be able to close it. Thanks.

**Comment by eariel** [comment]
Hi, I'm having the same issue with SP On-Premise 2013 (CU June 2016) and SP Core Lib v 2.11.1701.1. I have a publishing site with no customizations except a groups with no users. Creating the template I get the same message.  I'm working with a Windows application. Thanks!

**Comment by jansenbe** [comment]
@eariel , can you please try with the latest version (March 2017) and provide us the template and stack trace. Thanks;

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
