### ISSUE TITLE
Get-ProvisioningTemplate does not support Information Policies on libraries or Content Types

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#602]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[X ] Bug
[ ] Enhancement
#### Environment

[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Information Policies should be able to be migrated from original site to new site using Get-SPOProvisioingTemplate / Apply-SPOProvisiongTemplate.
#### Observed Behavior

No Information Policies in the template file after Get-SPO-ProvisioingTemplate

Thanks for your contribution! Sharing is caring.

**Comment by mrpullen** [comment]
Is there a way in CSOM to set information policies on libraries..?? I haven't been able to turn it up. I am looking for the same functionality.

**Comment by PaoloPia** [comment]
Hi Nigel,
So far (AFAIK) we don't have support for this capability at CSOM level. I marked this item as an enhancement request and we will keep it on hold until CSOM will allow this capability (if it will happen ...).

**Comment by jansenbe** [comment]
As mentioned by Paolo there's no API...however I'm closing the issue since whenever the API will be there (if it will happen) then we're eager add support for this in the engine...no need to have an open issue to remind us :-)
