### ISSUE TITLE
Quick Launch Bar not captured correctly

### ISSUE THREAD

**Issue by babajwa** [SharePoint/PnP-Sites-Core#623]
I have adjusted Quick Launch Bar links but after using Get-SPOProvisioning Template when I apply to the new site, its not showing all of them and not in order they were in the original site.

Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[x ] Enhancement
#### Environment

[x ] Office 365 / SharePoint Online

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._
#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
#### Steps to Reproduce

_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We introduced support for navigation items non publishing sites just last month. Thus, this issue should now be fixed and I will close this item. Please, feel free to ping me back in case of any further need about this topic. Thanks.
