### ISSUE TITLE
ApplyProvisioningTemplate Idempotence

### ISSUE THREAD

**Issue by mrpullen** [SharePoint/PnP-Sites-Core#624]
#### Category

[ ] Bug
[X] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013
#### Expected or Desired Behavior

Provisioning should be **Idempotent**, such that when calling **ApplyProvisioningTemplate** is called, if resources already exist that provisioning need not fail. Instead the Template should be match the "end state" and so long as that end state is reached, the **ApplyProvisioningTemplate** should be successful.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
