### ISSUE TITLE
Get-SPOProvisioningTemplate: The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by schneika** [SharePoint/PnP-Sites-Core#636]
After:
Get-SPOProvisioningTemplate -Out C:\temp\devtemplate.xml -PersistBrandingFiles

on the end i allways get an Error

Get-SPOProvisioningTemplate : The remote server returned an error: (403) Forbidden
In Zeile:1 Zeichen:1
- Get-SPOProvisioningTemplate -Out C:\temp\devtemplate.xml -PersistBran ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], WebException
  - FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.GetProvisioningTemplate
#### Environment

[ ] Office 365 / SharePoint Online

**Comment by paulculmsee** [comment]
This appears to be an auth issue. My troubleshooting can be found here: https://www.yammer.com/itpronetwork/#/Threads/show?threadId=734412919

**Comment by dannyjessee** [comment]
Is this happening on a wiki page? I've had luck getting around this error by removing all the HTML markup that sometimes gets left behind as changes are made to a page's contents.

**Comment by PaoloPia** [comment]
Hi,
Can you execute the following command in PowerShell, just after the exception occurs:

$error[0].Exception.Stacktrace

Thanks.

**Comment by jansenbe** [comment]
**Internal testing feedback:**
Not reproducible using correct PS version. We get this error when we try to download templates from SPO using on-premises version of PnP PS.

Closing the issue for now, feel free re-open if it can be reproduced using the correct PS/Environment setup
