### ISSUE TITLE
Error Logging to Show Line that Error Occured on

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#642]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[ ] Bug
[X ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

Is it possible for the error Logging module(s) in Core and PowerShell to show in the tracefile the line on which an error occurred ?

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi Nigel, stack trace information in an Exception object does contain line number information. Does this help you?

**Comment by NPrice99** [comment]
Hi Bert - so how do I find where error has occurred ? in JavaScript you can use $error[0].Exception.Stacktrace but still the line number where the error occurred is not shown.  
Regards 

Nigel

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
