### ISSUE TITLE
Only add fieldrefs for the actual content type, leave out the fieldsrefs from OOB inherited CT's

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/PnP-Sites-Core#657]
#### Category

[ ] Bug
[X] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Only add fieldrefs for the actual content type, leave out the fieldsrefs from OOB inherited CT's.

``` XML
<!-- provided XML -->
<pnp:ContentType ID="0x0101005D4F34E4BE7F4B6892AEBE088EDD215E" Name="CT_1" Description="CT 1" Group="PnP Demo" xmlns:pnp="http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema">
  <pnp:FieldRefs>
    <pnp:FieldRef ID="92bc6a41-d501-4fe2-938e-17fbf574a7cb" />
  </pnp:FieldRefs>
</pnp:ContentType>

<!-- returned XML -->
<pnp:ContentType ID="0x0101005D4F34E4BE7F4B6892AEBE088EDD215E" Name="CT_1" Description="CT 1" Group="PnP Demo" NewFormUrl="" EditFormUrl="" DisplayFormUrl="" xmlns:pnp="http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema">
  <pnp:FieldRefs>
    <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
    <pnp:FieldRef ID="5f47e085-2150-41dc-b661-442f3027f552" Name="SelectFilename" />
    <pnp:FieldRef ID="8553196d-ec8d-4564-9861-3dbe931050c8" Name="FileLeafRef" Required="true" />
    <pnp:FieldRef ID="8c06beca-0777-48f7-91c7-6da68bc07b69" Name="Created" Hidden="true" />
    <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" />
    <pnp:FieldRef ID="28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f" Name="Modified" Hidden="true" />
    <pnp:FieldRef ID="822c78e3-1ea9-4943-b449-57863ad33ca9" Name="Modified_x0020_By" />
    <pnp:FieldRef ID="4dd7e525-8d6b-4cb4-9d3e-44ee25f973eb" Name="Created_x0020_By" />
    <pnp:FieldRef ID="ae3e2a36-125d-45d3-9051-744b513536a6" Name="_dlc_DocId" />
    <pnp:FieldRef ID="3b63724f-3418-461f-868b-7706f69b029c" Name="_dlc_DocIdUrl" />
    <pnp:FieldRef ID="c010d384-479c-494f-968c-c413dbe3de29" Name="_dlc_DocIdPersistId" Hidden="true" />
    <pnp:FieldRef ID="92bc6a41-d501-4fe2-938e-17fbf574a7cb" Name="FLD_CT_1" />
  </pnp:FieldRefs>
</pnp:ContentType>
```
#### Observed Behavior

All fieldrefs are exported

**Comment by thearturs** [comment]
Wouldn't desired behaviour mess column order if custom columns are between OOB ones?
OOB column can have modified Required or Hidden setting, which also should be replicated if applying exported template.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
