### ISSUE TITLE
get-spoprovisioning temaplte with a list field followed by Apply-SPOProvisioningTemplate list field gets added to Content Type

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#659]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[X ] Bug
[ ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

When Get-SPOProvisioningTemplate on a site with a list field (SPSLocation) followed by Apply-SPOProvisioningTemplate, I expect the list field to stay a list field not added to the content type.
#### Observed Behavior

When Get-SPOProvisioningTemplate on a site with a list field (SPSLocation) followed by Apply-SPOProvisioningTemplate, the list field magically gets added to the content type.
#### Steps to Reproduce

Get-SPOProvisioningTemplate Followed by Apply-SPOProvisioningTemplate (Use ayttached zip file with Apply-SPOProvisioingTemplate to reproduce fault.)

Thanks for your contribution! Sharing is caring.
[temp SPS-London-template1.zip](https://github.com/OfficeDev/PnP-Sites-Core/files/353201/temp.SPS-London-template1.zip)

**Comment by jansenbe** [comment]
**Internal testing feedback**
Provisioned user provided template successfully. SPSLocation field not added to content type as mentioned by user.

Closing the issue now
