### ISSUE TITLE
Add delta handling for documentset settings of a documentset contenttype

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/PnP-Sites-Core#660]
#### Category

[ ] Bug
[X] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013
#### Expected or Desired Behavior

Updating the "documentset" properties of an existing documentset contenttype is not yet implemented whereas we've CSOM support to do this. Would expect that one can update the AllowedContentTypes, DefaultDocuments, SharedFields and WelcomePageFields 
#### Observed Behavior

No documentset updates done

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
