### ISSUE TITLE
Document Template attribute is missing in Content Type Definition

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#665]
Which PnP repository to report the issue?
•PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core 

Category

[X] Bug
 [ ] Enhancement

Environment

[ ] Office 365 / SharePoint Online
 [ ] SharePoint 2016
 [ X] SharePoint 2013

Expected or Desired Behavior

When I set Document Template for Content Type in Content type settings, and then I try to get provisioning template using web.GetProvisioningTemplate, save it using XMLFileSystemTemplateProvider - specified Document Template should be added to Content Type element in resulting .xml file.

Observed Behavior

Core component is unable to save DocumentTemplate attribute in the xml file via XMLFileSystemTemplateProvider .SaveAs.  The Problem is in XMLKplPnPSchemaV201512Formatter in 
ToFormattedTemplate, paragraph Content type. The DocumentTemplate attribute is missing.
I have corrected this bug - corrected file is in attachment

Steps to Reproduce

In Site Setting create new or take an existing one content type of type "Document". In Advance setting set upload new document template. The try to get provisioning template of this site and save it as File.

KR
Konrad

**Comment by bturkenburg** [comment]
Hi Konrad, see issue #378

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Yes, as stated by @bturkenburg we have the same issue/question in #378 and as you can see, it cannot be managed by the engine but you have to handle it manually. I will close this item. Thanks.
