### ISSUE TITLE
Apply-SPOProvisioningTemplate documentation does not detail the list of Handlers available

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#666]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[ ] Bug
[X ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[X ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

I would expect the documentation to detail the values that the parameters could take.

If I knew what the list of handlers was then I would do a pull request and update the documentation.

Thanks for your contribution! Sharing is caring.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
