### ISSUE TITLE
Update RoleAssignments for Site groups

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#667]
Hi,

I have followings scenario:
- I have created custom Site Group with Permission Level "Edit"
  so I have in my provisioning template something like this:
  pnp:SiteGroups
          <pnp:SiteGroup Title="TestGr1" Owner="i:0#.w|mobile\kplochar" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="false" />
      /pnp:SiteGroups
      pnp:Permissions
        pnp:RoleAssignments
               <pnp:RoleAssignment Principal="TestGr1" RoleDefinition="Edit" />
        /pnp:RoleAssignments
      /pnp:Permissions
- I want to change permission level to "Read"
  so I have in my provisioning template something like this:
  pnp:SiteGroups
          <pnp:SiteGroup Title="TestGr1" Owner="i:0#.w|mobile\kplochar" AllowMembersEditMembership="false" AllowRequestToJoinLeave="false" AutoAcceptRequestToJoinLeave="false" OnlyAllowMembersViewMembership="false" />
      /pnp:SiteGroups
      pnp:Permissions
        pnp:RoleAssignments
               <pnp:RoleAssignment Principal="TestGr1" RoleDefinition="Read" />
        /pnp:RoleAssignments
      /pnp:Permissions
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[ x] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Permission level for specified group would be changed from "Edit" to "Read".
#### Observed Behavior

"Edit" permission is still there and "Read" permission comes as the "second one".

KR
Konrad

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The engine has been updated since you created this issue. Now the engine works properly adding the new permissions to the target group. However, we do not remove (by default) any existing permissions. So you will end up having Read and Edit. I will close this item and eventually create a new one to think about supporting removal of already assigned permissions. Thanks.
