### ISSUE TITLE
Applying a Provisioning containing Files / Pages does not work with AuthenticationMode set to FormsAuthentication

### ISSUE THREAD

**Issue by sebastienlevert** [SharePoint/PnP-Sites-Core#697]
#### Category

[x ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ x] SharePoint 2013

If SharePoint on-premises, what's exact CU version:  
Major  Minor  Build  Revision

---

15     0      4805   1000
#### Expected or Desired Behavior

Applying a Provisioning template including Files and Pages should work when using AuthenticationMode FormsAuthentication
#### Observed Behavior

The frameworks reports the following exception (Using the PnP-PowerShell to test) :
Apply-SPOProvisioningTemplate : Value cannot be null.
Parameter name: You must set the forms authentication login information on the context.
At C:_\Git\Install-App.ps1:29 char:1
- Apply-SPOProvisioningTemplate -Path "..\templates\App.Files. ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ArgumentNullException
  - FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate
#### Steps to Reproduce
1. Add a FBA Management tool on top of you existing SharePoint environment
2. Enable Anonymous + FBA to the target Web Application
3. Install latest dev branch of PnP-PowerShell (https://github.com/OfficeDev/PnP-PowerShell/blob/dev/Binaries/SharePointPnPPowerShell2013.msi)
4. Connect-SPOnline -Url ... -AuthenticationMode FormsAuthentication
5. Apply-SPOProvisioningTemplate -Path "" with a template with files and / or pages

**Comment by roennes** [comment]
I get the same error from using Get-SPOProvisioningTemplate on a FBA web app. 

```
Get-SPOProvisioningTemplate : Value cannot be null.
Parameter name: You must set the forms authentication login information on the context.
```

**Comment by jansenbe** [comment]
FBA is indeed not something that has been actively developed and tested. Added enhancement label for it. See also related issue #615

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*

**Comment by jeancallisti** [comment]
So that's it? The malfunction (not an "enhancement", a literal malfunction) will never be fixed?

**Comment by PedroMordeP** [comment]
Using SharePointPnPPowerShell2019 with version 3.16.1912.0

Connect-PnPOnline -Url MYUrl -Credentials (Get-Credential) -AuthenticationMode FormsAuthentication

Get this error

    Value cannot be null.
    Parameter name: You must set the forms authentication login information on the context.
