### ISSUE TITLE
Directory recursion issue

### ISSUE THREAD

**Issue by BitBuckets** [SharePoint/PnP-Sites-Core#702]
Hello,

We're trying to use pnp:Directory to recursively provision various files structures into target locations in an Office 365 site collection.  Upon doing so, we're receiving this exception:  

Apply-SPOProvisioningTemplate : Could not find a part of the path
'c:\source\ep\provisioning\provisioningdemo\newssc\Files\Style Library\app\common\core'.
At line:1 char:1
- Apply-SPOProvisioningTemplate -Path "c:\source\ep\provisioning\provis ...
- CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], DirectoryNotFoundException
- FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

The path specified in the exception doesn't actually exist.  It seems to be trying to nest a peer directory under another (meaning, common and core are peers, core is not underneath common as it has been constructed above).

Is there a known issue around path construction when using Directory recursively?

Thanks.
Bryan

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback this issue have been close a while ago, and we left this issue open. I will close it now. Thanks.
