### ISSUE TITLE
Publishing handler exports too many {site} tokens

### ISSUE THREAD

**Issue by cveld** [SharePoint/PnP-Sites-Core#710]
#### Category

[x ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4815.1000; April 2016 CU
#### Expected or Desired Behavior

The output of the generated template being correct.
#### Observed Behavior

The output of the generated template contains too many {site} tokens. All occurences of "/" are being replaced by "{site}".
Output: `<pnp:File Src="MyPageLayout.aspx" Folder="{masterpagecatalog}{site}custom{site}PageLayoutsCustom" Overwrite="true">`
Expected: `<pnp:File Src="MyPageLayout.aspx" Folder="{masterpagecatalog}/custom/PageLayoutsCustom" Overwrite="true">`

To be more specific I have copied some source code from ObjectHandlerBase.cs; part of the Tokenize-method:

``` c#
Uri uri;
if (Uri.TryCreate(webUrl, UriKind.Absolute, out uri))
{
    string webUrlPathAndQuery = System.Web.HttpUtility.UrlDecode(uri.PathAndQuery);
    if (url.IndexOf(webUrlPathAndQuery, StringComparison.InvariantCultureIgnoreCase) > -1)
         {
               result = (uri.PathAndQuery.Equals("/") && url.StartsWith(uri.PathAndQuery))
               ? "{site}" + url // we need this for DocumentTemplate attribute of pnp:ListInstance also on a root site ("/") without managed path
                            : url.Replace(webUrlPathAndQuery, "{site}");
         }
}
```

| Expression | Value |
| --- | --- |
| weburl | http://sp2013.local |
| uri | http://sp2013.local/ |
| uri.PathAndQuery | / |
| webUrlPathAndQuery | / |
| uri.PathAndQuery.Equals("/") | true |
| url.StartsWith(uri.PathAndQuery) | false |
| url | {masterpagecatalog}/custom/PageLayoutsCustom |

It seems that the current logic does not expect subfolders within `url` and/or does not expect a token at the start of `url`.

Possibly related reported issues: #329, #406

**Comment by jansenbe** [comment]
Hi @cveld ,

Did you see this when exporting a top level site collection such as http://sp2013.local mentioned above?

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
