### ISSUE TITLE
List View WebPart does not keep view settings when provisioned

### ISSUE THREAD

**Issue by Bestadd** [SharePoint/PnP-Sites-Core#721]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: July 2016
#### Expected or Desired Behavior

List View Web Parts added to Home.aspx (or any page, we only have Home.aspx) maintain there list view configuration when being provisioned
#### Observed Behavior

List View Web Parts on the Home.aspx are reverting to the default view where Name, Modified, and Modified By are the only columns displayed. 
#### Steps to Reproduce

Use the following ProvisioningTemplateCreationInformation to extract a template from a site where Home.aspx has a List View Web Part with a modified view (not the default view with Name, Modified, and Modified By), then apply that to another site.    The WebPart is added but the view is not set.

```
 ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(templateCtx.Web);
                // Create FileSystemConnector, so that we can store composed files somewhere temporarily
                ptci.FileConnector = new FileSystemConnector(tempDir, "");
                ptci.PersistBrandingFiles = true;
                ptci.IncludeSiteGroups = true;
```

Here is the XML template pulled from one of my sites

`
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.6.1608.0, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Templates ID="CONTAINER-My-PD-Template">
    <pnp:ProvisioningTemplate ID="My-PD-Template" Version="1" BaseSiteTemplate="STS#0" DisplayName="My PD Template">
      <pnp:WebSettings NoCrawl="false" WelcomePage="SitePages/Home.aspx" SiteLogo="{site}/SiteAssets/pnnl_logo_battelle.png" AlternateCSS="{site}/Style Library/site.css" MasterPageUrl="{masterpagecatalog}/oslo.master" CustomMasterPageUrl="{masterpagecatalog}/oslo.master" />
      <pnp:RegionalSettings AdjustHijriDays="0" AlternateCalendarType="None" CalendarType="Gregorian" Collation="25" FirstDayOfWeek="Sunday" FirstWeekOfYear="0" LocaleId="1033" ShowWeeks="false" Time24="false" TimeZone="13" WorkDayEndHour="5:00PM" WorkDays="62" WorkDayStartHour="8:00AM" />
      <pnp:SupportedUILanguages>
        <pnp:SupportedUILanguage LCID="1033" />
      </pnp:SupportedUILanguages>
      <pnp:PropertyBagEntries>
        <pnp:PropertyBagEntry Key="DesignPreviewThemedCssFolderUrl" Value="{themecatalog}/Themed/475632DF" Overwrite="false" />
      </pnp:PropertyBagEntries>
      <pnp:Security ClearSubscopes="false">
        <pnp:AdditionalAdministrators>
          <pnp:User Name="i:0#.w|pnl\d3j096" />
          <pnp:User Name="c:0+.w|s-1-5-21-19610888-2120439649-608991905-97223" />
          <pnp:User Name="i:0#.w|pnl\svcspuser" />
        </pnp:AdditionalAdministrators>
        <pnp:Permissions />
      </pnp:Security>
      <pnp:Lists>
        <pnp:ListInstance Title="Documents" Description="" DocumentTemplate="{site}/Shared Documents/Forms/template.dotx" OnQuickLaunch="true" TemplateType="101" Url="Shared Documents" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" TemplateFeatureID="00bfea71-e717-4e80-aa17-d0c71b360101" EnableAttachments="false">
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0101" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
          <pnp:Views>
            <View Name="{A5CD3433-5159-494C-AC7B-AAFDE730EEF3}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Documents" Url="/sites/template/Shared Documents/Forms/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/dlicon.png?rev=23">
              <Query>
                <OrderBy>
                  <FieldRef Name="FileLeafRef" />
                </OrderBy>
              </Query>
              <ViewFields>
                <FieldRef Name="DocIcon" />
                <FieldRef Name="LinkFilename" />
                <FieldRef Name="Modified" />
                <FieldRef Name="Editor" />
                <FieldRef Name="Sent_x0020_to_x0020_HPRM" />
              </ViewFields>
              <RowLimit Paged="TRUE">30</RowLimit>
              <JSLink>clienttemplates.js</JSLink>
            </View>
          </pnp:Views>
          <pnp:Fields>
            <Field Type="Boolean" DisplayName="Sent to HPRM" EnforceUniqueValues="FALSE" Indexed="FALSE" ID="{1e6e495b-53f8-4183-a2c5-019fb3ab04bc}" SourceID="{{listid:Documents}}" StaticName="Sent_x0020_to_x0020_HPRM" Name="Sent_x0020_to_x0020_HPRM" ColName="bit2" RowOrdinal="0">
              <Default>0</Default>
            </Field>
          </pnp:Fields>
          <pnp:FieldRefs>
            <pnp:FieldRef ID="3881510a-4e4a-4ee8-b102-8ee8e2d0dd4b" Name="CheckoutUser" DisplayName="Checked Out To" />
          </pnp:FieldRefs>
        </pnp:ListInstance>
      </pnp:Lists>
      <pnp:Features>
        <pnp:WebFeatures>
          <pnp:Feature ID="f151bb39-7c3b-414f-bb36-6bf18872052f" />
        </pnp:WebFeatures>
      </pnp:Features>
      <pnp:Files>
        <pnp:File Src="pnnl_grid_silver.jpg" Folder="{themecatalog}" Overwrite="true" />
        <pnp:File Src="pnnl.spcolor" Folder="{themecatalog}/15" Overwrite="true" />
        <pnp:File Src="pnnl_logo_battelle.png" Folder="{site}/SiteAssets" Overwrite="true" />
        <pnp:File Src="site.css" Folder="{site}/Style Library" Overwrite="true" />
      </pnp:Files>
      <pnp:ComposedLook Name="PNNL" ColorFile="{themecatalog}/15/pnnl.spcolor" FontFile="" BackgroundFile="{themecatalog}/pnnl_grid_silver.jpg" Version="0" />
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
`

**Comment by gabbsmo** [comment]
Importing a XsltListViewWebPart from xml-file doesn't really work in SP out of the box either. You have to find the web part's view in the list and change it after provisioning the web part.

**Comment by Qebbo** [comment]
I encounter the same issue

**Comment by rajajii** [comment]
Same problem here any fix for this issue yet ?

**Comment by s-KaiNet** [comment]
@rajajii with this change you will get NullReferenceException on `nameAttribute.ToString()` in case if `Name` is null.   
Actually you don't need to change anything, just provide valid attribute for the view, using guide from corresponding issue #584  and that's it. I believe current issue can be closed.

**Comment by PaoloPia** [comment]
Thanks @s-KaiNet I totally agree with you. I will close this item, which can be re-routed to #584.

**Comment by imranraja** [comment]
this is still a bug:
Please change 
line 128 from nameAttribute != null to (nameAttribute != null && !String.IsNullOrEmpty(nameAttribute.ToString()))
line 141 from displayNameAttribute != null to (nameAttribute != null && !String.IsNullOrEmpty(displayNameAttribute.ToString()))
line 155 from urlAttribute != null to (nameAttribute != null && String.IsNullOrEmpty(urlAttribute.ToString()))
