### ISSUE TITLE
Add IndexedPropertyBagKey related methods to Client.List via extension methods

### ISSUE THREAD

**Issue by ezybzy** [SharePoint/PnP-Sites-Core#725]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[ ] Bug
[X] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013
#### Expected or Desired Behavior

Right now, Microsoft.SharePoint.Client.Web has already been extended via Microsoft.SharePoint.Client.WebExtensions with "AddIndexedPropertyBagKey", "GetIndexedPropertyBagKeys", and "RemoveIndexedPropertyBagKey". Microsoft.SharePoint.SPList also supports this behavior on SSOM but not on Microsoft.SharePoint.Client.List CSOM. The PnP implementation creates extension methods to List object is needed.

**Comment by ezybzy** [comment]
Have anyone worked this out yet?

**Comment by jansenbe** [comment]
Hi @ezybzy , I'm flagging this as enhancement so that it will end up in our backlog. If you need this urgently feel free to create a PR with your implementation as that will speed up things.

**Comment by ezybzy** [comment]
I've written that code for a while. Let me find it and figure out how to do the first pull release.

**Comment by jansenbe** [comment]
Hi @ezybzy ,

Checkout this training: https://www.youtube.com/watch?v=ELeGFILRFfQ&index=6&list=PLR9nK3mnD-OUifS8ao3pKLEyagRu6io8K

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
