### ISSUE TITLE
Support deployment of navigation elements inside PnP provisioning templates for regular sites

### ISSUE THREAD

**Issue by haroldvandekamp** [SharePoint/PnP-Sites-Core#738]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[ ] Bug
[X] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013
#### Expected or Desired Behavior

Being able to deploy navigation elements to a regular STS#0 (non-publishing) site works when deploying a PnP Provisioning Template including pnp:Navigation elements
#### Observed Behavior

The navigation pnp:Navigation elements inside a PnP Provisioning Template are not deployed on a regular (non-publishing) site with template ID STS#0. Only for publishing sites they are deployed.
#### Steps to Reproduce

For example we would like to be able to deploy this provisioning template to a regular (non-Publishing) site including the navigation elements. Currently this only works on Publishing sites:

```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.6.1608.0, Culture=neutral, PublicKeyToken=3751622786b357c2" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-7FB72622E1654B1C9765678E8C5093A3">
    <pnp:ProvisioningTemplate ID="TEMPLATE-7FB72622E1654B1C9765678E8C5093A3" Version="1" BaseSiteTemplate="STS#0">
      <pnp:Security ClearSubscopes="false">
        <pnp:AdditionalOwners>
          <pnp:User Name="c:0-.f|rolemanager|spo-grid-all-users/9fcc7bfd-834f-4f72-89f1-509ad9e9a92f" />
        </pnp:AdditionalOwners>
      </pnp:Security>
      <pnp:Navigation>
        <pnp:GlobalNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="true">
            <pnp:NavigationNode IsExternal="true" Title="Wikipedia" Url="http://www.wikipedia.org"></pnp:NavigationNode>
          </pnp:StructuralNavigation>
        </pnp:GlobalNavigation>
        <pnp:CurrentNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="true">
            <pnp:NavigationNode IsExternal="false" Title="Start" Url="/SitePages/Home.aspx"></pnp:NavigationNode>
            <pnp:NavigationNode IsExternal="false" Title="Project team" Url="{site}">
              <pnp:NavigationNode IsExternal="false" Title="Work docs" Url="{site}/Work documents"></pnp:NavigationNode>
              <pnp:NavigationNode IsExternal="false" Title="Mail" Url="{site}/Work mail"></pnp:NavigationNode>
              <pnp:NavigationNode IsExternal="false" Title="Deliverables" Url="{site}/Deliverables"></pnp:NavigationNode>
            </pnp:NavigationNode>
            <pnp:NavigationNode IsExternal="true" Title="Wikipedia" Url="http://www.wikipedia.org"></pnp:NavigationNode>
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>
      </pnp:Navigation>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```

**Comment by MartasSousek** [comment]
I´ve been experiencing the same issue. The Navigation nodes are actually parsed from provided xml template (as i can inspect them in the template class), but not provisioned.

**Comment by wobba** [comment]
Right now it checks if it's a pub site, and skips nav it's not.

@PaoloPia, would it be correct if I change the code to check that if it does not have publishing, then it will also check that nav is not managed metadata.

As it provisions structural nav just fine if I remove all pub checks in the handler on a non-pub site.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedbacks. Because the PRs #896 and #935 have been already merged, I will close this item.
