### ISSUE TITLE
Provisioning of directories fail when MetadataMappingFile empty or not provided in template

### ISSUE THREAD

**Issue by wilecoyotegenius** [SharePoint/PnP-Sites-Core#751]
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online (I have tried only in this one)
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

Successful provisioning of directories without providing MetadataFile to Directory element within the template.. 
#### Observed Behavior

According to Provisioning Schema 2016-05 specification, MetadataMappingFile property is optional. However, it is by default set to empty string, not null (in fact it is never null). Therefore it fails in GetMetadataProperties method from DirectoryExtensions (throws ArgumentException exception with "fileName" message). 

I would suggest changing line 401 in ObjectFiles.cs from
`if (directory.MetadataMappingFile != null)`
to
`if (!string.IsNullOrEmpty(directory.MetadataMappingFile))`
to avoid this problem.

There is a workaround for that - just specify wrong path for MetadataMappingFile property (any but empty). This will be caught and handled by FileSystemConnector's GetFileFromStorage method. But for the sake of correctness, maybe it's worthwile to fix that. It is not a huge change, but will save time of others, that will rely on MetadataMappingFile being optional.
#### Steps to Reproduce

I just took the file ProvisioningSchema-2016-05-DirectorySample.xml from PNP-Provisioning GitHub repo and just removed MetadataMappingFile property (since I didn't need any special metadata applied to provisioned files). No other changes were made to the template file.
I used XMLTemplateProvider for getting the template from file system.

Best Regards
Konrad

**Comment by jansenbe** [comment]
The suggested fix was already implemented
