### ISSUE TITLE
Exporting Web Part Pages

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#753]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

When I create pages in a site pages library i have two options. 
- Wiki page
- Web part page
  I would like to use a Web Part page ads my home page and export the site using PnP PoSh
#### Observed Behavior

If I now create a Web Part Page and set this to be the home page then the export fails with the folowing error:
Get-SPOProvisioningTemplate : Object reference not set to an instance of an object.
#### Steps to Reproduce
1. Create web Part page in a team site
2. Run Get-SPOProvisioningtemplate

**Comment by Laul0** [comment]
This issue can be reproduce to SharePoint 2013 too

**Comment by PaoloPia** [comment]
Now it should be fixed, please give it a try in the DEV branch. Thanks.
