### ISSUE TITLE
Problems with document libraries with custom document templates

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#758]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Get-SPOProvisioningTemplate and ApplyProvisioningTemplate should handle non standard document templates
#### Observed Behavior

When a custom document template is used on a library. The Get-SPOProvisioningTemplate doesn't collect the document and when trying to apply the template the following errors are thrown:

PowerShell_ISE.exe Information: 0 : 2016-09-19 16:29:46.4091    [List instances]    [12]    [Debug] Updating list CVDocuments failed: **Invalid template URL.**

**The template must exist in the Forms directory of this document library. Create the template in the Forms directory, and then re-type the Web address.** Note that you canno
t move or copy a template into the Forms directory. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.UpdateList(Web web, List existingList, ListInstance templateList, TokenParser parser, PnP
MonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, Provisioning
TemplateApplyingInformation applyingInformation)    5227ms  d7bd5ac7-f320-4295-b191-d287baaaf929
#### Steps to Reproduce

Option 1. Create document library  update the document template on the library
Option 2. Create document library with a custom content type and update the template on the content type.

**Comment by VesaJuvonen** [comment]
thx Pieter for submitting this. It's an race condition challenge, which we'll need to get solved.

**Comment by PaoloPia** [comment]
Hi Pieter,
Because you opened almost the same issue here #1007 I will close this one and keep the new one. Thanks.

**Comment by siderys** [comment]
I'm having the "Invalid template URL. The template must exist in the Forms directory of this document library. Create the template in the Forms directory, and then…..." issue, but the reason is that the template is an .xsn file (Infopath) not pointing any content type.
