### ISSUE TITLE
 When Apply-SPOProvisioning template applies the navigation a token isn't resolved

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#763]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[ X] Bug
[ ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Exporting site from one tenant to another fails.
#### Observed Behavior

When Apply-SPOProvisioning template applies the navigation a token isn't resolved:

> PowerShell_ISE.exe Information: 0 : 2016-09-22 13:36:25.8678  [Navigation]    [12]    [Debug] Code execution scope started    0ms 502c7dbd-c818-48d8-a2fa-f45464c3a437
> PowerShell_ISE.exe Information: 0 : 2016-09-22 13:36:26.0681  [Navigation]    [12]    [Debug] Code execution scope ended  205ms   502c7dbd-c818-48d8-a2fa-f45464c3a437
> PowerShell_ISE.exe Information: 0 : 2016-09-22 13:36:26.0849  [Provisioning]  [12]    [Debug] Code execution scope ended  92227ms 502c7dbd-c818-48d8-a2fa-f45464c3a437
> **Apply-SPOProvisioningTemplate : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).**

In the template.xml I'm seeing:

>  < pnp:GlobalNavigation NavigationType="Managed">
>           < pnp:ManagedNavigation TermStoreId="{sitecollectiontermstoreid}" TermSetId="{termsetid:Site Collection - mod123456.sharepoint.com-sites-BM:Site Navigation}" />
>         < /pnp:GlobalNavigation>
>         < pnp:CurrentNavigation NavigationType="Managed">
>           < pnp:ManagedNavigation TermStoreId="{sitecollectiontermstoreid}" TermSetId="{termsetid:Site Collection - mod123456.sharepoint.com-sites-BM:Site Navigation}" />
>         < /pnp:CurrentNavigation>

mod123456 is the other tenant.
#### Steps to Reproduce

Export site from one tenant and import it into a different tenant

**Comment by VesaJuvonen** [comment]
thx Pieter,
this is clearly a token replacement issue in the engine side, which we should get solved relatively fast.

**Comment by jansenbe** [comment]
Our testing shows that this now works. I'm closing the issue now, but if you still see the problem with the latest release please reopen this issue.
