### ISSUE TITLE
Errors provisioning lists in SP 2013 - April 2015 CU environment

### ISSUE THREAD

**Issue by dmdj** [SharePoint/PnP-Sites-Core#764]
PnP Sites Core - Sept 2016
#### Category

[ ] Bug
[X ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version:   **April 2015 CU**
#### Expected or Desired Behavior

Expected baseline to still be April 2015 CU
#### Observed Behavior

A number of the DLLs seem to be March 2016 PU.  Doing provisioning of Lists getting: 
   Could not load type 'Microsoft.SharePoint.Client.DocumentSet.DocumentSetTemplate' from assembly 'Microsoft.SharePoint.Client.DocumentManagement, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'. 
#### Steps to Reproduce

Try to use provisioning of lists in April 2015 CU environment.

The read me indicates "Current version: version deployed with the April 2015 CU: no separate redist (version 15.0.4711.1000)".  However, the build folder is showing what looks like some March 2016 PU DLLs.  Can we safely target April 2015 CU+ environments still with the Sept 2016 Sites Core libraries?

**Comment by VesaJuvonen** [comment]
Hi David,
you are absolutely correct on the version mismatch here. Our general baseline is April 2015 CU, but there are certain exceptions for this, which generally are being handled with server version checking. That checking is not however done with method, which is clearly a bug on our end. If you upgrade your server to March PU, things are resolved accordingly, but we do understand the possible complexity to do that.

We'll do a comparison between the versions and get this fixed - unfortunately schedule is for November release.

**Comment by jansenbe** [comment]
We've done improvements in this area, can you please retest with the latest version and let us know if you still are having this issue?

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
