### ISSUE TITLE
GetAzureADAppOnlyAuthenticatedContext MissingMethodException / GetAzureADNativeApplicationAuthenticatedContext: TypeLoadException 

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#769]
_From @TimDaborn2 on June 24, 2016 11:16_
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[ ] Bug
#### Environment

[ ] Office 365 / SharePoint Online
#### Expected or Desired Behavior

Not to crash!
#### Observed Behavior

I seem to be suffering a NuGet conflict with the pnp library and any version package of the Microsoft.IdentityModel.Clients.ActiveDirectory after 2.26.

The current version is 3.10.  The source references  version 2.18 - originally released in June 2015.

Using any of the last 3 versions of the Microsoft.IdentityModel.Clients.ActiveDirectory package, commands such as 
    AuthenticationManager().GetAzureADAppOnlyAuthenticatedContext
    AuthenticationManager().GetAzureADNativeApplicationAuthenticatedContext

raise Missing Method exception and TypeLoadExceptions, respectively.

_Copied from original issue: OfficeDev/PnP#1469_

**Comment by VesaJuvonen** [comment]
Unfortunately there are differences in the ActiveDirectory NuGet between 2.x and 3.x versions. PnP is build with 2.x, which means that if you upgrade to latest version, you will have an exception. This is really because the AD NuGet package does NOT have backward compatibility around the versions. We are looking for upgrading to newer version at some point, but until we do so, you should be using 2.x of the AD NuGet.

**Comment by jansenbe** [comment]
Closing this issue, the currently used version in PnP is the 2.x version.

**Comment by SchauDK** [comment]
Just for info. This is also an issue for me.
Can't downgrade to 2.x, so for now I'm compiling my own version of OfficeDevPnP.Core.
