### ISSUE TITLE
Inconsistent RoleDefinitionPermission enumeration

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#771]
_From @hyankov on June 22, 2016 7:20_
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[X] Bug

_Some_ of the members in the **RoleDefinitionPermission** enumeration differ from the SharePoint's **SPBasePermission** enumeration members.

e.g. '**AddListItems**' instead of '**InsertListItems**', '**AddAndCustomizePages**' instead of '**WriteWebPages**', '**Open**' instead of '**OpenWeb**, '**CancelCheckout**' instead of SharePoint's '**BreakCheckout**'.

_Copied from original issue: OfficeDev/PnP#1464_

**Comment by jansenbe** [comment]
This has been fixed, closing this issue.
