### ISSUE TITLE
Get-SPOProvisioningTemplate throws a fatal error if a look-up site-column in the source site is referencing a list in the sub web

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#772]
_From @mahajangaurav on August 18, 2015 22:31_

The error received is:
Get-SPOProvisioningTemplate: List does not exist.
The page you selected contains a list that does not exist.  It may have been deleted by another user.
At E:\Temp\Get-SPOProvisioningTemplate.ps1:5 char:1
- Get-SPOProvisioningTemplate -Out ("Root-" + $FileName) -IncludeAllTermGroups -Fo ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], ServerException
  - FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.GetProvisioningTemplate

Expected behavior:
Get-SPOProvisioningTemplate should check the web id and if the web id is different than the current web's id, it should not try to get the list.

Ideal would be to add another parameter to the filed schema so it can contain the name of the sub-web. This way, we can use that parameter in Apply-SPOProvisioningTemplate to recreate the association in the destination web

_Copied from original issue: OfficeDev/PnP#1142_

**Comment by VesaJuvonen** [comment]
Should be already fully fixed, but we would need assistance on testing and verifying this.

**Comment by jansenbe** [comment]
The engine supports a list in the same site or an existing list in root web when it comes to provisioning lookup fields. Closing the issue now
