### ISSUE TITLE
Apply‑SPOProvisioningTemplate: Sitecolumns not connected to termsets (inter tenant)

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#775]
_From @SjoerdV on July 10, 2015 14:33_

With an inter-tenant migration:
1)  I used Export-SPOTaxonomy -IncludeID and import the taxonomy with Import-SPOTaxonomy on a different tenant. The termsets are created with the exact same ID's like the source tenant
2) Afterwards I made a Get-SPOProvisioningTemplate to generate the source template and I applied it to the target tenant with Apply-SPOProvisioningTemplate. All Sitecolumns are created except they are not attached to the termsets even though all the ID's match up. (I do have a workaround for the duplicate fieldnames error) while applying the template

_Copied from original issue: OfficeDev/PnP#1035_

**Comment by VesaJuvonen** [comment]
Should be properly fixed, but we would need help on verifying this with latest version.

**Comment by stevus1970** [comment]
I've run this using version 2.10.1612.0 but the columns are still not connected to the related Term Set.  When you view the column through the UI it appears to be okay (the right Term Set looks selected), but using the column in a list/library shows that the column is not connected as no values are available to select.  Viewing the column in the UI and manually selecting Update appears to fix the problem, so I've tried running a simple update on the underlying Field post-deployment to effectively duplicate this but it doesn't appear to resolve it.  I'm assuming the version I've mentioned should have the fix?

**Comment by stevus1970** [comment]
Ignore my previous comment - having retested it again this morning I noticed that the AnchorId had been specified with a particular GUID instead of an empty GUID.  After changing it to 00000000-0000-0000-0000-000000000000 the provisioning worked perfectly and the column was bound to the underlying term set correctly.

**Comment by VesaJuvonen** [comment]
thx stevus1970, just to be 100% on the situation. You tested this and things are now working properly, like we assumed? I'll close up this after confirmation and absolutely give you credits on helping around this in the next monthly release notes.

**Comment by stevus1970** [comment]
Yes, it does appear to be working

-----Original Message-----

**Comment by VesaJuvonen** [comment]
thx stevus1970, happy to get you creds on this verification work on our monthly communications. I'll close this one for how. We can mention just your GitHub alias if you prefer or you can update the profile to have your correct name. Up to you in the end. Anyway - thx for the test work, really appreciated.
