### ISSUE TITLE
User's code does not compile with the September Drop of PnP-Sites-Core

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#776]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[ ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X ] SharePoint 2013

If on-premises, what's exact CU version:  SharePoint 2013 SP1 August 2016 CU
#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._
#### Observed Behavior

I have recently taken over looking after some code.  GetFolders in user's code fails when I recompile it with the September drop of the PnP.Core  -
This looks like this has been added recently 
/// <summary>

 
52         /// Get the folders of a specified container 
53         /// </summary>

 
54         /// <param name="container">Name of the container to get the folders from</param> 
55         /// <returns>List of folders</returns> 
56         public abstract List<string> GetFolders(string container); 
57  
 in Framework/Provisioning/Connectors/FileConnectorBase.cs.
#### Steps to Reproduce

Recompile code with September drop.

So does the version on your development box have to be the same as the version on your SharePoint Server ?

Does this provisioning Code run on your workstation or on your SharePoint Box ?

JavaScript runs in your browser as does the PnP Provisioning PowerShell run on your workstation.  But this is C# and C# normally runs on servers.

Thanks for your contribution! Sharing is caring.

**Comment by NPrice99** [comment]
To answer my own questions - the provisioning code runs on my workstation.  As far as I can see as long as the provisioning box is Windows 10 all is well.  The only question left is was the September drop include the change above

**Comment by VesaJuvonen** [comment]
It could be that there's an API, which has not been properly excluded with the on-premises tag, if the property / method is only available for SP Online. Looking on the description of the issue, it's however extremely hard to figure out what actually goes wrong. Could you share the exception details from Visual Studio (full information), so that we can double check - thx. 

PnP automated testing is using SP2013 August 2016 CU and has no issues with the September release, so additional details would be needed.

**Comment by jansenbe** [comment]
**internal testing feedback:**
VM: SharePoint version 15.0.4885.1000
Created console application and installed NuGet “SharePointPnPCore2013 dll version to 2.7.1609.3 - September 12, 2016 05:58” package.
Added piece of code mentioned in the issue.
Compiled the code successfully

Closing issue per test feedback.
