### ISSUE TITLE
Apply-SPOProvisioningTemplate - Problem with Permissions for Provisiong ContentType

### ISSUE THREAD

**Issue by Campergue** [SharePoint/PnP-Sites-Core#778]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
  _You can delete this section after you have confirmed target repository for your submission._
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

I expect that a provisioning for easy ContentType with Siteowner rights (Full Control) is possible.
#### Observed Behavior

when I started the provisioning, it breaks off constantly during the placement of content type. With the error message Acces Denied.

![image](https://cloud.githubusercontent.com/assets/6292190/18996855/46192e62-8732-11e6-9a5c-5b4c104c51b0.png)

When I put the ContentTypes manually via the Commands add-SPOContentType and the fields with add-SPOFieldToContentType, I get no error message.

In scheme I've seen requires the attribute Sealed Admin rights. This I did not use. Can it be that this is still set, even without that I have this defined in the XML file?
#### Steps to Reproduce
1. Start the Apply-SPOProvisioningTemplate with a User that is only in the Owner Group.
2. <pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
   <pnp:Preferences Author="BW" Version="1.0" Generator="">
   /pnp:Preferences
   pnp:Templates
     <pnp:ProvisioningTemplate ID="VFPos" Version="1">
   
   ```
   <!-- ################################## -->
   <!-- Content Types                      -->
   <!-- ################################## -->
   <pnp:ContentTypes>
     <!-- ================================ -->
     <!-- Ct_01 Auswahl                    -->
     <!-- ================================ -->
     <pnp:ContentType ID="0x0100B53BB1F1E1C946E7B17765432179BBEE"
            Name="Auswahl"
            Group="_VKF smart"
            Description="Auswahl">
       <pnp:FieldRefs>
         <pnp:FieldRef ID="{B7E63899-2FB7-488E-A4CF-268854D676DB}" Name="Details" Required="false" />
         <pnp:FieldRef ID="{C8E7C4E1-F2F0-4178-9B63-AC8C24B72C44}" Name="Bild"    Required="false" />
       </pnp:FieldRefs>
     </pnp:ContentType>
   </pnp:ContentTypes>
   ```
   
     /pnp:ProvisioningTemplate
   /pnp:Templates
   /pnp:Provisioning

The FieldRef must be replaced with columns that are available on the Current Web where are running the Script.

I use the actually Schema Version 2016-05 and PnP Powershell Module 2.7.1609.3

Hope you can find the Problem.

**Comment by jansenbe** [comment]
Issue was reproduced. Marking as bug

Internal testing feedback:
Online:
•	Created new test user and added to owners group
•	Got Access Denied error when provisioned but observed content types successfully created

Onprem:
No error observed and it provisioned successfully

**Comment by baywet** [comment]
Running into the same issue with 
- pnp ps 2.25.1804.1 (I had 2.24 something before and running into the same issue)
- schema 2016-05
- sp online 16.0.0.7611
- "classic site" (provisioned through the classic admin portal)

**Comment by jansenbe** [comment]
Closing as fix has been merged
