### ISSUE TITLE
Improve MUI Capabilities of Provisioning Engine / Core / Samples

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/PnP-Sites-Core#779]
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[ ] Bug
[X ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

As discussed with Erwin and Paolo at Ignite conference here is a suggestion how to improve the multilanguage capabilities of the provisioning engine and maybe even core library or samples.

In order to set MUI properties of navigation items, webpart titles and things that are not yet available through csom but that are possible using the UI, you can secify the language in the request header.

Here is a quick hint, how to do this. Feel free to contact me if you need further details.

```
node.Title="TEST";
ctx.PendingRequest.RequestExecutor.WebRequest.Headers["Accept-Language"] = System.Globalization.CultureInfo(1031)).Name;
ctx.ExecuteQuery();

```

**Comment by jansenbe** [comment]
This has been implemented in the engine, closing this issue now

**Comment by OliverZeiser** [comment]
How and where has this been implemented? Are view-titles now supported with MUI as well? Can we use localization tokens for this in provisioning engine now?

**Comment by VesaJuvonen** [comment]
Had a chat with Oliver and apparently, we are missing this in the parts of the engine. Will provide more details offline.

**Comment by MartinLaplante** [comment]
When this is confirmed done, I will change a slide I have used at conferences for over a year saying PnP Provisioning Engine does not yet do this. Not all MUI is supported by CSOM yet, and certainly not view titles, but most of it has a resource with a SetValueForUICulture method.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
