### ISSUE TITLE
contenttypeid token not correctly replaced

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#781]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[?] SharePoint 2016
[?] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

When extracting a ProvisioningTemplate from an existing site (used PowerShell for this) I get a ProvisioningTemplate XML containing {contenttypeid} tokens. I expect these to also work in a custom template using these tokens.
#### Observed Behavior

When using {contenttypeid} tokens in a custom template to specify the ContentType (for a File / Publishing Page in my case) applying succeeds but the correct ContentType is not set correctly
#### Steps to Reproduce
- Create a Publishing Site (sub site)
- Change the site's welcome page's layout to one of the other allowed Page Layouts based on a different Content Type (one of the Article Page layouts)
- Save the site as a ProvisioningTemplate and out to an XML file
- Open the XML file and notice the contenttypeid token in the File definition for the welcome page
- Create a new Provisioning template using a File definition to overwrite the site's welcome page
- In the file properties make use of contenttypeid token to specify the desired content type (you could use all file properties from the extracted template)
- Apply the ProvisioningTemplate to the same or a new publishing site
- See the welcome page's content type incorrectly configured to the default content type configured on the pages library

**Comment by paulpascha** [comment]
Update: this issue only seems to occur while provisioning subsites. I guess in TokenParser all contenttype tokens should be added based on Web.AvailableContentTypes collection instead of Web.ContentTypes. Web.ContentTypes is an empty collection in case of subsites

**Comment by jansenbe** [comment]
Your fix was merged, so closing the issue
