### ISSUE TITLE
contenttypeid token extracted but not documented as supported token

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#782]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[X] Bug
[ ] Enhancement
#### Environment

[X] Office 365 / SharePoint Online
[?] SharePoint 2016
[?] SharePoint 2013
#### Expected or Desired Behavior

I expect Tokens included in an extracted Provisioning Template to be documented in 
[List of Tokens supported by the PnP Provisioning Engine](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/ProvisioningEngineTokens.md).
#### Observed Behavior

In an extracted template I found contenttypeid token being used in File Properties but this one is no documented

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
