### ISSUE TITLE
startIndex cannot be larger than length of string. Parameter name: startIndex for apply site provisioningtemplate

### ISSUE THREAD

**Issue by VesaJuvonen** [SharePoint/PnP-Sites-Core#785]
_From @nramar on June 15, 2016 15:28_

I followed the exact same steps as mentioned in the sample but I get this error for a simple site.

   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.TokenParser..ctor(Web web, ProvisioningTemplate template)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)

XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"D:\templates", "");
var result = provider.GetTemplate("SampleTeamSite.xml");
if(result.PropertyBagEntries.Count >1)
{
ProvisioningTemplate template = result;
Web newweb = ctx.Web.GetWeb("amarnugettest5");
newweb.ApplyProvisioningTemplate(template);

}

_Copied from original issue: OfficeDev/PnP-Guidance#69_

**Comment by VesaJuvonen** [comment]
_From @jansenbe on June 15, 2016 17:12_

hi nramar,

Can you me more precise about what sample you're talking?

**Comment by VesaJuvonen** [comment]
_From @nramar on June 15, 2016 17:21_

Hi Jan,

I am just trying to export a current site as template and apply to new site using simple console app. Below is my code and template for SP 2013 On Prem
//SAVE TEMPLATE
Web newweb = ctx.Web.GetWeb("amarnugettest4");
ctx.Load(newweb, w => w.Title);
ctx.ExecuteQueryRetry();
ProvisioningTemplateCreationInformation ptci = new ProvisioningTemplateCreationInformation(newweb);
ptci.FileConnector = new FileSystemConnector(@"D:\templates\new", "");
ptci.PersistBrandingFiles = true;
ProvisioningTemplate stemplate = newweb.GetProvisioningTemplate(ptci);
XMLTemplateProvider sprovider = new XMLFileSystemTemplateProvider(@"D:\templates\new", "");
sprovider.SaveAs(stemplate, "newtemplate1.xml");
//APPLY
XMLTemplateProvider aprovider = new XMLFileSystemTemplateProvider(@"D:\templates\new", "");
ProvisioningTemplate atemplate = aprovider.GetTemplate("newtemplate1.xml");
Web applyweb = ctx.Web.GetWeb("amarnugettest5");
ctx.Load(applyweb, w => w.Title);
ctx.ExecuteQueryRetry();
atemplate.Connector = aprovider.Connector;
applyweb.ApplyProvisioningTemplate(atemplate);


[newtemplate1.zip](https://github.com/OfficeDev/PnP-Guidance/files/316738/newtemplate1.zip)


Amar

**Comment by jansenbe** [comment]
**internal testing feedback:**

Downloaded user provided template. 
Provisioned template successfully

Closing issue per test feedback
