### ISSUE TITLE
Apply-SPOProvisioningTemplate get error when provisioning reused sub term

### ISSUE THREAD

**Issue by kelvindongzicheng** [SharePoint/PnP-Sites-Core#792]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[x] Bug
[ ] Enhancement
#### Environment

[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

Try to use201605 xml template and  Apply-SPOProvisioningTemplate to create a reuesd sub term. structure as following
Term Group
--TermSetA
-----Term1
--------TermOriginal
--TermSetB
-----Term2
--------TermOriginal(Reused)
#### Observed Behavior

got "Failed to read from or write to the database" Error
#### Steps to Reproduce

create testing xml, and run the Apply-SPOProvisioningTemplate
`<pnp:ProvisioningTemplate ID="Setup1" Version="1" xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
 <pnp:TermGroups>
    <pnp:TermGroup Name="testgroup">
      <pnp:TermSets>
        <pnp:TermSet Name="termsetA" Language="1053" ID="{240238EF-C9DA-45D6-86C5-8F5ED2ED147D}">
          <pnp:Terms>
            <pnp:Term ID="288B75C0-6CEE-4E1D-971B-04F824F766AC" Name="term1">
              <pnp:Terms>
                <pnp:Term ID="E2BF9B94-37F7-4D6B-8EFC-36747F83FF65" Name="testterm" IsReused="true" IsSourceTerm="true" SourceTermId="E2BF9B94-37F7-4D6B-8EFC-36747F83FF65"/>
              </pnp:Terms>
            </pnp:Term>
          </pnp:Terms>
        </pnp:TermSet>
        <pnp:TermSet Name="test" Language="1053" ID="{07CD22AD-038C-4C68-A0CC-5B6B1E2AF3D9}">
          <pnp:Terms>
            <pnp:Term ID="{439D9666-7389-4ADE-9C3A-3EBD64B0C835}" Name="newterm">
              <pnp:Terms>
                <pnp:Term ID="E2BF9B94-37F7-4D6B-8EFC-36747F83FF65" Name="testterm" IsReused="true" IsSourceTerm="false" SourceTermId="E2BF9B94-37F7-4D6B-8EFC-36747F83FF65"/>
              </pnp:Terms>
            </pnp:Term>
          </pnp:Terms>
        </pnp:TermSet>
      </pnp:TermSets>
    </pnp:TermGroup>
  </pnp:TermGroups> 
</pnp:ProvisioningTemplate>`

Thanks

Dong

**Comment by jansenbe** [comment]
**Internal testing feedback**
Downloaded user provided template.
Provisioned global term group with reusable terms successfully.

This issue has been fixed, closing per test results.
