### ISSUE TITLE
Handle checked-out files when applying a Provisioning Template

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#796]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
  #### Category

[ ] Bug
[X] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[X ] SharePoint 2016
[X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

Applying a provisioning template overwriting checked out files causes an exception to be thrown. It would be nice to be able to handle this somehow and prevent ApplyProvisioningTemplate to break and skip applying other parts of the template.
#### Observed Behavior

Applying a provisioning template overwriting checked out files causes an exception to be thrown.
#### Steps to Reproduce

Apply a ProvisioningTemplate with Files targeting libraries requiring checking out files. Make sure one of the files is checked out (by a different user).

**Comment by jansenbe** [comment]
**internal testing feedback**

Followed the steps as mentioned by the user.
Got “Cannot access closed stream” error when provisioned.

Flagging as a bug

**Comment by PaoloPia** [comment]
The fix proposed by @luismanez has been merged. Thus, this issue can be closed.
