### ISSUE TITLE
RemoveExistingContentTypes doesnt work

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#798]
Hi
I have following scenario:
I try to Provisioning Template with 1 List instance and 3 Content types. After provisioning I expect all content types bindings are removed from list and replaced with this from template (RemoveExistingContentTypes="true"). My List definition:

<pnp:ListInstance Title="TestList" TemplateType="100" Url="Lists/TestList" ContentTypesEnabled="true" EnableFolderCreation="false" RemoveExistingContentTypes="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" >
          pnp:ContentTypeBindings
            <pnp:ContentTypeBinding ContentTypeID="0x01007fffcd24f4584b2bbdd2b4ea504abda4" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x01000db1094388984a16a819dc5415c8ca1e" />  
                  <pnp:ContentTypeBinding ContentTypeID="0x01003191dc832a9b4bd2a44ea921debba62e" />
          /pnp:ContentTypeBindings  
        /pnp:ListInstance

Which PnP repository to report the issue?
• PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core Master Branch 

Category
[ x] Bug
[ ] Enhancement

Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

Expected or Desired Behavior
It is possible to remove all unused content types from list.

Observed Behavior
All content type bindings remains in list after provisioning.

Steps to Reproduce
Provision template with ListInstance containing parameter RemoveExistingContentTypes="true".

**Comment by jansenbe** [comment]
Hi @konraplo ,

Did you check the provisioning logs? In our testing we saw this:

Got below warning when I try to remove unused content types from the list.
**WARNING: You specified to remove existing content types for the list  with url
'/sites/PnP_798_Source/Lists/EmployeeList'. We found a list with the same url in the site. In case of a list update we
cannot remove existing content types as they can be in use by existing list items and/or documents.**
