### ISSUE TITLE
Security changes on basetemplate list sitepages not extracted

### ISSUE THREAD

**Issue by StaffanNelemans** [SharePoint/PnP-Sites-Core#801]
#### Category

[x ] Bug
[ ] Enhancement
#### Environment

[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

If security is changed on for example sitepages list, which is a list inside the STS#0 basetemplate the list is should be included in the extracted template. 
#### Observed Behavior

If security is changed on for example sitepages list, which is a list inside the STS#0 basetemplate the list is not included in the extracted template. 
Due to the following check in code:
OfficeDevPnP.Core.Framework.Provisioning.Model.ListInstance
349:  (this.Security != null ? this.Security.Equals(other.Security) : true) 

If the basetemplate doesn't have any security definition in the listinstance tag in the basetemplate, then the code always returns that the security definition is equal to the basetemplate, which is not the case.  
#### Steps to Reproduce

Make security changes inside STS#0 sitepages list and make a sitetemplate extraction.

**Comment by jansenbe** [comment]
Hi @StaffanNelemans ,

Thanks for reporting this. I've flagged this as an enhancement so that it stays on our radar.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
