### ISSUE TITLE
Provisioning groups targeting subwebs with broken inheritance, not able to link groups to the subwebs

### ISSUE THREAD

**Issue by gunnarlied** [SharePoint/PnP-Sites-Core#806]
My scenario:
I'm adding subwebs with broken inheritance not inheriting any groups from the parent. I'm also creating a set of SP groups for each subweb (like SubWeb Members / SubWeb Visitors). This works with the latest OfficeDev PnP provisioning engine and template using pnp:SiteGroups, the groups are added to the site collection. But then it stops, there are no declarative way to assign these groups with any role to the subweb. Something to consider supporting?

In line 172 and below in /PnP-Sites-Core / Core / OfficeDevPnP.Core / Framework / Provisioning / ObjectHandlers / ObjectSiteSecurity.cs you don't support adding roleassignment to actually attach the groups to the affected subweb, leaving this part of the provisioning engine unusable without programmatical intervention. 
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
  [x] Bug / Enhancement
  [x] SharePoint 2013 (only tested on)
  If SharePoint on-premises, what's exact CU version: 
- Latest
#### Expected or Desired Behavior

When using a ProvisioningTemplate manipulating on subwebs with broken inheritance and adding SiteGroups, I need to add a roleassignment to the subweb in order to use the SiteGroup in the subweb context.
#### Observed Behavior

SiteGroups are created, but the RoleAssignment part of a ProvisioningTemplate is ignored so no declarative way to assign a group to a subweb.
#### Steps to Reproduce

Create a subweb with broken inheritance (unique permissions) without inheriting any top level groups. Apply a ProvisioningTemplate with a pnp:SiteGroups section i.e. adding a "Subweb Members" group. Add a pnp:Permissions + pnp:RoleAssignments section trying to assign a roledefinition to the Principal in this subweb applying context.

**Comment by jansenbe** [comment]
We recently added support for this scenario. @gunnarlied can you please test and verify it works with the current dev build or the upcoming Feb 2017 release?

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
