### ISSUE TITLE
Value does not fall within the expected range

### ISSUE THREAD

**Issue by imranraja** [SharePoint/PnP-Sites-Core#808]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
  _You can delete this section after you have confirmed target repository for your submission._
#### Category

[ x] Bug
[ ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

Additonal lookupfield gives "Value does not fall within the expected range" because listid attribute is removed from field schema

**Comment by jansenbe** [comment]
@imranraja , can you please share the provisioning template you've used for this? Does it still repro with the latest release?

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
