### ISSUE TITLE
No Support for Site Collections in Provisioning Templates

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/PnP-Sites-Core#811]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. **(BTW This needs changing !)** Thanks!
#### Which PnP repository to report the issue?

---
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[X ] Bug
[X ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[X ] SharePoint 2016
[ X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: September 2016
#### Expected or Desired Behavior

Support for Site Collections in the provisioning Template
#### Observed Behavior

I cannot find an element in the provisioningTemplate which deals with SiteCollections just like there is one for Content Types etc.
#### Steps to Reproduce

I cannot find this.CurrentProvisioningTemplate.SiteCollections (or SiteCollection)

I appreciate handling multiple Site Collections might be a challenge, but just a single one ?

**Comment by NPrice99** [comment]
If I knew enough about the way OfficeDevPnP works I would do this myself.  I know provisioingTemplate .cs needs changing.  I suspect objecthandlers needs a new object (SiteCollection) after that I am struggling.  Will the formatter or the XMLPnPHandler need updating ?

**Comment by erwinvanhunen** [comment]
what do you expect to do in the 'SiteCollections' handler? Create sitecollections? As we made an architectural decision to not provision site collections through the engine. For that we have other solutions, like the Partner Pack, CSOM methods or PnP PowerShell.

E.g. the architecture around the provisioning engine is that it always requires a sitecollection to be present, either created manually or through some other means.

Regarding any introduction of a new object handler:

step 1 is to propose a schema change in our schema repo: https://github.com/officedev/pnp-provisioning-schema
After that proposal has been approved _and_ merged work can start on the object handler. But before that:

 A schema change requires changes to the serialization and deserialization code (located in https://github.com/OfficeDev/PnP-Sites-Core/tree/master/Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml). 
Corresponding model classes need to be created in https://github.com/OfficeDev/PnP-Sites-Core/tree/master/Core/OfficeDevPnP.Core/Framework/Provisioning/Model.
After this is all in place, work can start on the actual objecthandler.

But the main question I have is: what do you envision to do with site collections that is missing right now?

**Comment by NPrice99** [comment]
Hi Erwin

I just need to create one site collection on an on-premises farm (So I think that rules out the Partner Pack unfortunately).

So we are left with CSOM or PnP PowerShell.   Either would do.  I just need to find somewhere to put the sitecollection information as per your PnP NewTenantSite.cs  command.  Hence I was wondering about a SiteCollection Collection in the ProvisioningTemplate.

Regards

Nigel

The provisioning schema already has provision for Site Collections :- https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md#sitecollection
<pnp:provisioning>
  <pnp:pequence>
    <pnp:siteCollection>
    ...
    </pnp:siteCollection>
  </pnp:sequence>
</pnp:provisioning>

**Comment by jansenbe** [comment]
Flagging this one as enhancement request, but given there's an easy workaround it's a low priority enhancement

**Comment by NPrice99** [comment]
whats the workaround ?

**Comment by jansenbe** [comment]
You create the site collections using custom code or custom PS scripting and then you use the engine to apply the template to the created site collections

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
