### ISSUE TITLE
Provisioning Page Layouts - web parts disappearing

### ISSUE THREAD

**Issue by suz7777** [SharePoint/PnP-Sites-Core#813]
3M Folder location for files dealing with this issue.
-   Vesa has access to the location.
-   (2) html page layout files – do not properly upload the web parts 
-   Zip file with provisioning scripts – 
  o   XML script to use:  Powershell - Scripts.zip\Powershell - Scripts\DWPCorp\Resources\DWPArtifacts_Global.xml
#### Which PnP repository to report the issue?
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[ ] Bug
[x ] Enhancement
#### Environment

[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013
#### Expected or Desired Behavior

When using provisioning to apply page layouts 2 specific page layouts do not appear to keep the web parts on the layout.  See html page layouts in the PageLayoutIssue Folder.
#### Observed Behavior

Web Parts are removed from the web part page when provisioning a new layout.  This does not happen in all page layouts.
#### Steps to Reproduce

• Create an HTML page layout – use our example provided
• Apply the template using our example template – Apply-SPOProvisioningTemplate -Path  DWPCorpInteriorLayout2.0-Accordion.html -ResourceFolder $ “.\Powershell - Scripts\DWPCorp\Resources”

**Comment by suz7777** [comment]
i have downloaded the latest code - this is the information i see when exporting a Field.
        <Field Type="Calculated" DisplayName="Review Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="DateTime" ReadOnly="TRUE" Group="DWPCorp Site Columns" ID="{30e2d19b-52b4-4d17-bc2c-9cff1aa8fa2c}" SourceID="{49b1ff83-fcbf-447d-97e9-0d3e6f3a9a03}" StaticName="DWPCorpReviewDate" Name="DWPCorpReviewDate" Required="FALSE">
          <Formula>=DATE(YEAR([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+1,MONTH([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+6,DAY([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}]))</Formula>
        </Field>

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
