### ISSUE TITLE
Get-SPOProvisioningTemplate  -IncludeAllTermGroups fails with unclear error message

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#816]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[X] Bug
[X] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

I found this in SharePoint 2013 on-premises, however I would expect the same to happen in other version of SharePoint.
#### Observed Behavior

When I'm not an administrator for the MMS then I'm getting the following error when I try to export my termstore.

Get-SPOProvisioningTemplate : Object reference not set to an instance of an object on server. The object is associated with property SourceTerm.
At line:1 char:1
- Get-SPOProvisioningTemplate -Out c:\Temp\Terms.xml -IncludeAllTermGroups -Han ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], ServerObjectNullReferenceException
  - FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate
#### Expected or Desired Behavior

When I'm not an administrator for the MMS then I might expect to get an error when I try to export all Term groups.  A clear error message would be helpful. But potentially the export should simply ignore the termgroups/termstore that I haven't got sufficient permissions for.
#### Steps to Reproduce

Remove administrator permissions on MMS for logged in user. 

Run the following in PowerShell:
Get-SPOProvisioningTemplate -Out c:\Temp\Terms.xml -IncludeAllTermGroups

**Comment by jansenbe** [comment]
We saw this error when the "This service application is the default storage location for column specific term sets" property was not set on the mms service application. As of the February release we're returning a warning in that case and skip processing the handler instead of throwing an error. Will close this issue, but please re-open when you can still reproduce using latest (March) version.
