### ISSUE TITLE
<Pnp:Navigation> Not creating items in Quick Launch.

### ISSUE THREAD

**Issue by BigBrahma** [SharePoint/PnP-Sites-Core#820]
PnP Engine displays sucessfully executed but it didn't create Items in Quick Launch.

![image](https://cloud.githubusercontent.com/assets/18693266/19642465/084d6024-9a03-11e6-80bf-59ac09352987.png)
#### Which PnP repository to report the issue?
- PnP Samples - https://github.com/OfficeDev/PnP
#### Category

[ ] Bug
#### Environment

[ ] Office 365 / SharePoint Online
#### Expected or Desired Behavior

Navigation Elements should be created
#### Observed Behavior

PnP Engine displays sucessfully executed but it didn't create Items in Quick Launch.

**Comment by konraplo** [comment]
Hi

Do you have publishing feature activated on your provisioning target site?

**Comment by jansenbe** [comment]
The Feb release of PnP will support navigation settings for non-publishing sites and as such your scenario will be possible. Will close this issue now, but don't hesitate to re-open if you can't realize your scenario using the Feb 2017 or later release.

**Comment by corriespondent** [comment]
Did the Feb release include navigation settings for non-publishing sites @jansenbe?
