### ISSUE TITLE
An error occurred while parsing EntityName

### ISSUE THREAD

**Issue by ngderb** [SharePoint/PnP-Sites-Core#827]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category

[x ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
15.0.4833.1000
#### Expected or Desired Behavior

Expected template to be created from running `Get-SPOProvisioningTemplate -Out template.xml`
#### Observed Behavior

After processing some of the lists in the site, I receive the error:

```
Get-SPOProvisioningTemplate : An error occurred while parsing EntityName. Line 1, position 316.
At line:1 char:1
+ Get-SPOProvisioningTemplate -Out template.xml -Handlers Lists
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], XmlException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.GetProvisioningTemplate

```
#### Steps to Reproduce

Ran the following using the October 2016 Intermediate Release of PNP/PowerShell:
`Connect-SPOnline https://mysite -CurrentCredentials
Get-SPOProvisioningTemplate -Out template.xml`

Is there any way to troubleshoot this error, not sure what is causing it?

**Comment by JBoman32768** [comment]
Happening to me also. Please post if you find a workaround.

**Comment by JBoman32768** [comment]
Okey - looks like this happens if any list or library title contains an ampersand.  Just bad XML handling.

Workaround: Rename the source list title to remove the ampersand.

**Comment by erwinvanhunen** [comment]
Hi! Thank you for reporting this issue, and apologies for the long delay in reacting. I just tested this with the latest DEV build and no issues occur with lists or libraries which have a title in the name when extracting a template. List titles are, as should be, escaped using ```&amp;```.

I will close this issue, but do not hesitate to reopen it in case you feel the issue still stands.
