### ISSUE TITLE
Problem by update List title

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#843]
Hi

Since Localizations are supported only for SharePoint Online or SharePoint2016,
 I used to put in my PnP Template in List something like that:
Title =“$Resources:MyResx,MyTextList”. MyResx are already deployed on SP Farm.
After the first provisioning is everything ok. But after update I see in my List title my key "$Resources:MyResx,MyTextList" not localized value.
It seem that by the List update process, the list title value for current language is replaced by key.

•PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

Category

[x ] Bug
 [ ] Enhancement

Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ x] SharePoint 2013

Expected or Desired Behavior

It should be possible to provision Lists more then one time with resource keys as title.

Steps to Reproduce

Create and provision a template with List Title="$Resources:MyResx,MyTextList". Then provision this template second time.

KR
Konrad

**Comment by jansenbe** [comment]
Hi @konraplo ,

SharePoint 2013 does not support setting translations, it's only allowed for SharePoint Online and SharePoint 2013. Are you able to repro this issue on SharePoint Online or SharePoint 2016? If so did you validate that in both runs the resource files were present. Both the list creation and list update support titleresource setting, so code looks good.

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
