### ISSUE TITLE
Errors using Apply-PnPProvisioningTemplate on exported publishing webs

### ISSUE THREAD

**Issue by kattenhoj** [SharePoint/PnP-Sites-Core#844]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[ ] SharePoint 2013 (not tested)

If SharePoint on-premises, what's exact CU version:
16.0.4327.1000

#### Expected or Desired Behavior
Using Apply-PnPProvisioningTemplate to apply an exported site template (exported using Get-PnPProvisioningTemplate) results in a lot of errors, when used on publishing webs. This is the same for SharePoint Online as SharePoint 2016 (we have not tested with SharePoint 2013). When eliminating the first error, the following errors vary from SharePoint Online to SharePoint 2016.

We expect the site to be exported and applied without any errors.

#### Observed Behavior
Here's a detailed example of the observed behaviour we are experiencing on a SharePoint 2016 on premise.
The following error is caused by missing page files (eg. default.aspx):
...irrelevant tracelog omitted...
PowerShell.exe Information: 0 : 2016-11-11 10:28:36.6722        [Files] [6]     [Debug] Code execution scope started    0ms     00d9ad49-0fa8-4bb2-af9d-92c92c739007
PowerShell.exe Information: 0 : 2016-11-11 10:28:36.7816        [Files] [6]     [Debug] Uploading and overwriting existing file default.aspx    111ms   00d9ad49-0fa8-4bb2-af9d-92c92c739007
PowerShell.exe Error: 0 : 2016-11-11 10:28:36.8760      [OfficeDevPnP.Core]     [0]     [Error] File default.aspx not found in directory . Exception = Could not find file 'E:\PnP\default.aspx'.       0ms
PowerShell.exe Error: 0 : 2016-11-11 10:28:36.8760      [OfficeDevPnP.Core]     [0]     [Error] File default.aspx not found in directory . Exception = Could not find file 'E:\PnP\default.aspx'.       0ms
PowerShell.exe Information: 0 : 2016-11-11 10:28:36.8760        [Files] [6]     [Debug] Code execution scope ended      208ms   00d9ad49-0fa8-4bb2-af9d-92c92c739007
PowerShell.exe Information: 0 : 2016-11-11 10:28:36.8760        [Provisioning]  [6]     [Debug] Code execution scope ended      39002ms 00d9ad49-0fa8-4bb2-af9d-92c92c739007
Apply-PnPProvisioningTemplate : Value cannot be null.
Parameter name: stream
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path $templateFilename;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Creating a file "default.aspx" in the directory of the exported site template with the following content, gets us past that issue (but this is not a solid workaround with an arbitrary number of pages):
<%@ Page Inherits="Microsoft.SharePoint.Publishing.TemplateRedirectionPage,Microsoft.SharePoint.Publishing,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c" %> <%@ Reference VirtualPath="~TemplatePageUrl" %> <%@ Reference VirtualPath="~masterurl/custom.master" %>

Running the line "Apply-PnPProvisioningTemplate -Path $templateFilename;" again now results in:
...irrelevant tracelog omitted...
PowerShell.exe Information: 0 : 2016-11-11 10:38:12.4504        [Files] [6]     [Debug] Code execution scope started    0ms     73e120c3-a7f1-4bef-9df7-3e5a9d759d21
PowerShell.exe Information: 0 : 2016-11-11 10:38:12.5754        [Files] [6]     [Debug] Uploading and overwriting existing file default.aspx    115ms   73e120c3-a7f1-4bef-9df7-3e5a9d759d21
PowerShell.exe Information: 0 : 2016-11-11 10:38:12.6379        [OfficeDevPnP.Core]     [0]     [Information]   File default.aspx retrieved from folder         0ms
PowerShell.exe Information: 0 : 2016-11-11 10:38:12.6379        [OfficeDevPnP.Core]     [0]     [Debug] Creating file info with Url 'default.aspx'      0ms
PowerShell.exe Information: 0 : 2016-11-11 10:38:13.6535        [OfficeDevPnP.Core]     [0]     [Debug] Checking in file 'default.aspx' 0ms
PowerShell.exe Information: 0 : 2016-11-11 10:38:14.0285        [OfficeDevPnP.Core]     [0]     [Information]   Creating folder 'mysite' under Web '/mysite/Destination/'.      0ms
PowerShell.exe Information: 0 : 2016-11-11 10:38:14.1379        [OfficeDevPnP.Core]     [0]     [Information]   Creating folder 'mysite/_catalogs' under Web '/mysite/Destination/'.    0ms
PowerShell.exe Information: 0 : 2016-11-11 10:38:14.2316        [OfficeDevPnP.Core]     [0]     [Information]   Creating folder 'mysite/_catalogs/masterpage' under Web '/mysite/Destination/'. 0ms
PowerShell.exe Error: 0 : 2016-11-11 10:38:14.3254      [OfficeDevPnP.Core]     [0]     [Error] File oslo.master not found in directory . Exception = Could not find file 'E:\PnP\oslo.master'. 0ms
PowerShell.exe Error: 0 : 2016-11-11 10:38:14.3254      [OfficeDevPnP.Core]     [0]     [Error] File oslo.master not found in directory . Exception = Could not find file 'E:\PnP\oslo.master'. 0ms
PowerShell.exe Information: 0 : 2016-11-11 10:38:14.3254        [Files] [6]     [Debug] Uploading file oslo.master      1876ms  73e120c3-a7f1-4bef-9df7-3e5a9d759d21
PowerShell.exe Information: 0 : 2016-11-11 10:38:14.3410        [Files] [6]     [Debug] Code execution scope ended      1877ms  73e120c3-a7f1-4bef-9df7-3e5a9d759d21
PowerShell.exe Information: 0 : 2016-11-11 10:38:14.3410        [Provisioning]  [6]     [Debug] Code execution scope ended      40558ms 73e120c3-a7f1-4bef-9df7-3e5a9d759d21
Apply-PnPProvisioningTemplate : Value cannot be null.
Parameter name: stream
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path $templateFilename;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Removing the entire <pnp:Files> section from the exported site template and running the line "Apply-PnPProvisioningTemplate -Path $templateFilename;" again results in:
PowerShell.exe Information: 0 : 2016-11-11 10:44:23.5245        [Composed Looks]        [6]     [Debug] Code execution scope started    0ms     425b7e67-36a5-4567-a7f5-d65251cf82d3
PowerShell.exe Information: 0 : 2016-11-11 10:44:23.5402        [Composed Looks]        [6]     [Debug] Code execution scope ended  10ms        425b7e67-36a5-4567-a7f5-d65251cf82d3
PowerShell.exe Information: 0 : 2016-11-11 10:44:23.5402        [Provisioning]  [6]     [Debug] Code execution scope ended      38958ms 425b7e67-36a5-4567-a7f5-d65251cf82d3
Apply-PnPProvisioningTemplate : Value cannot be null.
Parameter name: masterPageServerRelativeUrl
At line:1 char:1
+ Apply-PnPProvisioningTemplate -Path $templateFilename;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

and so on and so forth...

#### Steps to Reproduce
E.g. on SharePoint 2016, using PowerShell (same exact behaviour using SharePoint Online):
# Authentication.
$username = "contoso\administrator";
$password = "Pa$$word";
$credential = New-Object System.Management.Automation.PSCredential($userName, (ConvertTo-SecureString $Password -AsPlainText -Force));

# First create 2 publishing webs to illustrate the bug.
$siteCollectionUrl = "https://contoso.sharepoint.com/mysite";
$sourceWebUrl = "{0}/Source" -f $siteCollectionUrl;
$destinationWebUrl = "{0}/Destination" -f $siteCollectionUrl;
$webTemplate = "CMSPUBLISHING#0";
Connect-PnPOnline -Url $siteCollectionUrl -Credential $credential;
$sourceWeb = New-PnPWeb -Title "Source Web" -Url ($sourceWebUrl -replace '^.*/', '') -Template $webTemplate -Locale 1033;
$destinationWeb = New-PnPWeb -Title "Destination Web" -Url ($destinationWebUrl -replace '^.*/', '') -Template $webTemplate -Locale 1033;
Disconnect-PnPOnline;

# Second export the source web and try to apply it to the destination web.
Set-PnPTraceLog -On -Level Debug; # Enable logging for details about the error.
$templateFilename = "PnPPublishingSiteTemplate.xml";
Connect-PnPOnline -Url $sourceWebUrl -Credential $credential;
Get-PnPProvisioningTemplate -Out $templateFilename -Force;
Disconnect-PnPOnline;
Connect-PnPOnline -Url $destinationWebUrl -Credential $credential;
Apply-PnPProvisioningTemplate -Path $templateFilename;
Disconnect-PnPOnline;

**Comment by jansenbe** [comment]
Thanks @kattenhoj for logging this issue. We'll need to further investigate this.

**Comment by jansenbe** [comment]
Hi @kattenhoj ,

Can you try to use the following syntax when downloading the template:

Get-PnPProvisioningTemplate -Out $templateFilename -Handlers All -PersistBrandingFiles -PersistPublishingFiles –IncludeNativePublishingFiles

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
