### ISSUE TITLE
Error "The formula cannot refer to another column" when applying list template containing fields with validation 

### ISSUE THREAD

**Issue by elenanakhmanson** [SharePoint/PnP-Sites-Core#849]
#### Category
[ x] Bug
[ ] Enhancement

Note: it's not a bug because of a provisioning engine but because of how SharePoing handles validation formulas.

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
The validation formula of fields need to have display names of a field and not an internal name.

#### Observed Behavior
We get error "The formula cannot refer to another column.  Check the formula for spelling mistakes or update the formula to reference only this column." when we apply a template generated by the provisioning engine. The field is a normal text field that belongs to a list (not a Site Column) and that has a validation formula. The field was created in UI and functioning fine. We found that when we get a SchemaXml of a field, the validation formula contains InternalName of a field, but when a field is created using AddFieldAsXml method, validation formula is expected to have DisplayName of a field in square brackets. So it's not really a problem with proivisioning engine, but nevertheless, it crashes when applying a template.

#### Steps to Reproduce
Create a text field in a list and add validation formula that refers to the same field. 
Generate a provisioning template from the site with the list
Apply generated provisioning template to another site.

Sample field xml from the provisioning template which is <Field> in a <ListInstance>:
            <Field Type="Text" DisplayName="Primary Office 365 Email" Required="TRUE" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255" ID="{ff987f2c-5abb-4e0b-9070-db3caf6301ff}" SourceID="{{listid:Onboarding Requests}}" StaticName="Email" Name="Email" ColName="nvarchar5" RowOrdinal="0" Version="4" Description="Requested email address">
              <Validation Message="Please enter a valid email address">=(LEN(LEFT(Email,FIND("@",Email)-1))&gt;0)+(LEN(RIGHT(Email,LEN(Email)-FIND(".",Email,FIND("@",Email))))&gt;0)+(LEN(MID(Email,FIND("@",Email)+1,FIND(".",Email,FIND("@",Email))-FIND("@",Email)-1))&gt;0)+(ISERROR(FIND(" ",Email))=TRUE)=4</Validation>
            </Field>

**Comment by jansenbe** [comment]
Closing this issue now that #976 has been merged
