### ISSUE TITLE
Error when exporting template with modern pages

### ISSUE THREAD

**Issue by mburns77** [SharePoint/PnP-Sites-Core#854]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Generate xml template file for modern team sites

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
Execute Get-PnPProvisioningTemplate  against a group site or team site with modern pages and it errors out on page extract
It worked ok if I use -Hadlers Lists, Security

#### Steps to Reproduce
Get-PnPProvisioningTemplate errors out on Page extract when modern team sites are used with modern pages.
![bilde](https://cloud.githubusercontent.com/assets/17719380/20590980/7bf06d88-b226-11e6-8966-6088da69f610.png)

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Thanks for reporting this. We do support "noscript" sites (which is also set for modern sites), but we're not yet testing with actual modern sites...will test this.

**Comment by jansenbe** [comment]
Hi @mburns77, we couldn't reproduce this. Do you still have this issue with the latest (March) release? Is this an OOB group site?

Internal testing comments:

Created modern page and set as welcome page
Downloaded modern page successfully by using Get-PnPProvisioningTemplate command

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
