### ISSUE TITLE
Get-PnPProvisioningTemplate doesn't export the default.aspx

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#864]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Get-PnPProvisioningTemplate should include the default.aspx

#### Observed Behavior
Get-PnPProvisioningTemplate doesn't export the default.aspx when page content is exported resulting in 
Apply-PnPProvisioningTemplate giving an error

PowerShell_ISE.exe Information: 0 : 2016-11-29 15:38:34.1724	[Files]	[12]	[Debug]	Code execution scope started	0ms	5af80226-8d92-45e9-8998-6df48048ffe6
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:38:34.4069	[Files]	[12]	[Debug]	Uploading and overwriting existing file default.aspx	234ms	5af80226-8d92-45e9-8998-6df48048ffe6
PowerShell_ISE.exe Error: 0 : 2016-11-29 15:38:34.7018	[OfficeDevPnP.Core]	[0]	[Error]	File default.aspx not found in directory . Exception = Unable to find the specified file.	0ms	
PowerShell_ISE.exe Error: 0 : 2016-11-29 15:38:34.7043	[OfficeDevPnP.Core]	[0]	[Error]	File default.aspx not found in directory . Exception = Unable to find the specified file.	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:38:34.7066	[Files]	[12]	[Debug]	Code execution scope ended	534ms	5af80226-8d92-45e9-8998-6df48048ffe6
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:38:34.7077	[Provisioning]	[12]	[Debug]	Code execution scope ended	52304ms	5af80226-8d92-45e9-8998-6df48048ffe6
Apply-PnPProvisioningTemplate : Value cannot be null.
Parameter name: stream
At C:\PVSource\updateAll.ps1:37 char:1
+ Apply-PnPProvisioningTemplate -Path C:\PVSource\te ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

#### Steps to Reproduce
run Get- and Apply-PnPProvisioningTemplate on and to a publishing site.

#### Workaround
Export the site as .xml rather than .pnp  and download an default.aspx file from a SharePoint site and locate this in the same folder as the xml when applying the template.

**Comment by Pieter-Veenstra** [comment]
A similar issue also happens with master pages.

PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:37.8565	[Files]	[12]	[Debug]	Code execution scope started	0ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:38.1915	[Files]	[12]	[Debug]	Uploading and overwriting existing file default.aspx	335ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:38.3849	[OfficeDevPnP.Core]	[0]	[Information]	File default.aspx retrieved from folder 	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:38.3890	[OfficeDevPnP.Core]	[0]	[Debug]	Creating file info with Url 'default.aspx'	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:43.0319	[Files]	[12]	[Debug]	Adding webpart 'Documents' to page	5174ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:43.9631	[Files]	[12]	[Debug]	Adding webpart 'Announcements' to page	6106ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:44.9151	[Files]	[12]	[Debug]	Adding webpart 'Content Editor' to page	7058ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:45.3971	[OfficeDevPnP.Core]	[0]	[Debug]	Checking in file 'default.aspx'	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:46.2297	[OfficeDevPnP.Core]	[0]	[Information]	Creating folder 'sites' under Web '/sites/intranet/Dept/finance/'.	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:46.4762	[OfficeDevPnP.Core]	[0]	[Information]	Creating folder 'sites/intranet' under Web '/sites/intranet/Dept/finance/'.	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:46.7544	[OfficeDevPnP.Core]	[0]	[Information]	Creating folder 'sites/intranet/_catalogs' under Web '/sites/intranet/Dept/finance/'.	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:47.1447	[OfficeDevPnP.Core]	[0]	[Information]	Creating folder 'sites/intranet/_catalogs/masterpage' under Web '/sites/intranet/Dept/financ
e/'.	0ms	
PowerShell_ISE.exe Error: 0 : 2016-11-29 15:43:47.4212	[OfficeDevPnP.Core]	[0]	[Error]	File oslo.master not found in directory . Exception = Could not find file 'C:\PVSource\templates\oslo.master'.	0ms	
PowerShell_ISE.exe Error: 0 : 2016-11-29 15:43:47.4232	[OfficeDevPnP.Core]	[0]	[Error]	File oslo.master not found in directory . Exception = Could not find file 'C:\PVSource\templates\oslo.master'.	0ms	
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:47.4269	[Files]	[12]	[Debug]	Uploading file oslo.master	9569ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:47.4288	[Files]	[12]	[Debug]	Code execution scope ended	9571ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
PowerShell_ISE.exe Information: 0 : 2016-11-29 15:43:47.4293	[Provisioning]	[12]	[Debug]	Code execution scope ended	64661ms	276b7c1d-50fc-4728-a9eb-3ce2f5a43147
Apply-PnPProvisioningTemplate : Value cannot be null.
Parameter name: stream
At C:\PVSource\updateAll.ps1:37 char:1
+ Apply-PnPProvisioningTemplate -Path C:\PVSource\te ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ArgumentNullException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by erwinvanhunen** [comment]
We have fix this issue with PR #912  and PR #933 . I will close this issue.
