### ISSUE TITLE
Get-PnPProvisioningTemplate not including search settings

### ISSUE THREAD

**Issue by athrayee** [SharePoint/PnP-Sites-Core#868]
I am using PnPProvisioning powershell to extract template.

Below is my command.

Get-PnPProvisioningTemplate -Out $templateFileName -IncludeSiteCollectionTermGroup -PersistComposedLookFiles -Force -IncludeNativePublishingFiles -IncludeTermGroupsSecurity -PersistBrandingFiles -PersistPublishingFiles -Web $web

The extracted template did not include search settings and workflow. I do not see any obvious switch parameter in powershell. In C# code I am able to specify this 

rovisioningTemplateCreationInformation ptci
                        = new ProvisioningTemplateCreationInformation(ctx.Web);

                // Create FileSystemConnector, so that we can store composed files temporarely somewhere 
                ptci.FileConnector = new FileSystemConnector(directoryName, "");
                ptci.PersistBrandingFiles = true;
                ptci.IncludeSiteCollectionTermGroup = true;
                ptci.IncludeSearchConfiguration = true;

Please let me know if I am missing something or if there is another way to extract the workflow and search settings using powershell. I cannot use C# because the tenant has multi-factor authentication which is not supported in C#.

**Comment by erwinvanhunen** [comment]
Very good catch. I fixed this in the PnP-PowerShell repo with PR https://github.com/SharePoint/PnP-PowerShell/pull/629. In the next release of the cmdlets there will be a switch called "IncludeSearchConfiguration" available on the Get-PnPProvisioningTemplate cmdlet.
