### ISSUE TITLE
Lists : "RemoveExistingContentTypes" does not work

### ISSUE THREAD

**Issue by PaoloPia** [SharePoint/PnP-Sites-Core#875]
Please refer to this item: https://github.com/SharePoint/PnP-Provisioning-Schema/issues/144

**Comment by erwinvanhunen** [comment]
Hi!

I looked into this specific issue and the situation is as follows:

When you create a -new- list in a site, and the template of which the list is based upon contains Content Type references, then the RemoveExistingContentTypes switch will actually remove the content types.

However, when applying a template to a site where there is already a list present with the same URL as specified in the template we will update the list. However, as there might be list items in the list that use those content types, we cannot remove the content types. E.g. when updating an existing list we only allow adding content types, not removing all of them. I added a warning to the provisioning engine now that will show the moment we encounter such a situation.

I will close this issue again. If you feel the issue still stands, do not hesitate to reopen it.
