### ISSUE TITLE
Provisioning Schema: Exporting Navigation Nodes Handler on root sites

### ISSUE THREAD

**Issue by camiloborges** [SharePoint/PnP-Sites-Core#879]
#### Category [x ] Bug
[#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
<pnp:NavigationNode Title="Quick Links" Url="{site}Lists/QuickLinks/AllItems.aspx" />

#### Observed Behavior
<pnp:NavigationNode Title="Quick Links" Url="{site}Lists**{site}**QuickLinks**{site}**AllItems.aspx" />

#### Steps to Reproduce
Connect-PnPOnline "https://contoso.sharepoint.com" -Credentials $creds
 Get-PnPProvisioningTemplate -Handlers Navigation -Out NewTemplateLong.xml  -Force

This same behavior is found on a number of handlers whenever the root site is turned to an PnP schema. 
I am using the latest dev branch but it seems to be something that has always been a problem. At least 1 of the issues fixed last month( #675 ) was about the same scenario(templating root sites), 

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community.
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by erwinvanhunen** [comment]
Hi Camilo!

Thanks for reporting this. I just fixed this with PR #949 . I will close this issue.
