### ISSUE TITLE
ObjectHandlers ObjectFiles and ObjectPages not supporting updates to/replacing existing webparts

### ISSUE THREAD

**Issue by gunnarlied** [SharePoint/PnP-Sites-Core#882]
When provisioning files (i.e. publishing pages) containing webparts, using pnp:Files with a pnp:Webparts section, the provisioning engine does not support that the template can be re-run updating the existing webparts. Only new webparts are added, existing ones are not handled at all.

It would be a good lifecycle approach to be able to re-run the provisioning template and updating / replacing the existing webparts, the webpart definition might be changed during the page lifetime.

#### Category
[ ] Bug
[X] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013 (only tested on SP2013)

If SharePoint on-premises, what's exact CU version: Latest

#### Expected or Desired Behavior
Enhancement:
- Support overwriting existing webparts on a page created through the ObjectFiles handler.
- The code now simply skips handling any existing webparts: 
>"// check if the webpart is already set on the page"
>"if (existingWebParts.FirstOrDefault(w => w.WebPart.Title == parser.ParseString(webPart.Title)) == null)"
- One solution is to add an Overwrite attribute on the pnp:Webpart to control the behavior when existing webpart is found allowing a replace, deleting and adding the webpart again,
Expected benefit: Improved lifecycle management keeping all webparts in sync with the templated setup.

#### Observed Behavior
Currently any existing templated webparts are ignored, although your use-case are to keep any page webparts in sync with your templated setup.
Same behavior both on ObjectFiles and ObjectPages simply ignoring updating existing webparts without any properties to support overwrite/update scenarios.

#### Steps to Reproduce
For instance in a Search center you want to customize your own results.aspx page. This can be done by creating a page using pnp:File, placing webparts with adjusted properties on it. In order to maintain such a page adjusting webpart settings/properties when needed, it should be possible to re-run the template against the site/page adjusting the configuration. Currently, existing webparts are ignored.

**Comment by mrpullen** [comment]
How about checking the web part titles, and removing and replacing if they match? 

Would be another way to-do this without modifying the schema. 

I don't know if "overwrite" is a good attribute for each web part, cause then I have to set it, and I might forget. Let's just assume that if we delete the existing web part and replace it from what is in the template we should be in the correct state, right?

```
var existingWP = existingWebParts.FirstOrDefault(w=> w.WebPart.Title == parser.ParseString(webPart.Title))
if(existingWP != null) {
   //remove the existing web part
}
//go forward with adding the web part.

```

**Comment by gunnarlied** [comment]
In my point of view a switch of logic to always include removal of existing and readd is risky business, since a templated webpart can be altered by users, and rerunning the template will overwrite those changes. So in my point of view it is safer to have a default behavior as the current codebase.

But when we manage the templates actively, and want to re-run them, we know which webparts that should always be replaced, and which should be left untouched. So adding some sort of switch / flag property to actively be able to replace, would be an enhancement to the functionality without tampering with existing logic.
