### ISSUE TITLE
Recent, lists and libraries in navigation

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#890]
#### Which PnP repository should you use to report the issue? 
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I'm using "Structural Navigation: Display only the navigation items below the current site " as my navigation option for my site. I've exported my site to an xml. then I'm applying the template multiple times to a site and I I would like to see a single Recent option in my navigation.

#### Observed Behavior
In my template I found:

 < pnp:Navigation>
        < pnp:GlobalNavigation />
        < pnp:CurrentNavigation NavigationType="StructuralLocal">
          < pnp:StructuralNavigation RemoveExistingNodes="false">
            **< pnp:NavigationNode Title="Recent" Url="" IsExternal="true" />**
            < pnp:NavigationNode Title="Announcements" Url="{site}/Lists/Announcements/AllItems.aspx" />
            < pnp:NavigationNode Title="Documents" Url="{site}/Documents/Forms/AllItems.aspx" />
          < /pnp:StructuralNavigation>
        < /pnp:CurrentNavigation>
      < /pnp:Navigation>

The recent link should not be included or at least be ignored when adding a template.

Additionally my Announcements and Documents list/library should not be specifically included in the navigation section of the template. The reason for these lists to be included in the quick launch should be controlled within the list settings within the list instances of the template not within the navigation section template. For these lists I'm also ending up with double entries.

Maybe excluding the lists within the local site would be a good solution, so that links to other locations are still exported and therefor included in the quick launch.

#### Steps to Reproduce
See above.

**Comment by Pieter-Veenstra** [comment]
The problem is with the following code in Object Navigation.cs. The code should check the existing navaigation nodes and update the nodes that already exist.

` private void ProvisionStructuralNavigationNodes(Web web, TokenParser parser, Enums.NavigationType navigationType, Model.NavigationNodeCollection nodes, string parentNodeTitle = null)
        {
            foreach (var node in nodes)
            {
                web.AddNavigationNode(
                    parser.ParseString(node.Title),
                    new Uri(parser.ParseString(node.Url), UriKind.RelativeOrAbsolute),
                    parser.ParseString(parentNodeTitle),
                    navigationType,
                    node.IsExternal);

                ProvisionStructuralNavigationNodes(
                    web, 
                    parser,
                    navigationType, 
                    node.NavigationNodes, 
                    parser.ParseString(node.Title));
            }
        }
`

So we should add something like:
web.Context.Load(web, w => w.ServerRelativeUrl);
web.Context.Load(sourceNodes);
web.Context.ExecuteQueryRetry();

Then we need to check in web.Navigation.QuickLaunch if the node already exists

**Comment by erwinvanhunen** [comment]
Hi Pieter!

We decided not to change the default behavior of the engine as it is right now. E.g. we do not delete artifacts unless explicitly requested. 

Delta handling is pretty complex too as navigation nodes have no unique identifier that we can use to see if there is a delta occurring. 

We decided to introduce a ClearNavigation property on the ProvisioningTemplateApplyingInformation class (and a corresponding -ClearNavigation switch on the Apply-PnPProvisioningTemplate cmdlet) that will forcibly clear out the navigation nodes in the site before we provision the ones from the template. Notice that setting this value to true will override any value in the template: on the navigation element there is a property RemoveExistingNodes which defaults to 'false'. If you set that to true in the template the navigational nodes will be removed too before the new nodes are created.

**Comment by ImSumi** [comment]
Hi 
I'm facing similar issue but for my case the sequence is getting different.
viz. **Documents** is coming before **Announcements**
Please help.

< pnp:Navigation>
< pnp:GlobalNavigation />
< pnp:CurrentNavigation NavigationType="StructuralLocal">
< pnp:StructuralNavigation RemoveExistingNodes="false">
< pnp:NavigationNode Title="Recent" Url="" IsExternal="true" />
**< pnp:NavigationNode Title="Announcements" Url="{site}/Lists/Announcements/AllItems.aspx" />**
**< pnp:NavigationNode Title="Documents" Url="{site}/Documents/Forms/AllItems.aspx" />**
< /pnp:StructuralNavigation>
< /pnp:CurrentNavigation>
< /pnp:Navigation>
