### ISSUE TITLE
Inconsistency between objectfiles and objectlistinstancedatarows handlers

### ISSUE THREAD

**Issue by johannesekstrand** [SharePoint/PnP-Sites-Core#891]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4849.1000

#### Expected or Desired Behavior
There is a slight inconsistency between the two handlers ObjectFiles.cs and ObjectListInstanceDataRows.cs used by the Provisioning Engine. When adding a <pnp:file> you could breakroleinheritance using the <pnp:security> node without specifying any additional RoleAssignments. But when doing the same for a <pnp:DataRow> nothing will happen. This is due to a slightly different if-statement used in ObjectFiles.cs on row 160-161 compared to the if statement in ObjectListInstanceDataRows.cs on row 185.

**Comment by erwinvanhunen** [comment]
Hi! Thanks for reporting this. I just merged PR #948 which fixes this. I will close this issue.
