### ISSUE TITLE
Uploading a hierarchy of folders using PnP provisioning schema gives an error

### ISSUE THREAD

**Issue by Atul-Moghe** [SharePoint/PnP-Sites-Core#898]
#### Which PnP repository should you use to report the issue? 

- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016

[X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: SharePoint 2013 - 15.0.4711.1000

#### Expected or Desired Behavior
When you have a folder hierarchy that needs to be deployed to a library(on destination site) through Apply Template using PnP Provisioning Schema, the entire folder hierarchy with files inside the folder should be uploaded properly to the destination site. 

#### Observed Behavior
In case of folder hierarchy more than two level deep with multiple folders as siblings inside a parent folder, the ObjectFiles.cs code fails. 

#### Steps to Reproduce

- Deploy a folder hierarchy to Style Library. Folder hierarchy is as below.

1. Revamp
     1.1 CSS
          1.1.1 Fonts
                  1.1.1.1 Aldine
                  1.1.1.2 League

- When you apply template with the schema using following tag in the schema (2016-05).
     <pnp:Files>
        <pnp:Directory Src=".\Revamp" Folder="Style%20Library" Overwrite="true"
            Recursive="true" />
      </pnp:Files>

It gives the following error.
Apply-PnPProvisioningTemplate : Could not find a part of the path 'D:\Code\MySamples\Revamp\css\Fonts\Aldine\League'. 

Here the ideal path should have been 'D:\Code\MySamples\Revamp\css\Fonts\League' but here the Aldine(sibling) became parent of 'League'.

I have checked this issue with PowerShell commandlet and .Net code on multiple environment(on-Prem and Office 365)

#### Code Observation

The directory recursion code in ObjectFiles.cs in below method fails.
        internal static List<Model.File> GetDirectoryFiles(this Model.Directory directory,
            Dictionary<String, Dictionary<String, String>> metadataProperties = null)

**Comment by jansenbe** [comment]
Thx for the fix
