### ISSUE TITLE
Provisioning Recursive Directories 

### ISSUE THREAD

**Issue by mihmbox** [SharePoint/PnP-Sites-Core#900]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

Name                                    Version
----                                    -------
SharePointPnPPowerShellOnline           2.10.1612.0

#### Expected or Desired Behavior
Provision directories in SharePoint

#### Observed Behavior
Error.

#### Steps to Reproduce
Provision directory using xml file and Apply-PnPProvisioningTemplate  command

Directory structure:
- folder-1
   --file-1
- folder-2
   -- file-2

Framework tries to use paths:
- folder-1
   -- file-1
   -- folder-2
          -- file-2
When I have 2 sub-folders it tries to find the second one in first sub-folder.

**Comment by Atul-Moghe** [comment]
This is the same issue that i had reported(issue #898) and fixed.

The changes are merged in the dev branch and will be merged into the master during the monthly cycle.
