### ISSUE TITLE
GetWebPartXML function in PageExtensions.cs doesn't provide for non standard ports, and creates // when using root site collection.

### ISSUE THREAD

**Issue by mrpullen** [SharePoint/PnP-Sites-Core#907]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

OCT 2016 CU

#### Expected or Desired Behavior
Expected to get the XML from the web part I am requesting.

#### Observed Behavior
My development machine is running on http://site:8888
The request becomes
`//_vti_bin/exportwp.aspx?pageurl=http://site/Pages/mypage.aspx&guidstring={guid}`
which obviously doesn't work as I have an extra "/" and no port in my pageurl.

Looks like the problem in ni the following code.

```
var serverRelativeUrl = web.EnsureProperty(w => w.ServerRelativeUrl); 
var webUrl = $"{uri.Scheme}://{uri.Host}{serverRelativeUrl}"; 
var pageUrl = $"{uri.Scheme}://{uri.Host}{serverRelativePageUrl}"; 
var request = (HttpWebRequest)WebRequest.Create($"{webUrl}/_vti_bin/exportwp.aspx?pageurl={pageUrl}&guidstring={id}"); 
```
When we are on the rootWeb serverRelativeUrl is just "/" explaining the two "//" characters in the web request.

And since we aren't including {uri.Port} my webUrl && pageUrl is wrong.

My fix would be

```
var serverRelativeUrl = web.EnsureProperty(w => w.ServerRelativeUrl); 
var webUrl = $"{uri.Scheme}://{uri.Host}:{uri.Port}{serverRelativeUrl}"; 
var pageUrl = $"{uri.Scheme}://{uri.Host}:{uri.Port}{serverRelativePageUrl}"; 

if(!webUrl .endsWith("/")) {
    webUrl += "/"
}
var request = (HttpWebRequest)WebRequest.Create($"{webUrl}_vti_bin/exportwp.aspx?pageurl={pageUrl}&guidstring={id}"); 
```

#### Steps to Reproduce
Put you host on a non standard port.
Using PnP powershell run

`Get-PnPWebPartXML -serverRelativeUrl {relativePageUrl} -id {webparttitle}`

**Comment by erwinvanhunen** [comment]
Hi! Thank you for your efforts, as @PaoloPia mentioned, we will credit you for your work.
