### ISSUE TITLE
Apply-Provision template on subsite issue

### ISSUE THREAD

**Issue by ntinykumar** [SharePoint/PnP-Sites-Core#914]
Hi, 
I am also getting the below error and nothing get created in sub site using PnP provision commands.

Export : 
Connect-SPOnline -Url https://Domain1.sharepoint.com/Sites/TT1  -Credential  DEV #(Get-Credential)
Get-SPOProvisioningTemplate -Out .\RetailerExtranetQARootSiteStructureToTSW_2.xml 
 Import : 
Connect-SPOnline -Url https://Domain2.sharepoint.com/Sites/TT1  -Credential  DEV #(Get-Credential)
Apply-SPOProvisioningTemplate  -Path .\RetailerExtranetQARootSubSiteSiteStructureToTSW_2.xml 
 
Nothing get created on targeted sub site , but SC to SC migration happened successfully.  
 
Error :
Apply-SPOProvisioningTemplate : Value cannot be null.
Parameter name: stream
At line:1 char:1
+ Apply-SPOProvisioningTemplate -Path .\RetailerExtranetQASubSiteStruc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : WriteError: (Smiley Happy [Apply-PnPProvisioningTemplate], ArgumentNullException
+ FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by Pieter-Veenstra** [comment]
Can you run 

set-pnptracelog -on -level debug 

Before running the apply command

**Comment by ntinykumar** [comment]
Hi Pieter,

Thanks for your reply. I was using Set-SPOTraceLog -On -Level debug and
sending the error on the post. Now I came to know that there is separate
PnP Trace command (set-pnptracelog -on -level debug). I will set this and
re run the command and will come back to you.

Please let me know should I contact you via this email trail or should I go
ahead and post on community forum post.

Once again thanks for helping me.



Thanks & Regards,
Nitinkumar Kakulde
nitinkumar.kakulde@gmail.com
Mobile:-+91-9890336633/+91-9833077906

**Comment by ntinykumar** [comment]
Thanks Pieter, 

I have used this commands and there is generic log was displayed but when I did sub site Get template and apply template, xml does not have any content Type and has got standard warning from the powershell that CT type at sub site level can not be exported. 

Below is the warning I received for almost 37 content types. I am only mentioning warning for few CT as all warning where same for all CT with CT name

Warning : 

WARNING: You are extracting a template from a subweb. List 'Accessories Bulletin' refers to content types. Content types are not exported when extracting a template from a subweb
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:24:56.3635	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:24:57.1022	[Get Security]	[11]	[Debug]	Code execution scope ended	738ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:24:57.1032	[List instances]	[11]	[Debug]	Adding list: Announcements - Doc2	57433ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Warning: 0 : 2016-12-29 12:24:57.1042	[List instances]	[11]	[Information]	You are extracting a template from a subweb. List 'Announcements' refers to content types. Content types are not
 exported when extracting a template from a subweb	57435ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
WARNING: You are extracting a template from a subweb. List 'Announcements' refers to content types. Content types are not exported when extracting a template from a subweb
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:00.8234	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:01.4102	[Get Security]	[11]	[Debug]	Code execution scope ended	587ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:01.4112	[List instances]	[11]	[Debug]	Adding list: Centre Type - Lists/Centre Type	61741ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:11.0051	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:11.5849	[Get Security]	[11]	[Debug]	Code execution scope ended	580ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:11.5859	[List instances]	[11]	[Debug]	Adding list: Code of Practice or Policy - Code of Practice or Policy	71916ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Warning: 0 : 2016-12-29 12:25:11.5869	[List instances]	[11]	[Information]	You are extracting a template from a subweb. List 'Code of Practice or Policy' refers to content types. Content 
types are not exported when extracting a template from a subweb	71917ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
WARNING: You are extracting a template from a subweb. List 'Code of Practice or Policy' refers to content types. Content types are not exported when extracting a template from a subweb
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:21.3005	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:21.8737	[Get Security]	[11]	[Debug]	Code execution scope ended	572ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:21.8747	[List instances]	[11]	[Debug]	Adding list: Event - Event	82204ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Warning: 0 : 2016-12-29 12:25:21.8757	[List instances]	[11]	[Information]	You are extracting a template from a subweb. List 'Event' refers to content types. Content types are not exporte
d when extracting a template from a subweb	82206ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
WARNING: You are extracting a template from a subweb. List 'Event' refers to content types. Content types are not exported when extracting a template from a subweb
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:32.3204	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:33.0187	[Get Security]	[11]	[Debug]	Code execution scope ended	697ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Information: 0 : 2016-12-29 12:25:33.0187	[List instances]	[11]	[Debug]	Adding list: Form - Form	93349ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef
PowerShell_ISE.exe Warning: 0 : 2016-12-29 12:25:33.0207	[List instances]	[11]	[Information]	You are extracting a template from a subweb. List 'Form' refers to content types. Content types are not exported
 when extracting a template from a subweb	93351ms	e919a7cc-3af0-4e0f-88b3-d973cf85d9ef

**Comment by Pieter-Veenstra** [comment]
For the get command this is expected content types have to be created at site collection level. Can you get the additional info for the apply command? Is the apply failing on missing content types?

**Comment by ntinykumar** [comment]
Yes every CT in the sub site level which are referred in list and Document library are not exported in xml file structure and but with reference CT available in for lists. 
So when we import the structure to another site CT missing errors comes. However I am able to deploy the xmlfile structure to another subsite but list columns not created except Title columns.

**Comment by jansenbe** [comment]
The engine will not allow you to create content types in the root web when you apply a template to a sub web. This is by design and will not change. Do note that as of the February 2017 release (coming out soon) we will have an option to create content types at in sub sites if you specify the ProvisionContentTypesToSubWebs flag. We however recommend to create the needed content types and fields in the root site using a separate template and then apply the other template to the sub site.

I'm closing this issue as we're not planning on changing this behavior.
