### ISSUE TITLE
PnP Provisioning fails to -IncludeSiteGroups when Web.Title == ""

### ISSUE THREAD

**Issue by mrpullen** [SharePoint/PnP-Sites-Core#915]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013 SEPT CU

#### Expected or Desired Behavior
I would like to get site groups exported if the Web.Title is set to "". Currently it fails because it attempts to do some token replacement with {sitename} as it extracts the SiteGroups.

#### Observed Behavior
Provisioning Engine fails when Web.Title == "" when -IncludeSiteGroups option is provided.

#### Steps to Reproduce
(Using PnP Powershell for simplicity)
Connect-PnPOnline -url "http://somesite"
$ctx = Get-PnPContext
$web = $ctx.Web
$ctx.load($web)
$ctx.ExecuteQuery()

$web.Title = ""
$web.Update()

Now attempt to get Site Groups from provisioning engine

$template = Get-PnPProvisioningTemplate -Handlers SiteSecurity -IncludeSiteGroups

 ```
var siteGroup = new SiteGroup()
                            {
                                Title = **group.Title.Replace(web.Title, "{sitename}**"),
                                AllowMembersEditMembership = group.AllowMembersEditMembership,
                                AutoAcceptRequestToJoinLeave = group.AutoAcceptRequestToJoinLeave,
                                AllowRequestToJoinLeave = group.AllowRequestToJoinLeave,
                                Description = group.Description,
                                OnlyAllowMembersViewMembership = group.OnlyAllowMembersViewMembership,
                                Owner = **ReplaceGroupTokens(web, group.Owner.LoginName)**,
                                RequestToJoinLeaveEmailSetting = group.RequestToJoinLeaveEmailSetting
                            };
```

Thanks for your contribution! Sharing is caring.

**Comment by erwinvanhunen** [comment]
Your fix has been merged and I will close this issue. Thank you for your work!
