### ISSUE TITLE
Update Role asignments not possible

### ISSUE THREAD

**Issue by konraplo** [SharePoint/PnP-Sites-Core#918]
Hi

I try to assign group permissions for ListsInstances/Folder. The problem is, permissions are always "added" and there is not possible to remove/update role assignments for principals.

•PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

Category

[x ] Bug
 [ ] Enhancement

Environment

[ ] Office 365 / SharePoint Online
 [ ] SharePoint 2016
 [ x] SharePoint 2013

Expected or Desired Behavior

It should be possible to overwrite role assignments for principals.

Steps to Reproduce

Create and provision a template with ListInstance and Security settings paragraph.

KR
 Konrad

**Comment by vman** [comment]
Hi konraplo,

The way I have solved this is to use the PnPTemplate to add the role assignment:
```XML
<pnp:RoleAssignment Principal="{associatedmembergroup}" RoleDefinition="Contribute" />
```

And then use an extensiblity handler to remove the permissions which are not needed:

```CSharp
class CnCProvisioningExtensibilityHandler : IProvisioningExtensibilityHandler
    {
        public void Provision(ClientContext ctx, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation, TokenParser tokenParser, PnPMonitoredScope scope, string configurationData)
        {
            var web = ctx.Web;
            if (!web.IsSubSite())
            {
                var memberGroup = web.AssociatedMemberGroup;
                var editorRoleDefinition = web.RoleDefinitions.GetByType(RoleType.Editor);
                var roleAssignment = web.RoleAssignments.GetByPrincipal(memberGroup);
                roleAssignment.RoleDefinitionBindings.Remove(editorRoleDefinition);
                roleAssignment.Update();
                ctx.ExecuteQueryRetry();
            }
        }
    }
```

Here is how to add an extensiblity provided to your template:
http://www.clearpeople.com/insights/blog/2016/september/custom-extensibility-handlers-for-pnp-provisioning-framework

**Comment by konraplo** [comment]
Hi Vman,

Thx for your feedback! The problem is that if I use custom extension, then I should remove permission for all securable objects (Web, Lists, Folders) I broke permission. I find this too complicated and I think here should be more "general" solution. But this could be Plan "B" :)

**Comment by jansenbe** [comment]
The engine is indeed not removing permissions from roles, actually the engine is never deleting anything, we're only adding and when possible updating artefacts. The engine does add permissions to roles when it sees an already existing role, but as said we're not removing them. Will close this issue as we've no plans to change this behavior in the engine, the recommended approach is using an extensibility handler as mentioned by @vman .

**Comment by stact** [comment]
Same issue here. There is no alternative to allow us to remove permissions before adding them?
I think it's a real bug, indeed when we apply a template, we need to have the expected behavior.

I've open an uservoice
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/18852910-update-role-asignments-in-pnp-provisioning-schema

Thank you!
