### ISSUE TITLE
SetMasterPageByUrl Affects Sharepoint-Hosted Add-in Webs

### ISSUE THREAD

**Issue by Vindale** [SharePoint/PnP-Sites-Core#92]
BrandingExtensions.cs

If resetSubsitesToInherit is set to true when called on a web that contains SharePoint-Hosted add-ins, this function will apply a master page other than app.master to them, breaking them until the master page is set back manually or the add-in is reinstalled.

[This blog post](http://www.casvaniersel.com/2015/01/custom-masterpages-and-sharepoint-hosted-apps/) explains the issue with setting the master page for an add-in web.

**Comment by PaoloPia** [comment]
Hi Vindale,
I will inspect the issue and I will let you know about the outcome. Thanks.

**Comment by PaoloPia** [comment]
Hi Vindale,
Thanks for your patience. This bug should be now fixed in the DEV branch. If you can, give it a try. Thanks.
