### ISSUE TITLE
Error downloading the master page and page layouts from the gallery during template extraction

### ISSUE THREAD

**Issue by durayakar** [SharePoint/PnP-Sites-Core#929]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[] Office 365 / SharePoint Online
[] SharePoint 2016
[x] SharePoint 2013

Name                                                        Version
----                                                        -------
SharePointPnPPowerShellOnline                               2.10.1612.0
SharePointPnPPowerShell2013                                 2.10.1612.0

#### Expected or Desired Behavior
while extracting a template, PersistBrandingFiles option should extract the branding files.
However it is failing probably due to handling of the token {masterpagecatalog} in the code. 
Instead of converting {masterpagecatalog} token to  /_catalogs/masterpage/, it is converting it to _catalogsmasterpage a seen in the logs below. 

This is observed in PowerShell but the log indicated that it is sourced from the code in core library, and particularly from SharePointConnector, so posting it here. 

It was working before I got the latest updates of the library.

#### Observed Behavior
PowerShell_ISE.exe Information: 0 : 2017-01-03 15:47:13.1102	[Publishing]	[11]	[Debug]	Code execution scope started	0ms	0360ee13-e60c-4ab2-8521-8a6e5c5c36c6
PowerShell_ISE.exe Information: 0 : 2017-01-03 15:47:38.6318	[SharePointConnector]	[0]	[Debug]	GetFileStream('home.html','_catalogsmasterpageMyFolder')	0ms	
PowerShell_ISE.exe Error: 0 : 2017-01-03 15:47:38.9958	[OfficeDevPnP.Core]	[0]	[Error]	File home.html not found in site https://dev-sharepoint, library  _catalogsmasterpageMyFolder. Exception = Object reference not set to an instance of an object.	0ms	

#### Steps to Reproduce
1) create a folder called MyFolder in your master page gallery
2) put a master page in there
3) run the get pnp template code with persist branding files option
4) the files are not downloaded from SharePoint

**Comment by erwinvanhunen** [comment]
Hi! Thank you for reporting this issue. Investigation allowed us to reproduce this issue and we fixed it with PR #947 . I will close this issue now but please do not hesitate to reopen it if you believe the issue still stands.
