### ISSUE TITLE
Error running multiple Jobs from the same windows service or console app

### ISSUE THREAD

**Issue by emilverwoerd** [SharePoint/PnP-Sites-Core#936]
**Category**
[x ] Bug
[ ] Enhancement

 **Environment**
[ x] Office 365 / SharePoint Online
[ x] SharePoint 2016
[ x] SharePoint 2013

**Expected or Desired Behavior**
Allows other jobs to continue when multiple jobs are running in the same console application or windows service.

**Observed Behavior**
On my development machine I have a windows service that runs multiple timerjobs in the same thread at once. However when a job finishes the Timerjob signals all others that it is done and so the console or windows service will discard the process.

The fix is replacing the following code in the TimerJob.cs class
   // Threading
        private static int numberOfThreadsNotYetCompleted;
        private static ManualResetEvent doneEvent;

by
     // Threading
        private int numberOfThreadsNotYetCompleted;
        private ManualResetEvent doneEvent;

**Comment by jansenbe** [comment]
Hi @emilverwoerd ,

This change has been implemented. Closing this issue now.
