### ISSUE TITLE
JSLink in XSLTListViewWebpart : ~sitecollection is interprated

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Sites-Core#938]
_From @Amysno on January 5, 2017 16:39_

hello there !
When provisioning a simple page with layout OneColumn, i'm adding a XsltListViewWebPart.
In that webpart, i specify the URL of a JSLink, located in the Style Library on the Root Web.
Here is that property : (inside <properties></properties>)

>       <property name="JSLink" type="string">~SiteCollection/Style Library/js/contacts_JSLink.js</property>

As you certainly know, when it comes to JSLink URL in Webparts, it has to be written using "~siteCollection" in WP, it appears like this : 

> ~siteCollection/Style Library/

But strangely, here, the ~ is interpreted and becomes /teams/Myteam/Style Library... which does not work.

I tried using these, and i write the results for you : 

- with `~siteCollection` result :  /teams/LY/Style Library => SP does interprete this one.

- with `&#152;siteCollection` result : siteCollection/Style Library  => No ~ , SP does not understand that url.

- with `&#126;siteCollection` result : /teams/LY/Style Library/   => SP does interprete, and replaces by the real names, but this is not what we want.

Could you please help me ?

thanks a lot.
have a nice day

_Copied from original issue: SharePoint/PnP-Provisioning-Schema#160_

**Comment by erwinvanhunen** [comment]
Hi,

Thank for you reporting this issue. Are you using the PnP Provisioning engine to provision that page?

**Comment by erwinvanhunen** [comment]
I added a fix to the provisioning engine to skip parsing those specific tokens, e.g. the tokens will be send on  to SharePoint as is for parsing.  See PR #939. I will close this issue, but do not hesitate to reopen the issue if you believe the issue has not been resolved by this fix.

**Comment by Amysno** [comment]
Hello @erwinvanhunen , and thank you for your work on this.
I don't really know the whole operation, so i have to ask you : the fix you provided has to be validated by a MS developper, i guess? or is it yet disposable and i just have to upgrade and then to rebuild my solution to make it work ?

Thanks a lot, and have a nice day!
