### ISSUE TITLE
the splistitem being updated was not retrieved with all taxonomy fields.

### ISSUE THREAD

**Issue by ntinykumar** [SharePoint/PnP-Sites-Core#945]
We have Office 365 SharePoint online tenant A and B, 
We are able to migrated the SC structure from tenant A to B
Below are the process and deployment we did by using PnP Get/Apply provision template commands

1) Export /Import Taxonomy by using command 
Connect-SPOnline -Url https://sourcetenant.SharePoint.com/Sites/SiteCollection  -Credential (Get-Credential)
Export-SPOTermGroupToXml -Out .\AnyName.xml 
then 
Connect-SPOnline -Url https://targettenant SharePoint.com/Sites/SiteCollection  -Credential (Get-Credential
Import-SPOTermGroupFromXml -Path .\AnyName.xml 
then
2) Import Export Site structure using power shell commands PnP

#Export
Connect-SPOnline –Url https://sourcetenant.sharepoint.com/Sites/SiteCollection –Credentials (Get-Credential) 
Get-SPOProvisioningTemplate -Out .\SiteStructure.xml  -Force

#Import
Connect-SPOnline –Url https://Targettenant.sharepoint.com/Sites/SiteCollection –Credentials (Get-Credential) 
Apply-SPOProvisioningTemplate -Path .\SiteStructure.xml 

Now we have CT at site collection level where CT type has some columns which are coming from the Taxonomy metadata, Linked with Taxonomy. 

We are getting below big critical error when we update the items in document library for the used CT. Data not get saved due to bellow error 

ERROR :+1: 
the splistitem being updated was not retrieved with all taxonomy fields.

I can send you the screen shot if you send me email ID . I am not able to attached here in the post. Some issues comming

**Comment by erwinvanhunen** [comment]
Hi!

Can you try to generate the template -including- the managed metadata? By using ```Get-PnPProvisioningTemplate -Out SiteStructure.xml -IncludeAllTermGroups```? And then subsequently apply that template to the target site?

We have very recently (last week) made changes to the engine to tokenize the Taxonomy fields (this is not available yet in the released version of the engine) correctly. What you can consider doing is doing the tokenization yourself, 

See here for an overview of the tokens: https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/ProvisioningEngineTokens.md

Where possible, replace hardcoded values in the Taxonomy fields with applicable tokens (like {webid} for the Source attribute, {sitecollectiontermstoreid} for the SSP value, etc. etc.

In the February 2017 release the engine will do this replacement for you, unfortunately until then you will have to do it.

**Comment by ntinykumar** [comment]
Seems superb as of now. Waiting for actual updated release on it. Meanwhile
for project development , I will do the process you mentioned and the link
for current work. Would be great if you proactively inform us the new
changes of taxonomy stuff in coming PNP release.

Thanks,
Nitinkumar Kakulde

On Jan 14, 2017 5:09 AM, "Erwin van Hunen" <notifications@github.com> wrote:

Hi!

Can you try to generate the template -including- the managed metadata? By
using Get-PnPProvisioningTemplate -Out SiteStructure.xml
-IncludeAllTermGroups? And then subsequently apply that template to the
target site?

We have very recently (last week) made changes to the engine to tokenize
the Taxonomy fields (this is not available yet in the released version of
the engine) correctly. What you can consider doing is doing the
tokenization yourself,

See here for an overview of the tokens: https://github.com/SharePoint/
PnP-Sites-Core/blob/dev/Core/ProvisioningEngineTokens.md

Where possible, replace hardcoded values in the Taxonomy fields with
applicable tokens (like {webid} for the Source attribute,
{sitecollectiontermstoreid} for the SSP value, etc. etc.

In the February 2017 release the engine will do this replacement for you,
unfortunately until then you will have to do it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SharePoint/PnP-Sites-Core/issues/945#issuecomment-272577351>,
or mute the thread

**Comment by metalogique** [comment]
I had a similar issue and here's the answer if it can help someone: in my PNPTemplate, for the taxonomy field, the value for the webid property was a hardcoded value. I replaced it with {siteid} and it fixed it!

**Comment by mmsharepoint** [comment]
Thanks for the hint @metalogique I also came across that issue but instead I omitted the WebId which was successful most of the times. Thought this would be handled by SP itself. Do you think it's a better idea to set it like you did? And why? Have an explanation? Just curious ...
Markus

**Comment by martinlingstuyl** [comment]
You saved my day @metalogique, I though I was going crazy. A PnP template that functioned fine with an earlier version of PNP Sites Core, started to Malfunction with the latest. I swapped the WebId and SourceID guids with {siteId} and {{siteId}} and everything worked again.
