### ISSUE TITLE
Webpart provisioning extration/creation

### ISSUE THREAD

**Issue by KEMiCZA** [SharePoint/PnP-Sites-Core#955]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Category
[ ] Bug
[ ] Enhancement
[X] Question

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Hi I have a more general question about extracting a page with the web part information. The problem is now when I extract the template, the Home.aspx page is not extracted with the template. I would like to extract this page with the web parts as well. Is this feature included in this framework? If so how do I use it?

I've used the framework before for extracting and provisioning all other information such as lists/contenttypes/libraries/fields/etc. For the provisioning of the webpart I would do this purely in code. But it would be nice to be able to also include the page/webparts in the .xml file, if possible.

Thanks in advance

**Comment by erwinvanhunen** [comment]
Hi! If you want to extract the homepage you have to specify an additional flag. If you use the Provisioning Engine from code, set the PersistBrandingFiles property on the ProvisioningTemplateCreationInformation object to true. If you are using PowerShell to extract a template, specify -PersistBrandingFiles on the cmdlet. So:

```powershell
Get-PnPProvisioningTemplate -Out mytemplate.pnp -PersistBrandingFiles
```

If you use a .pnp extension for your template the homepage will be stored inside the PnP file, if you use an .xml extension the file will be stored in a folder (or subfolder if the file was located in a library in your site) of the current folder.

I will close this issue, but please do not hesitate to reopen it in case you have more questions.

**Comment by KEMiCZA** [comment]
Hi Erwin

Thank you for the response. I did try using the PresistBrandingFiles flag, but it does not have any effect. The Home.aspx file or any webparts are not extracted when setting this flag. I will include the code I'm using for this:
```csharp
clientContext.Load(clientContext.Web);
clientContext.ExecuteQueryRetry();

var creationInfo = new ProvisioningTemplateCreationInformation(clientContext.Web);
creationInfo.PersistBrandingFiles = true;
var fileSystemConnector = new FileSystemConnector(String.Format(@"{0}\Templates", AppDomain.CurrentDomain.BaseDirectory), "");

creationInfo.FileConnector = new OpenXMLConnector(string.Format("{0}.pnp", clientContext.Web.Title), fileSystemConnector);
                var template = clientContext.Web.GetProvisioningTemplate(creationInfo);

XMLTemplateProvider provider = new XMLOpenXMLTemplateProvider(creationInfo.FileConnector as OpenXMLConnector);
provider.SaveAs(template, string.Format("{0}.xml", clientContext.Web.Title));
```
More information: 
* Using SharePoint Online
* The code is running for a subsite (not rootsite)
* Using the latest SharePoint PnP Nugget package (2.10.1612)
* When examining the .pnp file with 7zip, I only see one file in the 'Files' folder and there are no references inside this xml file to any <File> attributes, only: WebSettings, RegionalSettings, SupportedUILanguages, Security, Lists and Features

If you need more information please let me know.
Thanks in advance

**Comment by KEMiCZA** [comment]
Update:

After reading the following discussion https://techcommunity.microsoft.com/t5/SharePoint-Developer/Home-aspx-content-and-webparts-when-extracting-PnP-site/td-p/26074, I tried changing the way I'm authenticating to SharePoint Online.

```csharp
using (var clientContext = new AuthenticationManager().GetWebLoginClientContext(siteURL))
 {
         var Password = "Password";
         SecureString securePassword = new SecureString();
         foreach (var c in Password) {securePassword.AppendChar(c); }
         clientContext.Credentials = new SharePointOnlineCredentials("username@etc.com", securePassword);
}
```

I'm still using the AuthenticationManager, but if I don't set the 'clienctContext.Credentials' manually afterwards the Pages are not extracted for some reason! Maybe this is still an open issue in some ticket, I'm not sure. Or maybe it was solved and then it broke again with some other change?

So the credentials that the "AuthenticationManager().GetWebLoginClientContext" method returns are not the same when using "SharePointOnlineCredentials"? I'm I using this method wrongly or is this a bug?

Thanks in advance

**Comment by erwinvanhunen** [comment]
Unfortunately, in this case, yes, they are different. When logging in with Web Credentials we receive a cookie. That cookie contains the access token. We then piggy back every request to SharePoint and inject that cookie in the request, which will be used to authenticate you against the server. In the case of webparts, we until very recently needed to call a webservice that required username and password to authenticate (this is currently still the case for SP On-Premises), hence we needed the Credentials to be present. We check, during extraction, if these credentials are being set. If not, we skip extracting the homepage. However, we do not have this requirement anymore for SPO, however ,the credential check was still there. I just removed the check with PR #975. Thank you for reporting this and helping me to fix this bug. The fix will be available in the February 2017 release.
