### ISSUE TITLE
PnP-Sites-Core has a non-listed dependency on Netwonsoft.Json

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#962]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
NuGet package

Guys, as per the title, your NuGet package has a direct dependency on Newtonsoft.Json >= 9.0, but that's not listed as a dependency properly

https://www.nuget.org/packages/SharePointPnPCoreOnline/

**Comment by jansenbe** [comment]
Hi Massimo
I'll take this in account when creating the Feb release. Thanks for reporting this.

**Comment by jansenbe** [comment]
Integrated in Feb release which we'll be pushing out tomorrow. Closing this issue now
