### ISSUE TITLE
No "RootWebOnly" attribute on the <pnp:File> element

### ISSUE THREAD

**Issue by vman** [SharePoint/PnP-Sites-Core#966]
#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
When provisioning a File with the <pnp:File> attribute, we should be able to specifiy "RootWebOnly=true" to specific that this file should be provisioned only if the site being provisioned is RootWeb of a site collection.

This would be helpful if you are using the same template to provision site collections (rootweb) as well as subsites. Files like display templates, spcolor files etc are only supposed to be provisioned at the root level. 

#### Observed Behavior
There is no "RootWebOnly" attribute on the <pnp:File> element.

Thank you.

**Comment by erwinvanhunen** [comment]
This issue was moved to SharePoint/PnP-Provisioning-Schema#161

**Comment by erwinvanhunen** [comment]
The issue has been moved to https://github.com/SharePoint/PnP-Provisioning-Schema/issues/161
