### ISSUE TITLE
ProvisioningEngine GetTemplate breaks when XML has some Navigation structure

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#969]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I have an XML Provisioning Template, extracted using 2017.01 version of PnP PowerShell, having the following information

```xml
...
      <pnp:Navigation>
        <pnp:GlobalNavigation NavigationType="Structural">
          <pnp:StructuralNavigation RemoveExistingNodes="false" />
        </pnp:GlobalNavigation>
        <pnp:CurrentNavigation NavigationType="StructuralLocal">
          <pnp:StructuralNavigation RemoveExistingNodes="false">
            <pnp:NavigationNode Title="Start" Url="{site}" />
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>
      </pnp:Navigation>
...
```

I want then to reuse this template by uploading it to SharePoint, or from the file system

#### Observed Behavior
When parsing a XML or PnP template file, _XMLTemplateProvider.GetTemplate_ throws a NullReferenceException because 

`source.Navigation.GlobalNavigation.StructuralNavigation.NavigationNode` is found `null` at 
[XMLPnPSchemaV201605Formatter.cs#L1535](https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201605Formatter.cs#L1535)

#### Steps to Reproduce
I've created a modified version of one of the XML templates files used in Unit Tests for including that piece of XML and reproducing the behavior.

It also has a 'bonus' test coverage for _XMLSharePointTemplatesProvider_, which is that one I originally had the issue with, and isn't covered by any unit test yet.

This is available in this branch
https://github.com/biste5/PnP-Sites-Core/tree/xmlspprovider_tests
Running 
- _XMLFileSystemGetTemplate3Test_ (new)
- _XMLSharePointGetTemplate1Test_ (new)

but as described, it's enough to have that piece of XML and trying _GetTemplate_ also from a console app

**Comment by erwinvanhunen** [comment]
Hi Massimo,

The StructuralNavigation node in GlobalNavigation expects nodes. If no nodes are there you will indeed receive an invalid template error. Removing the empty StructuralNavigation node will work. I will work on a fix for the formatter.

**Comment by erwinvanhunen** [comment]
I merged the fix into the dev branch. Thanks for reporting this one!

**Comment by biste5** [comment]
Thank you Erwin.
Btw, is a test coverage of XMLSharePointTemplatesProvider wished?
I think so, I'll issue a PR for that test

**Comment by erwinvanhunen** [comment]
We can always use more / better tests. So please do.
