### ISSUE TITLE
"Site Feed" missing when provisioning via PowerShell and base template was created via Central Administration

### ISSUE THREAD

**Issue by cheindel** [SharePoint/PnP-Sites-Core#981]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[X] SharePoint 2013

CU version: May 2016 CU (15.0.4823.1003)

PnP-PowerShell January 2017 Release (2.11.1701.1)

#### Expected or Desired Behavior
1. Base template is team site (STS#0) created via Central Administration which contains a Newsfeed webpart on the homepage by default. No changes are beeing made.
2. Extracting base template via `Get-PnPProvisioningTemplate -Out template.pnp`
3. Target website is created via PowerShell (`New-SPSite`) or C# SDK (`WebApplication.Sites.Add`).
4. Appyling template via `Apply-PnPProvisioningTemplate` or via C# SDK (`Microsoft.SharePoint.Client.ApplyProvisioningTemplate`).
5. Homepage on target website should look exactly like homepage on template website.

#### Observed Behavior
1. Homepage on target website does not show the input box for the "Newsfeed" ("Site Feed") webpart.
2. The site feature "Site Feed" is not activated on target website.
3. The XML definition in the template.pnp package does not contain a <pnp:features> section. Probably because no differences compared to base template were detected, which is what I would expect.

#### Steps to Reproduce
- See  steps 1-4 under "Expected or Desired Behavior"

#### Possible Solution
 - Actively check target site collection if it really matches base template and output a warning or prompt wether the user wants to re-enable missing features and/or provide a flag to be able to force re-enabling of "required" features.

**Comment by jansenbe** [comment]
Hi @cheindel ,

Can you verify you've been using the correct PS version for 2013. If you've for example used the Online PS then you'll be using a wrong base template when extracting. Would also be good to share the extracted template.

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
