### ISSUE TITLE
duplicate field

### ISSUE THREAD

**Issue by dahanmeir** [SharePoint/PnP-Sites-Core#982]
I got duplicate field error.

field: 
 `<Field Type="LookupMulti" DisplayName="כלי מערכת" Required="TRUE" EnforceUniqueValues="FALSE" Direction="None" List="{{listid:כלים ושירותים}}" WebId="65a8e8e3-abb7-413d-8e0a-6bdef3c81770" ShowField="Title" Mult="TRUE" Sortable="FALSE" UnlimitedLengthInDocumentLibrary="FALSE" Group="Discount Web Parts" ID="{88058888-c9fb-42e5-85b1-96da08c46bfb}" SourceID="{65a8e8e3-abb7-413d-8e0a-6bdef3c81770}" StaticName="DiscountWebPartTools" Name="DiscountWebPartTools" />`

**Comment by jansenbe** [comment]
Hi @dahanmeir ,

Did you verify that you don't have another field with the same ID or StaticName?

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
