### ISSUE TITLE
TeamSite Site Provisining is not working for SharePoint 2013 On-Prem using PNP Site Provisioning

### ISSUE THREAD

**Issue by virendramunot** [SharePoint/PnP-Sites-Core#992]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Samples - https://github.com/OfficeDev/PnP
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
- PnP JS Core - https://github.com/OfficeDev/PnP-JS-Core
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ X] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4787.1000

#### Expected or Desired Behavior
PNP should be able to Create Template for Teamsite using GetProvisioningTemplate() method using Remote Console App

#### Observed Behavior
Throwing below exception.
System.MissingMethodException was unhandled
  HResult=-2146233069
  Message=Method not found: 'System.String Microsoft.SharePoint.Client.WebParts.WebPartDefinition.get_ZoneId()'.
  Source=Core.Remote
  StackTrace:
       at Core.Remote.Program.Main(String[] args) in e:\Core.Remote\Program.cs:line 68
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
#### Steps to Reproduce
Created a C# Console app and used the sample Office PNP code

I am using OOTB SharePoint Team Site to Generate Template using Office PNP Code 

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Hi virendramunot,
could you also proved details around which NuGet package you have referenced in your solution - thx.

**Comment by VesaJuvonen** [comment]
This relates on issue with OOB CSOM Assemblies for providing us reliable mechanism in on-premises to check the used version. Core component used to use clientContext.ServerLibraryVersion property for detecting the used version. This oob API does not however work reliably in the on-premises and is providing wrong value as the version. We have now applied a fix to teh code where we use http header based detection on the used servers. This fix is currently in the dev branch and will be released as official NuGet package on 10th of February (next release date).

**Comment by jansenbe** [comment]
Closing issue has this indeed has been fixed. Feel free to re-open in case you still see this problem when using either our dev build or Feb 2017 release.

**Comment by virendramunot** [comment]
Thanks for the response and sorry for the late reply as I was away from work for some time due to my health issues.

While Answering to vesa's question I am using the latest nuget package which is Available on GITHUB. The current version is OfficeDevPnP.Core (2.11.1701.1).

I am still facing this issue and not sure how to resolve them as do not have access to the code of the core solution.
