### ISSUE TITLE
Site collection feature activation never finish

### ISSUE THREAD

**Issue by chuishen** [SharePoint/PnP-Sites-Core#994]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
After a new site collection is provisioned, the app is trying to active publishing feature on the site collection. I am expecting the method can be finish with in a certain time period.

#### Observed Behavior
After a new site collection is provisioned, the app is trying to active publishing feature on the site collection, but the process is never finish. below is the related log info:
__2017-01-24 01:46:50.3485	[OfficeDevPnP.Core]	[0]	[Information]	Activating feature f6924d36-2fa8-4f0b-b16d-06b7250180fa in web_

As you can see the log info is wrong, but I think it is because the source code is using wrong resource entry (off topic)

I already set the pollingIntervalSeconds to 60 sec and I keep get this issue since Monday

#### Steps to Reproduce
It seems like linked to the SharePoint Online CSOM service status, sometimes it will happen but not always

**Comment by jansenbe** [comment]
We've seen this randomly fail in our nightly tests...needs to be further investigated and fixed

**Comment by jansenbe** [comment]
I've not been able to spent time on this, would you be able to give it a shot and submit a PR for this?

**Comment by chuishen** [comment]
I have no idea how to fix it, if you can share some advice, I will give it a try.

**Comment by Pieter-Veenstra** [comment]
Why should pnp activate the publishing feature anyway? If publishing is part of the solution then should the base site template of the site that the template is applied to be a publishing site?

**Comment by chuishen** [comment]
some time you use a site template but you want to enable some feature which is not enable by default. For example, you use team site template but you want to active the publishing feature

**Comment by Pieter-Veenstra** [comment]
I would consider creating a publishing site. Apply your template and then export that site that you applied the template to and then use that as your new template.

**Comment by SchauDK** [comment]
It is a very valid scenario that @chuishen is describing.
Our solution is build on a Team Site. Some of our customers might want to activate publishing and some don't. When they're using Publishing we of course need to active the feature when they're creating multiple site collections.

Our workaround is to activate the feature before we apply the template. When get a timeout after 3 minutes we'll just wait until it is activated before we continue (the activation is still running on the server even though it throws a timeout).

**Comment by chuishen** [comment]
@SchauDK Do you mind to share your code please?

**Comment by Pieter-Veenstra** [comment]
@schaudk I agree that it is valid however you do end up with some leftover mess. 

E.g. Pages libraries are different and document libraries are different for both types of sites.

Having two different templates gives you a cleaner site.

Activating features upfront of applying templates does indeed work with the the pnp feature  activation.

**Comment by jansenbe** [comment]
Closing this issue...feel free to re-open if you still feel this is blocking you.
