### ISSUE TITLE
ListView Title when creating multilingual site

### ISSUE THREAD

**Issue by chinthamahesh** [SharePoint/PnP-Sites-Core#996]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use [SharePoint Developer Group](http://aka.ms/sppnp-community) at Microsoft Tech Community. Thanks!

#### Which PnP repository should you use to report the issue? 
*Please navigate to the appropriate repository by clicking on the link below and create your issue there. You can delete this section after you have navigated to the correct repository.*

Master - PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ X] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
List View Title should be displayed in the language that the site is provisioned

#### Observed Behavior
ListView Title is getting created with the last referenced resource value irrespective of the LCID of the site creating(in my case I am provisioning german site but the list view title is in Taiwanese). Eg: I have multiple resource files in the <PnP:Localizations> and the last reference file is core.zh-TW.resx

<pnp:Localization LCID="2052" Name="core" ResourceFile="..\App_GlobalResources\core.zh-CN.resx" />
    <pnp:Localization LCID="1028" Name="core" ResourceFile="..\App_GlobalResources\core.zh-TW.resx" />
#### Steps to Reproduce
1. Add the multiple resource files with different language. 
2. Apply the template with the localized View DisplayName eg: below is the view DisplayName
DisplayName="{resource:objectiv_schema_mwsidcamlidC24}" 

#### Submission Guidelines

PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectListInstance.cs
Below code is getting executed against SPOnline and list view title is 
This code execution may not be required for SPOnline as the DisplayName is being parsed already at the beginning of the method at line 381.

#if !SP2013
                // Localize view title
                if (displayNameElement.Value.ContainsResourceToken())
                {
                    createdView.LocalizeView(web, displayNameElement.Value, parser, monitoredScope);
                }
#endif

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @chinthamahesh ,

Localizing list view title does not work when using user credentials in combination with a value set for the SPS-MUILanguages user profile property. Below code is used to determine whether the localization can work. Can you verify your scenario against this?

```C#
private static bool CanUseAcceptLanguageHeaderForLocalization(Web web)
        {
            if (web.Context.IsAppOnly())
            {
                return true;
            }

            var currentUser = web.EnsureProperty(w => w.CurrentUser);
            PeopleManager peopleManager = new PeopleManager(web.Context);
            var languageSettings = peopleManager.GetUserProfilePropertyFor(web.CurrentUser.LoginName, "SPS-MUILanguages");
            web.Context.ExecuteQueryRetry();

            if (languageSettings == null || String.IsNullOrEmpty(languageSettings.Value))
            {
                return true;
            }

            return false;
        }
```

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
