### ISSUE TITLE
Bug with XsltListViewWebPart when applying on a subsite

### ISSUE THREAD

**Issue by s-KaiNet** [SharePoint/PnP-Sites-Core#997]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
When applying template on a subsite, XsltListViewWebpart view settings should be applied on the subsite.

#### Observed Behavior
If you are applying template on a subsite using following approach:  
```csharp
var ctx = new ClientContext("https://my.sharepoint.com/sites/dev");
var web = ctx.Site.OpenWeb("subsite");
web.ApplyProvisioningTemplate();
```  
XsltListViewWebpart view settings doesn't apply on the subsite

#### Steps to Reproduce  

 1. Create a new template with a page and XsltListViewWebPart. For XsltListViewWebPart definition provide custom view settings, ie. `<property name="ViewName" type="string">My View</property>`
 2. Apply template using approach described above
 3. View are not applied and default is used instead.    

 Consider also [this comment](https://github.com/SharePoint/PnP-Sites-Core/issues/584#issuecomment-275026480) from issue #584

**Comment by s-KaiNet** [comment]
With fix the process of resolving web is following: 

It tries to resolve the web using XsltListViewWebPart's WebId property (`<property name="WebId" type="System.Guid, mscorlib, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089">ID</property>`) otherwise it uses the same web where parent file is provisioned.

**Comment by KEMiCZA** [comment]
@s-KaiNet It now works when I set my clientcontext object to the subweb instead of the rootweb. I did not use the OpenWeb method but rather used the Clone method on the ClientContext object.

``` csharp
var ctx = new clientContextRootWeb.Clone(subwebUrl);
// Mistake was that I cloned the context using the url of the rootweb
...
ctx.Dispose();
```

This will resolve the issue for now. Again thanks for the quick fix.

**Comment by s-KaiNet** [comment]
Cool, glad to know it works. And right, `Clone` is another way to go.

**Comment by middiu** [comment]
Hi Guys,
I'm affected by the same bug but both the proposed workarounds are not fixing the problem.
I'm trying to drop a XsltListViewWebPart into a page on Sharepoint 2013 on-premise.
This is the XML template I'm using:

```
private static string ListWebPartXML = "<webParts><webPart xmlns=\"http://schemas.microsoft.com/WebPart/v3\">"+
		"<metaData>"+
			"<type name=\"Microsoft.SharePoint.WebPartPages.XsltListViewWebPart, Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c\" />"+
			"<importErrorMessage>Cannot import this Web Part.</importErrorMessage>"+
		"</metaData>"+
		"<data>"+
			"<properties>"+
				"<property name=\"ListDisplayName\" type=\"string\">{0}</property>"+
                 "<property name=\"ListName\" type=\"string\">{3}</property>"+
                 "<property name=\"ListId\" type=\"System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\">{1}</property>"+
				"<property name=\"ViewName\" type=\"string\">{2}</property>"+
                //"<property name=\"ViewGuid\" type=\"string\">{2}</property>" +
                "<property name=\"Title\" type=\"string\">{0}</property>" +
                "<property name=\"JSLink\" type=\"string\">/_layouts/15/STYLES/cimic-files/js/MyFavouritesColumns.js</property>"+
                "<property name=\"WebId\" type=\"System.Guid, mscorlib, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089\">{4}</property>"+
			"</properties>"+
		"</data>"+
	"</webPart>"+
"</webParts>";
```

I'm trying with both properties `ViewGuid` and `ViewName`.
The property `WebId` is the Subsite id
I'm setting my subsite context in this way:

```
ClientContext subsiteContext = new ClientContext(w.Url);
subsiteContext.Credentials = context.Credentials;
```

where `w.Url` is the subsite url and `contex.Credentials` are the credentials used in the RootSite context.

This is the code to drop the webpart:
```
WebPartDefinition newWebiie = limitedWebPartManager.ImportWebPart(webpartxml);
WebPartDefinition webpartie = limitedWebPartManager.AddWebPart(newWebiie.WebPart, "Header", 0);
```

The webpart is created but the view is not the one specified in the XML.

Any help is appreciated.
