### ISSUE TITLE
Apply-PnPProvisioningTemplate : Column '_dlc_DocId' does not exist. It may have been deleted by another user.

### ISSUE THREAD

**Issue by Pieter-Veenstra** [SharePoint/PnP-Sites-Core#999]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Applying a template shouldn't fail

#### Observed Behavior

When I apply my template:

Apply-PnPProvisioningTemplate : Column '_dlc_DocId' does not exist. It may have been deleted by another user.

#### Steps to Reproduce

run the following to exportthe site:
Get-PnPProvisioningTemplate -Web $web -Out "$path\Templates\$template\template.xml" -PersistBrandingFiles -PersistPublishingFiles -IncludeAllTermGroups 

In my case I'm now ending up with:
1. my welcome  page 
2. exports of 2 custom page layouts 

When I now apply the template the page is applied without any problem, but the page layouts created and fail with the above error.

all of the exported files seem to have something like:
   <pnp:Property Key="_dlc_DocId" Value="WSMQU3AS72XZ-123456789-2262" />

**Comment by jansenbe** [comment]
Hi Pieter,

Can you share a simple template that reproes this behavior? Will make troubleshooting much easier.

Thanks for reporting this.

**Comment by helloitsliam** [comment]
I have the same issue. Using two SharePoint Online site collections. Exporting works fine, exporting to XML I can see my Publishing Image field is there. When I apply it runs then fails with the same error, albeit with a different column name.

Liam

**Comment by Pieter-Veenstra** [comment]
@helloitsliam . can you share the template. The problem seems to have disappeared for me.

**Comment by jansenbe** [comment]
Adding template received from Liam.
[template.txt](https://github.com/SharePoint/PnP-Sites-Core/files/833579/template.txt)
